### ISSUE TITLE
[bitnami/mongodb] restarted "primary" pod cannot re-join the Replica Set

### ISSUE THREAD

**Issue by bmv-ce** [bitnami/charts#6741] opened 2021-06-23 14:43 UTC
**Which chart**:
bitnami/mongodb
version: 10.19.0

**Describe the bug**
Restarted "primary" pod is unable to re-join the replica set, failing with "replica set IDs do not match, ours: <>; remote node's: <>"

**To Reproduce**

1. Create a new Replica Set with 1 Primary and 2 Secondary nodes (note that a persistent volume is used, as I think it may be related to the problem):
>   helm install identification-service-rs0-mongodb bitnami/mongodb \
>	--set metrics.enabled=true \
>	--set arbiter.enabled=false \
>	--set persistence.size=100Gi \
>	--set persistence.mountPath=/mongodb \
>	--set persistence.storageClass=glusterfs-storage \
>	--set architecture=replicaset \
>	--set auth.enabled=true \
>	--set auth.rootPassword=XXXXX \
>	--set auth.username=myuser \
>	--set auth.password=XXXXXX \
>	--set auth.database=testdb \
>	--set auth.replicaSetKey=XXXXX \
>	--set replicaCount=3 \
>	--set resources.limits.cpu=1.0,resources.limits.memory=2Gi,resources.requests.cpu=0.5,resources.requests.memory=1Gi

2. As a result - 3 pods are successfully started, see each other and belong to the same replica set:

> ❯ kubectl get pods
> NAME                                   READY   STATUS    RESTARTS   AGE
> identification-service-rs0-mongodb-0   2/2     Running   0          151m
> identification-service-rs0-mongodb-1   2/2     Running   0          3h15m
> identification-service-rs0-mongodb-2   2/2     Running   0          3h49m

3. Replica Set status is correct:

>{
>	"set" : "rs0",
>	"date" : ISODate("2021-06-23T10:07:55.710Z"),
>	"myState" : 1,
>	"term" : NumberLong(2),
>	"syncSourceHost" : "",
>	"syncSourceId" : -1,
>	"heartbeatIntervalMillis" : NumberLong(2000),
>	"majorityVoteCount" : 2,
>	"writeMajorityCount" : 2,
>	"votingMembersCount" : 3,
>	"writableVotingMembersCount" : 3,
>	"optimes" : {
>		"lastCommittedOpTime" : {
>			"ts" : Timestamp(1624442872, 1),
>			"t" : NumberLong(2)
>		},
>		"lastCommittedWallTime" : ISODate("2021-06-23T10:07:52.976Z"),
>		"readConcernMajorityOpTime" : {
>			"ts" : Timestamp(1624442872, 1),
>			"t" : NumberLong(2)
>		},
>		"readConcernMajorityWallTime" : ISODate("2021-06-23T10:07:52.976Z"),
>		"appliedOpTime" : {
>			"ts" : Timestamp(1624442872, 1),
>			"t" : NumberLong(2)
>		},
>		"durableOpTime" : {
>			"ts" : Timestamp(1624442872, 1),
>			"t" : NumberLong(2)
>		},
>		"lastAppliedWallTime" : ISODate("2021-06-23T10:07:52.976Z"),
>		"lastDurableWallTime" : ISODate("2021-06-23T10:07:52.976Z")
>	},
>	"lastStableRecoveryTimestamp" : Timestamp(1624442812, 1),
>	"electionCandidateMetrics" : {
>		"lastElectionReason" : "electionTimeout",
>		"lastElectionDate" : ISODate("2021-06-21T08:58:28.328Z"),
>		"electionTerm" : NumberLong(2),
>		"lastCommittedOpTimeAtElection" : {
>			"ts" : Timestamp(0, 0),
>			"t" : NumberLong(-1)
>		},
>		"lastSeenOpTimeAtElection" : {
>			"ts" : Timestamp(1624265905, 8),
>			"t" : NumberLong(1)
>		},
>		"numVotesNeeded" : 1,
>		"priorityAtElection" : 5,
>		"electionTimeoutMillis" : NumberLong(10000),
>		"newTermStartDate" : ISODate("2021-06-21T08:58:28.332Z"),
>		"wMajorityWriteAvailabilityDate" : ISODate("2021-06-21T08:58:28.433Z")
>	},
>	"members" : [
>		{
>			"_id" : 0,
>			"name" : "identification-service-rs0-mongodb-0.identification-service-rs0-mongodb-headless.mongo.svc.cluster.local:27017",
>			"health" : 1,
>			"state" : 1,
>			"stateStr" : "PRIMARY",
>			"uptime" : 176968,
>			"optime" : {
>				"ts" : Timestamp(1624442872, 1),
>				"t" : NumberLong(2)
>			},
>			"optimeDate" : ISODate("2021-06-23T10:07:52Z"),
>			"syncSourceHost" : "",
>			"syncSourceId" : -1,
>			"infoMessage" : "",
>			"electionTime" : Timestamp(1624265908, 1),
>			"electionDate" : ISODate("2021-06-21T08:58:28Z"),
>			"configVersion" : 3,
>			"configTerm" : 2,
>			"self" : true,
>			"lastHeartbeatMessage" : ""
>		},
>		{
>			"_id" : 1,
>			"name" : "identification-service-rs0-mongodb-1.identification-service-rs0-mongodb-headless.mongo.svc.cluster.local:27017",
>			"health" : 1,
>			"state" : 2,
>			"stateStr" : "SECONDARY",
>			"uptime" : 176943,
>			"optime" : {
>				"ts" : Timestamp(1624442872, 1),
>				"t" : NumberLong(2)
>			},
>			"optimeDurable" : {
>				"ts" : Timestamp(1624442872, 1),
>				"t" : NumberLong(2)
>			},
>			"optimeDate" : ISODate("2021-06-23T10:07:52Z"),
>			"optimeDurableDate" : ISODate("2021-06-23T10:07:52Z"),
>			"lastHeartbeat" : ISODate("2021-06-23T10:07:55.071Z"),
>			"lastHeartbeatRecv" : ISODate("2021-06-23T10:07:55.279Z"),
>			"pingMs" : NumberLong(0),
>			"lastHeartbeatMessage" : "",
>			"syncSourceHost" : "identification-service-rs0-mongodb-0.identification-service-rs0-mongodb-headless.mongo.svc.cluster.local:27017",
>			"syncSourceId" : 0,
>			"infoMessage" : "",
>			"configVersion" : 3,
>			"configTerm" : 2
>		},
>		{
>			"_id" : 2,
>			"name" : "identification-service-rs0-mongodb-2.identification-service-rs0-mongodb-headless.mongo.svc.cluster.local:27017",
>			"health" : 1,
>			"state" : 2,
>			"stateStr" : "SECONDARY",
>			"uptime" : 176917,
>			"optime" : {
>				"ts" : Timestamp(1624442872, 1),
>				"t" : NumberLong(2)
>			},
>			"optimeDurable" : {
>				"ts" : Timestamp(1624442872, 1),
>				"t" : NumberLong(2)
>			},
>			"optimeDate" : ISODate("2021-06-23T10:07:52Z"),
>			"optimeDurableDate" : ISODate("2021-06-23T10:07:52Z"),
>			"lastHeartbeat" : ISODate("2021-06-23T10:07:54.046Z"),
>			"lastHeartbeatRecv" : ISODate("2021-06-23T10:07:55.172Z"),
>			"pingMs" : NumberLong(0),
>			"lastHeartbeatMessage" : "",
>			"syncSourceHost" : "identification-service-rs0-mongodb-1.identification-service-rs0-mongodb-headless.mongo.svc.cluster.local:27017",
>			"syncSourceId" : 1,
>			"infoMessage" : "",
>			"configVersion" : 3,
>			"configTerm" : 2
>		}
>	],
>	"ok" : 1,
>	"$clusterTime" : {
>		"clusterTime" : Timestamp(1624442872, 1),
>		"signature" : {
>			"hash" : BinData(0,"LFwblRbkKs/AQfFXmy45YgtquCo="),
>			"keyId" : NumberLong("6976168941982842884")
>		}
>	},
>	"operationTime" : Timestamp(1624442872, 1)
>}

4. Now delete the PRIMARY pod, and wait for it to be restarted automatically by the Stateful Set:
> kubectl delete pod identification-service-rs0-mongodb-0

**Expected behavior**
One of the SECONDARY nodes becomes the new PRIMARY, and the restarted pod becomes the new SECONDARY, when ready.

**Actual Result**
One of the SECONDARY nodes becomes the new PRIMARY, the restarted node joins the Replica Set, but is in unhealthy state.
The new `rs.status()`:

>{
>	"set" : "rs0",
>	"date" : ISODate("2021-06-23T13:27:00.273Z"),
>	"myState" : 1,
>	"term" : NumberLong(3),
>	"syncSourceHost" : "",
>	"syncSourceId" : -1,
>	"heartbeatIntervalMillis" : NumberLong(2000),
>	"majorityVoteCount" : 2,
>	"writeMajorityCount" : 2,
>	"votingMembersCount" : 3,
>	"writableVotingMembersCount" : 3,
>	"optimes" : {
>		"lastCommittedOpTime" : {
>			"ts" : Timestamp(1624454816, 1),
>			"t" : NumberLong(3)
>		},
>		"lastCommittedWallTime" : ISODate("2021-06-23T13:26:56.439Z"),
>		"readConcernMajorityOpTime" : {
>			"ts" : Timestamp(1624454816, 1),
>			"t" : NumberLong(3)
>		},
>		"readConcernMajorityWallTime" : ISODate("2021-06-23T13:26:56.439Z"),
>		"appliedOpTime" : {
>			"ts" : Timestamp(1624454816, 1),
>			"t" : NumberLong(3)
>		},
>		"durableOpTime" : {
>			"ts" : Timestamp(1624454816, 1),
>			"t" : NumberLong(3)
>		},
>		"lastAppliedWallTime" : ISODate("2021-06-23T13:26:56.439Z"),
>		"lastDurableWallTime" : ISODate("2021-06-23T13:26:56.439Z")
>	},
>	"lastStableRecoveryTimestamp" : Timestamp(1624454796, 1),
>	"electionCandidateMetrics" : {
>		"lastElectionReason" : "stepUpRequestSkipDryRun",
>		"lastElectionDate" : ISODate("2021-06-23T11:28:36.284Z"),
>		"electionTerm" : NumberLong(3),
>		"lastCommittedOpTimeAtElection" : {
>			"ts" : Timestamp(1624447713, 1),
>			"t" : NumberLong(2)
>		},
>		"lastSeenOpTimeAtElection" : {
>			"ts" : Timestamp(1624447713, 1),
>			"t" : NumberLong(2)
>		},
>		"numVotesNeeded" : 2,
>		"priorityAtElection" : 1,
>		"electionTimeoutMillis" : NumberLong(10000),
>		"priorPrimaryMemberId" : 0,
>		"numCatchUpOps" : NumberLong(0),
>		"newTermStartDate" : ISODate("2021-06-23T11:28:36.300Z"),
>		"wMajorityWriteAvailabilityDate" : ISODate("2021-06-23T11:28:38.389Z")
>	},
>	"members" : [
>		{
>			"_id" : 1,
>			"name" : "identification-service-rs0-mongodb-1.identification-service-rs0-mongodb-headless.mongo.svc.cluster.local:27017",
>			"health" : 1,
>			"state" : 1,
>			"stateStr" : "PRIMARY",
>			"uptime" : 7981,
>			"optime" : {
>				"ts" : Timestamp(1624454816, 1),
>				"t" : NumberLong(3)
>			},
>			"optimeDate" : ISODate("2021-06-23T13:26:56Z"),
>			"syncSourceHost" : "",
>			"syncSourceId" : -1,
>			"infoMessage" : "",
>			"electionTime" : Timestamp(1624447716, 1),
>			"electionDate" : ISODate("2021-06-23T11:28:36Z"),
>			"configVersion" : 6,
>			"configTerm" : 3,
>			"self" : true,
>			"lastHeartbeatMessage" : ""
>		},
>		{
>			"_id" : 2,
>			"name" : "identification-service-rs0-mongodb-2.identification-service-rs0-mongodb-headless.mongo.svc.cluster.local:27017",
>			"health" : 1,
>			"state" : 2,
>			"stateStr" : "SECONDARY",
>			"uptime" : 7948,
>			"optime" : {
>				"ts" : Timestamp(1624454816, 1),
>				"t" : NumberLong(3)
>			},
>			"optimeDurable" : {
>				"ts" : Timestamp(1624454816, 1),
>				"t" : NumberLong(3)
>			},
>			"optimeDate" : ISODate("2021-06-23T13:26:56Z"),
>			"optimeDurableDate" : ISODate("2021-06-23T13:26:56Z"),
>			"lastHeartbeat" : ISODate("2021-06-23T13:26:59.662Z"),
>			"lastHeartbeatRecv" : ISODate("2021-06-23T13:26:59.564Z"),
>			"pingMs" : NumberLong(0),
>			"lastHeartbeatMessage" : "",
>			"syncSourceHost" : "identification-service-rs0-mongodb-1.identification-service-rs0-mongodb-headless.mongo.svc.cluster.local:27017",
>			"syncSourceId" : 1,
>			"infoMessage" : "",
>			"configVersion" : 6,
>			"configTerm" : 3
>		},
>		{
>			"_id" : 3,
>			"name" : "identification-service-rs0-mongodb-0.identification-service-rs0-mongodb-headless.mongo.svc.cluster.local:27017",
>			"health" : 0,
>			"state" : 8,
>			"stateStr" : "(not reachable/healthy)",
>			"uptime" : 0,
>			"optime" : {
>				"ts" : Timestamp(0, 0),
>				"t" : NumberLong(-1)
>			},
>			"optimeDurable" : {
>				"ts" : Timestamp(0, 0),
>				"t" : NumberLong(-1)
>			},
>			"optimeDate" : ISODate("1970-01-01T00:00:00Z"),
>			"optimeDurableDate" : ISODate("1970-01-01T00:00:00Z"),
>			"lastHeartbeat" : ISODate("2021-06-23T13:27:00.261Z"),
>			"lastHeartbeatRecv" : ISODate("1970-01-01T00:00:00Z"),
>			"pingMs" : NumberLong(0),
>			"lastHeartbeatMessage" : "replica set IDs do not match, ours: 60d054b0cfe1dc9265e996f7; remote node's: 60d321b914915e255a0edd74",
>			"syncSourceHost" : "",
>			"syncSourceId" : -1,
>			"infoMessage" : "",
>			"configVersion" : -1,
>			"configTerm" : -1
>		}
>	],
>	"ok" : 1,
>	"$clusterTime" : {
>		"clusterTime" : Timestamp(1624454818, 1),
>		"signature" : {
>			"hash" : BinData(0,"YnAOaMQlNYoQ0F8LxGPrsgXf6W4="),
>			"keyId" : NumberLong("6976168941982842884")
>		}
>	},
>	"operationTime" : Timestamp(1624454816, 1)
>}

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.15.6"}```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}```

**Additional context**

**AS YOU CAN SEE, THE RESTARTED NODE IS UNHEALTHY WITH ERROR: replica set IDs do not match, ours: 60d054b0cfe1dc9265e996f7; remote node's: 60d321b914915e255a0edd74**

**I would like to know:**
1. What the proper behaviour should be, in case the PRIMARY pod is restarted?
2. How is it possible to re-join the node now, without destroying the Replica Set completely?

**Comment by bmv-ce** [comment] 2021-06-24 09:26
**Some more additional information:** 
When I connect to the restarted pod's mongo instance directly, it actually says that's a PRIMARY, so looks like another replicaSet was created upon restart.

This is the result of its own `rs.status()`:

> rs0:PRIMARY> rs.status()
> {
> 	"set" : "rs0",
> 	"date" : ISODate("2021-06-24T09:22:39.741Z"),
> 	"myState" : 1,
> 	"term" : NumberLong(2),
> 	"syncSourceHost" : "",
> 	"syncSourceId" : -1,
> 	"heartbeatIntervalMillis" : NumberLong(2000),
> 	"majorityVoteCount" : 1,
> 	"writeMajorityCount" : 1,
> 	"votingMembersCount" : 1,
> 	"writableVotingMembersCount" : 1,
> 	"optimes" : {
> 		"lastCommittedOpTime" : {
> 			"ts" : Timestamp(1624526548, 1),
> 			"t" : NumberLong(2)
> 		},
> 		"lastCommittedWallTime" : ISODate("2021-06-24T09:22:28.774Z"),
> 		"readConcernMajorityOpTime" : {
> 			"ts" : Timestamp(1624526548, 1),
> 			"t" : NumberLong(2)
> 		},
> 		"readConcernMajorityWallTime" : ISODate("2021-06-24T09:22:28.774Z"),
> 		"appliedOpTime" : {
> 			"ts" : Timestamp(1624526548, 1),
> 			"t" : NumberLong(2)
> 		},
> 		"durableOpTime" : {
> 			"ts" : Timestamp(1624526548, 1),
> 			"t" : NumberLong(2)
> 		},
> 		"lastAppliedWallTime" : ISODate("2021-06-24T09:22:28.774Z"),
> 		"lastDurableWallTime" : ISODate("2021-06-24T09:22:28.774Z")
> 	},
> 	"lastStableRecoveryTimestamp" : Timestamp(1624526526, 1),
> 	"electionCandidateMetrics" : {
> 		"lastElectionReason" : "electionTimeout",
> 		"lastElectionDate" : ISODate("2021-06-23T11:57:49.268Z"),
> 		"electionTerm" : NumberLong(2),
> 		"lastCommittedOpTimeAtElection" : {
> 			"ts" : Timestamp(0, 0),
> 			"t" : NumberLong(-1)
> 		},
> 		"lastSeenOpTimeAtElection" : {
> 			"ts" : Timestamp(1624449466, 8),
> 			"t" : NumberLong(1)
> 		},
> 		"numVotesNeeded" : 1,
> 		"priorityAtElection" : 5,
> 		"electionTimeoutMillis" : NumberLong(10000),
> 		"newTermStartDate" : ISODate("2021-06-23T11:57:49.272Z"),
> 		"wMajorityWriteAvailabilityDate" : ISODate("2021-06-23T11:57:49.372Z")
> 	},
> 	"members" : [
> 		{
> 			"_id" : 0,
> 			"name" : "identification-service-rs0-mongodb-0.identification-service-rs0-mongodb-headless.mongo.svc.cluster.local:27017",
> 			"health" : 1,
> 			"state" : 1,
> 			"stateStr" : "PRIMARY",
> 			"uptime" : 77091,
> 			"optime" : {
> 				"ts" : Timestamp(1624526548, 1),
> 				"t" : NumberLong(2)
> 			},
> 			"optimeDate" : ISODate("2021-06-24T09:22:28Z"),
> 			"syncSourceHost" : "",
> 			"syncSourceId" : -1,
> 			"infoMessage" : "",
> 			"electionTime" : Timestamp(1624449469, 1),
> 			"electionDate" : ISODate("2021-06-23T11:57:49Z"),
> 			"configVersion" : 1,
> 			"configTerm" : 2,
> 			"self" : true,
> 			"lastHeartbeatMessage" : ""
> 		}
> 	],
> 	"ok" : 1,
> 	"$clusterTime" : {
> 		"clusterTime" : Timestamp(1624526557, 1),
> 		"signature" : {
> 			"hash" : BinData(0,"gExcIwo6IDcyCWmXUazA3aArGE8="),
> 			"keyId" : NumberLong("6976957330474663940")
> 		}
> 	},
> 	"operationTime" : Timestamp(1624526548, 1)
> }

**Comment by bmv-ce** [comment] 2021-06-24 09:47
**And some more information:**
Whenever I restart that problematic pod - a new replica set with a single member is created (rs.conf() shows a different replicaSetId every time), and at the same time, this member is listed as part of the original replica set, but the status is unhealthy with the error message listed above.

**Comment by marcosbc** [comment] 2021-06-24 16:11
Hi @bmv-ce, thanks for all of the details. It seems like this issue is a duplicate of #5752, still pending investigation on our side. For now I'm going to mark it as on-hold and link it to our internal task.

Unfortunately I cannot give an ETA for when we expect to fix this.

**Comment by bmv-ce** [comment] 2021-06-24 20:25
Hi @marcosbc, thanks, the mentioned issue looks quite similar.
Is there any workaround for this? Is it possible to somehow move that PRIMARY node back to its original Replica Set?

**Comment by marcosbc** [comment] 2021-06-25 15:43
Unfortunately there is no workaround at this moment that I can think of, apart from exporting the data and importing it into a new working replicaset.

**Comment by shnurok672** [comment] 2021-08-08 19:47
Hello there
@marcosbc did you guys investigated the issue? I think it's super-important for all the mdb bitnami users. 
I think the issue happens because of initial primary env and corresponding selection of initial config. Could we create the init-container that searches for the running mongodb replicaset and if fails, startup the replica as Primary, otherwise secondary?

**Comment by marcosbc** [comment] 2021-08-09 10:24
Hi @shnurok672, unfortunately no update yet. Note  that due to summer holidays, development is moving slower than usual. However, I've increased the priority of the internal task so we tackle it sooner.

**Comment by shnurok672** [comment] 2021-08-09 10:31
@marcosbc Many thanks! Also, I think I've found the related issue
https://github.com/bitnami/bitnami-docker-mongodb/issues/187

**Comment by shnurok672** [comment] 2021-09-16 14:20
any updates?

**Comment by marcosbc** [comment] 2021-09-17 08:15
Hi @shnurok672, it seems like the internal task has been selected for development, so we may start working on a fix soon, however I cannot guarantee any specific ETA.

**Comment by ocoulson** [comment] 2021-11-04 18:18
@bmv-ce @shnurok672 We were eventually able to track down our issue to a problem with where we had mounted the volume to a place where the bitnami startup scripts weren't looking, using the config `persistence.mountPath` This meant that everytime a pod started up, it started up from scratch (seen in a message at the top of the logs for the pod), and in the case of the Primary it would just start its own replica set.
When we removed this config setting, the bitnami scripts correctly found the volume and existing db (including RS information) at the default location (/bitnami/mongodb).
I don't know if this would affect you but I thought I'd share in case

**Comment by shnurok672** [comment] 2021-11-04 19:20
@ocoulson Thank you for your investigation, but it's definitely not our issue. The issue was about rejoining lost primary (aka pod 0) replica to the replicaset, when the data with rs information was lost. So the pod-0 starts always as primary and creating new RS when there is no local data. This leads to 2 RSs in 1 StatefulSet. So its split braining

**Closed** 2022-03-11 17:02 UTC
Labels: on-hold
