### ISSUE TITLE
[bitnami/wildfly] misconfigured mgmtIngress annotations

### ISSUE THREAD

**Issue by emilianosantucci** [bitnami/charts#29787] opened 2024-10-06 10:50 UTC
### Name and Version

bitnami/wildfly 15.2.1

### What architecture are you using?

arm64

### What steps will reproduce the bug?

1. `helm install wildfly bitnami/wildfly --version 15.2.1 -f values.yaml`

### Are you using any custom parameters or values?

```yaml
exposeManagementConsole: true
ingress:
  enabled: true
  hostname: wildfly.192.168.70.2.nip.io
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
mgmtIngress:
  enabled: true
  hostname: wildfly-management.192.168.70.2.nip.io
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
```

### What is the expected behavior?

- `ingress` accept upload with max size **10m**
- `mgmtIngress` accept upload with max size **100m**

### What do you see instead?

Created ingress not inherit annotations added to `values.yaml`.

### Workaround used:
Use `commonAnnotations` into `values.yaml` as below:
```yaml
commonAnnotations:
  nginx.ingress.kubernetes.io/proxy-body-size: 100m
```
I know it is not the best choice (it set this annotations on all components created) but allow me to load WAR with a size greater than 1Mb.

### Hint for the resolutions:
I'm not a Helm master but I think the issue is on this [template](https://github.com/bitnami/charts/blob/main/bitnami/wildfly/templates/management-ingress.yaml) at row 19:
- Is:
```yaml
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.persistence.annotations .Values.commonAnnotations ) "context" . ) }}
``` 
- Should be:
```yaml
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.mgmtIngress.annotations .Values.commonAnnotations ) "context" . ) }}
```

**Comment by javsalgar** [comment] 2024-10-07 08:02
Hi!

Thank you so much for spotting it! Indeed, the issue is exactly as you mentioned. As you discovered it, would you like to submit a PR changing that line of the ingress file?

**Comment by emilianosantucci** [comment] 2024-10-08 13:43
Hi @javsalgar,
thank you for the feedback, I just open a PR for the fix.

Please feel free to give any advice about it.

**Comment by carrodher** [comment] 2024-10-10 07:40
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Closed** 2024-10-10 09:43 UTC
Labels: triage, tech-issues, wildfly
