### ISSUE TITLE
[bitnami/kong] Unable to install and run an Embedded Go Plugin with bitnami kong chart

### ISSUE THREAD

**Issue by jocadu** [bitnami/charts#9614] opened 2022-03-29 22:54 UTC
### Name and Version

bitnami/kong "2.8.0-debian-10-r5"

### What steps will reproduce the bug?

Environment: minikube
Command helm install kong -f kong/values.yaml bitnami/kong

I have a Go embedded Plugin working and tested with Kong 2.7, now I want to use the same Plugin with a bitnami chart installation, but it fails to start.

There are 2 Problems identified and solutions (work-arounds ) for each problem are provided.

### Are you using any custom parameters or values?
   extraEnvVars:

    - name: KONG_PLUGINSERVER_NAMES
      value: "ocp-gateway-plugin"
    - name: KONG_PLUGINS
      value: "bundled,ocp-gateway-plugin"
    - name: KONG_PLUGINSERVER_OCP_GATEWAY_PLUGIN_SOCKET
      value: "/usr/local/kong/ocp-gateway-plugin.socket"
    - name: KONG_PLUGINSERVER_OCP_GATEWAY_PLUGIN_START_CMD
      value: "/usr/local/bin/ocp-gateway-plugin"
    - name: KONG_PLUGINSERVER_OCP_GATEWAY_PLUGIN_QUERY_CMD
      value: "/usr/local/bin/ocp-gateway-plugin -dump"
    - name: KONG_LOG_LEVEL
      value: "debug"

I am also overriding the bitnami image with --set commands,  using the bitnami provided base image with the Go embedded plugin.

### What is the expected behavior?

The Plugin is supposed to Run properly, instead,the kong container fails to start

NAME                               READY   STATUS             RESTARTS   AGE
pod/ocp-gateway-855b7567b4-k9r7v   0/2     CrashLoopBackOff   1          10s

### What do you see instead?

**Issue number 1) missing .proto file:**

See error in "kong" container Logs:
```
2022/03/29 22:26:36 [debug] 83#0: [kong] process.lua:62 search config for pluginserver named: ocp-gateway-plugin
2022/03/29 22:26:36 [error] 83#0: init_by_lua error: /opt/bitnami/kong/openresty/luajit/share/lua/5.1/protoc.lua:334: module load error: pluginsocket.proto
	pluginsocket.proto: No such file or directory
	./pluginsocket.proto: No such file or directory
	/usr/include/pluginsocket.proto: No such file or directory
	/usr/local/opt/protobuf/include/pluginsocket.proto: No such file or directory
	/usr/local/kong/lib/pluginsocket.proto: No such file or directory
	kong/pluginsocket.proto: No such file or directory
	spec/fixtures/grpc/pluginsocket.proto: No such file or directory
```
This Problem was Resolved by adding this to my Dockerfile:

> RUN mkdir -p /usr/local/kong
> RUN chown 1001:root /usr/local/kong
> RUN chmod 755 /usr/local/kong

Then the next Issue arises.

**Issue Number 2) missing kong file "pluginsocket.proto" (and its dependencies)**

This is thrown in the Logs:
```
2022/03/28 19:51:44 [debug] 80#0: [kong] process.lua:62 search config for pluginserver named: ocp-gateway-plugin
2022/03/28 19:51:44 [error] 80#0: init_by_lua error: /opt/bitnami/kong/openresty/luajit/share/lua/5.1/protoc.lua:334: module load error: pluginsocket.proto
pluginsocket.proto: No such file or directory
./pluginsocket.proto: No such file or directory
/usr/include/pluginsocket.proto: No such file or directory
/usr/local/opt/protobuf/include/pluginsocket.proto: No such file or directory
/usr/local/kong/lib/pluginsocket.proto: No such file or directory
kong/pluginsocket.proto: No such file or directory
spec/fixtures/grpc/pluginsocket.proto: No such file or directory
stack traceback:
[C]: in function 'error'
/opt/bitnami/kong/openresty/luajit/share/lua/5.1/protoc.lua:334: in function 'f'
/opt/bitnami/kong/openresty/luajit/share/lua/5.1/protoc.lua:1152: in function 'do_compile'
/opt/bitnami/kong/openresty/luajit/share/lua/5.1/protoc.lua:1168: in function 'compilefile'
/opt/bitnami/kong/openresty/luajit/share/lua/5.1/protoc.lua:1181: in function 'loadfile'
...jit/share/lua/5.1/kong/runloop/plugin_servers/pb_rpc.lua:202: in function 'load_service'
...jit/share/lua/5.1/kong/runloop/plugin_servers/pb_rpc.lua:291: in function 'new'
...uajit/share/lua/5.1/kong/runloop/plugin_servers/init.lua:136: in function 'get_server_rpc'
...uajit/share/lua/5.1/kong/runloop/plugin_servers/init.lua:238: in function 'build_phases'
...uajit/share/lua/5.1/kong/runloop/plugin_servers/init.lua:285: in function 'get_plugin'
...uajit/share/lua/5.1/kong/runloop/plugin_servers/init.lua:292: in function 'load_plugin'
...g/openresty/luajit/share/lua/5.1/kong/db/dao/plugins.lua:136: in function 'load_plugin_handler'
...g/openresty/luajit/share/lua/5.1/kong/db/dao/plugins.lua:221: in function 'load_plugin'
...g/openresty/luajit/share/lua/5.1/kong/db/dao/plugins.lua:273: in function 'load_plugin_schemas'
...itnami/kong/openresty/luajit/share/lua/5.1/kong/init.lua:543: in function 'init'
init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /opt/bitnami/kong/openresty/luajit/share/lua/5.1/protoc.lua:334: module load error: pluginsocket.proto
pluginsocket.proto: No such file or directory
./pluginsocket.proto: No such file or directory
/usr/include/pluginsocket.proto: No such file or directory
/usr/local/opt/protobuf/include/pluginsocket.proto: No such file or directory
/usr/local/kong/lib/pluginsocket.proto: No such file or directory
kong/pluginsocket.proto: No such file or directory
spec/fixtures/grpc/pluginsocket.proto: No such file or directory
stack traceback:
[C]: in function 'error'
/opt/bitnami/kong/openresty/luajit/share/lua/5.1/protoc.lua:334: in function 'f'
/opt/bitnami/kong/openresty/luajit/share/lua/5.1/protoc.lua:1152: in function 'do_compile'
/opt/bitnami/kong/openresty/luajit/share/lua/5.1/protoc.lua:1168: in function 'compilefile'
/opt/bitnami/kong/openresty/luajit/share/lua/5.1/protoc.lua:1181: in function 'loadfile'
...jit/share/lua/5.1/kong/runloop/plugin_servers/pb_rpc.lua:202: in function 'load_service'
...jit/share/lua/5.1/kong/runloop/plugin_servers/pb_rpc.lua:291: in function 'new'
...uajit/share/lua/5.1/kong/runloop/plugin_servers/init.lua:136: in function 'get_server_rpc'
...uajit/share/lua/5.1/kong/runloop/plugin_servers/init.lua:238: in function 'build_phases'
...uajit/share/lua/5.1/kong/runloop/plugin_servers/init.lua:285: in function 'get_plugin'
...uajit/share/lua/5.1/kong/runloop/plugin_servers/init.lua:292: in function 'load_plugin'
...g/openresty/luajit/share/lua/5.1/kong/db/dao/plugins.lua:136: in function 'load_plugin_handler'
...g/openresty/luajit/share/lua/5.1/kong/db/dao/plugins.lua:221: in function 'load_plugin'
...g/openresty/luajit/share/lua/5.1/kong/db/dao/plugins.lua:273: in function 'load_plugin_schemas'
...itnami/kong/openresty/luajit/share/lua/5.1/kong/init.lua:543: in function 'init'
init_by_lua:3: in main chunk
Error: ...i/kong/openresty/luajit/share/lua/5.1/kong/cmd/start.lua:64: failed to start nginx (exit code: 1)
```

### Additional information

The second issue was Resolved like this:

Insert the missing file (/usr/include/pluginsocket.proto) (with its dependencies) in the proper location:

So I took file "pluginsocket.proto" from the Kong repository, I install the file and its dependencies.

So in my Dockerfile I added:

> RUN apt-get update -y
> RUN apt-get install -y libprotobuf-dev
> COPY pluginsocket.proto /usr/local/kong/lib/pluginsocket.proto
> RUN chown 1001:root /usr/local/kong
> RUN chmod 755 /usr/local/kong

and problem solved. So it seems that the bitnami kong package forgot about installing pluginsocket.proto and its dependencies.

Note that changing the permissions to /usr/local/kong is required or else kong can't create file:

/usr/local/kong/ocp-gateway-plugin.socket

(bad permissions)

Please Note that the latest Kong 2.8 Documentation does NOT mention that KONG_PLUGINS needs to be defined, however it is not, the KongIngressController won't be able to post config to Kong (400 error) as the plugin is then considered to be not installed.

With the work-arounds provided I managed to get my Go plugin to work properly with Bitnami.

**Comment by jocadu** [comment] 2022-04-12 21:13
Hello Fran,

Thanks for answering. 

Yes, my custom plugin "ocp-gateway-plugin" is defined as a KongPlugin CRD (this is a pre-requisite as per Kong documentation)

Most likely the issue with the permissions would be automatically resolved if the second issue is also resolved (by adding missing file in bitnami package)

The root cause of this second issue is that bitnami packaging forgot kong file:

pluginsocket.proto  and its dependencies (package libprotobuf-dev)

In the original kong package, this file is located here:

 /kong/kong/pluginsocket.proto 

If the file is placed where it is expected to be in bitnami packaging:

/usr/local/kong/lib/pluginsocket.proto

and /usr/local/kong/ has proper permissions then both issues will be resolved in one shot.

Would it be possible for you to fix the bitnami/kong package?

Thank you

**Comment by fmulero** [comment] 2022-04-13 07:55
Hi @jocadu

I am checking official kong images and as you mentioned we are missing the protobuf files, but I don't see any package about protobuf installed, so I am not sure if the libprotobuf-dev is a kong requirement or your custom plugin requirement. Have you reproduced this issue with other plugin from the kong hub?

Regards

**Comment by jocadu** [comment] 2022-04-13 12:51
Hi Fran,

If only Kong file "pluginsocket.proto" is placed in "/usr/local/kong/lib/ " exceptions regarding other missing ".proto" files are raised. This gets resolved all at once by installing package " libprotobuf-dev". Now this is the simplest way I could find to resolve the missing "protobuf" dependency issue.

I have not loaded other plugin from the kong hub. 
My plugin works fine with just [kong] but I get the issue reported here when attempting to use the [bitnami/kong] package.

Regards

**Comment by jotamartos** [comment] 2022-04-20 15:23
Hi @jocadu,

I've been reviewing this ticket and found this information that will be useful for you: 

- Creating the "/usr/local/kong" directory shouldn't be necessary, that's the default KONG_PREFIX directory but we change that in the configuration to "/opt/bitnami/kong/server".

```
cat /opt/bitnami/kong/conf/kong.conf | grep "prefix ="
```

You can also see that every time you run a kong command, you get this output 

```
2022/04/20 15:02:56 [verbose] reading config file at /opt/bitnami/kong/conf/kong.conf
```

If you take a look at the "/opt/bitnami/kong/server" directory, it is owned by the user 1001 so kong should be using that directory. Actually, it's kong, when the container runs the "kong start" command, who fills the content of that folder. 

Are you modifying the conf file somehow or the prefix parameter that is making Kong to try to create that directory? If your plugin needs to specify a destination directory, can use the "/opt/bitnami/kong/server" one? 

- Regarding the "pluginsocket.proto" file, we are going to include it inside the "/opt/bitnami/kong/server/lib" directory. Could you please try the following lines as a temporal workaround to see if they work for you? 

```
...
COPY rootfs /
RUN /opt/bitnami/scripts/kong/postunpack.sh

# New lines to include pluginsocket.proto
RUN install_packages libprotobuf-dev
RUN mkdir -p /opt/bitnami/kong/server/lib
COPY pluginsocket.proto /opt/bitnami/kong/server/lib/pluginsocket.proto
RUN chown -R 1001:root /opt/bitnami/kong/server/lib
RUN chmod 755 /opt/bitnami/kong/server/lib
...
```

Does this work for you? kong should find the file and shouldn't need to require the creation of the /usr/local/kong directory structure. As @fmulero mentioned, it'd be great if you can share an example plugin we can use to deploy and test the container/chart with the changes we are going to include in the solution. 

Thanks

**Comment by jotamartos** [comment] 2022-05-04 12:00
Hi @jocadu,

We just published a new version of the Bitnami Kong container with the changes I mentioned above

https://github.com/bitnami/bitnami-docker-kong/commit/e5daf02715dadf0a321a8dd3820e0d3113b9b7a9

The image now includes the `libprotobuf-dev` package and we also copied the `pluginsocket.proto` file to the `/opt/bitnami/kong/server/lib/` folder. 

I'll close this issue but please reopen it if necessary.

Thanks.

**Closed by jotamartos** 2022-05-04 12:00 UTC

**Comment by thanhtai9606** [comment] 2022-10-28 10:20
I wanna install kong-oidc free. But I dont know how to install it inside bitnami/kong
this is sample in kong/kong image and it already working!

> `FROM kong:2.8.1-alpine
> 
> LABEL description="Alpine + Kong  + kong-oidc plugin"
> 
> USER root
> RUN apk update && apk add curl git gcc musl-dev
> RUN luarocks install luaossl OPENSSL_DIR=/usr/local/kong CRYPTO_DIR=/usr/local/kong
> RUN luarocks install --pin lua-resty-jwt
> RUN luarocks install kong-oidc
> 
> USER kong`

**Comment by busyboy77** [comment] 2023-05-19 18:52
@thanhtai9606 -- are you able to configure this oidc plugin?..

We are also stuck with the oidc plugin developed by nokia and bitnami/kong is not picking it up.. not sure it is because of paths or  anything else..

Can someone please guide

**Comment by thanhtai9606** [comment] 2023-05-22 01:26
> @thanhtai9606 -- are you able to configure this oidc plugin?..
> 
> We are also stuck with the oidc plugin developed by nokia and bitnami/kong is not picking it up.. not sure it is because of paths or anything else..
> 
> Can someone please guide

I already make this image public, you can use it! It already added kong-oidc
becamexidc2020/kong-oidc:3.0.0
**I used Bitnam Helm chart to deploy it** 
this is my config, hope it help you!!
[kong.zip](https://github.com/bitnami/charts/files/11526084/kong.zip)

**Comment by busyboy77** [comment] 2023-05-22 07:19
Thanks a lot @thanhtai9606 -- Are you also able to route your ingresses using this image? Ours is not picking up the HTTPS. Can you please share your sample  ingress over HTTPS. if you dont mind it. Please. This will be a huge favor.

Regards,

**Comment by ahsan-raza** [comment] 2023-05-22 09:32
@thanhtai9606 , if possible can you share the git repository for the image you build with oidc plugin. Thanks

**Comment by thanhtai9606** [comment] 2023-05-24 01:18
> Thanks a lot @thanhtai9606 -- Are you also able to route your ingresses using this image? Ours is not picking up the HTTPS. Can you please share your sample ingress over HTTPS. if you dont mind it. Please. This will be a huge favor.
> 
> Regards,

It depend's your ingress, I use Nginx ingress controller. HTTP is default when I use kong-api gateway, 
You can use http://<kong-service-name>:8001 to connect kong-admin. When you wanna expose outside internet, you need external ingress like: nginx, traefik, ambassador,..., With that ingress you can route https or http

**Comment by thanhtai9606** [comment] 2023-05-24 01:21
> @thanhtai9606 , if possible can you share the git repository for the image you build with oidc plugin. Thanks

You can use it, this is an example similarly
[https://dev.to/robincher/securing-your-site-via-oidc-powered-by-kong-and-keycloak-2ccc](url)
I used bitnami/kong:3.0.0 for my purpose, with set up the same
