### ISSUE TITLE
Mongodb-sharded custom user and db is not creating

### ISSUE THREAD

**Issue by pankaj-dahiya** [bitnami/charts#10018] opened 2022-05-04 08:16 UTC
### Name and Version

bitnami/mongo-sharded    ---   version: 5.0.0

### What steps will reproduce the bug?

Assign values to these variables :
```yaml
  username: "pankaj"
  password: "randompassword"
  database: "pankaj"
```

### What is the expected behavior?

We can connect mongob via custom user and password.

### What do you see instead?

Connection failed. Checked by connecting via root password and found that custom user and password are not created.

**Comment by migruiz4** [comment] 2022-05-04 13:00
Hi @pankaj-dahiya,

I'm sorry for the inconvenience. Looks like during the MongoDB standardization (5.0.0) #9829 we accidentally recovered some values that were already removed because of some remaining dead code in the templates.

This issue would be a duplicate of https://github.com/bitnami/charts/issues/1655, where the decision to remove the previously mongodbUsername, mongodbPassword and mongodbDatabase.

I have submitted this PR #10025 removing the unused code.

**Closed** 2022-05-05 07:26 UTC

**Comment by Shilagrawal** [comment] 2022-05-30 05:58
@migruiz4  does this mean that in the latest version user wont have a choice of using mongodbUsername, mongodbPassword and mongodbDatabase ? till what version of chart can use use these values ? I found it useful

**Comment by migruiz4** [comment] 2022-05-30 07:54
Hi @Shilagrawal,

Those values were present in early versions of the mongodb-sharded chart's `values.yaml` but were never implemented in the templates, so there is no version of the chart where these values can be used.

The solution to your problem would be to use an init script. I would suggest checking issue #1665 where you can find several approaches to your use case.

**Comment by Shilagrawal** [comment] 2022-05-30 08:52
> 

While i explore other manual ways, something that I will always wonder is like nearly 2 months back with 4.4.12 or 4.4.13 same option when passed via helm command worked for me and now for same version of charts it dont !!

**Comment by migruiz4** [comment] 2022-05-31 09:26
Hi @Shilagrawal,

These values exist in the `mongodb` chart, but have never been implemented in the `mongodb-sharded` chart.

**Comment by Shilagrawal** [comment] 2022-05-31 11:32
> Hi @Shilagrawal,
> 
> These values exist in the `mongodb` chart, but have never been implemented in the `mongodb-sharded` chart.

Okay, thats strange :) I have been passing it for sharded deployments and it took effect at startup as i ran some read/write operations too with that user
