### ISSUE TITLE
[bitnami/kafka] controller.extraEnvVars doesn’t work

### ISSUE THREAD

**Issue by ahmedkhabkhab** [bitnami/charts#18374] opened 2023-08-11 10:22 UTC
### Name and Version

bitnami/kafka 24.0.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Add an environment variable in `controller.extraEnvVars` with KAFKA_CFG prefix. Example: set `KAFKA_CFG_MIN_INSYNC_REPLICAS` to 2 and `KAFKA_CFG_DEFAULT_REPLICATION_FACTOR` to 3.

### What is the expected behavior?

Kafka parameters change accordingly 

### What do you see instead?

The environment variable are set correctly and are seen by the application (kafka) running in the pod but it doesn’t use it. The `default.replication.factor` and the `min.insync.replicas` are still 1

**Comment by imaboyz** [comment] 2023-08-14 09:31
Hi,
Encountered same issue on my side
The environment variables are set correctly on the pod container
![image](https://github.com/bitnami/charts/assets/142215741/6183e6e2-b701-47cf-ab8e-9499f9ee4933)

but when check the broker config with /opt/bitnami/kafka/bin/kafka-configs.sh utility, found : 

- default.replication.factor=1
- min.insync.replicas=1
- num.partitions=1

Try with both controller.extraEnvVars and broker.extraEnvVars but also with just extraEnvVars  and none of them work.

**Comment by Mauraza** [comment] 2023-08-16 17:08
Hi @ahmedkhabkhab and @imaboyz,

Could you be so kind as to share the logs to the thread? Have you added the variable image.debug=true?

**Comment by HariKalakada** [comment] 2023-08-19 14:21
Same problem for me as well. 
However, for now, I'm relying on "extraConfig" string to set additional parameters seperated by '\n"

**Comment by Mauraza** [comment] 2023-08-22 15:03
Hi @HariKalakada,

Adding to the `extraConfig` parameters is it working?

**Comment by mr-ssd** [comment] 2023-08-23 06:49
Same problem for me as well.

**Comment by pchang388** [comment] 2023-08-23 19:41
same here as well tried using 25.0.0 version that just got released

**Comment by mr-ssd** [comment] 2023-08-24 01:46
@Mauraza 
> Adding to the `extraConfig` parameters is it working?
that working

**Comment by DingGGu** [comment] 2023-08-28 02:49
@Mauraza 

`extraConfig` (that only limited configuration available) and `KAFKA_CFG_` also does not work well either.

```yaml
broker:
  extraConfig:
    numPartitions: 6
```

```
# kafka-config.sh
  num.partitions=1 sensitive=false synonyms={DEFAULT_CONFIG:num.partitions=1}
```


`extraInit` also does not support `KAKFA_CFG_`.

```yaml
extraInit: |
  export KAFKA_CFG_BROKER_RACK=$(curl "http://169.254.169.254/latest/meta-data/placement/availability-zone-id")
```

```
# kafka-config.sh
All configs for broker 102 are:
  broker.rack=null sensitive=false synonyms={}
```

**Comment by DingGGu** [comment] 2023-08-28 06:40
Below solutions will work for now.

```yaml
extraInit: |
  kafka_conf_set "$KAFKA_CONFIG_FILE" "min.insync.replicas" "2"
  KAFKA_CFG_BROKER_RACK=$(curl "http://169.254.169.254/latest/meta-data/placement/availability-zone-id")
  kafka_conf_set "$KAFKA_CONFIG_FILE" "broker.rack" "$KAFKA_CFG_BROKER_RACK"
```

**Comment by Mauraza** [comment] 2023-09-06 15:27
Hi @DingGGu,

Thanks for the contribution!! 
If those variables are needed, and appear in the config file should be added to the 
[enviroment variables](https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.5/debian-11/rootfs/opt/bitnami/scripts/kafka-env.sh) and in the [script](https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.5/debian-11/rootfs/opt/bitnami/scripts/libkafka.sh)

**Comment by mr-ssd** [comment] 2023-09-22 01:46
Is there any plan for this?

**Comment by Mauraza** [comment] 2023-09-22 08:28
Hi @mr-ssd,

We are open to contributions!!! If so, could you be more specific? please

**Comment by Mauraza** [comment] 2023-09-27 09:59
Hi @mr-ssd,

That's right, and is the reason why the extraEnvVars doesn't work. If these variables are needed, it is necessary to update the container scripts.

**Comment by carrodher** [comment] 2023-09-29 07:15
Thank you for submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Comment by joancafom** [comment] 2023-10-02 14:45
Hi all,

Let me shed some light on the topic here 😁 

Since version `24.0.0`, the intended way to specify any additional configuration is by using the `extraConfig` parameters. These params, if specified, will be automatically appended to the configuration file, and rendered (if required):

https://github.com/bitnami/charts/blob/5d6fb6c0c4bfc8f44149e628bb23d33bbd217c7a/bitnami/kafka/templates/broker/configmap.yaml#L44-L45

This change allows to simplify the logic of both the chart and container, while preserving the same feature.

You can see a full, detailed list of the changes introduced in version `24.0.0` in the [upgrade notes section](https://github.com/bitnami/charts/tree/main/bitnami/kafka#to-2400).

---

Having said that, the `extraEnvVars` feature seems to work as intended:

```
$ cat vars.yaml
controller:
  extraEnvVars:
    - name: MY_ENV_VAR
      value: "WORKS"
$ helm install kafka bitnami/kafka -f vars.yaml
$ kubectl exec -it kafka-controller-0 -c kafka -- printenv | grep MY
MY_ENV_VAR=WORKS
```

**Comment by mr-ssd** [comment] 2023-10-03 01:48
@joancafom if so the section here https://github.com/bitnami/charts/blob/main/bitnami/kafka/README.md#setting-custom-parameters should be updated to avoid confusion.
![image](https://github.com/bitnami/charts/assets/9067408/485f8737-b0ec-4bfe-83c8-312965cd1405)

**Closed** 2023-10-09 13:21 UTC
Labels: in-progress, tech-issues, kafka
