### ISSUE TITLE
Chart repository not reachable (DNS Issue)

### ISSUE THREAD

**Issue by arsenetar** [bitnami/charts#13313] opened 2022-11-02 15:27 UTC
### Name and Version

All Charts

### What steps will reproduce the bug?

1. Try loading https://charts.bitnami.com/bitnami
2. Observe DNS error

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Chart repository is reachable at https://charts.bitnami.com/bitnami

### What do you see instead?

In browser `DNS_PROBE_FINISHED_NXDOMAIN`, in helm `dial tcp: lookup charts.bitnami.com on ... : no such host`

### Additional information

nslookup gives the following:
`charts.bitnami.com      canonical name = d1xe8nqhpmcyfh.cloudfront.net.`

**Comment by theyough** [comment] 2022-11-02 15:28
same issue

**Comment by dalbani** [comment] 2022-11-02 15:31
Does Bitnami provide some kind of status page by the way?
I googled for something like that but couldn't find anything.

**Comment by aarnaud** [comment] 2022-11-02 15:31
Seem fix now : http://dns.squish.net/traverses/958c5af6fa063f7bb00db86b71aecb18

But CNAME are in cache for 2h

**Comment by arsenetar** [comment] 2022-11-02 15:37
I can confirm I am now getting good DNS lookups from some locations.

**Comment by tigrantovmasyan** [comment] 2022-11-02 15:57
![Uploading Screen Shot 2022-11-02 at 7.53.28 PM.png…]()

**Comment by tigrantovmasyan** [comment] 2022-11-02 15:57
<img width="1113" alt="Screen Shot 2022-11-02 at 7 53 28 PM" src="https://user-images.githubusercontent.com/4698738/199538765-3f94bf01-d985-437e-90d6-0f87de85cf44.png">

**Comment by vinoth-kumar-k** [comment] 2022-11-02 15:58
I am still hitting errors too.

> │ Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: Get "https://charts.bitnami.com/bitnami/index.yaml": dial tcp: lookup charts.bitnami.com on [fe80::1%en0]:53: no such host

**Comment by Bjego** [comment] 2022-11-02 16:01
Yes - you have to flush DNS. Then the issue should be solved. Having the same issue..

**Comment by PallidPajeet** [comment] 2022-11-02 16:03
hello sir when will the issue be of the fix sir? my koobyneet is now in the broke??

**Comment by WarheadsSE** [comment] 2022-11-02 16:05
Recommendation: LOCK, and add comment from maintainers.

DNS is repopulating, and the issue is resolved. 

Flush your caches, if necessary. For confirmation, use `dig` pointed at a an upstream core provider.

**Comment by shiftbase-tvanriel** [comment] 2022-11-02 16:17
hello i of the call have google and they are not assist?? why?  pls respond

**Comment by hunj** [comment] 2022-11-02 16:22
Had to re-run the command a few times to have the DNS propagate to the new URL

**Comment by vinoth-kumar-k** [comment] 2022-11-02 16:24
my DNS was still hitting old distribution. Updating the nameserver to 8.8.4.4 did the trick for me. thanks, guys.

**Comment by carrodher** [comment] 2022-11-02 17:09
Thanks for reporting this issue. It was a problem in the CloudFront distribution that we used for the Charts repository.

The problem is that terraform recreated the CloudFront collection, creating a new DNS endpoint that needed to replicate globally. A small number of [DNS](https://dnschecker.org/#CNAME/charts.bitnami.com) are still resolving the old CloudFront collection name, but for the most part, the issue should be fixed shortly.

**Comment by dishi-github** [comment] 2022-11-02 17:35
I ran the following commands but still got the same issue. Am I missing anything?

```
dig @8.8.4.4 charts.bitnami.com
helm fetch bitnami/keycloak
```
I ran the commands multiple times/ fresh session.

**Comment by moeketsichristopher** [comment] 2022-11-02 17:36
@codablock  I can resolve the host:

```
charts.bitnami.com	canonical name = dqk9m89za31r9.cloudfront.net.
Name:	dqk9m89za31r9.cloudfront.net
Address: 13.224.222.45
Name:	dqk9m89za31r9.cloudfront.net
Address: 13.224.222.114
Name:	dqk9m89za31r9.cloudfront.net
Address: 13.224.222.14
Name:	dqk9m89za31r9.cloudfront.net
Address: 13.224.222.43
```
but this is what I a getting now:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>HHMZQEDQG4YQYWYN</RequestId>
<HostId>DlkCXrmgUG/XbFqq5S2pGyUULA3Q3vAYKRyzRmFLO6EkSe+btS4dA9aRlpyb2m+bivvsoy9unSU=</HostId>
</Error>
```

I am not sure if this is a new issue.

**Comment by sumesh-aot** [comment] 2022-11-02 23:04
Same issue here:
```
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "https://charts.bitnami.com/bitnami/postgresql" chart repository:
	failed to fetch https://charts.bitnami.com/bitnami/postgresql/index.yaml : 403 Forbidden

```

**Comment by aarnaud** [comment] 2022-11-03 00:25
> Same issue here:
> ```
> Getting updates for unmanaged Helm repositories...
> ...Unable to get an update from the "https://charts.bitnami.com/bitnami/postgresql" chart repository:
> 	failed to fetch https://charts.bitnami.com/bitnami/postgresql/index.yaml : 403 Forbidden
> 
> ```

not related, 403 Forbidden mean your reach the endpoint.

this issue was about DNS issues not permissions.

**Comment by sumesh-aot** [comment] 2022-11-03 00:35
> > Same issue here:
> > ```
> > Getting updates for unmanaged Helm repositories...
> > ...Unable to get an update from the "https://charts.bitnami.com/bitnami/postgresql" chart repository:
> > 	failed to fetch https://charts.bitnami.com/bitnami/postgresql/index.yaml : 403 Forbidden
> > ```
> 
> not related, 403 Forbidden mean your reach the endpoint.
> 
> this issue was about DNS issues not permissions.

Thanks. Thought it is be related, charts were working few days back. We are using postgres chart as a dependency. I will see if there is another ticket, or will report one for 403.

**Closed** 2022-11-03 08:53 UTC
Labels: triage, tech-issues

**Comment by julien-michaud** [comment] 2022-11-04 10:48
getting the same error as @sumesh-aot with the prestashop chart, nothing has changed on our end and since this morning I im getting 403

**Comment by tal-ayalon** [comment] 2022-12-20 15:33
Getting error:
<img width="1700" alt="image" src="https://user-images.githubusercontent.com/74187228/208704704-4a08cc68-c198-40ec-88a6-86d8eba1f6fc.png">

**Comment by carrodher** [comment] 2022-12-20 17:36
> Getting error: <img alt="image" width="1700" src="https://user-images.githubusercontent.com/74187228/208704704-4a08cc68-c198-40ec-88a6-86d8eba1f6fc.png">

You are missing the `/bitnami` at the end of the URL, the proper command should be:
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories
```

**Comment by tal-ayalon** [comment] 2022-12-21 10:20
@carrodher Still getting errors:
<img width="1694" alt="image" src="https://user-images.githubusercontent.com/74187228/208881712-d9195879-3a8a-4c7c-89e2-49d6df84679f.png">
If I'm using the `--insecure-skip-tls-verify` flag than it will work

**Comment by oomgomgxx** [comment] 2023-12-30 10:03
The problem still exists
