### ISSUE TITLE
[bitnami/zookeeper] Cannot create fresh install with volumePermissions.enabled=true

### ISSUE THREAD

**Issue by johnymbr** [bitnami/charts#9186] opened 2022-02-23 18:54 UTC
### Name and Version

bitnami/zookeeper 8.0.3

### What steps will reproduce the bug?

1. On a fresh install
2. helm install bitnami/zookeeper --generate-name --set volumePermissions.enabled=true

The init container on the Kafka broker will fail with the following error:

```
/bin/chown: missing operand after '1001:1001'
Try '/bin/chown --help' for more information.
```
The issue is on a fresh PVC the chown command fails.

Current code:
```
mkdir -p /bitnami/zookeeper
find /bitnami/zookeeper -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs chown -R {{ .Values.containerSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }}

{{- if .Values.dataLogDir }}
mkdir -p {{ .Values.dataLogDir }}
find {{ .Values.dataLogDir }} -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs chown -R {{ .Values.containerSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }}
```

### Are you using any custom parameters or values?

volumePermissions.enabled=true

### What is the expected behavior?

The Zookeeper is successfully initialized.

### What do you see instead?

The volume permissions init container crashes because the chown command is invalid.

### Additional information

In the chart [bitnami/kafka] the same error was reported, follow the link: [https://github.com/bitnami/charts/issues/9126](https://github.com/bitnami/charts/issues/9126).
This bug has been resolved on that chart, but still exists on chart of zookeeper.

**Comment by juan131** [comment] 2022-02-24 08:02
Duplicate of https://github.com/bitnami/charts/issues/9126 and fixed at https://github.com/bitnami/charts/pull/9134

**Closed by juan131** 2022-02-24 08:02 UTC

**Comment by johnymbr** [comment] 2022-02-24 10:58
Thanks for the feedback, @juan131.
