### ISSUE TITLE
[bitnami/harbor] Harbor config does not work with bitnami/redis with Sentinel auth enabled

### ISSUE THREAD

**Issue by RichardSufliarsky** [bitnami/charts#11266] opened 2022-07-20 08:09 UTC
### Name and Version

bitnami/harbor, appVersion: 2.5.3, version: 15.0.0

### What steps will reproduce the bug?

Want to use bitnami/harbor helm chart with bitnami/redis helm chart with Sentinel auth enabled.
Redis chart is deployed and Sentinel authentication works (tested via command line).
When deploying harbor chart with external Redis config, Harbor Core can't connect to Redis.
```yaml
externalRedis:
  host: ""
  port: 6379
  password: "rEdIs.PaS3"
  coreDatabaseIndex: '10'
  jobserviceDatabaseIndex: '11'
  registryDatabaseIndex: '12'
  chartmuseumDatabaseIndex: '13'
  trivyAdapterDatabaseIndex: '14'
  sentinel:
    enabled: true
    masterSet: 'k8s123'
    hosts: "redis-sentinels-node-0.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379,redis-sentinels-node-1.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379,redis-sentinels-node-2.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379"
```

### Are you using any custom parameters or values?

Sentinel authentication is enabled in bitnami/redis chart.

### What is the expected behavior?

Harbor Core should connect to Redis using Sentinel.

### What do you see instead?

```
2022-07-20T07:58:07Z [DEBUG] [/lib/redis/redisclient.go:66]: get redis pool:efcd66f81e42e3a31f0ace7be94093f809d7eecacc7358aea14c787fdabe0519redis+sentinel://rEdIs.PaS3@redis-sentinels-node-0.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379,redis-sentinels-node-1.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379,redis-sentinels-node-2.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379/k8s123/10
2022-07-20T07:58:07Z [DEBUG] [/lib/redis/redisclient.go:101]: getSentinelPool:redis+sentinel://rEdIs.PaS3@redis-sentinels-node-0.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379,redis-sentinels-node-1.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379,redis-sentinels-node-2.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379/k8s123/10
2022-07-20T07:58:07Z [DEBUG] [/lib/redis/redisclient.go:104]: efcd66f81e42e3a31f0ace7be94093f809d7eecacc7358aea14c787fdabe0519sentinel DialConnectionTimeout:1s
2022-07-20T07:58:07Z [DEBUG] [/lib/redis/redisclient.go:108]: efcd66f81e42e3a31f0ace7be94093f809d7eecacc7358aea14c787fdabe0519sentinel DialReadTimeout:2s
2022-07-20T07:58:07Z [DEBUG] [/lib/redis/redisclient.go:112]: efcd66f81e42e3a31f0ace7be94093f809d7eecacc7358aea14c787fdabe0519sentinel DialWriteTimeout:5s
2022-07-20T07:58:07Z [DEBUG] [/lib/redis/redisclient.go:121]: efcd66f81e42e3a31f0ace7be94093f809d7eecacc7358aea14c787fdabe0519redis has password
2022-07-20T07:58:07Z [DEBUG] [/lib/redis/redisclient.go:142]: efcd66f81e42e3a31f0ace7be94093f809d7eecacc7358aea14c787fdabe0519dial redis sentinel:redis-sentinels-node-0.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379
2022-07-20T07:58:07Z [DEBUG] [/lib/redis/redisclient.go:142]: efcd66f81e42e3a31f0ace7be94093f809d7eecacc7358aea14c787fdabe0519dial redis sentinel:redis-sentinels-node-1.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379
2022-07-20T07:58:07Z [DEBUG] [/lib/redis/redisclient.go:142]: efcd66f81e42e3a31f0ace7be94093f809d7eecacc7358aea14c787fdabe0519dial redis sentinel:redis-sentinels-node-2.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379
2022-07-20T07:58:07Z [ERROR] [/lib/cache/cache.go:110]: failed to ping redis+sentinel://redis:xxxxx@redis-sentinels-node-0.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379,redis-sentinels-node-1.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379,redis-sentinels-node-2.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379/k8s123/10, retry after 500ms : redigo: no sentinels available; last error: NOAUTH Authentication required.
```

### Additional information

This issue https://github.com/goharbor/harbor/issues/16907 contains info that goharbor/registry-photon:v2.5.1 image should work with Sentinel authentication enabled.

**Comment by marcosbc** [comment] 2022-07-27 06:37
Hi @RichardSufliarsky, this seems to be a limitation of the Harbor project. It has been reported in https://github.com/goharbor/harbor/issues/14757, feel free to subscribe to the issue.

**Comment by RichardSufliarsky** [comment] 2022-07-27 08:32
Hi @marcosbc, did you check the issue https://github.com/goharbor/harbor/issues/16907 that I mentioned in additional info when I opened this one?

**Comment by marcosbc** [comment] 2022-08-02 16:41
@RichardSufliarsky It seems like they are referring to the harbor-registryctl container, but you were reporting issues with harbor-core. Also, it doesn't seem like there is a specific fix for the chart, but for the binaries. If that is the case, Bitnami's 2.5.1 should work exactly the same as upstream Harbor as we compile them in the same way.

Have you tried to reproduce the issue with the official Harbor images, to see if it is still happening?

**Comment by RichardSufliarsky** [comment] 2022-08-04 09:07
So I have turned Redis Sentinel auth on again and found out that official Harbor images are not working either (goharbor/harbor v1.9.3 helm chart). At least they work with multiple Sentinels as I was not able to make bitnami helm chart work with them (https://github.com/bitnami/charts/issues/11354#issuecomment-1199794508).
Regarding which containers, it is little bit complicated as core, registry and jobservice are using redis in my case and it seems that each is doing it on its own way. 
I will continue on goharbor's github as there are two issues open regarding sentinel auth and am currently running on their helm chart:
https://github.com/goharbor/harbor/issues/14757
https://github.com/goharbor/harbor/issues/17244

Feel free to close this one.

**Comment by marcosbc** [comment] 2022-08-05 15:06
Thanks for the update! I will close this issue in the meantime, but hopefully this issue gets resolved soon on Harbor's side.

**Closed by marcosbc** 2022-08-05 15:06 UTC
Labels: in-progress, tech-issues, harbor
