### ISSUE TITLE
[bitnami/mysql] Error with executing "common.labels.standard"

### ISSUE THREAD

**Issue by mjasnowski** [bitnami/charts#18839] opened 2023-08-24 15:55 UTC
### Name and Version

bitnami/mysql 9.12

### What architecture are you using?

amd64

### What steps will reproduce the bug?

MacOS
Helm 3.12
Go: 1.20

We have some in-house CLI that deploys our K8s Microservices using helm.  In this case the services use the bitnami/mysql charts for RDS configuration (dbname, username, etc.) along with its own service specific chart.

I see: https://github.com/bitnami/charts/commit/1e57297dcce21795a8b6b16f3efb5b9c074e62b0 was merged recently but not sure if released.  We did pick up that version though.  I also saw that https://github.com/bitnami/charts/pull/18154 was merged and mentions updating existing charts to be compatible with the aforementioned change. 

### Are you using any custom parameters or values?

None specifically

### What is the expected behavior?

Expected behavior is existing chart(s) works and service its deployed into cluster when using Bitnam/mysql

### What do you see instead?

```
helm | Error: template: notification/charts/mysql/templates/primary/svc.yaml:11:14: executing "notification/charts/mysql/templates/primary/svc.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: notification/charts/localstack/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: notification/charts/localstack/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
helm | helm.go:84: [debug] template: notification/charts/mysql/templates/primary/svc.yaml:11:14: executing "notification/charts/mysql/templates/primary/svc.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: notification/charts/localstack/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: notification/charts/localstack/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

### Additional information

Pinning bitnami/mysql chart to 9.11.2 removes the error:
```
- name: mysql
    repository: "https://charts.bitnami.com/bitnami"
    version: '9.11.2'
    condition: mysql.local
```

**Comment by juan131** [comment] 2023-08-25 08:52
Hi @mjasnowski

Could you please share your `Chart.lock` file?

**Comment by jouve** [comment] 2023-08-27 18:43
looks like the same issue as #18890

**Comment by juan131** [comment] 2023-08-28 06:37
Correct @jouve! It's very likely @mjasnowski needs to update the chart deps to ensure charts using the latest common version are used, which is compatible with both new old and new formats.
That's why I requested to share the `Chart.lock`.

**Comment by mjasnowski** [comment] 2023-08-29 16:53
> Correct @jouve! It's very likely @mjasnowski needs to update the chart deps to ensure charts using the latest common version are used, which is compatible with both new old and new formats.
> That's why I requested to share the `Chart.lock`.

Ack, makes sense, let me find it

**Comment by mjasnowski** [comment] 2023-08-29 17:10
> Hi @mjasnowski
> 
> Could you please share your `Chart.lock` file?

```
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.9.0
digest: sha256:416ad278a896f0e9b51d5305bef5d875c7cca6fbb64b75e1f131b04763e2aff9
generated: "2023-08-22T14:23:05.454524+02:00"
```

**Comment by juan131** [comment] 2023-08-30 06:29
The problem is that localstack is referencing an old version of Bitnami common that's not compatible with the changes we recently introduced in MySQL.

As you can see in the link below, when several charts have the same library chart as dependency but using different versions weird things can happen since the same template is declared twice with the same name but you can't tell which one will be loaded last and, therefore, used.

- https://github.com/helm/helm/issues/11561

I'd open an issue at https://github.com/localstack/helm-charts/issues requesting them to update their dependencies so they use the latest Bitnami common library.

**Comment by mjasnowski** [comment] 2023-08-30 15:24
> The problem is that localstack is referencing an old version of Bitnami common that's not compatible with the changes we recently introduced in MySQL.
> 
> As you can see in the link below, when several charts have the same library chart as dependency but using different versions weird things can happen since the same template is declared twice with the same name but you can't tell which one will be loaded last and, therefore, used.
> 
> * [Dependency charts with same library chart, but different version, have unexpected behavior helm/helm#11561](https://github.com/helm/helm/issues/11561)
> 
> I'd open an issue at https://github.com/localstack/helm-charts/issues requesting them to update their dependencies so they use the latest Bitnami common library.

Ack, TY for taking a look.  will proceed as suggested.

**Comment by mjasnowski** [comment] 2023-08-30 16:08
> The problem is that localstack is referencing an old version of Bitnami common that's not compatible with the changes we recently introduced in MySQL.
> 
> As you can see in the link below, when several charts have the same library chart as dependency but using different versions weird things can happen since the same template is declared twice with the same name but you can't tell which one will be loaded last and, therefore, used.
> 
> * [Dependency charts with same library chart, but different version, have unexpected behavior helm/helm#11561](https://github.com/helm/helm/issues/11561)
> 
> I'd open an issue at https://github.com/localstack/helm-charts/issues requesting them to update their dependencies so they use the latest Bitnami common library.

@juan131  I've opened https://github.com/localstack/helm-charts/issues/92 to follow up.

**Comment by juan131** [comment] 2023-08-31 07:10
> @juan131 I've opened https://github.com/localstack/helm-charts/issues/92 to follow up.

Yes... Latest release of LocalStack uses `2.2` and we need it to use `2.9`

> @juan131 I've opened https://github.com/localstack/helm-charts/issues/92 to follow up

Awesome!!

**Comment by mjasnowski** [comment] 2023-08-31 16:05
> > I did try the latest release of the LocalStack chart (on 2.2 of Bitnami/Common) but no dice.
> 
> Yes... Latest release of LocalStack uses `2.2` and we need it to use `2.9`
> 
> > @juan131 I've opened [localstack/helm-charts#92](https://github.com/localstack/helm-charts/issues/92) to follow up
> 
> Awesome!!

LocalStack folks work quick, they've deployed a new release 0.63 for https://github.com/localstack/helm-charts/pull/93 I've pulled down the new local stack chart and confirmed the issue is resolved on our end.

**Comment by juan131** [comment] 2023-09-01 06:17
this is awesome!! I'm glad LocalStack performed a release so fast! I proceed to close the issue, but feel free to reopen it if you require further assistance.

**Closed by juan131** 2023-09-01 06:17 UTC
Labels: in-progress, tech-issues, mysql
