### ISSUE TITLE
Apache spark chart fails with Error: requirements.lock is out of sync with requirements.yaml

### ISSUE THREAD

**Issue by lpamlie** [bitnami/charts#4034] opened 2020-10-16 09:57 UTC
**Which chart**:
spark/master

**Describe the bug**
helm install fails with helm 2

**To Reproduce**
run helm install my-release bitnami/spark

**Expected behavior**
spark installed

**Version of Helm and Kubernetes**:
helm 2
kubernetes 1.17

- Output of `helm version`:

```
Error: requirements.lock is out of sync with requirements.yaml
```

- Output of `kubectl version`:

```
N/A
```

**Additional context**
seems to be similar to this https://github.com/bitnami/charts/issues/3643

**Comment by andresbono** [comment] 2020-10-16 13:14
Hi @lpamlie, I couldn't reproduce the issue with the latest version of the chart (`3.0.2`):

```
helm repo update
helm dep update
helm install --name my-release bitnami/spark
```

Is there any reason to stick to Helm version 2?

**Comment by lpamlie** [comment] 2020-10-16 13:18
Hi.  We're running FluxCD and we have helm 2 in our cluster.  Plan to upgrade but haven't yet.  I created a PR.

Thanks

**Comment by joancafom** [comment] 2020-10-19 10:16
Closing this as the changes in the associated PR (which solved the issue) were implemented in https://github.com/bitnami/charts/commit/9a042b7b51b5f778a35986f5732bcee6570155c5

Thanks for your issue!

**Closed by joancafom** 2020-10-19 10:16 UTC
