### ISSUE TITLE
[bitnami/mysql] ERROR InnoDB Cannot create redo log files.

### ISSUE THREAD

**Issue by DFazeli** [bitnami/charts#12471] opened 2022-09-17 17:26 UTC
### Name and Version

bitnami/mysql  9.3.3

### What steps will reproduce the bug?

`helm upgrade --install mysql  -n db  bitnami/mysql -f ./mysql.yaml`

### Are you using any custom parameters or values?
```
image:
  registry: docker.io
  repository: bitnami/mysql
  tag: 8.0.30-debian-11-r15
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: true
architecture: standalone
livenessProbe:
    enabled: true
    initialDelaySeconds: 300
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 30
    successThreshold: 1
livenessProbe:
    enabled: true
    initialDelaySeconds: 300
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 30
    successThreshold: 1
livenessProbe:
    enabled: true
    initialDelaySeconds: 300
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 30
    successThreshold: 1
persistence:
      enabled: true
      storageClass: "csi-rbd-sc"
      annotations: {}
      accessModes:
        - ReadWriteOnce
      size: 12Gi
volumePermissions:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 11-debian-11-r32
    digest: ""
    pullPolicy: IfNotPresent
```
### What is the expected behavior?
Up and Running  MySQL

### What do you see instead?
First time I have this `log` 
```
mysql 17:58:15.38 Welcome to the Bitnami mysql container
mysql 17:58:15.38 Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 17:58:15.39 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 17:58:15.39
mysql 17:58:15.40 INFO  ==> ** Starting MySQL setup **
mysql 17:58:15.44 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 17:58:15.45 INFO  ==> Initializing mysql database
mysql 17:58:15.45 DEBUG ==> Ensuring expected directories/files exist
mysql 17:58:15.50 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 17:58:15.51 DEBUG ==> Cleaning data directory to ensure successfully initialization
mysql 17:58:15.52 INFO  ==> Installing database
2022-09-17T17:58:15.562666Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
2022-09-17T17:58:15.562688Z 0 [System] [MY-013169] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.30) initializing of server in progress as process 33
2022-09-17T17:58:15.565098Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2022-09-17T17:58:15.565126Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8mb3_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
2022-09-17T17:58:16.146122Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-09-17T18:01:56.029936Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
```
## and after about 10 min restart container and then this error:
```
mysql 17:20:34.78
mysql 17:20:34.78 Welcome to the Bitnami mysql container
mysql 17:20:34.79 Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 17:20:34.79 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 17:20:34.80
mysql 17:20:34.81 INFO  ==> ** Starting MySQL setup **
mysql 17:20:34.85 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 17:20:37.07 INFO  ==> Initializing mysql database
mysql 17:20:37.08 DEBUG ==> Ensuring expected directories/files exist
mysql 17:20:37.71 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 17:20:37.72 INFO  ==> Using persisted data
mysql 17:20:37.79 INFO  ==> Running mysql_upgrade
mysql 17:20:37.82 INFO  ==> Starting mysql in background
2022-09-17T17:20:38.299693Z 0 [Warning] [MY-011068] [Server] The syntax 'skip_slave_start' is deprecated and will be removed in a future release. Please use skip_replica_start instead.
2022-09-17T17:20:38.300062Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
2022-09-17T17:20:38.300118Z 0 [System] [MY-010116] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.30) starting as process 48
2022-09-17T17:20:38.307163Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2022-09-17T17:20:38.307199Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8mb3_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
2022-09-17T17:20:38.321154Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-09-17T17:20:39.628862Z 1 [ERROR] [MY-012960] [InnoDB] Cannot create redo log files because data files are corrupt or the database was not shut down cleanly after creating the data files.
2022-09-17T17:20:40.073494Z 1 [ERROR] [MY-010334] [Server] Failed to initialize DD Storage Engine
2022-09-17T17:20:40.074385Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
2022-09-17T17:20:40.074450Z 0 [ERROR] [MY-010119] [Server] Aborting
2022-09-17T17:20:40.076065Z 0 [System] [MY-010910] [Server] /opt/bitnami/mysql/bin/mysqld: Shutdown complete (mysqld 8.0.30)  Source distribution.
```
## Update, I change Probs valuse and mysql stuck this step:
```
 startupProbe:
    enabled: true
    initialDelaySeconds: 2000
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 5
    successThreshold: 1
readinessProbe:
    enabled: true
    initialDelaySeconds: 650
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 30
    successThreshold: 1
livenessProbe:
    enabled: true
    initialDelaySeconds: 300
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
```
```
mysql 09:29:21.81 INFO  ==> ** Starting MySQL setup **
mysql 09:29:21.87 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 09:29:21.89 INFO  ==> Initializing mysql database
mysql 09:29:21.90 DEBUG ==> Ensuring expected directories/files exist
mysql 09:29:21.95 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 09:29:21.96 INFO  ==> Using persisted data
mysql 09:29:22.07 INFO  ==> Running mysql_upgrade
mysql 09:29:22.09 INFO  ==> Starting mysql in background
2022-09-18T09:29:22.539615Z 0 [Warning] [MY-011068] [Server] The syntax 'skip_slave_start' is deprecated and will be removed in a future release. Please use skip_replica_start instead.
2022-09-18T09:29:22.539910Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
2022-09-18T09:29:22.539944Z 0 [System] [MY-010116] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.30) starting as process 49
2022-09-18T09:29:22.546752Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2022-09-18T09:29:22.546779Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8mb3_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
2022-09-18T09:29:22.563979Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-09-18T09:31:03.769048Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2022-09-18T09:31:09.786204Z 4 [System] [MY-013381] [Server] Server upgrade from '80030' to '80030' started.

**Comment by migruiz4** [comment] 2022-09-20 15:00
Hi @DFazeli,

Did you provide the correct values? Although you are using `architecture: standalone`, values must be provided under `primary.*` in order to take effect. In this case, `persistence` and Probes settings would not take effect unless you provide them using `primary.persistence` and `primary.livenessProbe`.

In addition, is it possible you have data from a previous installation? In order to perform a fresh install, make sure you remove the persistent volumes from any prior installation using the same release name.

**Comment by DFazeli** [comment] 2022-09-21 12:51
Hi @migruiz4 
my `Values.yaml:`
```
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: "csi-rbd-sc"
kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
clusterDomain: cluster.local
commonAnnotations: {}
commonLabels: {}
extraDeploy: []
diagnosticMode:
  enabled: false
  command:
    - sleep
  args:
    - infinity
image:
  registry: docker.io
  repository: infra/mysql
  tag: 8.0.30-debian-11-r15
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: true
architecture: standalone
auth:
  rootPassword: "123abc"
  createDatabase: false
  database: "my_database"
  username: ""
  password: ""
  replicationUser: replicator
  replicationPassword: ""
  existingSecret: ""
  usePasswordFiles: false
  customPasswordFiles: {}
initdbScripts: {}
initdbScriptsConfigMap: ""
primary:
  name: primary
  command: []
  args: []
  lifecycleHooks: {}
  hostAliases: []
  configuration: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=0
    slow_query_log_file=/opt/bitnami/mysql/logs/mysqld.log
    long_query_time=10.0
    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
  existingConfigmap: ""
  updateStrategy:
    type: RollingUpdate
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  topologySpreadConstraints: []
  podManagementPolicy: ""
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 50
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 30
    successThreshold: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 300
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 20
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraFlags: ""
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  persistence:
    enabled: true
    existingClaim: ""
    storageClass: "csi-rbd-sc"
    annotations: {}
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    selector: {}
  extraVolumes: []
  extraVolumeMounts: []
  initContainers: []
  sidecars: []
  service:
    type: ClusterIP
    ports:
      mysql: 3306
    nodePorts:
      mysql: ""
    clusterIP: ""
    loadBalancerIP: ""
    externalTrafficPolicy: Cluster
    loadBalancerSourceRanges: []
    extraPorts: []
    annotations: {}
    sessionAffinity: None
    sessionAffinityConfig: {}
  pdb:
    create: false
    minAvailable: 1
    maxUnavailable: ""
  podLabels: {}
secondary:
  name: secondary
  replicaCount: 1
  hostAliases: []
  command: []
  args: []
  lifecycleHooks: {}
  configuration: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=0
    slow_query_log_file=/opt/bitnami/mysql/logs/mysqld.log
    long_query_time=10.0
    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
  existingConfigmap: ""
  updateStrategy:
    type: RollingUpdate
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  schedulerName: ""
  terminationGracePeriodSeconds: ""
  topologySpreadConstraints: []
  podManagementPolicy: ""
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  startupProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  extraFlags: ""
  extraEnvVars: []
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  persistence:
    enabled: true
    storageClass: "csi-rbd-sc"
    annotations: {}
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    selector: {}
  extraVolumes: []
  extraVolumeMounts: []
  initContainers: []
  sidecars: []
  service:
    type: ClusterIP
    ports:
      mysql: 3306
    nodePorts:
      mysql: ""
    clusterIP: ""
    loadBalancerIP: ""
    externalTrafficPolicy: Cluster
    loadBalancerSourceRanges: []
    extraPorts: []
    annotations: {}
    sessionAffinity: None
    sessionAffinityConfig: {}
  pdb:
    create: false
    minAvailable: 1
    maxUnavailable: ""
  podLabels: {}
serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: true
rbac:
  create: false
  rules: []
networkPolicy:
  enabled: false
  allowExternal: true
  explicitNamespacesSelector: {}
volumePermissions:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 11-debian-11-r32
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: {}
metrics:
  enabled: false
  image:
    registry: kuber.repo.local
    repository: infra/mysqld-exporter
    tag: 0.14.0-debian-11-r33
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
  service:
    type: ClusterIP
    port: 9104
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.port }}"
  extraArgs:
    primary: []
    secondary: []
  resources:
    limits: {}
    requests: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  serviceMonitor:
    enabled: false
    namespace: ""
    jobLabel: ""
    interval: 30s
    scrapeTimeout: ""
    relabelings: []
    metricRelabelings: []
    selector: {}
    honorLabels: false
    labels: {}
    annotations: {}
  prometheusRule:
    enabled: false
    namespace: ""
    additionalLabels: {}
    rules: []
```

**Comment by migruiz4** [comment] 2022-09-22 15:05
Hi @DFazeli,

Thank you for sharing the values.yaml

The only customization I see is the different storageClass and Probes' initialDelaySeconds set to 50.

From your logs, I have noticed that  InnoDB took more than 3 minutes to initialize in a first start:
```
2022-09-17T17:58:16.146122Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-09-17T18:01:56.029936Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
```

And I do not see the final `** Starting MySQL **` log when Mysql finishes its first setup.
It is possible that the storageClass is too slow for the current liveness/readiness probes timers, and you may need to increase the initialDelaySeconds even more.

Below you can see the logs from a finished initialization with debug enabled:
```
mysql 15:01:20.23 
mysql 15:01:20.24 Welcome to the Bitnami mysql container
mysql 15:01:20.24 Subscribe to project updates by watching https://github.com/bitnami/containers
mysql 15:01:20.24 Submit issues and feature requests at https://github.com/bitnami/containers/issues
mysql 15:01:20.24 
mysql 15:01:20.24 INFO  ==> ** Starting MySQL setup **
mysql 15:01:20.26 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mysql 15:01:20.27 INFO  ==> Initializing mysql database
mysql 15:01:20.27 DEBUG ==> Ensuring expected directories/files exist
mysql 15:01:20.28 WARN  ==> The mysql configuration file '/opt/bitnami/mysql/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
mysql 15:01:20.29 DEBUG ==> Cleaning data directory to ensure successfully initialization
mysql 15:01:20.29 INFO  ==> Installing database
2022-09-22T15:01:20.309362Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
2022-09-22T15:01:20.309375Z 0 [System] [MY-013169] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.30) initializing of server in progress as process 33
2022-09-22T15:01:20.310379Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2022-09-22T15:01:20.310386Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8mb3_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
2022-09-22T15:01:20.315800Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-09-22T15:01:20.643998Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2022-09-22T15:01:21.692814Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
mysql 15:01:23.81 INFO  ==> Starting mysql in background
2022-09-22T15:01:24.042744Z 0 [Warning] [MY-011068] [Server] The syntax 'skip_slave_start' is deprecated and will be removed in a future release. Please use skip_replica_start instead.
2022-09-22T15:01:24.042838Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
2022-09-22T15:01:24.042851Z 0 [System] [MY-010116] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.30) starting as process 88
2022-09-22T15:01:24.044778Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2022-09-22T15:01:24.044784Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8mb3_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
2022-09-22T15:01:24.050653Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-09-22T15:01:24.155616Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2022-09-22T15:01:24.360430Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2022-09-22T15:01:24.360484Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2022-09-22T15:01:24.379867Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /tmp/mysqlx.sock
2022-09-22T15:01:24.379982Z 0 [System] [MY-010931] [Server] /opt/bitnami/mysql/bin/mysqld: ready for connections. Version: '8.0.30'  socket: '/opt/bitnami/mysql/tmp/mysql.sock'  port: 3306  Source distribution.
mysql 15:01:25.82 DEBUG ==> Executing SQL command:
select 1
1
mysql 15:01:25.83 INFO  ==> Configuring authentication
mysql 15:01:25.84 DEBUG ==> Executing SQL command:
DELETE FROM mysql.user WHERE user not in ('mysql.sys','mariadb.sys');
mysql 15:01:25.85 DEBUG ==> Configuring root user credentials
mysql 15:01:25.86 DEBUG ==> Executing SQL command:
-- create admin user
create user 'root'@'%' identified by "123abc";
grant all on *.* to 'root'@'%' with grant option;
flush privileges;
mysql 15:01:25.88 DEBUG ==> removing the unknown user
mysql 15:01:25.89 DEBUG ==> Executing SQL command:
select Host from user where User='';
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql 15:01:25.92 INFO  ==> Running mysql_upgrade
mysql 15:01:25.92 INFO  ==> Stopping mysql
2022-09-22T15:01:25.929297Z 0 [System] [MY-013172] [Server] Received SHUTDOWN from user <via user signal>. Shutting down mysqld (Version: 8.0.30).
2022-09-22T15:01:26.791172Z 0 [System] [MY-010910] [Server] /opt/bitnami/mysql/bin/mysqld: Shutdown complete (mysqld 8.0.30)  Source distribution.
mysql 15:01:26.93 DEBUG ==> Waiting for mysql to unlock db files
mysql 15:01:26.94 INFO  ==> Starting mysql in background
2022-09-22T15:01:27.172314Z 0 [Warning] [MY-011068] [Server] The syntax 'skip_slave_start' is deprecated and will be removed in a future release. Please use skip_replica_start instead.
2022-09-22T15:01:27.172407Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
2022-09-22T15:01:27.172473Z 0 [System] [MY-010116] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.30) starting as process 196
2022-09-22T15:01:27.174446Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2022-09-22T15:01:27.174454Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8mb3_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
2022-09-22T15:01:27.178640Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-09-22T15:01:27.272977Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2022-09-22T15:01:27.372301Z 4 [System] [MY-013381] [Server] Server upgrade from '80030' to '80030' started.
2022-09-22T15:01:31.326390Z 4 [System] [MY-013381] [Server] Server upgrade from '80030' to '80030' completed.
2022-09-22T15:01:31.479710Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2022-09-22T15:01:31.479764Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2022-09-22T15:01:31.493748Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /tmp/mysqlx.sock
2022-09-22T15:01:31.493853Z 0 [System] [MY-010931] [Server] /opt/bitnami/mysql/bin/mysqld: ready for connections. Version: '8.0.30'  socket: '/opt/bitnami/mysql/tmp/mysql.sock'  port: 3306  Source distribution.
find: '/docker-entrypoint-startdb.d/': No such file or directory
mysql 15:01:32.97 INFO  ==> Stopping mysql
2022-09-22T15:01:32.978549Z 0 [System] [MY-013172] [Server] Received SHUTDOWN from user <via user signal>. Shutting down mysqld (Version: 8.0.30).
2022-09-22T15:01:34.475521Z 0 [System] [MY-010910] [Server] /opt/bitnami/mysql/bin/mysqld: Shutdown complete (mysqld 8.0.30)  Source distribution.
mysql 15:01:34.98 DEBUG ==> Waiting for mysql to unlock db files
mysql 15:01:35.00 INFO  ==> ** MySQL setup finished! **

mysql 15:01:35.02 INFO  ==> ** Starting MySQL **
2022-09-22T15:01:35.265182Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
2022-09-22T15:01:35.265195Z 0 [System] [MY-010116] [Server] /opt/bitnami/mysql/bin/mysqld (mysqld 8.0.30) starting as process 1
2022-09-22T15:01:35.267152Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
2022-09-22T15:01:35.267158Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8mb3_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
2022-09-22T15:01:35.271761Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2022-09-22T15:01:35.376657Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2022-09-22T15:01:35.555648Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2022-09-22T15:01:35.555704Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2022-09-22T15:01:35.572859Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /tmp/mysqlx.sock
2022-09-22T15:01:35.572926Z 0 [System] [MY-010931] [Server] /opt/bitnami/mysql/bin/mysqld: ready for connections. Version: '8.0.30'  socket: '/opt/bitnami/mysql/tmp/mysql.sock'  port: 3306  Source distribution.
```

**Comment by DFazeli** [comment] 2022-09-24 05:19
Hi @migruiz4.
migruiz4 you are right i can't believe it, my ceph storage is very slow, i changed the StorageClass to 'nfs' and the service ran very smooth.
thanks for your help.

**Comment by migruiz4** [comment] 2022-09-26 13:32
I'm happy to hear the issue is now resolved.
I will now close this issue, please let us know if you have any further issues.

**Closed by migruiz4** 2022-09-26 13:32 UTC
Labels: in-progress, tech-issues, mysql
