### ISSUE TITLE
[Harbor] harbor upgrade fails to start several pods.

### ISSUE THREAD

**Issue by paulczar** [bitnami/charts#5191] opened 2021-01-22 15:12 UTC
**Which chart**:

Harbor 9.3.0

**Describe the bug**

When you upgrade Harbor several Deployments don't properly roll the pods as they have PVCs attached. Whether upgrading for a new version, or upgrading for changes to a config (such as a TLS cert).

**To Reproduce**

```
helm install harbor bitnami/harbor -n harbor --version 9.2.2
helm upgrade harbor bitnami/harbor -n harbor --version 9.3.0
```

```
$ k get pods
NAME                                  READY   STATUS              RESTARTS   AGE
harbor-chartmuseum-58b59458bd-24nz4   0/1     ContainerCreating   0          6m11s
harbor-chartmuseum-5d6c447c88-2pznz   1/1     Running             0          22h
harbor-clair-65969895f-6whkq          2/2     Running             1          6m11s
harbor-core-7b569878d9-gg5kv          1/1     Running             0          6m10s
harbor-jobservice-66ddcf649-p7tn8     1/1     Running             1          22h
harbor-jobservice-86d5887fcb-vnnlt    0/1     ContainerCreating   0          6m10s
harbor-portal-c6679df6-bzmdh          1/1     Running             0          6m10s
harbor-postgresql-0                   1/1     Running             0          5m38s
harbor-redis-master-0                 1/1     Running             0          6m
harbor-registry-7658ccc65d-xkwz8      0/2     ContainerCreating   0          6m10s
harbor-registry-85f98f865c-pchcq      2/2     Running             0          22h
harbor-trivy-0                        1/1     Running             0          6m7s
```

```
$ k describe pod harbor-chartmuseum-58b59458bd-24nz4
Events:
  Type     Reason              Age                    From                     Message
  ----     ------              ----                   ----                     -------
  Normal   Scheduled           6m51s                  default-scheduler        Successfully assigned harbor/harbor-chartmuseum-58b59458bd-24nz4 to ip-10-0-1-133.us-east-2.compute.internal
  Warning  FailedAttachVolume  6m51s                  attachdetach-controller  Multi-Attach error for volume "pvc-9aefeba7-2e50-4348-b6ae-e01e35fb5209" Volume is already used by pod(s) harbor-chartmuseum-5d6c447c88-2pznz
  Warning  FailedMount         2m31s (x2 over 4m48s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[chartmuseum-data], unattached volumes=[chartmuseum-data]: timed out waiting for the condition

Can manually delete the old pods to work around. but not ideal.  Likely these should be StatefulSet or have custom rollout rules.

**Comment by rafariossaa** [comment] 2021-01-22 17:31
Hi,
  Could you list your pvc and the nodes they are attached too ? also the pods.
  Maybe the new pods are being deployed in a different node that does not have that PVC.

**Comment by paulczar** [comment] 2021-01-25 22:54
Hi,

The issue is that the Deployment tries to start the new Pod before it deletes the old Pod.  Obviously this doesn't work because you can't attach a PVC to two Pods (or even if you can, there's no guarantee the Pods will be scheduled on the same node).

**Comment by rafariossaa** [comment] 2021-01-26 11:02
Hi,
  I have tried in minikube and azure k8s clusters and I as not able to reproduce the issue.
  When you upgrade there is a warning about you need to use the same password for the admin. 
  Did you indicate that ?

```
$ helm install harbor bitnami/harbor  --version 9.2.2


NAME: harbor
LAST DEPLOYED: Tue Jan 26 10:50:44 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

1. Get the Harbor URL:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w harbor'
  export SERVICE_IP=$(kubectl get svc --namespace default harbor --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo "Harbor URL: http://$SERVICE_IP/"

2. Login with the following credentials to see your Harbor application

  echo Username: "admin"
  echo Password: $(kubectl get secret --namespace default harbor-core-envvars -o jsonpath="{.data.HARBOR_ADMIN_PASSWORD}" | base64 --decode)

```
Wait until is it deployed, then:
```
$ helm upgrade harbor bitnami/harbor  --version 9.3.0
Error: UPGRADE FAILED: template: harbor/templates/NOTES.txt:66:4: executing "harbor/templates/NOTES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" $passwordErrors "context" $)>: error calling include: template: harbor/charts/common/templates/_errors.tpl:18:48: executing "common.errors.upgrade.passwords.empty" at <fail>: error calling fail: 
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'harborAdminPassword' must not be empty, please add '--set harborAdminPassword=$HARBOR_ADMIN_PASSWORD' to the command. To get the current value:

        export HARBOR_ADMIN_PASSWORD=$(kubectl get secret --namespace default harbor-core-envvars -o jsonpath="{.data.HARBOR_ADMIN_PASSWORD}" | base64 --decode)
```

```
$ export HARBOR_ADMIN_PASSWORD=$(kubectl get secret --namespace default harbor-core-envvars -o jsonpath="{.data.HARBOR_ADMIN_PASSWORD}" | base64 --decode)

$ helm upgrade harbor bitnami/harbor  --version 9.3.0 --set harborAdminPassword=$HARBOR_ADMIN_PASSWORD


Release "harbor" has been upgraded. Happy Helming!
NAME: harbor
LAST DEPLOYED: Tue Jan 26 10:56:54 2021
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

1. Get the Harbor URL:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace default -w harbor'
  export SERVICE_IP=$(kubectl get svc --namespace default harbor --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
  echo "Harbor URL: http://$SERVICE_IP/"

2. Login with the following credentials to see your Harbor application

  echo Username: "admin"
  echo Password: $(kubectl get secret --namespace default harbor-core-envvars -o jsonpath="{.data.HARBOR_ADMIN_PASSWORD}" | base64 --decode)
```

**Comment by paulczar** [comment] 2021-01-27 15:15
I did set the password in the values.yaml file, so I didn't have to specify it on the command line, I should have mentioned that.

As the your helm upgrade, Helm itself succeeds because it doesn't actually wait for all the pods to come up.  Did you do a `kubectl get pods` after the helm upgrade?  I just ran through again using your exact commands t obe sure on both GKE and AWS and get the same result as my original issue.  here's one of the pods that refuses to start.

```
❯ kubectl describe pod harbor-chartmuseum-645f55487b-qw8cp | tail
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason              Age    From                     Message
  ----     ------              ----   ----                     -------
  Normal   Scheduled           2m29s  default-scheduler        Successfully assigned default/harbor-chartmuseum-645f55487b-qw8cp to gke-jan26-default-pool-f9599c36-4x6x
  Warning  FailedAttachVolume  2m29s  attachdetach-controller  Multi-Attach error for volume "pvc-57a833ac-123d-44f2-ab2a-c98a88649eb8" Volume is already used by pod(s) harbor-chartmuseum-59cfd7b9f-xj2vb
  Warning  FailedMount         26s    kubelet                  Unable to attach or mount volumes: unmounted volumes=[chartmuseum-data], unattached volumes=[chartmuseum-data]: timed out waiting for the condition
``

**Comment by rafariossaa** [comment] 2021-01-28 09:32
Hi,
  Yes, I did run kubectl get pods.
  This is an example of a intermediate state when ugrading:
```
NAME                                        READY   STATUS              RESTARTS   AGE
pod/harbor-chartmuseum-5b8997df74-mhzfh     1/1     Running             0          3m51s
pod/harbor-chartmuseum-9f474db4-vl7fs       0/1     Running             0          28s
pod/harbor-clair-5747b6dbf-j9msk            2/2     Running             2          3m51s
pod/harbor-clair-676fbf58b5-t82vd           0/2     ContainerCreating   0          28s
pod/harbor-core-79b77c7b96-tctv9            0/1     Running             0          28s
pod/harbor-core-f6c99b885-5jq6b             1/1     Running             1          3m51s
pod/harbor-jobservice-68b4946899-nnqs9      1/1     Running             0          3m51s
pod/harbor-jobservice-7876f89c5b-tns84      0/1     Running             0          27s
pod/harbor-nginx-5cdf49c9f6-9qxh8           0/1     Running             0          27s
pod/harbor-nginx-6d56889c79-nhn49           1/1     Running             0          3m51s
pod/harbor-notary-server-6cc86bff89-9k2jk   0/1     Running             0          27s
pod/harbor-notary-server-7575b586f5-pddx4   1/1     Running             0          3m50s
pod/harbor-notary-signer-6f8dd5bc88-95jdm   1/1     Running             1          3m51s
pod/harbor-notary-signer-c785ff8c5-sqdrd    0/1     Running             0          27s
pod/harbor-portal-55bd48c64f-wjwdt          0/1     Running             0          27s
pod/harbor-portal-74ccd95bf4-kb5wl          1/1     Running             0          3m51s
pod/harbor-postgresql-0                     1/1     Terminating         0          3m50s
pod/harbor-redis-master-0                   0/1     ContainerCreating   0          25s
pod/harbor-registry-67c7fd94d6-nhvsl        2/2     Running             0          3m51s
pod/harbor-registry-7cc5d48bbf-dbr9h        0/2     ContainerCreating   0          27s
pod/harbor-trivy-0                          0/1     ContainerCreating   0          8s

NAME                                 TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                                     AGE
service/harbor                       LoadBalancer   10.0.181.57    20.62.226.93   80:30874/TCP,443:32534/TCP,4443:31827/TCP   3m51s
service/harbor-chartmuseum           ClusterIP      10.0.72.19     <none>         80/TCP                                      3m51s
service/harbor-clair                 ClusterIP      10.0.84.80     <none>         6060/TCP,6061/TCP,8080/TCP                  3m51s
service/harbor-core                  ClusterIP      10.0.108.127   <none>         80/TCP                                      3m51s
service/harbor-jobservice            ClusterIP      10.0.110.210   <none>         80/TCP                                      3m51s
service/harbor-notary-server         ClusterIP      10.0.219.231   <none>         4443/TCP                                    3m51s
service/harbor-notary-signer         ClusterIP      10.0.186.159   <none>         7899/TCP                                    3m51s
service/harbor-portal                ClusterIP      10.0.210.149   <none>         80/TCP                                      3m51s
service/harbor-postgresql            ClusterIP      10.0.30.57     <none>         5432/TCP                                    3m51s
service/harbor-postgresql-headless   ClusterIP      None           <none>         5432/TCP                                    3m51s
service/harbor-redis-headless        ClusterIP      None           <none>         6379/TCP                                    3m51s
service/harbor-redis-master          ClusterIP      10.0.25.189    <none>         6379/TCP                                    3m51s
service/harbor-registry              ClusterIP      10.0.134.20    <none>         5000/TCP,8080/TCP                           3m51s
service/harbor-trivy                 ClusterIP      10.0.51.122    <none>         8080/TCP                                    3m51s
service/kubernetes                   ClusterIP      10.0.0.1       <none>         443/TCP                                     11m
```
And this was the final state:
```
NAME                                        READY   STATUS    RESTARTS   AGE
pod/harbor-chartmuseum-9f474db4-vl7fs       1/1     Running   0          2m51s
pod/harbor-clair-5747b6dbf-j9msk            1/2     Running   4          6m14s
pod/harbor-clair-676fbf58b5-t82vd           1/2     Running   3          2m51s
pod/harbor-core-79b77c7b96-tctv9            1/1     Running   1          2m51s
pod/harbor-jobservice-7876f89c5b-tns84      1/1     Running   1          2m50s
pod/harbor-nginx-5cdf49c9f6-9qxh8           1/1     Running   0          2m50s
pod/harbor-notary-server-6cc86bff89-9k2jk   1/1     Running   1          2m50s
pod/harbor-notary-signer-c785ff8c5-sqdrd    1/1     Running   1          2m50s
pod/harbor-portal-55bd48c64f-wjwdt          1/1     Running   0          2m50s
pod/harbor-postgresql-0                     1/1     Running   0          2m11s
pod/harbor-redis-master-0                   1/1     Running   0          2m48s
pod/harbor-registry-7cc5d48bbf-dbr9h        2/2     Running   0          2m50s
pod/harbor-trivy-0                          1/1     Running   0          2m31s

NAME                                 TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                                     AGE
service/harbor                       LoadBalancer   10.0.181.57    20.62.226.93   80:30874/TCP,443:32534/TCP,4443:31827/TCP   6m14s
service/harbor-chartmuseum           ClusterIP      10.0.72.19     <none>         80/TCP                                      6m14s
service/harbor-clair                 ClusterIP      10.0.84.80     <none>         6060/TCP,6061/TCP,8080/TCP                  6m14s
service/harbor-core                  ClusterIP      10.0.108.127   <none>         80/TCP                                      6m14s
service/harbor-jobservice            ClusterIP      10.0.110.210   <none>         80/TCP                                      6m14s
service/harbor-notary-server         ClusterIP      10.0.219.231   <none>         4443/TCP                                    6m14s
service/harbor-notary-signer         ClusterIP      10.0.186.159   <none>         7899/TCP                                    6m14s
service/harbor-portal                ClusterIP      10.0.210.149   <none>         80/TCP                                      6m14s
service/harbor-postgresql            ClusterIP      10.0.30.57     <none>         5432/TCP                                    6m14s
service/harbor-postgresql-headless   ClusterIP      None           <none>         5432/TCP                                    6m14s
service/harbor-redis-headless        ClusterIP      None           <none>         6379/TCP                                    6m14s
service/harbor-redis-master          ClusterIP      10.0.25.189    <none>         6379/TCP                                    6m14s
service/harbor-registry              ClusterIP      10.0.134.20    <none>         5000/TCP,8080/TCP                           6m14s
service/harbor-trivy                 ClusterIP      10.0.51.122    <none>         8080/TCP                                    6m14s
service/kubernetes                   ClusterIP      10.0.0.1       <none>         443/TCP                                     13m
```

What is the state of the pod `harbor-chartmuseum-59cfd7b9f-xj2vb`? that is the one that is not releasing the PVC so the new pod will be able to attach it

**Comment by paulczar** [comment] 2021-02-05 17:35
What cloud are you deploying into?  I wonder if this is an issue specific to a provider.  I'll try and test with the same provider as you.

**Comment by rafariossaa** [comment] 2021-02-08 17:05
I deployed it into Azure and locally in minikube.

**Comment by lusu007** [comment] 2021-02-13 13:24
I have the same problem with my installation. I deployed Harbor into a Managed OVH Kubernetes cluster.
The problem occurs when an update is triggered via Argocd. The version does not even have to be upgraded.

**Comment by rafariossaa** [comment] 2021-02-15 09:03
Hi,
  Thanks for providing more info.
  Could you check the logs of your pods and look for some errors ?

**Comment by lusu007** [comment] 2021-02-15 13:32
The logs unfortunately do not contain any errors.

Chartmuseum, Jobservice and the registry itself cant attach the old volume because it isn't detached from the old pod.
![image](https://user-images.githubusercontent.com/10341994/107952756-76942880-6f9a-11eb-9257-564809fb5aad.png)
![image](https://user-images.githubusercontent.com/10341994/107952808-8875cb80-6f9a-11eb-94b9-c57f8c202430.png)

**Comment by rafariossaa** [comment] 2021-02-15 14:44
Could you check in which node was deployed the "old" pod and in which node is trying to deploy the "new" pod ?

**Comment by lusu007** [comment] 2021-02-15 15:40
Every new pod gets deployed on a new node. So none of the new pods is on the same node as the old ones.

When I add your suggested changes Harbor restarts without any error and without a Multi-Attach error.
But I think Harbor should be able to restart on other nodes too. Or am I wrong?

**Comment by rafariossaa** [comment] 2021-02-16 17:17
The volumes are related to a node, because is the node the one who provides this storage space to the container. If the container starts in other node, it can not found its storage space. More info on this [topic here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#introduction).

**Comment by lusu007** [comment] 2021-02-16 18:04
Okay, that makes sense. So actually the old pods should be stopped before the new ones start or not?

**Comment by rafariossaa** [comment] 2021-02-17 08:38
As it is a Rolling Update, it will stop the old ones once the new ones are running. This is the way you get the issue, because to run the new ones the volumes need to be mounted but as they are in a different node, and it can not be done.

**Comment by lusu007** [comment] 2021-04-14 20:09
> Could you check in which node was deployed the "old" pod and in which node is trying to deploy the "new" pod ?
> If the nodes are different, I think that the problem is related to affinity.
> Maybe you can try to add this to your settings when upgrading:

This fixes the problem. This issue could be closed.

**Comment by rafariossaa** [comment] 2021-04-15 09:01
Hi,
  I am happy the issue was solved.
  Thanks for coming back and letting us know.
  I am closing the issue.

**Closed by rafariossaa** 2021-04-15 09:01 UTC

**Comment by laurivosandi** [comment] 2022-01-26 20:02
This actually seems upstream issue which I documented here: https://github.com/goharbor/harbor-helm/issues/1137
