### ISSUE TITLE
[bitnami/redis] cannot create temp file for here-document

### ISSUE THREAD

**Issue by jirisrba** [bitnami/charts#5877] opened 2021-03-23 09:28 UTC
**Which chart**:
bitnami/redis redis-12.8.3

**Describe the bug**

master redis pod failed to start with error:
```
/run.sh: line 23: cannot create temp file for here-document: No space left on device
```
**To Reproduce**

default helm install with
```
helm install redis bitnami/redis
```

**Expected behavior**
Redis started

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.16rc1"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

The issue is related to  /tmp mounted as empty dir 

https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/redis-master-statefulset.yaml#L191

**Comment by migruiz4** [comment] 2021-03-25 07:27
Hi @jirisrba ,

Sorry for the late response.

Is it possible that your Kubernetes cluster is low on disk space?
Could you please run the command `kubectl describe nodes` and look for the status of [ephemeral-storage](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/) and DiskPressure.

Mounting /tmp as an emptydir was a recent change #5601 but it shouldn't prevent Redis nodes from starting.

**Comment by jirisrba** [comment] 2021-03-25 07:38
Hi @migruiz4,

issue resolved, you were right, low disk space. Thank you,

Jiri Srba

**Comment by migruiz4** [comment] 2021-03-26 08:17
I'm happy the issue is resolved.

I will now close the issue, let me know if you need any further help.

**Closed by migruiz4** 2021-03-26 08:17 UTC
