### ISSUE TITLE
[bitnami/mariadb-galera] 3 replicas running, but wsrep_cluster_size=1

### ISSUE THREAD

**Issue by omegazeng** [bitnami/charts#8560] opened 2022-01-04 03:19 UTC
**Which chart**:
helm.sh/chart: mariadb-galera-6.1.1

**Describe the bug**
a fresh install, 3 replicas, but every member wsrep_cluster_size=1
**To Reproduce**

* mariadb-galera.yaml
```yaml
rootUser:
  password: xxxxxxxxxxxxxxxxxxxx

db:
  user: maria
  password: xxxxxxxxxxxxxxxxxxx
  name: maria

galera:
  mariabackup:
    password: xxxxxxxxxxxxxxxxx

replicaCount: 3

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 1024Mi

persistence:
  size: 5Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```
```console
$ kubectl create ns mariadb
helm install mariadb bitnami/mariadb-galera -n mariadb -f mariadb-galera.yaml

$ kubectl get po -n mariadb
NAME                       READY   STATUS    RESTARTS   AGE
mariadb-mariadb-galera-0   2/2     Running   0          11h
mariadb-mariadb-galera-1   2/2     Running   0          11h
mariadb-mariadb-galera-2   2/2     Running   0          11h
```
```bash
show status like 'wsrep_cluster_size';
wsrep_cluster_size	1

show status like 'wsrep_incoming_addresses';
wsrep_incoming_addresses	AUTO
```
3 members are the same result
**Expected behavior**
wsrep_cluster_size should 3
**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

https://github.com/bitnami/charts/issues/7071#issuecomment-1003742015

enable TLS is failed, so disable TLS, delete PVC, redeploy Galera, failed.

**Comment by omegazeng** [comment] 2022-01-04 04:30
delete release
```bash
helm delete mariadb -n mariadb
```
keep pvc
add
```
--set galera.mariabackup.password=YYYY
--set galera.bootstrap.bootstrapFromNode=2 \
--set galera.bootstrap.forceSafeToBootstrap=true \
--set podManagementPolicy=Parallel
```
redeploy
```bash
k get po -n mariadb 
NAME                       READY   STATUS    RESTARTS   AGE
mariadb-mariadb-galera-0   2/2     Running   3          3m14s
mariadb-mariadb-galera-1   2/2     Running   3          3m14s
mariadb-mariadb-galera-2   2/2     Running   0          3m14s
```
```
MariaDB [(none)]> show status like 'wsrep_cluster_size';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| wsrep_cluster_size | 3     |
+--------------------+-------+
1 row in set (0.001 sec)

MariaDB [(none)]> show status like 'wsrep_incoming_addresses';
+--------------------------+----------------+
| Variable_name            | Value          |
+--------------------------+----------------+
| wsrep_incoming_addresses | AUTO,AUTO,AUTO |
+--------------------------+----------------+
1 row in set (0.001 sec)
```

**Comment by miguelaeh** [comment] 2022-01-04 09:17
Hi @omegazeng ,
Is the issue solved then?

**Comment by omegazeng** [comment] 2022-01-04 11:58
@miguelaeh 
a fresh install is not working.
but `helm delete`, dot not delete the PVC, reinstall with options 
```
--set galera.mariabackup.password=YYYY
--set galera.bootstrap.bootstrapFromNode=2 \
--set galera.bootstrap.forceSafeToBootstrap=true \
--set podManagementPolicy=Parallel"
```
then Galera cluster becomes normal.

**Comment by miguelaeh** [comment] 2022-01-05 10:21
I was able to reproduce the issue with the default chart just adding `replicas=3`. I will add this information to an internal task I just created about the same chart so we can work on both at the same time.

**Comment by chauwel** [comment] 2022-01-07 10:03
Met the same issue ([#8580](https://github.com/bitnami/charts/issues/8580)) 
May be related to this error message ?

```
�[38;5;6mmariadb �[38;5;5m19:52:34.51 �[0m�[38;5;2mINFO �[0m ==> Setting wsrep_node_address option
/opt/bitnami/scripts/libmariadbgalera.sh: line 164: local_ip: unbound variable
```

**Comment by miguelaeh** [comment] 2022-01-07 10:50
Hi guys,
It looks like the mentioned unbound `local_ip` could be related. You can see the code [here](https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/cfe01d93d2c17f2c1406a4768bd956f573db0b68/10.6/debian-10/rootfs/opt/bitnami/scripts/libmariadbgalera.sh#L164).
It is making that the `has_nodes` variable is always `yes` since being unbound, the condition is always true, so the cluster thinks that there are always other nodes in the cluster even when there aren't.
So, it seems that the `local_ip` variable should be assigned to the current node IP, which I think we can just obtain by using `getent`.
Could any of you give a try to that?

**Comment by Cryingmouse** [comment] 2022-01-10 05:54
It is wierd that I tried with the following command in k3s today:
```
helm install mariadb bitnami/mariadb-galera
```
mariadb-mariadb-galera-0 and mariadb-mariadb-galera-1 are in ONE Galera cluster, but mariadb-mariadb-galera-2 are in another Galera cluster.
Here is the output from the pod **mariadb-mariadb-galera-1**:
```
I have no name!@mariadb-mariadb-galera-1:/$ export |grep DB_GALERA_CLUSTER_ADDRESS
declare -x MARIADB_GALERA_CLUSTER_ADDRESS="gcomm://mariadb-mariadb-galera-headless.default.svc.cluster.local"
I have no name!@mariadb-mariadb-galera-1:/$ hostname -i
10.42.1.73
I have no name!@mariadb-mariadb-galera-1:/$ getent ahosts mariadb-mariadb-galera-headless.default.svc.cluster.local
10.42.1.73      STREAM mariadb-mariadb-galera-headless.default.svc.cluster.local
10.42.1.73      DGRAM
10.42.1.73      RAW
10.42.0.91      STREAM
10.42.0.91      DGRAM
10.42.0.91      RAW
10.42.2.61      STREAM
10.42.2.61      DGRAM
10.42.2.61      RAW
```
The status of the pods are as follow:
```
[root@node-1 ~]# kubectl get po -l app.kubernetes.io/instance=mariadb -owide
NAME                       READY   STATUS    RESTARTS   AGE   IP           NODE     NOMINATED NODE   READINESS GATES
mariadb-mariadb-galera-0   1/1     Running   0          99m   10.42.0.91   node-1   <none>           <none>
mariadb-mariadb-galera-1   1/1     Running   0          47m   10.42.1.73   node-2   <none>           <none>
mariadb-mariadb-galera-2   1/1     Running   0          95m   10.42.2.61   node-3   <none>           <none>
```
I also attach the logs of each pods for your reference:
[galera-1.txt](https://github.com/bitnami/charts/files/7836999/galera-1.txt)
[galera-2.txt](https://github.com/bitnami/charts/files/7837000/galera-2.txt)

**Comment by miguelaeh** [comment] 2022-01-11 09:30
@Cryingmouse I guess you refer to the configured `DB_GALERA_CLUSTER_ADDRESS`, right? That seems to be correct, the `DB_GALERA_CLUSTER_ADDRESS` has to indicate the IP of any node in the cluster ([ref](https://mariadb.com/kb/en/galera-cluster-address/)). Using the headless service, it will return the rest of the pods of the statefulset.

**Comment by Cryingmouse** [comment] 2022-01-12 02:14
@miguelaeh Yes. Is there any clue from the logs I provided for the issue? Please do not hesitate to let me know any other information if you need to root cause the issue.

**Comment by miguelaeh** [comment] 2022-01-12 09:50
Hi @Cryingmouse ,
I created an internal task so we can dedicate more time to checking what is actually happening. Nevertheless, I cannot provide an ETA for the fix.
If we need more information or release a fix for the issue we will update this thread.
Thank you very much for the collaboration!

**Comment by withinboredom** [comment] 2022-01-21 10:38
@miguelaeh are these versions totally borked or is there some situation they work fine in? Should people avoid upgrading to 6.x?

**Comment by miguelaeh** [comment] 2022-01-24 08:33
Hi @withinboredom ,
I am afraid we don't know when did this start to happen. We raised the priority for fixing this issue since looks like the cluster is not created, which is a critical level for us. 
If you could confirm a version in which the reported issue does not appear that would be great for the rest of users.

**Comment by withinboredom** [comment] 2022-01-24 10:48
> If you could confirm a version in which the reported issue does not appear that would be great for the rest of users.

Using these helm values:

```
## Custom db configuration
##
db:
  ## @param db.user Username of new user to create
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb-galera#creating-a-database-user-on-first-run
  ##
  user: "user"
  ## @param db.password Password for the new user. Ignored if existing secret is provided.
  ##
  password: "password"
  ## @param db.name Name for new database to create
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb-galera#creating-a-database-on-first-run
  ##
  name: db
  ## @param db.forcePassword Option to force users to specify a password. That is required for 'helm upgrade' to work properly.
  ## If it is not force, a random password will be generated.
  ##
  forcePassword: true
## Galera configuration
##
galera:
  ## @param galera.name Galera cluster name
  ##
  name: galera

## @param mariadbConfiguration [string] Configuration for the MariaDB server
## ref: https://mysql.com/kb/en/mysql/configuring-mysql-with-mycnf/#example-of-configuration-file
## Alternatively, you can put your my.cnf under the files/ directory
##
mariadbConfiguration: |-
  [client]
  port=3306
  socket=/opt/bitnami/mariadb/tmp/mysql.sock
  plugin_dir=/opt/bitnami/mariadb/plugin

  [mysqld]
  default_storage_engine=InnoDB
  basedir=/opt/bitnami/mariadb
  datadir=/bitnami/mariadb/data
  plugin_dir=/opt/bitnami/mariadb/plugin
  tmpdir=/opt/bitnami/mariadb/tmp
  socket=/opt/bitnami/mariadb/tmp/mysql.sock
  pid_file=/opt/bitnami/mariadb/tmp/mysqld.pid
  bind_address=0.0.0.0
  event_scheduler=on

  ## Character set
  ##
  collation_server=utf8_unicode_ci
  init_connect='SET NAMES utf8'
  character_set_server=utf8

  ## MyISAM
  ##
  key_buffer_size=32M
  myisam_recover_options=FORCE,BACKUP

  ## Safety
  ##
  skip_host_cache
  skip_name_resolve
  max_allowed_packet=16M
  max_connect_errors=1000000
  sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY
  sysdate_is_now=1

  ## Binary Logging
  ##
  log_bin=mysql-bin
  expire_logs_days=14
  # Disabling for performance per http://severalnines.com/blog/9-tips-going-production-galera-cluster-mysql
  sync_binlog=0
  # Required for Galera
  binlog_format=row

  ## Caches and Limits
  ##
  tmp_table_size=32M
  max_heap_table_size=32M
  # Re-enabling as now works with Maria 10.1.2
  query_cache_type=1
  query_cache_limit=4M
  query_cache_size=256M
  max_connections=500
  thread_cache_size=50
  open_files_limit=65535
  table_definition_cache=4096
  table_open_cache=4096

  ## InnoDB
  ##
  innodb=FORCE
  innodb_strict_mode=1
  # Mandatory per https://github.com/codership/documentation/issues/25
  innodb_autoinc_lock_mode=2
  # Per https://www.percona.com/blog/2006/08/04/innodb-double-write/
  innodb_doublewrite=1
  innodb_flush_method=O_DIRECT
  innodb_log_files_in_group=2
  innodb_log_file_size=128M
  innodb_flush_log_at_trx_commit=1
  innodb_file_per_table=1
  # 80% Memory is default reco.
  # Need to re-evaluate when DB size grows
  innodb_buffer_pool_size=2G
  innodb_file_format=Barracuda

  ## Logging
  ##
  log_error=/opt/bitnami/mariadb/logs/mysqld.log
  slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
  log_queries_not_using_indexes=1
  slow_query_log=1

  ## SSL
  ## Use extraVolumes and extraVolumeMounts to mount /certs filesystem
  # ssl_ca=/certs/ca.pem
  # ssl_cert=/certs/server-cert.pem
  # ssl_key=/certs/server-key.pem

  [galera]
  wsrep_on=ON
  wsrep_provider=/opt/bitnami/mariadb/lib/libgalera_smm.so
  wsrep_sst_method=mariabackup
  wsrep_slave_threads=4
  wsrep_cluster_address=gcomm://
  wsrep_cluster_name=galera
  wsrep_sst_auth="root:"
  # Enabled for performance per https://mariadb.com/kb/en/innodb-system-variables/#innodb_flush_log_at_trx_commit
  innodb_flush_log_at_trx_commit=2
  # MYISAM REPLICATION SUPPORT #
  wsrep_replicate_myisam=ON

  [mariadb]
  plugin_load_add=auth_pam

  ## Data-at-Rest Encryption
  ## Use extraVolumes and extraVolumeMounts to mount /encryption filesystem
  # plugin_load_add=file_key_management
  # file_key_management_filename=/encryption/keyfile.enc
  # file_key_management_filekey=FILE:/encryption/keyfile.key
  # file_key_management_encryption_algorithm=AES_CTR
  # encrypt_binlog=ON
  # encrypt_tmp_files=ON

  ## InnoDB/XtraDB Encryption
  # innodb_encrypt_tables=ON
  # innodb_encrypt_temporary_tables=ON
  # innodb_encrypt_log=ON
  # innodb_encryption_threads=4
  # innodb_encryption_rotate_key_age=1

  ## Aria Encryption
  # aria_encrypt_tables=ON
  # encrypt_tmp_disk_tables=ON

## Pod disruption budget configuration
##
podDisruptionBudget:
  ## @param podDisruptionBudget.create Specifies whether a Pod disruption budget should be created
  ##
  create: true
  ## @param podDisruptionBudget.minAvailable Minimum number / percentage of pods that should remain scheduled
  ##
  minAvailable: 1
  ## @param podDisruptionBudget.maxUnavailable Maximum number / percentage of pods that may be made unavailable
  ##
  maxUnavailable: ""
```

bisecting:
```
6.0.0 - cluster [good]
6.0.1
6.0.2
6.0.3
6.0.4
6.0.5
6.0.6 - cluster [good]
6.0.8 - cluster [good]
6.0.10 - no cluster [bad]
6.0.11 - no cluster [bad]
6.1.0
6.1.1
6.2.0 - no cluster [bad]
```

Looks like 6.0.8 is the last good version.

**Comment by miguelaeh** [comment] 2022-01-25 09:11
Thank you very much for the information @omegazeng

**Comment by iomarcovalente** [comment] 2022-01-26 02:12
I have just attempted running `6.0.8`, cluster came up fine but as soon as I scaled the cluster to 1 node I got this error and it started crashlooping.
```
Liveness probe failed: ERROR 1047 (08S01) at line 1: WSREP has not yet prepared node for application use
```

**Comment by withinboredom** [comment] 2022-01-26 09:56
@iomarcovalente if that final node isn't the leader (or whatever the terminology is), that sounds about right. You might have to bootstrap it.

**Comment by iomarcovalente** [comment] 2022-01-26 10:05
That final node was the leader as it was node 0. Or at least that is how is meant to work as far as I am aware: node 0 will be the bootstrapping node hence the leader.
I just started a cluster in a standard way via helm and then scale the statefulset to 1.

**Comment by withinboredom** [comment] 2022-01-26 10:10
It can def change once the cluster is started :).

**Comment by iomarcovalente** [comment] 2022-01-26 10:29
great, so how will it roll update in case an update is needed? does that mean that restarting a cluster is not an option?

**Comment by withinboredom** [comment] 2022-01-26 20:04
It feels like we are getting a bit off topic and maybe create a new issue. But to digress: scaling stateful sets is always risky and imho, involves unplanned downtime more than not. I'd recommend not doing it unless you have to. 

Yet still, you bring up a good point. In looking deeper at this issue, and skimming the Galera docs to recover a cluster, I discovered that when bringing it back online you need to discover the "leader" and bring that one online first. K8s doesn't really let you decide which node to bring online first in a controlled way, so it has me questioning whether this chart makes a lot of sense for production in a disaster recovery situation. It may be better to deploy several replica:1 stateful sets that can be managed independently for disaster recovery.

The practical reality is that if the whole cluster goes down, losing a few seconds of data isn't the end of the world. There are probably bigger problems. So this chart is probably fine for production? I don't actually know, but it will work well enough for me.

But why were you scaling the cluster?

**Comment by withinboredom** [comment] 2022-01-26 20:05
But to answer your question. Rolling updates work fine. Stopping the whole cluster, ymmv, but it results in downtime ime.

**Comment by withinboredom** [comment] 2022-01-26 22:18
Ha, I just wrote about this. But after a slow-rolling reboot of nodes, it's pod `-0` that is in a crash-loop. Can't scale down because the pod it would scale down to is the bad one 😂.

**Comment by rafariossaa** [comment] 2022-01-27 09:19
Hi,
  I am currently working in fixing this issue of the nodes not being part of the cluster. Thanks for your patience.

**Comment by withinboredom** [comment] 2022-02-07 16:19
Yep it's fixed!

**Comment by rafariossaa** [comment] 2022-02-08 09:17
@withinboredom  I am happy to hear that !
@omegazeng Could you give it a try to check if your case is also fixed with the new release ?

**Comment by omegazeng** [comment] 2022-02-10 10:53
> @withinboredom I am happy to hear that ! @omegazeng Could you give it a try to check if your case is also fixed with the new release ?

fixed. thx!

**Closed** 2022-02-10 10:53 UTC
Labels: on-hold

**Comment by acim** [comment] 2022-03-25 23:29
Se still have sudden splits of cluster using the latest chart. Today I could see one node restarted once and it made it‘s own cluster after that while the remaining two nodes with 0 restarts remained in the same (old) cluster.

**Comment by rafariossaa** [comment] 2022-03-28 09:25
Hi @acim 
  If you keep observing this behavior, would you mind opening a new issue ? could you gather all the information you can ? This kind of issues are usually very difficult to reproduce and usually involves timing, so eventually this kind of this could happen.
