### ISSUE TITLE
[postgresql-ha] Creation failed 

### ISSUE THREAD

**Issue by smlee729** [bitnami/charts#1568] opened 2019-11-07 14:10 UTC
While creating pgpool, it encountered permission issue:
```
pgpool 14:07:02.08
pgpool 14:07:02.08 Welcome to the Bitnami pgpool container
pgpool 14:07:02.09 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
pgpool 14:07:02.09 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
pgpool 14:07:02.09 Send us your feedback at containers@bitnami.com
pgpool 14:07:02.09
pgpool 14:07:02.09 INFO  ==> ** Starting Pgpool-II setup **
pgpool 14:07:02.10 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 14:07:02.15 INFO  ==> Initializing Pgpool-II...
chown: changing ownership of '/opt/bitnami/pgpool/logs/pgpool.log': Permission denied
```

**Comment by juan131** [comment] 2019-11-08 07:51
Hi @smlee729 

Could you please provide more information about how you're deploying this container? 
Are you using the Helm chart? What **values.yaml** are you using if so?

**Comment by smlee729** [comment] 2019-11-08 18:26
Hi @juan131 . I tried to use `values-production.yaml` except metrics exporter.
I use this command,
```
helm install --name postgresql-ha -f values-production.yaml bitnami/postgresql-ha
```

**Comment by juan131** [comment] 2019-11-11 08:41
Closing as a duplicate of https://github.com/bitnami/bitnami-docker-pgpool/issues/3

**Closed by juan131** 2019-11-11 08:41 UTC
