### ISSUE TITLE
[bitnami/etcd] etcd client autoTLS error

### ISSUE THREAD

**Issue by nurlanf** [bitnami/charts#1278] opened 2019-07-08 12:31 UTC
**https://github.com/bitnami/charts/tree/master/bitnami/etcd**:

**Description**
While trying to install etcd chart with `--set auth.client.secureTransport="true" --set auth.client.useAutoTLS="true"` parameter, getting error:
`/scripts/setup.sh: line 9: ETCD_CERT_FILE: unbound variable`

**Steps to reproduce the issue:**

1. `git clone https://github.com/bitnami/charts.git`
2. `helm install --name bitnami-etcd charts/bitnami/etcd/ --set auth.client.secureTransport="true" --set auth.client.useAutoTLS="true"`

**Describe the results you received:**

`CrashLoopBack` error, and log shows `/scripts/setup.sh: line 9: ETCD_CERT_FILE: unbound variable`
**Describe the results you expected:**
Etcd cluster (3 replicas) should be created with client-server encryption with automatically created `key.pem` and `cert.pem` certificates

**Version of Helm and Kubernetes**:
Helm server version: v2.13.1
Kubernetes server version: v1.12.8-gke.10
- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by alemorcuq** [comment] 2019-07-09 11:27
Hi, @nurlanf.

Thank you for reporting this. It looks like the `ETCD_CERT_FILE` is not being declared when `auth.client.useAutoTLS` in enabled. We will take a closer look and make a PR as soon as we can.

Regards,
Alejandro

**Comment by mordf** [comment] 2019-07-30 11:58
Any news regarding this issue?

**Comment by alemorcuq** [comment] 2019-07-31 06:54
Hi, @mordf.

No news yet, we will notify you when we have something to share. Thank you for your patience.

Regards,
Alejandro

**Comment by miklezzzz** [comment] 2019-12-20 05:50
The chart is inconsistent with etcd AUTO_TLS feature :( I was able to remediate issues with ETCD_CERT_FILE (this ENV should not be used with ETCD_AUTO_TLS because it turns off the TLS certs generation process) and /scripts/probe.sh (etcdctl can't connect to healthcheck a cluster due to out of a client certificate definition) but there is an issue with entrypoint.sh because it calls etcdctl without a client cert and fails to create root/enable auth.

**Comment by alemorcuq** [comment] 2019-12-20 08:20
Hi, @miklezzzz.

We merged this yesterday #1750 yesterday. Does it solve your issues?

cc @mordf @nurlanf

**Comment by miklezzzz** [comment] 2019-12-20 08:42
Hi @alemorcuq.
The original problem with ETCD_CERT_FILE has gone but healthchecks keep failing with:
```
==> [DEBUG] Probing etcd cluster
==> [DEBUG] Probe command: "etcdctl --user root:SDF5dflk345fkr --cert=/bitnami/etcd/data/fixtures/client/cert.pem --key=/bitnami/etcd/data/fixtures/client/key.pem endpoint health"
{"level":"warn","ts":"2019-12-20T08:38:46.584Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-a5204415-cb8c-41a2-993a-4e3ec0d1ee2d/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: authentication handshake failed: x509: certificate is valid for 0.0.0.0, not 127.0.0.1\""}
127.0.0.1:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Error: unhealthy cluster
```
I've used "--insecure-skip-tls-verify" etcdctl's option to overcome it.

**Comment by alemorcuq** [comment] 2019-12-23 14:59
Can you share the command you are using to run the chart so I can reproduce the issue, @miklezzzz?

**Comment by miklezzzz** [comment] 2019-12-24 10:09
Here it is, @alemorcuq :
```
helm3 search repo bitnami/etcd
NAME        	CHART VERSION	APP VERSION	DESCRIPTION                                       
bitnami/etcd	4.4.7        	3.4.3      	etcd is a distributed key value store that prov...

helm3 install dev-etcd bitnami/etcd -f values-production.yaml
```
values-production.yaml's settings regarding TLS are below:
```
auth:
  rbac:
    enabled: true
    ## etcd root user password. The root user is always `root`
    ##
    rootPassword: "SDF5dflk345fkr"
    ## Name of the existing secret containing credentials for the root user.
    ##
    # existingSecret: name-of-existing-secret

  client:
    ## Switch to encrypt client communication using TLS certificates
    ##
    secureTransport: true
    ## Switch to automatically create the TLS certificates
    ##
    useAutoTLS: true
    ## Switch to enable host authentication using TLS certificates. Requires existing secret.
    ##
    enableAuthentication: false
    ## Name of the existing secret containing cert files for client communication.
    ##
    # existingSecret: name-of-existing-secret

  peer:
    ## Switch to encrypt peer communication using TLS certificates
    ##
    secureTransport: true
    ## Switch to automatically create the TLS certificates
    ##
    useAutoTLS: true
    ## Switch to enable host authentication using TLS certificates. Requires existing secret.
    ##
    enableAuthentication: false
    ## Name of the existing secret containing cert files for peer communication.
    ##
    # existingSecret: name-of-existing-secret
```
pods stay in 0/1 Running forever 
```
kubectl get pods | grep etcd
dev-etcd-0                            0/1     Running                 0          4m16s
dev-etcd-1                            0/1     Running                 1          4m15s
dev-etcd-2                            0/1     Running                 1          4m15s
```
i turned on debug and here what i have in kubectl describe pod dev-etcd-0:
```
==> [DEBUG] Probing etcd cluster
==> [DEBUG] Probe command: "etcdctl --user root:SDF5dflk345fkr --cert=/bitnami/etcd/data/fixtures/client/cert.pem --key=/bitnami/etcd/data/fixtures/client/key.pem endpoint health"
{"level":"warn","ts":"2019-12-24T10:02:23.882Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-b1ba1700-344b-40e5-8b3f-40eca12b5016/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: authentication handshake failed: x509: certificate is valid for 0.0.0.0, not 127.0.0.1\""}
127.0.0.1:2379 is unhealthy: failed to commit proposal: context deadline exceeded
Error: unhealthy cluster
  Warning  Unhealthy  3m26s  kubelet, elma365-minion-3  Readiness probe failed: ==> Bash debug is on

```

**Comment by alemorcuq** [comment] 2019-12-27 15:33
Thanks, @miklezzzz. I was able to reproduce the issue. I've created an internal task to investigate it and added it to our backlog.

We will update this thread when we make any findings. Is it ok for you in the meantime to use the `--insecure-skip-tls-verify` flag?

**Comment by miklezzzz** [comment] 2019-12-27 16:46
sure, @alemorcuq . thanks!

**Comment by mordf** [comment] 2019-12-30 15:57
@miklezzzz you could use your own certificates, I tested it with certificates I generated and it worked great.

**Comment by miklezzzz** [comment] 2019-12-31 06:01
@mordf great to hear it! though, an ability to deploy tls-ed etcd from the box appeals to me :)

**Comment by javsalgar** [comment] 2019-12-31 10:32
There must be a way to have the auto-generated certificates to have 127.0.0.1 as one of the authorized hosts. We will update the ticket when we have more information.

**Comment by tgdfool2** [comment] 2020-06-05 09:50
> @miklezzzz you could use your own certificates, I tested it with certificates I generated and it worked great.

Hi @mordf. Could you please elaborate on how you managed to get it working with your own certificates? Especially how the format of the `existingSecret` should look like. Thanks in advance!

**Comment by devopsk8s999** [comment] 2021-06-03 06:55
Hi @mordf 
Could you please elaborate on how you managed to get it working with your own certificates?

Especially how the format of the existingSecret should look like and how to handle certificates for multiple etcd members?

Thanks in advance for your help!

**Comment by devopsk8s999** [comment] 2021-06-03 08:10
@mordf  -  i have gerated tls certifications, i am getting below error message .

(error "remote error: tls: bad certificate", ServerName "etcd-2.etcd-headless.etcd-test.svc.cluster.local")

cat values-op.yaml
replicaCount: 3
removeMemberOnContainerTermination: false
auth:
 rbac:
   enabled: true
   rootPassword: "testrear"
 client:
   secureTransport: true
   useAutoTLS: false
   enableAuthentication: true
   existingSecret: "test-tls-secret1"
   certFilename: tls.crt
   certKeyFilename: tls.key
#   caFilename: "ca.crt"
 peer:
   useAutoTLS: true
   secureTransport: true
persistence:
 enabled: false
 size: 2Gi

**Comment by javsalgar** [comment] 2021-06-07 07:40
Hi,

Just a note to let you know that we're standardizing the automatic generation of TLS certificates inside the chart so it is easier to test SSL/TLS. We will update the ticket when we have more information.

**Comment by thangamani-arun** [comment] 2021-12-28 07:48
@javsalgar Do we have any updates on useAutoTLS? We have tried to use `useAutoTLS: true`, but still cluster is not enabled with TLS.

**Comment by marcosbc** [comment] 2021-12-28 11:37
@thangamani-arun Note that `useAutoTLS` is not an option supported by the chart, but either `auth.client.useAutoTLS` or `auth.peer.useAutoTLS`.

If you have set the proper parameters, and SSL is still not enabled, it could be possible for it to be a bug of the container image scripts. If so, I recommend you to take a look into the [`run.sh`](https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/etcd/run.sh) script for etcd.

Maybe it is missing something like the below snippet for it to work. If so, would you be up for testing it in your deployment, and making a PR for fixing this in the container image repo?

```
...
read -r -a extra_flags <<< "$(etcdctl_auth_flags)"
[[ "${#extra_flags[@]}" -gt 0 ]] && cmd+=("${extra_flags[@]}")
...
cmd+=("$@")
```

**Comment by alop** [comment] 2022-04-19 20:27
Setting `auth.client.useAutoTLS: true` causes helm upgrades to fail.
Chart version 7.0.5, image version 3.4.18-debian-10-r20

```
etcd 20:22:47.35 
etcd 20:22:47.35 Welcome to the Bitnami etcd container
etcd 20:22:47.35 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
etcd 20:22:47.35 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
etcd 20:22:47.36 
etcd 20:22:47.36 INFO  ==> ** Starting etcd setup **
etcd 20:22:47.37 INFO  ==> Validating settings in ETCD_* env vars..
etcd 20:22:47.37 INFO  ==> Initializing etcd
etcd 20:22:47.38 INFO  ==> Generating etcd config file using env variables
etcd 20:22:47.38 INFO  ==> There is no data from previous deployments
etcd 20:22:47.38 INFO  ==> Adding new member to existing cluster
Error: open /bitnami/etcd/data/fixtures/client/cert.pem: no such file or directory
```
This causes the pod to restart, subsequent pod that launches fails with this error:
```
etcd 20:24:36.72 
etcd 20:24:36.73 Welcome to the Bitnami etcd container
etcd 20:24:36.73 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
etcd 20:24:36.73 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
etcd 20:24:36.73 
etcd 20:24:36.73 INFO  ==> ** Starting etcd setup **
etcd 20:24:36.75 INFO  ==> Validating settings in ETCD_* env vars..
etcd 20:24:36.75 INFO  ==> Initializing etcd
etcd 20:24:36.75 INFO  ==> Generating etcd config file using env variables
etcd 20:24:36.76 INFO  ==> Detected data from previous deployments
etcd 20:24:44.90 WARN  ==> Cluster not responding!
etcd 20:24:44.90 WARN  ==> Disaster recovery is disabled, the cluster will try to recover on it's own
etcd 20:24:44.90 INFO  ==> ** etcd setup finished! **

etcd 20:24:44.92 INFO  ==> ** Starting etcd **
2022-04-19 20:24:44.936214 I | pkg/flags: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=https://etcd-4.etcd-headless.muon-tenant-latitude-dev-1.svc.cluster.local:2379,https://etcd.muon-tenant-latitude-dev-1.svc.cluster.local:2379
2022-04-19 20:24:44.936255 I | pkg/flags: recognized and used environment variable ETCD_AUTH_TOKEN=jwt,priv-key=/opt/bitnami/etcd/certs/token/jwt-token.pem,sign-method=RS256,ttl=10m
2022-04-19 20:24:44.936262 I | pkg/flags: recognized and used environment variable ETCD_AUTO_TLS=true
2022-04-19 20:24:44.936270 I | pkg/flags: recognized and used environment variable ETCD_CLIENT_CERT_AUTH=false
2022-04-19 20:24:44.936277 I | pkg/flags: recognized and used environment variable ETCD_DATA_DIR=/bitnami/etcd/data
2022-04-19 20:24:44.936300 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=https://etcd-4.etcd-headless.muon-tenant-latitude-dev-1.svc.cluster.local:2380
2022-04-19 20:24:44.936313 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=etcd-0=https://etcd-0.etcd-headless.muon-tenant-latitude-dev-1.svc.cluster.local:2380,etcd-1=https://etcd-1.etcd-headless.muon-tenant-latitude-dev-1.svc.cluster.local:2380,etcd-2=https://etcd-2.etcd-headless.muon-tenant-latitude-dev-1.svc.cluster.local:2380,etcd-3=https://etcd-3.etcd-headless.muon-tenant-latitude-dev-1.svc.cluster.local:2380,etcd-4=https://etcd-4.etcd-headless.muon-tenant-latitude-dev-1.svc.cluster.local:2380
2022-04-19 20:24:44.936317 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=existing
2022-04-19 20:24:44.936323 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-k8s
2022-04-19 20:24:44.936332 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
2022-04-19 20:24:44.936342 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
2022-04-19 20:24:44.936346 I | pkg/flags: recognized and used environment variable ETCD_LOG_LEVEL=info
2022-04-19 20:24:44.936358 I | pkg/flags: recognized and used environment variable ETCD_NAME=etcd-4
2022-04-19 20:24:44.936371 I | pkg/flags: recognized and used environment variable ETCD_PEER_AUTO_TLS=true
2022-04-19 20:24:44.936392 W | pkg/flags: unrecognized environment variable ETCD_TRUSTED_CA_FILE=
2022-04-19 20:24:44.936397 W | pkg/flags: unrecognized environment variable ETCD_SERVICE_HOST=10.100.224.142
2022-04-19 20:24:44.936400 W | pkg/flags: unrecognized environment variable ETCD_PORT_2380_TCP_ADDR=10.100.224.142
2022-04-19 20:24:44.936403 W | pkg/flags: unrecognized environment variable ETCD_PORT_2379_TCP=tcp://10.100.224.142:2379
2022-04-19 20:24:44.936406 W | pkg/flags: unrecognized environment variable ETCD_CONF_FILE=/opt/bitnami/etcd/conf/etcd.yaml
2022-04-19 20:24:44.936409 W | pkg/flags: unrecognized environment variable ETCD_ON_K8S=yes
2022-04-19 20:24:44.936412 W | pkg/flags: unrecognized environment variable ETCD_PORT_2380_TCP_PROTO=tcp
2022-04-19 20:24:44.936415 W | pkg/flags: unrecognized environment variable ETCD_SNAPSHOTS_DIR=/snapshots
2022-04-19 20:24:44.936418 W | pkg/flags: unrecognized environment variable ETCD_BIN_DIR=/opt/bitnami/etcd/bin
2022-04-19 20:24:44.936421 W | pkg/flags: unrecognized environment variable ETCD_VOLUME_DIR=/bitnami/etcd
2022-04-19 20:24:44.936424 W | pkg/flags: unrecognized environment variable ETCD_PORT_2379_TCP_PORT=2379
2022-04-19 20:24:44.936429 W | pkg/flags: unrecognized environment variable ETCD_PORT_2379_TCP_ADDR=10.100.224.142
2022-04-19 20:24:44.936433 W | pkg/flags: unrecognized environment variable ETCD_PORT_2380_TCP_PORT=2380
2022-04-19 20:24:44.936438 W | pkg/flags: unrecognized environment variable ETCD_PORT_2380_TCP=tcp://10.100.224.142:2380
2022-04-19 20:24:44.936443 W | pkg/flags: unrecognized environment variable ETCD_CLUSTER_DOMAIN=etcd-headless.muon-tenant-latitude-dev-1.svc.cluster.local
2022-04-19 20:24:44.936445 W | pkg/flags: unrecognized environment variable ETCD_DISASTER_RECOVERY=no
2022-04-19 20:24:44.936448 W | pkg/flags: unrecognized environment variable ETCD_KEY_FILE=
2022-04-19 20:24:44.936451 W | pkg/flags: unrecognized environment variable ETCD_CONF_DIR=/opt/bitnami/etcd/conf
2022-04-19 20:24:44.936455 W | pkg/flags: unrecognized environment variable ETCD_DAEMON_GROUP=etcd
2022-04-19 20:24:44.936457 W | pkg/flags: unrecognized environment variable ETCD_START_FROM_SNAPSHOT=no
2022-04-19 20:24:44.936461 W | pkg/flags: unrecognized environment variable ETCD_SERVICE_PORT_CLIENT=2379
2022-04-19 20:24:44.936464 W | pkg/flags: unrecognized environment variable ETCD_INIT_SNAPSHOT_FILENAME=
2022-04-19 20:24:44.936466 W | pkg/flags: unrecognized environment variable ETCD_INIT_SNAPSHOTS_DIR=/init-snapshot
2022-04-19 20:24:44.936469 W | pkg/flags: unrecognized environment variable ETCD_TMP_DIR=/opt/bitnami/etcd/tmp
2022-04-19 20:24:44.936472 W | pkg/flags: unrecognized environment variable ETCD_SERVICE_PORT_PEER=2380
2022-04-19 20:24:44.936475 W | pkg/flags: unrecognized environment variable ETCD_BASE_DIR=/opt/bitnami/etcd
2022-04-19 20:24:44.936481 W | pkg/flags: unrecognized environment variable ETCD_PORT_2379_TCP_PROTO=tcp
2022-04-19 20:24:44.936484 W | pkg/flags: unrecognized environment variable ETCD_CERT_FILE=
2022-04-19 20:24:44.936487 W | pkg/flags: unrecognized environment variable ETCD_SERVICE_PORT=2379
2022-04-19 20:24:44.936490 W | pkg/flags: unrecognized environment variable ETCD_PORT=tcp://10.100.224.142:2379
2022-04-19 20:24:44.936492 W | pkg/flags: unrecognized environment variable ETCD_NEW_MEMBERS_ENV_FILE=/bitnami/etcd/data/new_member_envs
2022-04-19 20:24:44.936495 W | pkg/flags: unrecognized environment variable ETCD_DAEMON_USER=etcd
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2022-04-19 20:24:44.936523 I | etcdmain: etcd Version: 3.4.18
2022-04-19 20:24:44.936528 I | etcdmain: Git SHA: 72d3e382e
2022-04-19 20:24:44.936532 I | etcdmain: Go Version: go1.12.17
2022-04-19 20:24:44.936535 I | etcdmain: Go OS/Arch: linux/amd64
2022-04-19 20:24:44.936539 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2022-04-19 20:24:44.936577 W | etcdmain: found invalid file/dir fixtures under data dir /bitnami/etcd/data (Ignore this if you are upgrading etcd)
2022-04-19 20:24:44.936581 W | etcdmain: found invalid file/dir new_member_envs under data dir /bitnami/etcd/data (Ignore this if you are upgrading etcd)
2022-04-19 20:24:44.936608 N | etcdmain: the server is already initialized as member before, starting as etcd member...
[WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
2022-04-19 20:24:44.936714 I | embed: peerTLS: cert = /bitnami/etcd/data/fixtures/peer/cert.pem, key = /bitnami/etcd/data/fixtures/peer/key.pem, trusted-ca = , client-cert-auth = false, crl-file = 
2022-04-19 20:24:44.947721 I | embed: name = etcd-4
2022-04-19 20:24:44.947735 I | embed: data dir = /bitnami/etcd/data
2022-04-19 20:24:44.947739 I | embed: member dir = /bitnami/etcd/data/member
2022-04-19 20:24:44.947743 I | embed: heartbeat = 100ms
2022-04-19 20:24:44.947745 I | embed: election = 1000ms
2022-04-19 20:24:44.947748 I | embed: snapshot count = 100000
2022-04-19 20:24:44.947758 I | embed: advertise client URLs = https://etcd-4.etcd-headless.muon-tenant-latitude-dev-1.svc.cluster.local:2379,https://etcd.muon-tenant-latitude-dev-1.svc.cluster.local:2379
2022-04-19 20:24:44.947762 I | embed: initial advertise peer URLs = https://etcd-4.etcd-headless.muon-tenant-latitude-dev-1.svc.cluster.local:2380
2022-04-19 20:24:44.947767 I | embed: initial cluster = 
2022-04-19 20:24:44.958625 I | etcdserver: restarting member ed01ef3ea6a31427 in cluster 1ba234f0808a2a04 at commit index 0
raft2022/04/19 20:24:44 INFO: ed01ef3ea6a31427 switched to configuration voters=()
raft2022/04/19 20:24:44 INFO: ed01ef3ea6a31427 became follower at term 0
raft2022/04/19 20:24:44 INFO: newRaft ed01ef3ea6a31427 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2022-04-19 20:24:44.978897 I | etcdserver: starting server... [version: 3.4.18, cluster version: to_be_decided]
2022-04-19 20:24:44.989376 I | embed: ClientTLS: cert = /bitnami/etcd/data/fixtures/client/cert.pem, key = /bitnami/etcd/data/fixtures/client/key.pem, trusted-ca = , client-cert-auth = false, crl-file = 
2022-04-19 20:24:44.989446 I | embed: listening for peers on [::]:2380
2022-04-19 20:24:45.054858 I | rafthttp: started HTTP pipelining with peer 5851426593a2802e
2022-04-19 20:24:45.055034 E | rafthttp: failed to find member 5851426593a2802e in cluster 1ba234f0808a2a04
2022-04-19 20:24:45.085257 I | rafthttp: started HTTP pipelining with peer 247b63a3d72adfa6
2022-04-19 20:24:45.085276 E | rafthttp: failed to find member 247b63a3d72adfa6 in cluster 1ba234f0808a2a04
2022-04-19 20:24:45.088490 I | rafthttp: started HTTP pipelining with peer 164796b03338c849
2022-04-19 20:24:45.088507 E | rafthttp: failed to find member 164796b03338c849 in cluster 1ba234f0808a2a04
2022-04-19 20:24:45.090699 I | rafthttp: started HTTP pipelining with peer 87fc48ec92415321
2022-04-19 20:24:45.090719 E | rafthttp: failed to find member 87fc48ec92415321 in cluster 1ba234f0808a2a04
2022-04-19 20:24:45.093341 E | rafthttp: failed to find member 87fc48ec92415321 in cluster 1ba234f0808a2a04
2022-04-19 20:24:45.094627 E | rafthttp: failed to find member 164796b03338c849 in cluster 1ba234f0808a2a04
2022-04-19 20:24:45.098181 E | rafthttp: failed to find member 5851426593a2802e in cluster 1ba234f0808a2a04
2022-04-19 20:24:45.099980 E | rafthttp: failed to find member 247b63a3d72adfa6 in cluster 1ba234f0808a2a04
raft2022/04/19 20:24:45 INFO: ed01ef3ea6a31427 [term: 0] received a MsgHeartbeat message with higher term from 247b63a3d72adfa6 [term: 7]
raft2022/04/19 20:24:45 INFO: ed01ef3ea6a31427 became follower at term 7
raft2022/04/19 20:24:45 tocommit(23) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?
panic: tocommit(23) is out of range [lastIndex(0)]. Was the raft log corrupted, truncated, or lost?

goroutine 149 [running]:
log.(*Logger).Panicf(0xc000153860, 0x10e77d8, 0x5d, 0xc001314040, 0x2, 0x2)
	/home/remote/sbatsche/.gvm/gos/go1.12.17/src/log/log.go:219 +0xc1
go.etcd.io/etcd/raft.(*DefaultLogger).Panicf(0x1add5a0, 0x10e77d8, 0x5d, 0xc001314040, 0x2, 0x2)
	/home/remote/sbatsche/tmp/etcd-new-release/release-3.4/etcd/release/etcd/raft/logger.go:127 +0x60
go.etcd.io/etcd/raft.(*raftLog).commitTo(0xc0001161c0, 0x17)
	/home/remote/sbatsche/tmp/etcd-new-release/release-3.4/etcd/release/etcd/raft/log.go:203 +0x131
go.etcd.io/etcd/raft.(*raft).handleHeartbeat(0xc00017c280, 0x8, 0xed01ef3ea6a31427, 0x247b63a3d72adfa6, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/remote/sbatsche/tmp/etcd-new-release/release-3.4/etcd/release/etcd/raft/raft.go:1396 +0x54
go.etcd.io/etcd/raft.stepFollower(0xc00017c280, 0x8, 0xed01ef3ea6a31427, 0x247b63a3d72adfa6, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/remote/sbatsche/tmp/etcd-new-release/release-3.4/etcd/release/etcd/raft/raft.go:1341 +0x480
go.etcd.io/etcd/raft.(*raft).Step(0xc00017c280, 0x8, 0xed01ef3ea6a31427, 0x247b63a3d72adfa6, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/remote/sbatsche/tmp/etcd-new-release/release-3.4/etcd/release/etcd/raft/raft.go:984 +0x1113
go.etcd.io/etcd/raft.(*node).run(0xc000090a80)
	/home/remote/sbatsche/tmp/etcd-new-release/release-3.4/etcd/release/etcd/raft/node.go:352 +0xab6
created by go.etcd.io/etcd/raft.RestartNode
	/home/remote/sbatsche/tmp/etcd-new-release/release-3.4/etcd/release/etcd/raft/node.go:240 +0x33c
```

**Comment by marcosbc** [comment] 2022-04-21 15:49
@alop Could you share the steps and configurations to reproduce the issue in a consistent way?

**Comment by alop** [comment] 2022-04-21 17:25
@marcosbc This is my overrides:
```
auth:
  client:
    secureTransport: true
    useAutoTLS: true
  peer:
    secureTransport: true
    useAutoTLS: true
  rbac:
    create: true
    existingSecret: etcd
  token:
    type: simple
persistence:
  enabled: false
replicaCount: 5
```

installed by `helm install etcd bitnami/etcd --version 7.0.5 -f overrides.yaml`

**Comment by marcosbc** [comment] 2022-04-28 15:33
I see. I think your issue is happening because etcd is not able to keep track of the nodes in the cluster, getting confused when there is a full cluster re-deployment. You should consider enabling [disaster recovery](https://docs.bitnami.com/kubernetes/infrastructure/etcd/administration/enable-disaster-recovery/).

**Comment by carrodher** [comment] 2022-10-20 12:57
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.

**Closed by carrodher** 2022-10-20 12:57 UTC
Labels: on-hold
