### ISSUE TITLE
Node 1 deploys, node > 1 not deploying with WSREP: failed to open gcomm backend

### ISSUE THREAD

**Issue by darealShadow** [bitnami/charts#8498] opened 2021-12-24 20:32 UTC
**Which chart**:
Mariadb-galera-6.0.8
Appversion 10.6.5

**Describe the bug**
Deploying through helm, the first node is created and is running but any subsequent node is not created failing with:
```
2021-12-23 22:27:16 0 [ERROR] WSREP: failed to open gcomm backend connection: 110: failed to reach primary view: 110 (Connection timed out) at /bitnami/blacksmith-sandox/libgalera-26.4.9/gcomm/src/pc.cpp:connect():160
2021-12-23 22:27:16 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs_core.cpp:gcs_core_open():220: Failed to open backend connection: -110 (Connection timed out)
2021-12-23 22:27:16 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs.cpp:gcs_open():1633: Failed to open channel 'galera' at 'gcomm://mariadb-galera-cluster-headless.database.svc.cluster.local': -110 (Connection timed out)
2021-12-23 22:27:16 0 [ERROR] WSREP: gcs connect failed: Connection timed out
2021-12-23 22:27:16 0 [ERROR] WSREP: wsrep::connect(gcomm://mariadb-galera-cluster-headless.database.svc.cluster.local) failed: 7
2021-12-23 22:27:16 0 [ERROR] Aborting
```

**To Reproduce**

1. create 3 NFS persistent volumes
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-persistent-storage-0
  labels:
    app: mariadb-galera-cluster
  namespace: database
spec:
  capacity:
    storage: 5Gi
  mountOptions:
    - nolock
  accessModes:
    - ReadWriteOnce
  nfs:
    server: <NFS SERVER IP>
    path: /full/path/to/mnt
```
2. run the `helm install mariadb-galera-cluster bitnami/mariadb-galera -n database -f values.yaml` only changes I made to the values file are:
```yaml
persistence:
  ...
  enabled: true
  ## @param persistence.selector Selector to match an existing Persistent Volume (this value is evaluated as a template)
  selector:
    matchLabels:
      app: mariadb-galera-cluster
  ##
  selector: {}
  annotations: {}
  ## @param persistence.accessModes Persistent Volume Access Modes
  ##
  accessModes:
    - ReadWriteOnce
  ## @param persistence.size Persistent Volume Size
  ##
  size: 5Gi
```
3. watch the logs for the nodes

**Expected behavior**
communication between the different nodes should work without issue.
**Version of Helm and Kubernetes**:
```
Client Version: v1.23.1
Server Version: v1.23.0
```

**Additional context**
I was able to make the cluster work by walking through the following steps:
1.	Find the file for the first node and `cat grastate.dat`
2.	Copy the information in the file.
3.	Edit the file for the next node with `vim grastate.dat`
4.	Paste the information into the next nodes file. 
5.	Remove UUID
6.	Save the file
7.	Delete the last node in the status `CrashLoopBackOff` or `Error` so it is recreated with `kubectl delete pod mariadb-galera-cluster-X` where x stands for the node in the cluster you want to delete.
8. once the new node is created the information in the file is used and the pod starts running without any issue.

**Comment by javsalgar** [comment] 2021-12-27 09:08
Hi,

Does the first node ever become in READY status? This connection timeout error sounds to me that the node never gets available. If it is ready, it seems to me that it could be related to some networking error in the cluster. Do you have any NetworkPolicy enabled?

**Comment by darealShadow** [comment] 2021-12-27 17:19
Thanks for your answer. Yes, node 1 becomes ready and is available. There are no network policies established. I implemented the cluster again and that time node 2 deployed as well just node 3 did not. So I deleted the node and then the last one started fine as well. I just don't know how I can make sure that everything works as it should without interfering. On top of that I simulated the failure of node 2 by deleting it and when the node was restarted I ran into the same error. Without manual intervention the node did not want to come up again. I am concerned that in a production environment such a failure could become catastrophic.

**Comment by javsalgar** [comment] 2021-12-28 09:05
Hi,

Could you check in which of the Kubernetes nodes the pods get deployed. It seems that network connection fails in one of the Kubernetes nodes, that would explain why it sometimes work and sometimes it doesn't.

**Comment by darealShadow** [comment] 2021-12-28 19:04
Hi,

I did what you asked and tested the failure again. Deleting node 1 and waiting for recreation. The initial failure, not being able to communicate with the first node, happened twice this time before the node recreated properly.  I got the same error message as mentioned in my initial post (`failed to open gcomm...`). The node is hosted on my worker 4. I did the same with node 2 hosted on worker 2 and that one created without an issue instantly. Deleting node 0, hosted on worker 2, failed to recreate as well with the `failed to open gcomm` error and ran into a CrashLoopError. After deleting the pod again it recreated flawlessly. 
On none of my VM's (1 master, 4 workers) a firewall is active. I checked that to make sure I don't run into issues. It is a test cluster on which I try new stuff before deploying in production. As I mentioned in my previous post, there are not network policies applied. That would be the last step after everything is working to tighten security.
I am grateful for any ideas.

**Comment by javsalgar** [comment] 2021-12-30 08:59
Hi

> After deleting the pod again it recreated flawlessly

Question, did it get scheduled in the same node after recreating?

**Comment by darealShadow** [comment] 2021-12-30 21:44
Yes. Same node.

**Comment by javsalgar** [comment] 2021-12-31 11:03
Hi,

Just a note to let you know that I was able to reproduce the issue. This is what I did using an installation with the default values in minikube.

```
kubectl delete pod galera-mariadb-galera-0
# wait until ready
kubectl delete pod galera-mariadb-galera-0 galera-mariadb-galera-2
```

I've opened a task for investigating this. As soon as there are news, we will update the ticket. Thank you so much for reporting!

**Comment by darealShadow** [comment] 2022-01-02 19:35
Thanks for your feedback. I am really glad you were able to reproduce the issue and can try to find a way to make it work for future releases. I really like that database cluster and want to do anything I can help to improve it. Even though it is not a lot just reporting an issue... Anyway looking forward to your update. Let me know and I will test it.

**Comment by rafariossaa** [comment] 2022-02-07 14:48
We have released a new version of the chart that should fix the issues releated with nodes not being part of the cluster and cluster not bootstraping correctly.

Chart version: 7.0.1
Galera Docker image: 10.6.5-debian-10-r66

Could you give it a try ?

**Comment by darealShadow** [comment] 2022-02-07 15:29
Hello Rafael,

thanks for your message. Absolutely. I'll deploy it in my dev environment and let you know if I run into any issues.

**Comment by rafariossaa** [comment] 2022-02-08 09:15
Hi @darealShadow ,
  Thank you very much for taking the time to test it again and provide feedback.
  I am happy this seems to be solved in your initial tests. 
  If  you don't mind, I am closing this issue now, but don't hesitate to reopen it if you find any problem.

**Closed by rafariossaa** 2022-02-08 09:15 UTC
Labels: on-hold
