### ISSUE TITLE
[bitnami/redis-cluster] unable to connect to redis-cluster using nodeport

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#12184] opened 2022-08-29 07:41 UTC
### Name and Version

bitnami/redis-cluster , latest

### What steps will reproduce the bug?

helm install redis-cluster redis-cluster

### Are you using any custom parameters or values?

service.type =nodeport
externalacess.enabled=true

### What is the expected behavior?

i should be able to connect to redis-cluster pod using nodeport 

### What do you see instead?

i am unable to connect through node port 
i am using redis-cli -c -a password123 -h 172.16.3.50 -p 30116 command 
it is neither showing any error nor any thing else. it is just stuck
![Screenshot from 2022-08-29 13-11-43](https://user-images.githubusercontent.com/68244292/187149822-e9a06f29-fb33-4796-bf80-a220394fb0a1.png)

### Additional information

i am using metallb to get external ip . 
output of kubectl describe svc redis-cluster
![Uploading Screenshot from 2022-08-29 13-09-13.png…]()

**Comment by abhishekgupta2205** [comment] 2022-08-29 07:42
![Screenshot from 2022-08-29 13-09-13](https://user-images.githubusercontent.com/68244292/187149985-d5d6ef01-9084-4563-81a6-abb2653754fb.png)

**Comment by javsalgar** [comment] 2022-08-29 08:47
Hi,

Could you provide the output of `kubectl get svc -o wide`

**Comment by abhishekgupta2205** [comment] 2022-08-29 11:50
![image](https://user-images.githubusercontent.com/68244292/187194666-b52cd0c3-8f74-4392-a2f9-3f690483e836.png)

**Comment by abhishekgupta2205** [comment] 2022-08-30 05:18
i am using minikube type of cluster and using metallb to get externalip.
Also i am unable to connect to any pod through its external ip

**Comment by javsalgar** [comment] 2022-08-30 09:44
Hi,

I see that you are configuring the chart to use LoadBalancer, judging by the services created. Could you also set `cluster.externalAccess.service.type` to `NodePort`?

**Comment by abhishekgupta2205** [comment] 2022-08-30 10:27
it only support loadbalancer or cluster type only according to docs.
![Screenshot from 2022-08-30 15-57-07](https://user-images.githubusercontent.com/68244292/187414232-1499acd8-51fb-4981-8a7b-253504a420c5.png)

**Comment by migruiz4** [comment] 2022-09-01 06:28
Hi @abhishekgupta2205, this issue is a duplicate of #12165, please let's continue the discussion there.

**Closed by migruiz4** 2022-09-01 06:28 UTC
Labels: in-progress, tech-issues, redis-cluster
