### ISSUE TITLE
[bitnami/minio] chart 11.10.13 deploys broken docker.io/bitnami/minio:2022.10.29-debian-11-r0 image

### ISSUE THREAD

**Issue by morremeyer** [bitnami/charts#13245] opened 2022-10-29 16:31 UTC
### Name and Version

bitnami/minio

### What steps will reproduce the bug?

I upgraded from `11.10.12` to `11.10.13` today, which upgraded the image from `docker.io/bitnami/minio:2022.10.24-debian-11-r0` to `docker.io/bitnami/minio:2022.10.29-debian-11-r0`.

### Are you using any custom parameters or values?

```yaml
auth:
  existingSecret: minio-secret
  forcePassword: true
persistence:
  size: 300Gi
ingress:
  enabled: true
  hostname: minio-console.example.com
  annotations:
    "traefik.ingress.kubernetes.io/router.middlewares": minio-allowlist-minio@kubernetescrd
apiIngress:
  enabled: true
  hostname: minio.example.com
  annotations:
    "traefik.ingress.kubernetes.io/router.middlewares": minio-allowlist-minio@kubernetescrd
extraEnvVars:
  - name: MINIO_BROWSER_REDIRECT_URL
    value: https://minio-console.example.com
metrics:
  serviceMonitor:
    enabled: true
```

### What is the expected behavior?

Minio not crashlooping.

### What do you see instead?

With that image version, the `minio` container kept getting Terminated with the exit code 137 (OOM), but I could not find any other sign of a memory issue - the pod did not seem to use more than 10MB of memory at any point.

However, the logs showed the following:

```plain
 16:23:09.11 
 16:23:09.11 Welcome to the Bitnami minio container
 16:23:09.11 Subscribe to project updates by watching https://github.com/bitnami/containers
 16:23:09.11 Submit issues and feature requests at https://github.com/bitnami/containers/issues
 16:23:09.11 
 16:23:09.11 INFO  ==> ** Starting MinIO setup **
minio 16:23:09.14 INFO  ==> Starting MinIO in background...
minio 16:23:19.17 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:23:24.25 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:23:29.32 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:23:34.40 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:23:39.51 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:23:44.57 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 16:23:49.64 INFO  ==> Adding local Minio host to 'mc' configuration...
```

Where `Adding local Minio host to 'mc' configuration...` usually only appears once.

### Additional information

I downgraded back to `11.10.12` which immediately fixed the issue.

**Comment by ekeih** [comment] 2022-10-29 17:38
I can confirm the issue, updated from the same version and the new pod seems stuck in a loop of `Adding local Minio host to 'mc' configuration` messages.
But I don't think it is an OOM issue. Exit code 137 indicates that the container was killed by the container runtime, one of the triggers for this could be OOM, but in this case I think the liveness probe keeps failing until the kubelet tells the container runtime to kill the container.

**Comment by ekeih** [comment] 2022-10-29 18:02
Looks like it is stuck in https://github.com/bitnami/containers/blob/a1247fc8c297646844b557cd243cf5a313606453/bitnami/minio/2022/debian-11/rootfs/opt/bitnami/scripts/minio/setup.sh#L51 which calls https://github.com/bitnami/containers/blob/a1247fc8c297646844b557cd243cf5a313606453/bitnami/minio/2022/debian-11/rootfs/opt/bitnami/scripts/libminioclient.sh#L79.

**Comment by ekeih** [comment] 2022-10-29 18:16
To check if maybe the new version just takes longer to start I increased the initial delay of the liveness probe to 120 seconds, but then it just retries until it runs into the 1 minute timeout of the `setup.sh` from the last comment:
```
 18:12:39.83 Welcome to the Bitnami minio container
 18:12:39.83 Subscribe to project updates by watching https://github.com/bitnami/containers
 18:12:39.84 Submit issues and feature requests at https://github.com/bitnami/containers/issues
 18:12:39.84
 18:12:39.84 INFO  ==> ** Starting MinIO setup **
minio 18:12:39.87 INFO  ==> Starting MinIO in background...
minio 18:12:49.89 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 18:12:54.92 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 18:12:59.96 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 18:13:04.99 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 18:13:10.03 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 18:13:15.06 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 18:13:20.09 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 18:13:25.12 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 18:13:30.15 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 18:13:35.20 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 18:13:40.23 INFO  ==> Adding local Minio host to 'mc' configuration...
minio 18:13:45.26 INFO  ==> Adding local Minio host to 'mc' configuration...
Failed to add temporary MinIO server
minio 18:13:50.29 INFO  ==> MinIO is already stopped...
```

**Comment by ekeih** [comment] 2022-11-11 19:27
Let me know if there is anything I can try to help debugging this. It is still happening with the newer chart/image for me.

**Comment by ekeih** [comment] 2022-11-23 22:16
Looks like it is still happening with chart `11.10.18` and the image `docker.io/bitnami/minio:2022.11.17-debian-11-r0`.

@CeliaGMqrz Is there another place where we should report this or is this the right place?

**Comment by ekeih** [comment] 2022-11-24 17:37
Reading up on https://github.com/bitnami/containers/issues/13592 the answer to this is https://min.io/docs/minio/linux/operations/install-deploy-manage/migrate-fs-gateway.html, so to solve it it is necessary to migrate the minio instance to a new backend.

I would say we can close this issue as it is unrelated to the chart.

**Comment by CeliaGMqrz** [comment] 2022-11-28 08:30
Hi @ekeih 

Thank you for your patience. It seems that this is related to the container as you say. If the problem was not solved that way, you can open this issue in [bitnami/containers](https://github.com/bitnami/containers/issues).

Thanks for the report.

**Closed by CeliaGMqrz** 2022-11-28 08:30 UTC
Labels: in-progress, tech-issues, minio
