### ISSUE TITLE
[bitnami/mongodb] Can't upgrade chart when auth.enable=false

### ISSUE THREAD

**Issue by ktaletsk** [bitnami/charts#15311] opened 2023-03-03 05:07 UTC
### Name and Version

bitnami/mongodb 13.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. install the chart with --set auth.enabled=false
2. update any value (the service values for example)
3. upgrade
4. see error

### Are you using any custom parameters or values?

auth.enabled=false

### What is the expected behavior?

Upgrade should go through without error messages

### What do you see instead?

```
Error: UPGRADE FAILED: execution error at (compute/charts/mongodb/templates/secrets.yaml:20:21): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MONGODB_ROOT_PASSWORD' to the command. To get the current value:

        export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace "default" <release_name>-mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 -d)
```

### Additional information

I tested a number of previous version which are not affected by this bug: 13.0.0, 13.2.0, 13.4.0, 13.6.0, 13.6.8
13.7.0 was the first version to have the issue
Current version 13.8.2 still has the issue

Also, it looks like the problem surfaced before and was fixed then https://github.com/bitnami/charts/issues/3425

**Comment by day1118** [comment] 2023-03-03 10:30
I think the issue is caused by the following PR: https://github.com/bitnami/charts/pull/14910

I was able to work around it by leaving `auth.enabled=false` and creating a secret with a dummy value for the `mongodb-root-password` key, however, the logic should be fixed to remove this condition.

**Closed** 2023-03-08 11:24 UTC
Labels: in-progress, tech-issues
