### ISSUE TITLE
reinstalled mariadb-galera cluster can't start, failed to open gcomm backend connection

### ISSUE THREAD

**Issue by ohthehugemanatee** [bitnami/charts#8277] opened 2021-11-30 22:36 UTC
**Which chart**:

CHART NAME: mariadb-galera
CHART VERSION: 6.0.5
APP VERSION: 10.6.5

**Describe the bug**
After a `helm uninstall`, delete PV/Cs, and fresh install, no pods can start. In the log they appear to be attempting to load a previous boot, but even if I delete the data directory from the (new) PVC, the error state is unchanged: `WSREP: failed to open gcomm backend connection`. 

**To Reproduce**

1. Install the chart, let all nodes start
2. Uninstall the chart
3. Manually remove any PVCs and PVs left lying around
4. Double check there's nothing left with `kubectl get all`
5. Install the chart again. Can be under a new name and/or new namespace if you like.
6. Watch your pods fail. 

**Expected behavior**
I expect the pods to start and form a cluster normally, as they did on the first installation.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
 ```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.1"}`
```
- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"archive", BuildDate:"2021-10-28T06:55:39Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+k3s1", GitCommit:"3e250fdbab72d88f7e6aae57446023a0567ffc97", GitTreeState:"clean", BuildDate:"2021-08-19T19:10:16Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/arm"}

```

**Additional context**

Complete log from the first failed pod below. The data directory had just been deleted on a previous run, which is why it has 00000000-0000-0000-0000-000000000000 as the ID. This did not change the end failure to connect, however. 

```
mariadb 22:26:13.33 
mariadb 22:26:13.33 Welcome to the Bitnami mariadb-galera container
mariadb 22:26:13.33 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
mariadb 22:26:13.34 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
mariadb 22:26:13.35 
mariadb 22:26:13.36 INFO  ==> ** Starting MariaDB setup **
mariadb 22:26:13.40 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 22:26:13.41 INFO  ==> Initializing mariadb database
mariadb 22:26:13.45 WARN  ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable or does not exist. Configurations based on environment variables will not be applied for this file.
mariadb 22:26:13.46 INFO  ==> ** MariaDB setup finished! **

mariadb 22:26:13.53 INFO  ==> ** Starting MariaDB **
mariadb 22:26:13.54 INFO  ==> Setting previous boot
2021-11-30 22:26:13 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (server 10.6.5-MariaDB-log) starting as process 1 ...
2021-11-30 22:26:13 0 [Note] WSREP: Loading provider /opt/bitnami/mariadb/lib/libgalera_smm.so initial position: 00000000-0000-0000-0000-000000000000:-1
2021-11-30 22:26:13 0 [Note] WSREP: wsrep_load(): loading provider library '/opt/bitnami/mariadb/lib/libgalera_smm.so'
2021-11-30 22:26:13 0 [Note] WSREP: wsrep_load(): Galera 4.9(rXXXX) by Codership Oy <info@codership.com> loaded successfully.
2021-11-30 22:26:13 0 [Note] WSREP: CRC-32C: using 64-bit x86 acceleration.
2021-11-30 22:26:13 0 [Note] WSREP: Found saved state: 00000000-0000-0000-0000-000000000000:-1, safe_to_bootstrap: 1
2021-11-30 22:26:13 0 [Note] WSREP: GCache DEBUG: opened preamble:
Version: 2
UUID: 00000000-0000-0000-0000-000000000000
Seqno: -1 - -1
Offset: -1
Synced: 1
2021-11-30 22:26:13 0 [Note] WSREP: Skipped GCache ring buffer recovery: could not determine history UUID.
2021-11-30 22:26:13 0 [Note] WSREP: Passing config to GCS: base_dir = /bitnami/mariadb/data/; base_host = 10.42.7.199; base_port = 4567; cert.log_conflicts = no; cert.optimistic_pa = yes; debug = no; evs.auto_evict = 0; evs.delay_margin = PT1S; evs.delayed_keep_period = PT30S; evs.inactive_check_period = PT0.5S; evs.inactive_timeout = PT15S; evs.join_retrans_period = PT1S; evs.max_install_timeouts = 3; evs.send_window = 4; evs.stats_report_period = PT1M; evs.suspect_timeout = PT5S; evs.user_send_window = 2; evs.view_forget_timeout = PT24H; gcache.dir = /bitnami/mariadb/data/; gcache.keep_pages_size = 0; gcache.mem_size = 0; gcache.name = galera.cache; gcache.page_size = 128M; gcache.recover = yes; gcache.size = 128M; gcomm.thread_prio = ; gcs.fc_debug = 0; gcs.fc_factor = 1.0; gcs.fc_limit = 16; gcs.fc_master_slave = no; gcs.max_packet_size = 64500; gcs.max_throttle = 0.25; gcs.recv_q_hard_limit = 9223372036854775807; gcs.recv_q_soft_limit = 0.25; gcs.sync_donor = no; gmcast.segment = 0; gmcast.version = 0; pc.announce_timeout = PT3S; p
2021-11-30 22:26:13 0 [Note] WSREP: Start replication
2021-11-30 22:26:13 0 [Note] WSREP: Connecting with bootstrap option: 0
2021-11-30 22:26:13 0 [Note] WSREP: Setting GCS initial position to 00000000-0000-0000-0000-000000000000:-1
2021-11-30 22:26:13 0 [Note] WSREP: protonet asio version 0
2021-11-30 22:26:13 0 [Note] WSREP: Using CRC-32C for message checksums.
2021-11-30 22:26:13 0 [Note] WSREP: backend: asio
2021-11-30 22:26:13 0 [Note] WSREP: gcomm thread scheduling priority set to other:0 
2021-11-30 22:26:13 0 [Warning] WSREP: access file(/bitnami/mariadb/data//gvwstate.dat) failed(No such file or directory)
2021-11-30 22:26:13 0 [Note] WSREP: restore pc from disk failed
2021-11-30 22:26:13 0 [Note] WSREP: GMCast version 0
2021-11-30 22:26:13 0 [Note] WSREP: (86d77b2d-b3d1, 'tcp://0.0.0.0:4567') listening at tcp://0.0.0.0:4567
2021-11-30 22:26:13 0 [Note] WSREP: (86d77b2d-b3d1, 'tcp://0.0.0.0:4567') multicast: , ttl: 1
2021-11-30 22:26:13 0 [Note] WSREP: EVS version 1
2021-11-30 22:26:13 0 [Note] WSREP: gcomm: connecting to group 'galera', peer 'home-galera-mariadb-galera-headless.galera.svc.cluster.local:'
2021-11-30 22:26:13 0 [Note] WSREP: (86d77b2d-b3d1, 'tcp://0.0.0.0:4567') Found matching local endpoint for a connection, blacklisting address tcp://10.42.7.199:4567
2021-11-30 22:26:16 0 [Note] WSREP: EVS version upgrade 0 -> 1
2021-11-30 22:26:16 0 [Note] WSREP: PC protocol upgrade 0 -> 1
2021-11-30 22:26:16 0 [Warning] WSREP: no nodes coming from prim view, prim not possible
2021-11-30 22:26:16 0 [Note] WSREP: view(view_id(NON_PRIM,86d77b2d-b3d1,1) memb {
	86d77b2d-b3d1,0
} joined {
} left {
} partitioned {
})
2021-11-30 22:26:17 0 [Warning] WSREP: last inactive check more than PT1.5S ago (PT3.50778S), skipping check
2021-11-30 22:26:46 0 [Note] WSREP: PC protocol downgrade 1 -> 0
2021-11-30 22:26:46 0 [Note] WSREP: view((empty))
2021-11-30 22:26:46 0 [ERROR] WSREP: failed to open gcomm backend connection: 110: failed to reach primary view: 110 (Connection timed out)
	at /bitnami/blacksmith-sandox/libgalera-26.4.9/gcomm/src/pc.cpp:connect():160
2021-11-30 22:26:46 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs_core.cpp:gcs_core_open():220: Failed to open backend connection: -110 (Connection timed out)
2021-11-30 22:26:46 0 [ERROR] WSREP: /bitnami/blacksmith-sandox/libgalera-26.4.9/gcs/src/gcs.cpp:gcs_open():1633: Failed to open channel 'galera' at 'gcomm://home-galera-mariadb-galera-headless.galera.svc.cluster.local': -110 (Connection timed out)
2021-11-30 22:26:46 0 [ERROR] WSREP: gcs connect failed: Connection timed out
2021-11-30 22:26:46 0 [ERROR] WSREP: wsrep::connect(gcomm://home-galera-mariadb-galera-headless.galera.svc.cluster.local) failed: 7
2021-11-30 22:26:46 0 [ERROR] Aborting
```

**Comment by juan131** [comment] 2021-12-16 07:36
Hi @ohthehugemanatee 

Sorry but the we lose the track of this issue.

Could you please share the values.yaml (or equivalent parameters) you're using to install the chart? We'd like to reproduce the exact same issue in our environment.

**Comment by floek** [comment] 2021-12-26 09:46
Same problem here with latest Bitnami helm chart 6.1.0

**Comment by Lamaspanzer** [comment] 2021-12-27 13:42
Same problem here with latest Bitnami helm chart 6.1.0

**Comment by carrodher** [comment] 2021-12-27 16:02
I am trying to reproduce the issue by following the next steps:

1.- Install the chart in a new namespace by running
```console
$ helm install galera -n new-ns --create-namespace bitnami/mariadb-galera
NAME: galera
LAST DEPLOYED: Mon Dec 27 15:45:12 2021
NAMESPACE: new-ns
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: mariadb-galera
CHART VERSION: 6.1.1
APP VERSION: 10.6.5
...
```

2.- Check the different resources in that namespace. Everything is up and running:
```console
$ kubectl get all -n new-ns
NAME                          READY   STATUS    RESTARTS   AGE
pod/galera-mariadb-galera-0   1/1     Running   0          3m15s
pod/galera-mariadb-galera-1   1/1     Running   0          2m23s
pod/galera-mariadb-galera-2   1/1     Running   0          78s

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/galera-mariadb-galera            ClusterIP   10.30.254.158   <none>        3306/TCP                     3m16s
service/galera-mariadb-galera-headless   ClusterIP   None            <none>        4567/TCP,4568/TCP,4444/TCP   3m16s

NAME                                     READY   AGE
statefulset.apps/galera-mariadb-galera   3/3     3m16s
```

3.- Uninstall the chart, remove PVs/PVCs:
```console
$ helm delete galera -n new-ns
release "galera" uninstalled

$ kubectl delete pvc -n new-ns data-galera-mariadb-galera-0 data-galera-mariadb-galera-1 data-galera-mariadb-galera-2
persistentvolumeclaim "data-galera-mariadb-galera-0" deleted
persistentvolumeclaim "data-galera-mariadb-galera-1" deleted
persistentvolumeclaim "data-galera-mariadb-galera-2" deleted

$ kubectl get all -n new-ns
No resources found in new-ns namespace.
```

4.- Install the chart again using different approaches:
4.1.- Same name and namespace
```
$ helm install galera -n new-ns bitnami/mariadb-galera

$ kubectl get all -n new-ns
NAME                          READY   STATUS    RESTARTS   AGE
pod/galera-mariadb-galera-0   1/1     Running   0          7m23s
pod/galera-mariadb-galera-1   1/1     Running   0          6m26s
pod/galera-mariadb-galera-2   1/1     Running   0          5m30s

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/galera-mariadb-galera            ClusterIP   10.30.251.100   <none>        3306/TCP                     7m23s
service/galera-mariadb-galera-headless   ClusterIP   None            <none>        4567/TCP,4568/TCP,4444/TCP   7m23s

NAME                                     READY   AGE
statefulset.apps/galera-mariadb-galera   3/3     7m23s
```
4.2.- Same name and different namespace
```console
$ helm install galera -n new-ns2 --create-namespace bitnami/mariadb-galera

$ kubectl get all -n new-ns2
NAME                          READY   STATUS    RESTARTS   AGE
pod/galera-mariadb-galera-0   1/1     Running   0          7m57s
pod/galera-mariadb-galera-1   1/1     Running   0          7m4s
pod/galera-mariadb-galera-2   1/1     Running   0          6m6s

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/galera-mariadb-galera            ClusterIP   10.30.249.255   <none>        3306/TCP                     7m57s
service/galera-mariadb-galera-headless   ClusterIP   None            <none>        4567/TCP,4568/TCP,4444/TCP   7m57s

NAME                                     READY   AGE
statefulset.apps/galera-mariadb-galera   3/3     7m58s
```
4.3.- Different name and namespace
```console
$ helm install galera3 -n new-ns3 --create-namespace bitnami/mariadb-galera

$ kubectl get all -n new-ns3
NAME                           READY   STATUS    RESTARTS   AGE
pod/galera3-mariadb-galera-0   1/1     Running   0          7m47s
pod/galera3-mariadb-galera-1   1/1     Running   0          6m58s
pod/galera3-mariadb-galera-2   1/1     Running   0          5m54s

NAME                                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
service/galera3-mariadb-galera            ClusterIP   10.30.248.43   <none>        3306/TCP                     7m47s
service/galera3-mariadb-galera-headless   ClusterIP   None           <none>        4567/TCP,4568/TCP,4444/TCP   7m47s

NAME                                      READY   AGE
statefulset.apps/galera3-mariadb-galera   3/3     7m48s
```

The different use cases are working fine, what are you doing differently than me?

**Comment by floek** [comment] 2021-12-28 07:23
Hi,

I'm using Ansible to install the chart in it's own namespace. I have a bare-metal cluster setup with kubeprod here. The chart was working fine up to Version 5.6.2. Now I even can't upgrade from 5.6.2 to 6.1.0. I end up with `WSREP: failed to open gcomm backend connection`. I haven't testet 6.1.1 yet.

Best,
Floek

**Comment by carrodher** [comment] 2021-12-28 08:55
Can you try using 6.1.1? it seems an issue with upgrades introduced in a previous PR was fixed in this version, see https://github.com/bitnami/charts/pull/8271

**Comment by Cryingmouse** [comment] 2021-12-29 09:36
> Can you try using 6.1.1? it seems an issue with upgrades introduced in a previous PR was fixed in this version, see #8271

Hi Carrodher，
Base on your instruction, I can deploy Galera cluster successfully. But it is very strange that there are three Galera clusters with only ONE member. Could you please help to double check?

**The output from mariadb:**
```
[root@node-1 k3s_install]# kubectl run galera-mariadb-galera-client --rm --tty -i --restart='Never' --namespace galera --image docker.io/bitnami/mariadb-galera:10.6.5-debian-10-r35 --command \
>       -- mysql -h galera-mariadb-galera -P 3306 -uroot -p$(kubectl get secret --namespace galera galera-mariadb-galera -o jsonpath="{.data.mariadb-root-password}" | base64 --decode) my_database
If you don't see a command prompt, try pressing enter.
MariaDB [my_database]> show status like 'wsrep_cluster_size';
+--------------------+-------+
| Variable_name      | Value |
+--------------------+-------+
| wsrep_cluster_size | 1     |
+--------------------+-------+
1 row in set (0.022 sec)

MariaDB [my_database]>
```

In addition, I also check the logs from each pod
>> **Pod 1 (galera-mariadb-galera-0)**
```
2021-12-29  9:11:45 2 [Note] WSREP: ================================================
View:
  id: 557106c2-6887-11ec-9b7b-1fa6ca051bf1:13
  status: primary
  protocol_version: 4
  capabilities: MULTI-MASTER, CERTIFICATION, PARALLEL_APPLYING, REPLAY, ISOLATION, PAUSE, CAUSAL_READ, INCREMENTAL_WS, UNORDERED, PREORDERED, STREAMING, NBO
  final: no
  own_index: 0
  members(1):
        0: 5827dab9-6887-11ec-b31e-a767a86e55ab, galera-mariadb-galera-0
=================================================
```

>> **Pod 2 (galera-mariadb-galera-1)**
```
2021-12-29  9:12:46 1 [Note] WSREP: ================================================
View:
  id: 7a4dc8f3-6887-11ec-a893-fe6f7a26c041:13
  status: primary
  protocol_version: 4
  capabilities: MULTI-MASTER, CERTIFICATION, PARALLEL_APPLYING, REPLAY, ISOLATION, PAUSE, CAUSAL_READ, INCREMENTAL_WS, UNORDERED, PREORDERED, STREAMING, NBO
  final: no
  own_index: 0
  members(1):
        0: 7cef98d4-6887-11ec-a47f-0209c904831e, galera-mariadb-galera-1
=================================================
```
>> **Pod 3 (galera-mariadb-galera-2)**
```
2021-12-29  9:14:07 2 [Note] WSREP: ================================================
View:
  id: aacd711d-6887-11ec-97a1-3b40e7d88c56:13
  status: primary
  protocol_version: 4
  capabilities: MULTI-MASTER, CERTIFICATION, PARALLEL_APPLYING, REPLAY, ISOLATION, PAUSE, CAUSAL_READ, INCREMENTAL_WS, UNORDERED, PREORDERED, STREAMING, NBO
  final: no
  own_index: 0
  members(1):
        0: ad330a40-6887-11ec-8c6b-472e7aa8ce41, galera-mariadb-galera-2
=================================================
```

**Comment by carrodher** [comment] 2021-12-30 09:11
If you are not using the defaults, can you please provide the parameters or values you're using to deploy the Helm chart?
In the same way and in order to reproduce the issue, are you doing any other customization or just deploying the Helm chart with custom values?

**Comment by floek** [comment] 2021-12-30 18:17
Hi,
I'll test 6.1.1 in a few days. At the moment I've not time. If the the issue is still there, I'll report my setup in detail.

Best,
floek

**Comment by Cryingmouse** [comment] 2022-01-04 02:10
@carrodher, I tested 6.1.1 with your instruction today, the same behavior as I mentioned above - It does not setup a Galera cluster with three members:
```
helm install galera -n new-ns --create-namespace bitnami/mariadb-galera
```
I am using K3S, here is the environment I used:
```
[root@node-1 /]# kubectl get node
NAME     STATUS     ROLES                  AGE     VERSION
node-1   Ready      control-plane,master   5d16h   v1.22.2+k3s2
node-2   NotReady   control-plane,master   5d16h   v1.22.2+k3s2
node-3   Ready      control-plane,master   5d16h   v1.22.2+k3s2

[root@node-1 /]# helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

**Comment by carrodher** [comment] 2022-01-04 07:15
It seems a different issue. The original issue was related to an issue during the upgrade which should be solved in version `6.1.1` once implemented the changes at https://github.com/bitnami/charts/pull/8271.

Now, you are reporting a different issue in which the chart is deployed correctly but the cluster configuration seems not to be adequate. This second issue was reported at https://github.com/bitnami/charts/issues/8560 which seems the same behaviour you're having

**Comment by Cryingmouse** [comment] 2022-01-05 01:37
Thanks a lot! I will keep an eye on #8560. :)

**Comment by morei25** [comment] 2022-01-07 09:06
> Hi,
> 
> I'm using Ansible to install the chart in it's own namespace. I have a bare-metal cluster setup with kubeprod here. The chart was working fine up to Version 5.6.2. Now I even can't upgrade from 5.6.2 to 6.1.0. I end up with `WSREP: failed to open gcomm backend connection`. I haven't testet 6.1.1 yet.
> 
> Best, Floek

Hi Guys,

I also faced the same problems and spend some time to find the root of the this issue. But I foundout that the Version 6.00 of the Chart is working fine for me.

**Comment by michaltrzcinski** [comment] 2022-01-09 10:18
It works on 6.0.6, which uses "docker.io/bitnami/mariadb-galera:10.6.5-debian-10-r0".
It stopped working since 6.0.8 which uses "docker.io/bitnami/mariadb-galera:10.6.5-debian-10-r26".

**Comment by carrodher** [comment] 2022-01-10 08:14
Thanks for the info, in order to maintain the conversations in a single place, please use https://github.com/bitnami/charts/issues/8560 for this topic.

I am going to close this issue just to avoid confusion since the original topic was a different one.

**Closed by carrodher** 2022-01-10 08:14 UTC
