### ISSUE TITLE
[bitnami/fluentd] Fluentd is unable to read logs

### ISSUE THREAD

**Issue by irizzant** [bitnami/charts#2253] opened 2020-04-07 14:57 UTC
**Which chart**:
[bitnami/fluentd] fluentd-0.5.3

**Describe the bug**
Fluentd is unable to read container logs and produces these messages:
```
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/kube-controller-manager-minikube_kube-system_kube-controller-manager-a37f50683ece640a66a43a80e304cd1059cbad549610330969bd26fcca2e535c.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/efk-kibana-b64cc597d-jf82m_efk_istio-proxy-70af96a168795f00bb7c261dbe445bb3c7b83a1df965266f0ccd9751316f51d9.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/efk-elasticsearch-data-1_efk_istio-init-938fbff9ae1461c1bc1b4741bac4d2e93264f1ecce4ddeaa3133058c8b40be5d.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/istio-tracing-9dd6c4f7c-87jsg_istio-system_jaeger-c715edd9447864108acd10f8e8b3228b7a2cccbb83127dad984f53361997998f.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/prometheus-6d96d7b5bb-75xzk_istio-system_prometheus-de995b72b1c0e217b36376ab0849e34476a11533bdd3d8edd76f66dc2bba555e.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/efk-kibana-b64cc597d-jf82m_efk_kibana-c440e3b01d62336755439376a7ad22db1432902ee297f01547965c2be0828619.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/grafana-5f6f8cbf75-b9d6r_istio-system_grafana-6566d5ad3b2182b08ef0b3be11c2b57d6af9817adb2097f657796887b9ff18dd.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/kube-scheduler-minikube_kube-system_kube-scheduler-19d92af1d513e3ea47bfef77ae2ee9bf770abd9af62803c6a0ee0ff0b56f7ccb.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/efk-elasticsearch-metrics-67b497fd96-vmjvr_efk_metrics-7842f80cdbc57f81d33790965d86feba168a621d45f55f
```
This is because the forwarder Fluentd does not run as root as expected but as user `fluentd`.

Just do `kubectl exec -it <name of fluentd forwarder pod> bash` and once inside the pod give `top -c`, this is what you get:
```
  1 fluentd   20   0  563612  55996   9872 S   0.0   0.5   0:01.65 /opt/bitnami/ruby/bin/ruby /opt/bitnami/fluentd/bin/fluentd --config /opt/bitnami/fluen+ 
   64 fluentd   20   0  835884  58716  10196 S   0.0   0.5   0:02.63 /opt/bitnami/ruby/bin/ruby -Eascii-8bit:ascii-8bit /opt/bitnami/fluentd/bin/fluentd --c+ 
   76 root      20   0    4000   3012   2608 S   0.0   0.0   0:00.00 bash                                                                                     
   81 root      20   0    8052   2936   2484 R   0.0   0.0   0:00.01 top -c  
```
Despite of the default settings:

forwarder.securityContext.enabled | Enable security context for forwarder pods | true
-- | -- | --
forwarder.securityContext.fsGroup | Group ID for forwarder's containers filesystem | 0
forwarder.securityContext.runAsUser | User ID for forwarder's containers | 0

**To Reproduce**
1. start a Kubernetes cluster with Minikube
1. deploy the chart `helm install fluentd -n efk bitnami/fluentd`
1. inspect the forwarder logs `kubectl logs -f -l app.kubernetes.io/component=forwarder`

**Expected behavior**
Fluentd should start reading the logs and forwarding them to stdout

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by andresbono** [comment] 2020-04-08 11:53
Hi @irizzant, for security reasons, even if the container user is `root`, the process is spawned with a non privileged user. You can check the logic here:

https://github.com/bitnami/bitnami-docker-fluentd/blob/0695af66fe0e444abf97acfa87ef481e45071be4/1/debian-10/rootfs/opt/bitnami/scripts/fluentd/run.sh#L28-L32

If you still need to execute the process as root, you can specify the following extra environment variables to `forwarder.extraEnv` https://github.com/bitnami/charts/blob/771131bad911cd516f8fc3171d1b7047592cbcb5/bitnami/fluentd/values.yaml#L76

```diff
-  extraEnv: []
+  extraEnv:
+    - name: FLUENTD_DAEMON_USER
+      value: root
+    - name: FLUENTD_DAEMON_GROUP
+      value: root
```

But please, keep in mind that doing that is not recommended in a production environment.

**Comment by irizzant** [comment] 2020-04-08 15:12
Hi @andresbono 
> But please, keep in mind that doing that is not recommended in a production environment.

if you don't include this:
```diff
-  extraEnv: []
+  extraEnv:
+    - name: FLUENTD_DAEMON_USER
+      value: root
+    - name: FLUENTD_DAEMON_GROUP
+      value: root
```
fluentd can't read the docker containers log at all and starts emitting these logs:
```
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/kube-controller-manager-minikube_kube-system_kube-controller-manager-a37f50683ece640a66a43a80e304cd1059cbad549610330969bd26fcca2e535c.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/efk-kibana-b64cc597d-jf82m_efk_istio-proxy-70af96a168795f00bb7c261dbe445bb3c7b83a1df965266f0ccd9751316f51d9.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/efk-elasticsearch-data-1_efk_istio-init-938fbff9ae1461c1bc1b4741bac4d2e93264f1ecce4ddeaa3133058c8b40be5d.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/istio-tracing-9dd6c4f7c-87jsg_istio-system_jaeger-c715edd9447864108acd10f8e8b3228b7a2cccbb83127dad984f53361997998f.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/prometheus-6d96d7b5bb-75xzk_istio-system_prometheus-de995b72b1c0e217b36376ab0849e34476a11533bdd3d8edd76f66dc2bba555e.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/efk-kibana-b64cc597d-jf82m_efk_kibana-c440e3b01d62336755439376a7ad22db1432902ee297f01547965c2be0828619.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/grafana-5f6f8cbf75-b9d6r_istio-system_grafana-6566d5ad3b2182b08ef0b3be11c2b57d6af9817adb2097f657796887b9ff18dd.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/kube-scheduler-minikube_kube-system_kube-scheduler-19d92af1d513e3ea47bfef77ae2ee9bf770abd9af62803c6a0ee0ff0b56f7ccb.log unreadable. It is excluded and would be examined next time.
2020-04-07 14:48:47 +0000 [warn]: #0 /var/log/containers/efk-elasticsearch-metrics-67b497fd96-vmjvr_efk_metrics-7842f80cdbc57f81d33790965d86feba168a621d45f55f
```
so the chart without those variables is unusable.
Also, your `values-production.yaml` which is supposed to be for production use is affected by the same issue.
So those variables should be included by default in the chart.

**Comment by andresbono** [comment] 2020-04-10 08:45
Hi @irizzant, #1905 seems to be the same issue, I didn't notice before. (We got to the same workaround!) Can you please continue the conversation there?

I'm closing this one as duplicate of #1905.

**Closed by andresbono** 2020-04-10 08:45 UTC

**Comment by irizzant** [comment] 2020-04-10 08:49
Hi @andresbono correct, no problem
