### ISSUE TITLE
[postgresql-ha] Using postgresql.existingSecret causes repmgr authentation error

### ISSUE THREAD

**Issue by krichter722** [bitnami/charts#6392] opened 2021-05-17 16:06 UTC
**Which chart**:
bitnami/postgresql-ha 7.4.1

**Describe the bug**
Using an existing secret with keys `postgresql-password` and `repmgr-password` which is passed as chart value `postgresql.existingSecret` causes the second replica/pod in the statefulset to fail due to

```
2021-05-13 15:30:30.251 GMT [163] FATAL:  password authentication failed for user "repmgr"
2021-05-13 15:30:30.251 GMT [163] DETAIL:  Password does not match for user "repmgr".
	Connection matched pg_hba.conf line 1: "host     all            repmgr    0.0.0.0/0    md5"
[2021-05-13 15:30:30] [ERROR] connection to database failed
[2021-05-13 15:30:30] [DETAIL] 
FATAL:  password authentication failed for user "repmgr"
```

When specifying `pgpoolImage.debug=true` one sees

```
$ kubectl -n some-namespace logs deployment/postgresql-ha-release-pgpool
pgpool 08:20:55.61 
pgpool 08:20:55.61 Welcome to the Bitnami pgpool container
pgpool 08:20:55.62 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-pgpool
pgpool 08:20:55.62 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-pgpool/issues
pgpool 08:20:55.62 
pgpool 08:20:55.62 INFO  ==> ** Starting Pgpool-II setup **
pgpool 08:20:55.65 INFO  ==> Validating settings in PGPOOL_* env vars...
pgpool 08:20:55.66 INFO  ==> Initializing Pgpool-II...
pgpool 08:20:55.67 INFO  ==> Generating pg_hba.conf file...
pgpool 08:20:55.68 INFO  ==> Generating pgpool.conf file...
sed: -e expression #1, char 61: unterminated `s' command
```

**To Reproduce**

Reproducer in GitLab CI (personal choice):

```
variables:
  CLUSTER_NAME: "bitnami-psql-116-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_IID"
  CLUSTER_VERSION: "1.19.9-gke.1900"
  CLUSTER_MASCHINE_TYPE: e2-standard-4
  CLUSTER_ZONE: us-central1-c
  HELM_VERSION: "3.5.4"

stages:
  - setup-cluster
  - setup-operations
  - tear-down-cluster

setup-cluster:
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:340.0.0
  stage: setup-cluster
  script:
    - gcloud config set project $PROJECT_ID
    - gcloud auth activate-service-account --key-file "$GOOGLE_KEY"
    - gcloud config set compute/zone $CLUSTER_ZONE
    - gcloud beta container clusters create $CLUSTER_NAME --machine-type=$CLUSTER_MASCHINE_TYPE --cluster-version=$CLUSTER_VERSION --no-enable-stackdriver-kubernetes --enable-autoupgrade

setup-cluster-operations:
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:340.0.0
  stage: setup-operations
  script:
    - gcloud config set project $PROJECT_ID
    - gcloud auth activate-service-account --key-file "$GOOGLE_KEY"
    - gcloud config set compute/zone $CLUSTER_ZONE
    - gcloud config set container/cluster $CLUSTER_NAME
    - gcloud container clusters get-credentials $CLUSTER_NAME
    - curl https://get.helm.sh/helm-v$HELM_VERSION-linux-amd64.tar.gz > helm-v$HELM_VERSION-linux-amd64.tar.gz && tar xf helm-v$HELM_VERSION-linux-amd64.tar.gz && rm helm-v$HELM_VERSION-linux-amd64.tar.gz && mkdir -p /usr/local/bin && mv linux-amd64/helm /usr/local/bin/
    - kubectl version
    - helm version
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo update
    - kubectl create namespace some-namespace
    - kubectl -n some-namespace apply -f postgres-secret.yml
    - helm install postgresql-ha-release bitnami/postgresql-ha --namespace some-namespace --version 7.4.0 --wait --set postgresql.existingSecret=postgres-secret || true
    - helm -n some-namespace ls --all
    - kubectl get pods --all-namespaces
    - kubectl -n some-namespace logs pod/postgresql-ha-release-postgresql-0
    - kubectl -n some-namespace logs pod/postgresql-ha-release-postgresql-1

tear-down-cluster:
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:340.0.0
  stage: tear-down-cluster
  when: always
  script:
    - gcloud config set project $PROJECT_ID
    - gcloud auth activate-service-account --key-file "$GOOGLE_KEY"
    - gcloud config set compute/zone $CLUSTER_ZONE
    - gcloud config set container/cluster $CLUSTER_NAME
    - gcloud container clusters get-credentials $CLUSTER_NAME
    - python3 k8s-ci-tools/find_disks.py
    - cat disk-name-suffixes
    - gcloud container clusters delete --quiet $CLUSTER_NAME
    - python3 k8s-ci-tools/delete_disks.py
```

with `postgres-secret.yml`

```
apiVersion: v1
kind: Secret
metadata:
  name: "postgres-secret"
type: Opaque
data:
  postgresql-password: "cG9zdGdyZXMK"
  repmgr-password: "cG9zdGdyZXMK"
```
and `values.yml`

```
postgresql:
  existingSecret: "postgres-secret"
```

**Expected behavior**
Afaiu the REAMDE a secret with the specified keys is supposed to work, i.e. create a deployment with pgpool and PostgreSQL pods which can comminicate with each other and provide the functionality of a HA cluster.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
`libfile.sh` contains the note
```
    # We should avoid using 'sed in-place' substitutions
    # 1) They are not compatible with files mounted from ConfigMap(s)
    # 2) We found incompatibility issues with Debian10 and "in-place" substitutions
```

**Comment by rafariossaa** [comment] 2021-05-18 15:39
Hi,
  Thank you very much for your detail description of the issue.

  The `sed` error could be related to the characters used in the password, could you try first with a simpler password ?

  I was not able to reproduce it, I used minikube and followed these steps:
- Clone the bitnami's chart repository
- Go to postgresql-ha directory
- Update dependencies:
```console
$ helm dependency update
```
- Create the secret:
```console
$ cat mysecret.yml 
apiVersion: v1
kind: Secret
metadata:
  name: "mysecret"
type: Opaque
data:
  postgresql-password: "mypasswd"
  repmgr-password: "mypasswd"

$ kubectl apply -f mysecret.yml
```
- Modify values.yaml  (or use `set` in the next step)
```console
$ git diff values.yaml
diff --git a/bitnami/postgresql-ha/values.yaml b/bitnami/postgresql-ha/values.yaml
index 47d16bbe5..5f806b05e 100644
--- a/bitnami/postgresql-ha/values.yaml
+++ b/bitnami/postgresql-ha/values.yaml
@@ -341,7 +341,7 @@ postgresql:
   # database:
 
   ## PostgreSQL password using existing secret
-  # existingSecret: secret
+  existingSecret: "mysecret"
 
   ## PostgreSQL admin password (used when `postgresql.username` is not `postgres`)
   ## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-user-on-first-run (see note!)

```
- Deploy chart
```console
$ helm install mypg -f values.yml .
```
- All nodes up and running:
```console
$ kubectl get all
NAME                                            READY   STATUS    RESTARTS   AGE
pod/mypg-postgresql-ha-pgpool-c4c44b588-55g7w   1/1     Running   0          11m
pod/mypg-postgresql-ha-postgresql-0             1/1     Running   0          11m
pod/mypg-postgresql-ha-postgresql-1             1/1     Running   0          11m

NAME                                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/kubernetes                               ClusterIP   10.96.0.1       <none>        443/TCP    69d
service/mypg-postgresql-ha-pgpool                ClusterIP   10.108.12.9     <none>        5432/TCP   11m
service/mypg-postgresql-ha-postgresql            ClusterIP   10.103.201.88   <none>        5432/TCP   11m
service/mypg-postgresql-ha-postgresql-headless   ClusterIP   None            <none>        5432/TCP   11m

NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/mypg-postgresql-ha-pgpool   1/1     1            1           11m

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/mypg-postgresql-ha-pgpool-c4c44b588   1         1         1       11m

NAME                                             READY   AGE
statefulset.apps/mypg-postgresql-ha-postgresql   2/2     11m

```

- In node 0 the log was normal:
```console
postgresql-repmgr 15:27:51.48 INFO  ==> ** Starting repmgrd **
[2021-05-18 15:27:51] [NOTICE] repmgrd (repmgrd 5.2.1) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2021-05-18 15:27:51] [NOTICE] starting monitoring of node "mypg-postgresql-ha-postgresql-0" (ID: 1000)
[2021-05-18 15:27:51] [NOTICE] monitoring cluster primary "mypg-postgresql-ha-postgresql-0" (ID: 1000)
[2021-05-18 15:28:15] [NOTICE] new standby "mypg-postgresql-ha-postgresql-1" (ID: 1001) has connected
[2021-05-18 15:28:21] [NOTICE] new standby "mypg-postgresql-ha-postgresql-1" (ID: 1001) has connected
```
- In node 1 the logs was normal:
```console
postgresql-repmgr 15:28:16.87 INFO  ==> ** Starting repmgrd **
[2021-05-18 15:28:16] [NOTICE] repmgrd (repmgrd 5.2.1) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2021-05-18 15:28:16] [NOTICE] starting monitoring of node "mypg-postgresql-ha-postgresql-1" (ID: 1001)
2021-05-18 15:28:16.970 GMT [266] LOG:  started streaming WAL from primary at 0/5000000 on timeline 1
[2021-05-18 15:28:40] [WARNING] unable to ping "user=repmgr password=�*Z�� host=mypg-postgresql-ha-postgresql-0.mypg-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5"
[2021-05-18 15:28:40] [DETAIL] PQping() returned "PQPING_NO_RESPONSE"
[2021-05-18 15:28:40] [WARNING] unable to connect to upstream node "mypg-postgresql-ha-postgresql-0" (ID: 1000)
[2021-05-18 15:28:40] [NOTICE] node "mypg-postgresql-ha-postgresql-0" (ID: 1000) has recovered, reconnecting
[2021-05-18 15:28:40] [NOTICE] reconnected to upstream node after 0 seconds
[2021-05-18 15:29:09] [WARNING] unable to ping "user=repmgr password=�*Z�� host=mypg-postgresql-ha-postgresql-0.mypg-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5"
[2021-05-18 15:29:09] [DETAIL] PQping() returned "PQPING_NO_RESPONSE"
[2021-05-18 15:29:09] [WARNING] unable to connect to upstream node "mypg-postgresql-ha-postgresql-0" (ID: 1000)
[2021-05-18 15:29:09] [NOTICE] node "mypg-postgresql-ha-postgresql-0" (ID: 1000) has recovered, reconnecting
[2021-05-18 15:29:09] [NOTICE] reconnected to upstream node after 0 seconds

```

**Comment by krichter722** [comment] 2021-05-18 16:35
@rafariossaa Interesting, I'll try to reproduce with minikube. However, you're password is way more complex. As the secret `data` is always base64 encoding in Kubernetes. My password is `postgres`, yours is `�*Z��` (which is `echo 'mypassword | base64 --decode`) as you can see in the logs. Maybe that's preventing the issue? Could you try with `postgres`?

**Comment by rafariossaa** [comment] 2021-05-19 09:02
Hi,
  Sorry for that.  I recreated the secret with a encoded passwd:
```
$ cat mysecret.yml 
apiVersion: v1
kind: Secret
metadata:
  name: "mysecret"
type: Opaque
data:
  postgresql-password: "bXlwYXNzMg=="
  repmgr-password: "bXlwYXNzMg=="
```
and got the same behavior:
Node 0 log:
```
postgresql-repmgr 08:43:54.85 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2021-05-19 08:43:54.873 GMT [267] LOG:  pgaudit extension initialized
2021-05-19 08:43:54.874 GMT [267] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-05-19 08:43:54.874 GMT [267] LOG:  listening on IPv6 address "::", port 5432
2021-05-19 08:43:54.883 GMT [267] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-05-19 08:43:54.896 GMT [267] LOG:  redirecting log output to logging collector process
2021-05-19 08:43:54.896 GMT [267] HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
2021-05-19 08:43:54.901 GMT [269] LOG:  database system was shut down at 2021-05-19 08:43:54 GMT
2021-05-19 08:43:54.908 GMT [267] LOG:  database system is ready to accept connections
 done
server started
postgresql-repmgr 08:43:54.98 INFO  ==> ** Starting repmgrd **
[2021-05-19 08:43:54] [NOTICE] repmgrd (repmgrd 5.2.1) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2021-05-19 08:43:55] [NOTICE] starting monitoring of node "mypg2-postgresql-ha-postgresql-0" (ID: 1000)
[2021-05-19 08:43:55] [NOTICE] monitoring cluster primary "mypg2-postgresql-ha-postgresql-0" (ID: 1000)
[2021-05-19 08:44:13] [NOTICE] new standby "mypg2-postgresql-ha-postgresql-1" (ID: 1001) has connected
```
Node 1 log:
```
postgresql-repmgr 08:44:13.38 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2021-05-19 08:44:13.410 GMT [266] LOG:  pgaudit extension initialized
2021-05-19 08:44:13.411 GMT [266] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-05-19 08:44:13.411 GMT [266] LOG:  listening on IPv6 address "::", port 5432
2021-05-19 08:44:13.421 GMT [266] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-05-19 08:44:13.445 GMT [266] LOG:  redirecting log output to logging collector process
2021-05-19 08:44:13.445 GMT [266] HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
2021-05-19 08:44:13.453 GMT [268] LOG:  database system was shut down in recovery at 2021-05-19 08:44:13 GMT
2021-05-19 08:44:13.453 GMT [268] LOG:  entering standby mode
2021-05-19 08:44:13.460 GMT [268] LOG:  redo starts at 0/4000028
2021-05-19 08:44:13.461 GMT [268] LOG:  consistent recovery state reached at 0/5000958
2021-05-19 08:44:13.461 GMT [268] LOG:  invalid record length at 0/5000958: wanted 24, got 0
2021-05-19 08:44:13.462 GMT [266] LOG:  database system is ready to accept read only connections
 done
server started
postgresql-repmgr 08:44:13.51 INFO  ==> ** Starting repmgrd **
[2021-05-19 08:44:13] [NOTICE] repmgrd (repmgrd 5.2.1) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2021-05-19 08:44:13] [NOTICE] starting monitoring of node "mypg2-postgresql-ha-postgresql-1" (ID: 1001)
2021-05-19 08:44:13.565 GMT [272] LOG:  started streaming WAL from primary at 0/5000000 on timeline 1
[2021-05-19 08:44:22] [WARNING] unable to ping "user=repmgr password=mypass2 host=mypg2-postgresql-ha-postgresql-0.mypg2-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5"
[2021-05-19 08:44:22] [DETAIL] PQping() returned "PQPING_NO_RESPONSE"
[2021-05-19 08:44:22] [WARNING] unable to connect to upstream node "mypg2-postgresql-ha-postgresql-0" (ID: 1000)
[2021-05-19 08:44:29] [WARNING] unable to ping "user=repmgr password=mypass2 connect_timeout=5 dbname=repmgr host=mypg2-postgresql-ha-postgresql-0.mypg2-postgresql-ha-postgresql-headless.default.svc.cluster.local port=5432 fallback_application_name=repmgr"
[2021-05-19 08:44:29] [DETAIL] PQping() returned "PQPING_NO_RESPONSE"
[2021-05-19 08:44:34] [NOTICE] node "mypg2-postgresql-ha-postgresql-0" (ID: 1000) has recovered, reconnecting
[2021-05-19 08:44:34] [NOTICE] reconnected to upstream node after 12 seconds
```
I also tested it in GKE and it went well too.

**Comment by krichter722** [comment] 2021-05-23 15:03
@rafariossaa Thanks for testing, I can confirm that the installation of postgresql-ha with helm from this git repository works fine. I used `--set existingSecret=postgres-secret` rather than patch `values.yaml` in the repository, but that shouldn't matter. I also tried to install the most recent 7.5.1 from the helm repository which doesn't work due to the error of this issue. May I ask you to install from the remote helm repository? It's very odd that the same versions don't work installed in different ways through helm.

**Comment by rafariossaa** [comment] 2021-05-25 07:39
Hi,
  I was not able to reproduce the issue.
  This is what I did:
- Create the secret `mysecret` by using the following file:
```console
$ cat mysecret.yml
apiVersion: v1
kind: Secret
metadata:
  name: "mysecret"
type: Opaque
data:
  postgresql-password: "bXlwYXNzMg=="
  repmgr-password: "bXlwYXNzMg=="

$ kubectl apply -f mysecret.yml
```
- Update the repo info and install the chart using the secret:
```console
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈


$ helm install mypostgresql bitnami/postgresql-ha --version=7.5.1 --set postgresql.existingSecret="mysecret
```

I got the chart installed and working without issues.

You can use: `helm pull bitnami/postgresql-ha --version=7.5.1` to download the chart tarball.
The 7.5.1 tar ball has this sha256 checksum:
```console
$ helm pull bitnami/postgresql-ha --version=7.5.1
$ sha256sum postgresql-ha-7.5.1.tgz 
f9252c5b524e30cb32149fb1aeefc033ec862888b11bb70061f7b98e1b7543d9  postgresql-ha-7.5.1.tgz
```

**Comment by dsiperek-vendavo** [comment] 2021-05-25 18:38
I am having the same issue.  Maybe this information will help.  The first time it created just fine.  After i deleted the helm chart, secret, pvc and created it with a different password i get same error.

**Comment by rafariossaa** [comment] 2021-05-28 09:25
Hi,
  I tried by using `postgres` as password and it worked for me.
  This is what I did:

```console
$ echo -n "postgres" | base64
cG9zdGdyZXM=

$ cat postgrespwd.yml
apiVersion: v1
kind: Secret
metadata:
  name: "postgrespwd"
type: Opaque
data:
  postgresql-password: "cG9zdGdyZXM="
  repmgr-password: "cG9zdGdyZXM="

$ kubectl apply -f postgrespwd.yml 
secret/postgrespwd created


$ helm install mypostgresql bitnami/postgresql-ha --version=7.5.1 --set postgresql.existingSecret=postgrespwd

$ kubectl get pods
NAME                                                 READY   STATUS    RESTARTS   AGE
mypostgresql-postgresql-ha-pgpool-77c9c46865-fj68v   1/1     Running   0          73s
mypostgresql-postgresql-ha-postgresql-0              1/1     Running   0          73s
mypostgresql-postgresql-ha-postgresql-1              1/1     Running   0          73s
```

  Have into account that if you are reusing the name for the deployment you should be deleting the PVCs, because the postgresql data files are persisted.

**Comment by krichter722** [comment] 2021-05-28 10:00
@rafariossaa The issue is with a trailing newline included in the password. I misread @dsiperek-vendavo' s comment for a problem with using the `base64` command line tool, on second read, I don't know why. The issue is indeed with confusing `echo` and `echo -n` as input for `base64`.

This is a user error, however, I wouldn't mind extracting a software change from this issue. This is a not a problem of the Bitnami domain because this error can be done for any Kubernetes secret. However, it's not supported by Bitnami and I think a failure of the helm value processing is helpful. I just checked  a different system where I'm using `postgresql-ha` and noticed I had `postgres"` as a password. This seems to be troublesome as well, maybe the template processing can be tested systematically and all failures can cause a failure of the chart with a clear error message.

**Comment by rafariossaa** [comment] 2021-05-31 08:03
Hi,
  I am happy you were able to solve the issue.
  Thanks for your proposal, but I am not very sure of what you mean. Our charts are tested in our CI/CD on several kubernetes clusters, but it is not feasible to test all the parameter combinations and different inputs an user can provide.
  Also, helm templating is very limited to what you can implement, and you maybe what to use `"` as character in your password, or you have a non ascii8 character set.   
  In any case, feel free to send a PR, we will be glad to review and merge it.

**Comment by krichter722** [comment] 2021-05-31 18:22
@rafariossaa I was thinking of some kind of unit tests for the template processing logic. Picking out small units makes the possible combinations of input parameter manageable and only the template output needs to be tested, not the application to a Kubernetes cluster which are equally important integration tests. I'll look into that, but it's probably going to take some time. Feel free to close the issue in the meantime if you don't like them to be open for a long time.

**Comment by rafariossaa** [comment] 2021-06-01 07:09
Hi,
  Thanks @krichter722 , we will be glad to review it.
  I am closing this issue by now. Don't hesitate to reopen it if needed.

**Closed by rafariossaa** 2021-06-01 07:09 UTC
