### ISSUE TITLE
 bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex

### ISSUE THREAD

**Issue by fritzstauff** [bitnami/charts#6943] opened 2021-07-13 20:06 UTC
**Which chart**:
etcd-6.2.9

**Describe the bug**
Our k8s scales nodes down as needed etcd-2 in a three-node cluster always hits the same issue when restarting onto a new node 
```bash
Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex
```
**To Reproduce**
1. Trigger restart in 3rd node of HA etcd cluster

**Expected behavior**
I expect the third node in the cluster to start up and not crash

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```bash
helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I manually resolve the issue by scaling up another node. Deleting the pv associated with etcd-2 and restarting it. Then I can safely scale back down.

**Comment by Mauraza** [comment] 2021-07-14 08:18
Hi @fritzstauff,

Could you check if your issue is related to https://github.com/bitnami/charts/issues/6251?

**Comment by fritzstauff** [comment] 2021-07-14 20:04
@Mauraza Looks like the same issue. Existing members don't have member_id data. 

ls /bitnami/etcd/data/
member

**Comment by javsalgar** [comment] 2021-07-16 07:52
If it is the same issue, let's close this as a duplicate of https://github.com/bitnami/charts/issues/6251

**Closed by javsalgar** 2021-07-16 07:52 UTC
