### ISSUE TITLE
[bitnami/airflow] Support LDAP authentication

### ISSUE THREAD

**Issue by colek42** [bitnami/charts#1832] opened 2020-01-16 20:44 UTC
**Which chart**:

Airflow 4.1.1

**Description**

Airflow chart should support LDAP authentication.

**Comment by alemorcuq** [comment] 2020-01-17 09:34
Hi, @colek42. 

I have created an internal task to add LDAP support to the chart. On the other hand, PRs are welcome, so if you want to contribute we will gladly review and merge it.

**Comment by colek42** [comment] 2020-01-17 16:06
I have to work on this for a client.  Expect a PR sometime next week.

**Comment by colek42** [comment] 2020-01-17 20:13
It is a priority task for me.  I will try to upstream it next week.

**Comment by alemorcuq** [comment] 2020-01-20 08:28
That's great! Thank you very much, @colek42 !

**Comment by colek42** [comment] 2020-01-21 23:55
@alemorcuq It looks like the work will require a major refactor to use the airflow.cfg file instead of environment variables if we want to keep it maintainable.

**Comment by denisgigli** [comment] 2020-03-03 14:33
Hi, any updates on this task?

**Comment by carrodher** [comment] 2020-03-04 09:07
Hi! We have a task included in our backlog but as the impact of the issue is limited, there are no immediate plans to work on it. Nevertheless, it will be considered for future chart versions.

We will update this thread as soon as we have more news.

**Comment by beltran-rubo** [comment] 2020-04-03 13:05
We are working on it at https://github.com/bitnami/charts/pull/2174

**Comment by don4of4** [comment] 2021-02-22 18:00
@alemorcuq @colek42  This issue is closed by #2174.  Can you close this?

**Comment by carrodher** [comment] 2021-02-23 08:04
Thanks for letting us know, I am closing it

**Closed by carrodher** 2021-02-23 08:04 UTC
Labels: on-hold
