### ISSUE TITLE
[bitnami/wordpress] Enabling MULTISITE via wordpressExtraConfigContent for wordpress helm chart not working

### ISSUE THREAD

**Issue by AdamLuckey** [bitnami/charts#4158] opened 2020-10-29 19:31 UTC
**Which chart**:
Wordpress

**Describe the bug**
Enabling the wordpressExtraConfigContent and adding the define('MULTISITE', true); does not enable multisite because that function cannot be enabled from appending to the end of the file. It must be appended right after the define( 'WP_DEBUG', false ); entry in the wp-config.php. Extra config content should be added above the /* That's all, stop editing! Happy publishing. */ line in the wp-config.php, not at the end.

**To Reproduce**

1. Add the following to your values file:
```
wordpressExtraConfigContent: |
  define('MULTISITE', true);
```

**Expected behavior**
multisite will not be enabled on wordpress. If you manually edit the wp-config.php by entering the pod and moving the define('MULTISITE', true); to right below the define( 'WP_DEBUG', false );, it begins enablement of multisite.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.3", GitCommit:"0a9a9a88e8afd6e77337a3e2ad744756e191429a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```
This also happens w/ earlier versions
- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T23:32:44Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"afea77eefe3272c0f53c4552183ecb16c091db41", GitTreeState:"clean", BuildDate:"2020-09-17T06:32:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by andresbono** [comment] 2020-10-30 12:57
Hi @AdamLuckey, are you following some guide that recommends using `wordpressExtraConfigContent` to enable WordPress Multisite?

As you mention, you might want to edit the `wp-config.php` in a manual way for advanced configuration.

**Comment by AdamLuckey** [comment] 2020-10-30 22:02
@AndreaBeggiato I am following the readme from the chart repo to add the extra config line value to activate multisite.

**Comment by pestebogdan** [comment] 2020-11-02 13:53
@AdamLuckey : Setting this to values.yml

`wordpressExtraConfigContent: |-
  /* Multisite */
  define( 'WP_ALLOW_MULTISITE', true );`

..will only take care of the first step in the Multisite enablement procedure , basically you will get the new "Tools > Network Setup" tab from the Administration menu. I confirm this has worked for me.

The problem is that after you click that Install button , you get a couple of snippets that you should inject into the wp-config.php and .htaccess files, which is not very cloud-nativey.

I'm also currently looking into making this entire process automated with only helm & k8s hacks, have a couple of ideas that i will try out but at the moment AFAIK there is no clean way oif enabling multi-site end-to-end using this helm chart.

**Comment by andresbono** [comment] 2020-11-03 08:04
Thanks for the clarification, @pestebogdan. It would be great if you share your workaround to use multi-site once you have it ready. We will try to keep improving our chart.

**Comment by pestebogdan** [comment] 2020-11-16 19:15
Actually submitted a PR for allowing the use of custom user post-init.d scripts, which i used to get the Multisite working upon first boot, so if it goes through i will post the necessary values.yaml data to accomplish this.
https://github.com/bitnami/charts/pull/4373

**Comment by andresbono** [comment] 2020-11-17 19:07
Thanks so much! ❤️

**Comment by mikerlt** [comment] 2020-11-19 15:36
Looks like the PR was merged. Would you be able to share the values.yaml data to accomplish this?

**Comment by pestebogdan** [comment] 2020-11-19 17:23
@mikerlt : Sure thing , please check out https://github.com/bitnami/charts/issues/4255#issuecomment-730520452 , I put the example there.

**Comment by andresbono** [comment] 2020-11-20 12:23
Thanks again for your contributions, @pestebogdan!!

I'm going to close this issue for now.

@AdamLuckey, @mikerlt, please let us know if you are still facing issues.

**Closed by andresbono** 2020-11-20 12:23 UTC
