### ISSUE TITLE
cassandra/Maximum memory usage reached

### ISSUE THREAD

**Issue by devopsdymyr** [bitnami/charts#1757] opened 2019-12-20 07:00 UTC
**Which chart**:

3.11.5

**Description**
Current error getting in application
```
<WARNING:cassandra.cluster:Cluster.__init__ called with contact_points specified, but no load_balancing_policy. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['a5ad8e558c2311e9a524-11964365.us-west-2.elb.amazonaws.com'], lbp = None)
WARNING:cassandra.pool:Error attempting to reconnect to 100.100.0.3, scheduling retry in 4.0 seconds: [Errno None] Tried connecting to [('100.100.0.3', 9042)]. Last error: timed out
WARNING:cassandra.pool:Error attempting to reconnect to 100.100.0.2, scheduling retry in 128.0 seconds: [Errno None] Tried connecting to [('100.100.0.2', 9042)]. Last error: timed out 
WARNING:cassandra.pool:Error attempting to reconnect to 100.100.0.2, scheduling retry in 4.0 seconds: [Errno None] Tried connecting to [('100.100.0.2', 9042)]. Last error: timed out
INFO:cassandra.policies:Using datacenter 'datacenter1' for DCAwareRoundRobinPolicy (via host '34.217.153.0'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
INFO:cassandra.cluster:New Cassandra host <Host: 100.100.0.3 datacenter1> discovered
INFO:cassandra.cluster:New Cassandra host <Host: 100.100.0.2 datacenter1> discovered  
INFO:cassandra.cluster:Cassandra host 52.26.34.69 removed 
```

**Describe the results you received:**

**Describe the results you expected:**

error should solve

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:
Client: v2.14.3+g0e7f3b6
Server: v2.14.2+ga8b13cc

- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rafariossaa** [comment] 2019-12-20 08:38
Hi,
  Could you provide more information on how to reproduce it

**Comment by devopsdymyr** [comment] 2019-12-21 03:21
Hi have created cassandra using bitnami helm repo  and mofified pnly replicas 3 and loadbancer
helm install -n cassandra .

Which is working fine when i am using direct connection from python connector.
Connotor.py
`from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
from cassandra import ReadTimeout
import os
class CassandraConnection():
    def getConnection():
        auth_provider = PlainTextAuthProvider(username ='admin', password='Dog2019')
        cluster=Cluster(['a5ad8e558c23e9a524-1196365.us-west-2.elb.amazonaws.com'], auth_provider=auth_provider)
        session = cluster.connect()
        session.set_keyspace('tonnage')
        cluster.connect()
        return session

While run my python code getting this error

WARNING:

cassandra.cluster:Cluster.init called with contact_points specified, but **no load_balancing_policy.** In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['a5ad8e558c23e9a524-1196365.us-west-2.elb.amazonaws.com'], lbp = None)

WARNING:

cassandra.pool:Error attempting to reconnect to 100.100.0.3, scheduling retry in 4.0 seconds: [Errno None] Tried connecting to [('100.100.0.3', 9042)]. Last error: timed out

WARNING:

cassandra.pool:Error attempting to reconnect to 100.100.0.2, scheduling retry in 128.0 seconds: [Errno None] Tried connecting to [('100.100.0.2', 9042)]. Last error: timed out

WARNING:

cassandra.pool:Error attempting to reconnect to 100.100.0.2, scheduling retry in 4.0 seconds: [Errno None] Tried connecting to [('100.100.0.2', 9042)]. Last error: timed out

INFO:cassandra.policies:Using datacenter 'datacenter1' for DCAwareRoundRobinPolicy (via host '34.217.153.0'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes INFO:cassandra.cluster:New Cassandra host discovered INFO:cassandra.cluster:New Cassandra host discovered
INFO:cassandra.cluster:Cassandra host 52.26.34.69 removed

**Comment by javsalgar** [comment] 2019-12-23 12:16
Hi,

Are you connecting to the cassandra cluster form inside Kubernetes or outside Kubernetes? That could explain that the nodes are not accessible, because it looks to me that 100.100.0.2 are ClusterIP addresses.

**Comment by devopsdymyr** [comment] 2019-12-24 01:00
I am connecting outside kubernetes cluster Using loadbalancer

**Comment by javsalgar** [comment] 2019-12-24 10:11
If the python code requires all the nodes to be publicly available, then I'm afraid that is not possible at the moment. In order to allow that we would need a statefulset and a service per replica, and that would require major changes in the chart. The alternative would be accessing Cassandra from inside the cluster. If accessing from outside the cluster having all the nodes accessible is a common requirement, then we could consider implementing such a change in the chart.

**Comment by devopsdymyr** [comment] 2019-12-25 06:10
Fine.
Let me take this way 
One python application deployed on pod which required Cassandra connection to access all nodes.
Should i use kubernetes cassandra svc or pod ip of all  can you guide me .

or how i can define load balancing strategy in python connector to access all node which is deployed in kubernetes

**Comment by javsalgar** [comment] 2019-12-26 09:10
Hi,

If you are inside Kubernetes you could use the svc address, and by accessing Cassandra I presume it will get the list of nodes. At least that what I deduce from the output you posted before

**Comment by devopsdymyr** [comment] 2019-12-26 09:40
@javsalgar How i can solve this issue
 NoSpamLogger.java:91 - Maximum memory usage reached (131072000), cannot allocate chunk of 1048576

**Comment by devopsdymyr** [comment] 2019-12-26 09:42
Because of that memory usage issue all my pod get restarted

![image](https://user-images.githubusercontent.com/41105507/71470411-110f3680-27f2-11ea-897d-9bfe0a3498a3.png)

**Comment by javsalgar** [comment] 2019-12-27 08:50
Could you let us know how we can get to the memory usage spike? Is it after executing your script? I see that the instance was without restarts after 116 days.

**Comment by devopsdymyr** [comment] 2019-12-28 16:36
instance is not a issues. if instance is restarted then other pod should has same issue are new pod should deployed in to cluster.

Currently my cassandra cluster is running in the kubernetes cluster.when every more request send to cluster getting memory issues.

**Comment by javsalgar** [comment] 2019-12-30 14:09
Do you have any log information about the crashing message that Cassandra shows? If more requests get to the cluster it would make sense that the memory increases, did you set any limit in the statefulset definition?

**Comment by devopsdymyr** [comment] 2019-12-31 00:29
statfulset configuration
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2019-08-31T14:02:11Z"
  generation: 1
  labels:
    app: cassandra
  name: cassandra
  namespace: default
  resourceVersion: "38039472"
  selfLink: /apis/apps/v1/namespaces/default/statefulsets/cassandra
  uid: edaed916-cbf7-11e9-a524-02a9aed9b262
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cassandra
  serviceName: cassandra
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cassandra
    spec:
      containers:
      - env:
        - name: MAX_HEAP_SIZE
          value: 512M
        - name: HEAP_NEWSIZE
          value: 100M
        - name: CASSANDRA_SEEDS
          value: cassandra-0.cassandra.default.svc.cluster.local
        - name: CASSANDRA_CLUSTER_NAME
          value: Evs Dev
        - name: CASSANDRA_DC
          value: DC1
        - name: CASSANDRA_RACK
          value: Rack1-EvsDev
        - name: POD_IP
           valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: bitnami/cassandra:latest
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - nodetool drain
        name: cassandra
        ports:
        - containerPort: 7000
          name: intra-node
          protocol: TCP
        - containerPort: 7001
          name: tls-intra-node
          protocol: TCP
        - containerPort: 7199
          name: jmx
          protocol: TCP
        - containerPort: 9042
          name: cql
          protocol: TCP
        resources: {}
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/cassandra
          name: cassandra-data
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - chmod
        - -R
        - g+rwX
        - /bitnami
        image: busybox
        imagePullPolicy: Always
        name: fix-non-root-permissions
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami
          name: cassandra-data
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 1800
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: cassandra-data
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 5Gi
      storageClassName: gp2
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: cassandra-5c5dc54cdb
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: cassandra-5c5dc54cdb
  updatedReplicas: 3

**Comment by javsalgar** [comment] 2019-12-31 09:59
Hi,

I see that you did not set any request nor limit. I do not know the details of the underlying hardware, but this kind of pods (the ones that do not have limits or requests set) have the minimum priority and therefore kubelet (a kubernetes component responsible for managing the container execution) would kill them first in case of node exhaustion. Which are the details of your cluster hardware?

**Comment by devopsdymyr** [comment] 2020-01-01 05:47
Let me know if there is any Sample.
t2. 2xlarge machine kubernetes cluster is used for this Cassandra

**Comment by rafariossaa** [comment] 2020-01-02 12:31
Hi @devopsdymyr ,
  Just a couple of questions.
  The cluster is only running cassandra or there are other pods running there ?
  Could you check if the cassandra pods are deployed on different cluster nodes ?

**Comment by devopsdymyr** [comment] 2020-01-02 14:32
@rafariossaa Thnaks for your responds
The cluster is only running cassandra or there are other pods running there ?
There is other pod's also
Could you check if the cassandra pods are deployed on different cluster nodes ?
yes it's deployed on multiple node

**Comment by rafariossaa** [comment] 2020-01-03 08:24
Hi @devopsdymyr ,
  Is this happening with the python code provided or it is produced by a real application ?n

  Maybe, there is a problem with the environment vars you used for the memory. Could you check the memory requirements for cassandra [here](http://cassandra.apache.org/doc/latest/operating/hardware.html)

**Comment by devopsdymyr** [comment] 2020-01-07 04:49
what is the size should i use from the kubernetes resourse to solve this issue

**Comment by rafariossaa** [comment] 2020-01-13 08:25
Hi @devopsdymyr ,
  If you are only running cassandra in the kubernetes cluster. I would add +2GB to the memory needed for cassandra to the kubernetes master node and +1GB to the workers nodes.
  Those are the typical memory requirements for kubernetes.

**Comment by devopsdymyr** [comment] 2020-01-14 01:16
i have added 3Core and 5 Gb Ram,
![Screenshot from 2020-01-14 06-45-05](https://user-images.githubusercontent.com/41105507/72305362-822b6680-3699-11ea-8ff5-0e367ab31f9a.png)

**Comment by rafariossaa** [comment] 2020-01-14 15:50
I meant memory for the kubernetes cluster nodes, not for the cassandra pods. The `resources` section limits the use of memory and cpu by the pods.

Did it work ?

**Comment by devopsdymyr** [comment] 2020-01-21 15:48
yes it working as of now

**Comment by rafariossaa** [comment] 2020-01-22 09:38
Hi
  So, Cloud we close this issue by now ?

**Closed** 2020-01-25 04:16 UTC
