### ISSUE TITLE
Error: YAML parse error on keycloak/templates/secrets.yaml: error converting YAML to JSON:

### ISSUE THREAD

**Issue by vardangh** [bitnami/charts#7334] opened 2021-08-27 06:42 UTC
**Which chart**:
keycloak (version: 5.0.4)

**Describe the bug**
After [this PR](https://github.com/bitnami/charts/pull/7319) providing password for external DB fails with this error message
```
Error: YAML parse error on keycloak/templates/secrets.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key
```

**To Reproduce**

1. create values-keycloak-test.yml file with this content
```
externalDatabase:
  host: external_db_IP
  port: 5432
  user: keycloak
  password: anything
  database: keycloak
```
2. helm template keycloak bitnami/keycloak -f values-keycloak-test.yml --debug
the output of above command will be
```
---
# Source: keycloak/templates/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: ns-ist-pro
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-5.0.4
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: keycloak
type: Opaque
data:
  admin-password: "xxxx"
  management-password: "xxxxx"postgresql-password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```
4. as you can see there is no new line after `management-password:`

I think **the issue is with chomping modifiers** 
https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/secrets.yaml

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by MatteoGioioso** [comment] 2021-08-30 04:57
Same issue here , as current workaround I am deploying the previous version:

```
helm upgrade --install identity bitnami/keycloak --version 5.0.1 
```

**Comment by schroedt** [comment] 2021-08-30 07:30
Hi @MatteoGioioso,

I'll test your approach and update if it works out.

**Comment by alvneiayu** [comment] 2021-08-30 11:10
hi @schroedt 

I reproduced the error and I tested the solution that you suggested and it works. We are open to receive PRs, so I invite you to do it (if you want, for sure). Thanks for sharing your solution.

Thanks a lot for your time and for your help (to everyone in the case)

Álvaro

**Comment by schroedt** [comment] 2021-08-30 11:53
Hi @alvneiayu,

My pull request should be available and looks like being merged. Please let me know, once released. I'll install and verify once done (e.g. `helm upgrade --install identity bitnami/keycloak --version ???`).

**Comment by juan131** [comment] 2021-09-01 07:32
Solved at https://github.com/bitnami/charts/pull/7340

**Closed by juan131** 2021-09-01 07:32 UTC
