### ISSUE TITLE
[bitnami/mongodb] External Access with nodeport doesn't work when node restart and moves to new node

### ISSUE THREAD

**Issue by deveshk0** [bitnami/charts#8898] opened 2022-02-03 18:41 UTC
**Which chart**:
chart -  bitnami/mongodb
version- all

**Describe the bug**

when a mongodb pod restart and moved to new node, IP of the node is changed pod tries to generate the ssl certificate with this IP but pod  was setup using diff IP. Node can not be added to the cluster due to change in cert which is not valid anymore 

**To Reproduce**

1. Install a mongodb chart with nodeport external access without domain or externalIP
2. When cluster is in ready state kill one of the pod or forcefully move this to another node.
3. See pod logs

**Expected behavior**

Mongo db node should be able to handle node restart or displacement

**Additional context**

**Possible Solution**

We introduce a new mandatory variable -
- NodePortIPs: []

When nodePort type is defined, NodePortIPs must be defined except when you define `domain`, this will enable a movement of the pod inside the cluster.

**Comment by juan131** [comment] 2022-02-04 07:07
Duplicate of https://github.com/bitnami/charts/issues/3579 and https://github.com/bitnami/charts/issues/8868

**Closed by juan131** 2022-02-04 07:07 UTC
