### ISSUE TITLE
[bitnami/airflow] does bitnami airflow supports statsd

### ISSUE THREAD

**Issue by surendar-argtech** [bitnami/charts#30184] opened 2024-11-04 06:38 UTC
### Name and Version

helm install my-release oci://registry-1.docker.io/bitnamicharts/airflow

### What architecture are you using?

None

### What steps will reproduce the bug?

i have configured statsd with bitnami airflow, it didnt work.

### What do you see instead?

statsd is unable to connect to airflow.

**Comment by surendar-argtech** [comment] 2024-11-04 06:40
i am not able get metrics from airflow through statsd

**Comment by javsalgar** [comment] 2024-11-04 08:56
Hi,

I am afraid we do not have experience with statsd, so I'm not sure what is needed to integrate a solution with statsd. Do you have any documentation on this?

**Comment by juan131** [comment] 2024-11-05 10:42
Duplicate of https://github.com/bitnami/charts/issues/30185

**Closed by juan131** 2024-11-05 10:42 UTC
Labels: triage, airflow, tech-issues
