### ISSUE TITLE
Deploy Harbor with SSL terminated on AWS ELB using ACM certificate

### ISSUE THREAD

**Issue by harrishcris** [bitnami/charts#6763] opened 2021-06-25 08:48 UTC
Hello,

I’m using the Harbour Bitnami Helm chart (https://github.com/bitnami/charts/tree/master/bitnami/harbor) which deploys successfully in AWS k8 however I want to use my own public certificate to secure the connection instead of a self signed one. I have the cert in AWS ACM but I’m unsure what values to use to assign it to either the nginx service or AWS ELB?

Thanks

Chris

**Comment by migruiz4** [comment] 2021-06-25 14:01
Hi @harrishcris,

 If you'd like to configure the Harbor Nginx service with SSL certificates, you have to create a TLS secret and provide it using the value `service.tls.existingSecret`.

First, you need the following certificates in PEM format:
-  ca.crt: Your CA certificate.
- myserver.crt: Your Nginx server public certificate.
- myserver.key: Your Nginx server private key.

Create a Kubernetes secret containing the certificates, in this example I called it 'ca-secret':
```
kubectl create secret generic ca-secret --from-file=tls.crt=myserver.crt --from-file=tls.key=myserver.key --from-file=ca.crt=ca.crt
```

After creating the certificates secret, upgrade your Harbor chart to use it instead of the autogenerated certs:
```
helm upgrade my_release bitnami/harbor --set service.tls.existingSecret=ca-secret --set harborAdminPassword=$HARBOR_ADMIN_PASSWORD
```

If you use AWS ELB with HTTPS, connections through the ELB will use your certificate, but connections not going through the ELB will continue using the self-signed certificate.

**Comment by harrishcris** [comment] 2021-06-25 15:05
Hello @migruiz4

Thanks for the reply. I've managed to get the AWS ELB to use my cert by providing the following values.yaml file

`
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:XXXXXXX:certificate/XXXXXXX"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
`

However i'm now getting the following error when I try to access Harbor on https
`
400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx
`

I believe it's because SSL is terminating on the ELB and passing traffic through unencrypted to nginx however nginx is still using the self signed cert. I need to configure nginx to use target port HTTPS > HTTP however adding the following value to my values.yaml file didn't help, do you know how I would go about configuring nginx in my values.yaml helm file?

`
controller:
  service:
    targetPorts:
      https: http
`

**Comment by migruiz4** [comment] 2021-06-28 08:11
Hi @harrishcris, 

Shouldn't it be `service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "https"`?

Maybe that is the cause of this issue: `400 Bad Request The plain HTTP request was sent to HTTPS port nginx`.

**Comment by harrishcris** [comment] 2021-06-28 08:45
Hello @migruiz4 

I just tried changing `aws-load-balancer-backend-protocol ` to `http` however this changed the error to the following:

http = ERR_EMPTY_RESPONSE
https = HTTP ERROR 503

I want SSL to terminate at the ELB then pass on traffic unencrypted to Harbor, I think that when I change aws-load-balancer-backend-protocol to https, the ELB will try and access harbor using it's self signed cert on http that isn't trusted and therefore will fail.

I think I just need to tell nginx to use http only and not SSL \ a self signed certificate, I'm just not sure what value to use to do this?

**Comment by migruiz4** [comment] 2021-06-28 15:15
You can configure NGINX to use HTTP instead of HTTPS by setting `service.tls.enabled=false`.

**Comment by harrishcris** [comment] 2021-06-29 10:24
So adding `service.tls.enabled=false` removes port 443 / HTTPS connection inbound to the **AWS ELB** so it's only listening on port 80 and 4443, it loads correctly on port 80 but ovbiously there is no HTTPS/certificate.

**Comment by migruiz4** [comment] 2021-06-29 10:38
Could you please try using the following:
```
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:XXXXXXX:certificate/XXXXXXX"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  ports:
    http: 443
  tls:
    enabled: false
```

I know that setting `http: 443` may sound contradictory, but this doing so I expect to:
- Configure Nginx to not use self-signed certificates
- Configure the Nginx service, and therefore the **AWS ELB** with two ports, 443 and 4443, and use the ACM certificate.

**Comment by harrishcris** [comment] 2021-06-30 07:36
@migruiz4 Thank you so much, this worked!!

**Comment by migruiz4** [comment] 2021-07-01 06:27
I'm glad it worked!

In that case, I will then close this issue. If you have any further questions please let me know.

**Closed by migruiz4** 2021-07-01 06:27 UTC
