### ISSUE TITLE
IP  in the configuration file is not updated when we restart any redis kubernetes pod

### ISSUE THREAD

**Issue by Yashasvii** [bitnami/charts#10774] opened 2022-06-15 18:15 UTC
### Name and Version

redis-cluster/6.3.6

### What steps will reproduce the bug?

1. Kill any Redis pod in the Kubernetes cluster and wait for it to come back
2. It won't come back to the full running state
On inspecting `nodes.conf ` located in  `/bitnami/redis/data/` it seems its IP is not updated to the new pod IP created after killing the pod.

### What is the expected behavior?

When any redis pod is restarted `nodes.conf ` located in  `/bitnami/redis/data/`  should update the IP automatically. 

### What do you see instead?

When any redis pod is restarted `nodes.conf ` located in  `/bitnami/redis/data/` is showing the old IP of the pod. So, it seems the pod IP is not updated to the cluster.
![Screenshot from 2022-06-15 23-27-05](https://user-images.githubusercontent.com/4491811/173891429-7fbc1c6b-427e-40ae-9850-08cd4cff0d92.png)

**Comment by javsalgar** [comment] 2022-06-20 09:47
Hi,

I was unable to reproduce the issue. I tried removing one of the pods and I could see it was in running state

```
» kubectl get pods
NAME              READY   STATUS    RESTARTS      AGE
redis-cluster-0   1/1     Running   1 (33s ago)   115s
redis-cluster-1   1/1     Running   1 (32s ago)   115s
redis-cluster-2   1/1     Running   1 (37s ago)   115s
redis-cluster-3   1/1     Running   0             115s
redis-cluster-4   1/1     Running   1 (37s ago)   115s
redis-cluster-5   1/1     Running   1 (37s ago)   114s

~
» kubectl delete pod redis-cluster-3
pod "redis-cluster-3" deleted

~
» kubectl get pods -w
NAME              READY   STATUS    RESTARTS      AGE
redis-cluster-0   1/1     Running   1 (79s ago)   2m41s
redis-cluster-1   1/1     Running   1 (78s ago)   2m41s
redis-cluster-2   1/1     Running   1 (83s ago)   2m41s
redis-cluster-3   1/1     Running   0             38s
redis-cluster-4   1/1     Running   1 (83s ago)   2m41s
redis-cluster-5   1/1     Running   1 (83s ago)   2m40s
```

**Comment by yashasvirajpant** [comment] 2022-06-20 09:58
> Hi,
> 
> I was unable to reproduce the issue. I tried removing one of the pods and I could see it was in running state
> 
> ```
> » kubectl get pods
> NAME              READY   STATUS    RESTARTS      AGE
> redis-cluster-0   1/1     Running   1 (33s ago)   115s
> redis-cluster-1   1/1     Running   1 (32s ago)   115s
> redis-cluster-2   1/1     Running   1 (37s ago)   115s
> redis-cluster-3   1/1     Running   0             115s
> redis-cluster-4   1/1     Running   1 (37s ago)   115s
> redis-cluster-5   1/1     Running   1 (37s ago)   114s
> 
> ~
> » kubectl delete pod redis-cluster-3
> pod "redis-cluster-3" deleted
> 
> ~
> » kubectl get pods -w
> NAME              READY   STATUS    RESTARTS      AGE
> redis-cluster-0   1/1     Running   1 (79s ago)   2m41s
> redis-cluster-1   1/1     Running   1 (78s ago)   2m41s
> redis-cluster-2   1/1     Running   1 (83s ago)   2m41s
> redis-cluster-3   1/1     Running   0             38s
> redis-cluster-4   1/1     Running   1 (83s ago)   2m41s
> redis-cluster-5   1/1     Running   1 (83s ago)   2m40s
> ```

Hi @javsalgar ,
Which version are you using? I find it's working fine on `7.6.3`.

**Comment by javsalgar** [comment] 2022-06-22 08:37
Hi,

I tried with the latest version. Did you try to use the latest version of the chart?

**Comment by nixancha** [comment] 2022-06-22 10:54
@javsalgar If you check the logs or try to exec `redis-cli` followed by `cluster info`, It can seen that `cluster_state: fail`
<img width="579" alt="image" src="https://user-images.githubusercontent.com/103242759/175012066-c2364fc6-7fff-4bfd-bbbd-6878be6d2b1f.png">
Also, nodes are stuck at following state:
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/103242759/175012188-4d5e5e0e-107d-4e7b-94b4-775710e60793.png">

**Comment by javsalgar** [comment] 2022-06-27 09:31
Hi,

I tried again and did not get that error

This is from the restarted pod

```
» kubectl exec -ti redis-cluster-3 bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I have no name!@redis-cluster-3:/$ redis-cli -a $REDIS_PASSWORD
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:6379> cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:6
cluster_my_epoch:3
cluster_stats_messages_ping_sent:189
cluster_stats_messages_pong_sent:201
cluster_stats_messages_sent:390
cluster_stats_messages_ping_received:201
cluster_stats_messages_pong_received:189
cluster_stats_messages_received:390
```

**Comment by nixancha** [comment] 2022-06-27 09:34
@javsalgar Thanks for reply. I was also able to fix by doing below:

1. use latest chart version
2. setting `persistence.enabled = false` both during first install and while doing `helm upgrade`.

**Comment by Yashasvii** [comment] 2022-06-28 10:46
@javsalgar  @nixancha  yes using the latest version solves it.

**Comment by javsalgar** [comment] 2022-06-29 09:55
Great! Thanks for letting us know. Closing the ticket then

**Closed by javsalgar** 2022-06-29 09:55 UTC
