### ISSUE TITLE
[bitnami/postgresql-ha] repmgr password disclosure in logfile

### ISSUE THREAD

**Issue by Majen** [bitnami/charts#4833] opened 2020-12-23 21:26 UTC
**Which chart**:
`bitnami/postgresql-ha:6.0.0`

**Describe the bug**
The repmgr password is disclosed in plaintext in the postgresql pod logs if a node goes down.

    [2020-12-08 15:14:52] [WARNING] unable to ping "user=repmgr password=<plaintext_password> host=postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.my-dev.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5"
    [2020-12-08 15:14:52] [DETAIL] PQping() returned "PQPING_NO_RESPONSE"
    [2020-12-08 15:14:52] [WARNING] connection to node "postgresql-ha-postgresql-0" (ID: 1000) lost
    [2020-12-08 15:14:52] [DETAIL] 
    
    [2020-12-08 15:14:57] [ERROR] connection to database failed
    [2020-12-08 15:14:57] [DETAIL] 
    timeout expired
    
    [2020-12-08 15:14:57] [DETAIL] attempted to connect using:
    user=repmgr password=<plaintext_password> connect_timeout=5 dbname=repmgr host=postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.my-dev.svc.cluster.local port=5432 fallback_application_name=repmgr options=-csearch_path=
    [2020-12-08 15:14:57] [WARNING] reconnection to node "postgresql-ha-postgresql-0" (ID: 1000) failed
    [2020-12-08 15:14:57] [WARNING] unable to connect to local node
    [2020-12-08 15:14:57] [NOTICE] node 1000 has recovered, reconnecting
    [2020-12-08 15:14:57] [NOTICE] reconnected to local node after 0 seconds
    

**To Reproduce**

1. Install the helm chart with `repmgrPassword` set in the `values.yaml`
2. Delete/bounce one of the postgresql pods, e.g. `postgresql-ha-postgresql-0`
3. Tail the log of the other postgresql replica.

**Expected behavior**
The repmgr password is not disclosed in the logs of the pods on a connection/ping failure.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
My idea on how to solve this issue was to not include the repmgr password in the conninfo string in the `repmgr.conf` and use either the ENV variable or password file option to provide the repmgr password as outlined in https://repmgr.org/docs/current/configuration-password-management.html.

I tried multiple ways to remove the password from the connection string (e.g. via a custom `files/repmgr.conf`), but wasn't able to get it working while properly replacing the environment variables in my custom conf file.

All the other properties as set in [librepmgr.sh ](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/11/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L398) are fine, I just would like to know a way on how to not disclose the repmgr password in the log file and hope one of you can help me out.

**Comment by FraPazGal** [comment] 2020-12-24 11:34
Hello @Majen,

Looking into the `values.yaml` file, we have the parameter `usePasswordFile` to avoid passing the password by an ENV. Would that work for you?

**Comment by FraPazGal** [comment] 2021-01-07 12:53
Hi @Majen,

You are right, I looked into the container code and the env `REPMGR_PASSWORD_FILE` is not been treated properly. We are just taking the content of said file and passing it to `repmgr.conf` as part of `conninfo` and not as explained in the repmgr documentation.  

Before creating an internal task to address this, I came across an issue deploying the chart with `postgresql.usePasswordFile=true` but it seems you didn't have that problem. Could you confirm that the chart initialises correctly in the latest version or your end?

**Comment by Majen** [comment] 2021-02-06 01:17
I finally was able to update the chart from `6.0.0` to `6.5.1` and it deployed fine. The cluster isn't coming up though as the second node is waiting for the primary node and gets killed after the liveness/readiness probes. I tried increasing the liveness/readiness probes, but it still crashes. The pod postgresql-ha-postgresql-1 terminates with error code 1 after approximately 1m 12s but doesn't print anything in the log files when terminating.

@FraPazGal Is this the issue you're experiencing as well or is this something else?

**Comment by javsalgar** [comment] 2021-02-12 10:14
Hi,

Could you show the logs of the initialization? That way we could check what's causing the crash.

**Comment by Majen** [comment] 2021-02-17 00:03
The pod even got killed by the liveness probe at 300s initialDelay. Further investigation revealed that we had a performance degradation on our storage backend. After fixing this, the pods now show the behaviour that @FraPazGal originally asked me about (pods don't come up properly with `usePasswordFile: true` in the latest chart version. I didn't experience this issue with `6.0.0` but can reproduce it with `6.5.1`.

Using `usePasswordFile: false` all three pods come up `1/1` without any issues:

    postgresql-ha-pgpool-6bfc478d46-4gjs6                     1/1     Running     0          2m36s
    postgresql-ha-postgresql-0                                1/1     Running     0          2m35s
    postgresql-ha-postgresql-1                                1/1     Running     0          2m35s

When setting `usePasswordFile: true`, the readiness and liveness probes fail with `Readiness probe failed: psql: fe_sendauth: no password supplied`.

How do you want to proceed? I would be open to help fixing these two issues, but would need to know how as all my attempts so far in removing the password from the `conninfo` in the `repmgr.conf` file have failed.

**Comment by migruiz4** [comment] 2021-02-17 11:02
Hi @Majen ,

Thank you for reporting this issue, I have created this PR #5525 that fixes the problem when using `usePasswordFile: true`.

**Comment by Majen** [comment] 2021-02-17 15:44
Great, the PR fixes the problem with `usePasswordFile: true` in my deployment!

I'm still getting the original issue with the `conninfo` disclosing the password in the logs though as confirmed by @FraPazGal:
> You are right, I looked into the container code and the env `REPMGR_PASSWORD_FILE` is not been treated properly. We are just taking the content of said file and passing it to `repmgr.conf` as part of `conninfo` and not as explained in the repmgr documentation.

**Comment by Majen** [comment] 2021-02-18 14:30
Just wanted to note that the original issue isn't resolved yet, therefore this ticket should be reopened.

**Comment by Mauraza** [comment] 2021-02-18 14:33
Hi @Majen,

I just reopen the issue, we keep working in:

> I'm still getting the original issue with the conninfo disclosing the password in the logs though as confirmed by @FraPazGal:
  > You are right, I looked into the container code and the env REPMGR_PASSWORD_FILE is not been treated properly. We are 
   just taking the content of said file and passing it to repmgr.conf as part of conninfo and not as explained in the repmgr 
  documentation.

**Comment by Mauraza** [comment] 2021-02-22 15:51
Hi @Majen,

I found why happen, if you check the container the files of the container `bitnami-docker-postgresql-repmg`, you can find this 
https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/1916d4f0bc479a1c5b20d634abb9b419340879ef/13/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L414
```
conninfo='user=${REPMGR_USERNAME} password=${REPMGR_PASSWORD} host=${REPMGR_NODE_NETWORK_NAME} dbname=${REPMGR_DATABASE} port=${REPMGR_PORT_NUMBER} connect_timeout=${REPMGR_CONNECT_TIMEOUT}'
```
I going a create an internal to investigate possibles solutions, but if you want you can create a PR in that repository with your possible solution.

**Comment by Majen** [comment] 2021-03-01 14:44
Yes, that's the code in librepmgr.sh I pointed out in the original bug report. I replaced that line with
```
conninfo='user=${REPMGR_USERNAME} host=${REPMGR_NODE_NETWORK_NAME} dbname=${REPMGR_DATABASE} port=${REPMGR_PORT_NUMBER} connect_timeout=${REPMGR_CONNECT_TIMEOUT}'
```
and tried to set the environment variable properly in the other shell scripts via `PGPASSWORD=<pwd>`, but didn't get it working successful. Therefore I'm hoping that you can come up with a solution that works :)

**Comment by migruiz4** [comment] 2021-03-23 10:11
Hi @Majen ,

The Postgresql Repmgr docker image has been updated to configure `passfile` instead of `password`(https://github.com/bitnami/bitnami-docker-postgresql-repmgr).

Additionally, I have submitted this PR #5879 that adds the feature to the postgresql-ha chart by setting `postgresql.repmgrUsePassfile=true`. 

In the **Additional information** section of the PR, you can see how the issue with the conninfo exposing the password should be fixed.

**Closed** 2021-03-23 16:18 UTC
Labels: on-hold

**Comment by Majen** [comment] 2021-03-24 00:53
Thanks a lot @migruiz4! The chart version `6.8.0` fixes the problem 👍

**Comment by migruiz4** [comment] 2021-03-24 09:59
Awesome! Thank you for your feedback confirming the issue is fixed.

**Comment by rafariossaa** [comment] 2022-07-19 07:03
Hi @Deepanshu6dec ,
  Do you mind opening  a new issue ? This way we can ask you for the details of your use case and properly track the issue.
Thanks forehand.
