### ISSUE TITLE
[kong] 'An unexpected error occurred' with basic deployment

### ISSUE THREAD

**Issue by blakelead** [bitnami/charts#7248] opened 2021-08-17 14:26 UTC
**Which chart**:
bitnami/kong version 3.8.2

**Describe the bug**
After deploying Kong ingress controller in EKS and testing it with the example provided in the official Kong documentation (https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/getting-started) I get the following CURL output:

```bash
> curl http://xxxxxxxxxxxxxx-xxxxxx.eu-west-3.elb.amazonaws.com/foo
HTTP/1.1 500 Internal Server Error
Date: Tue, 17 Aug 2021 14:19:02 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Content-Length: 42
X-Kong-Response-Latency: 30031
Server: kong/2.5.0

{"message":"An unexpected error occurred"}
```

Error logs inside the `kong` pod are as follows:

```bash
> cat /opt/bitnami/kong/server/logs/error.log
2021/08/17 13:47:06 [error] 90#0: *7 [lua] handler.lua:342: config flip failed: ...luajit/share/lua/5.1/kong/runloop/balancer/balancers.lua:108: module 'kong.runloop.balancer.consistent_hashing' not found:No LuaRocks module found for kong.runloop.balancer.consistent_hashing
        no field package.preload['kong.runloop.balancer.consistent_hashing']
        no file './kong/runloop/balancer/consistent_hashing.lua'
        no file './kong/runloop/balancer/consistent_hashing/init.lua'
        no file '/opt/bitnami/kong/openresty/site/lualib/kong/runloop/balancer/consistent_hashing.ljbc'
        no file '/opt/bitnami/kong/openresty/site/lualib/kong/runloop/balancer/consistent_hashing/init.ljbc'
        no file '/opt/bitnami/kong/openresty/lualib/kong/runloop/balancer/consistent_hashing.ljbc'
        no file '/opt/bitnami/kong/openresty/lualib/kong/runloop/balancer/consistent_hashing/init.ljbc'
        no file '/opt/bitnami/kong/openresty/site/lualib/kong/runloop/balancer/consistent_hashing.lua'
        no file '/opt/bitnami/kong/openresty/site/lualib/kong/runloop/balancer/consistent_hashing/init.lua'
        no file '/opt/bitnami/kong/openresty/lualib/kong/runloop/balancer/consistent_hashing.lua'
        no file '/opt/bitnami/kong/openresty/lualib/kong/runloop/balancer/consistent_hashing/init.lua'
        no file '/opt/bitnami/kong/openresty/luajit/share/luajit-2.1.0-beta3/kong/runloop/balancer/consistent_hashing.lua'
        no file '/usr/local/share/lua/5.1/kong/runloop/balancer/consistent_hashing.lua'
        no file '/usr/local/share/lua/5.1/kong/runloop/balancer/consistent_hashing/init.lua'
        no file '/opt/bitnami/kong/openresty/luajit/share/lua/5.1/kong/runloop/balancer/consistent_hashing.lua'
        no file '/opt/bitnami/kong/openresty/luajit/share/lua/5.1/kong/runloop/balancer/consistent_hashing/init.lua'
        no file '/.luarocks/share/lua/5.1/kong/runloop/balancer/consistent_hashing.lua'
        no file '/.luarocks/share/lua/5.1/kong/runloop/balancer/consistent_hashing/init.lua'
        no file '/opt/bitnami/kong/openresty/site/lualib/kong/runloop/balancer/consistent_hashing.so'
        no file '/opt/bitnami/kong/openresty/lualib/kong/runloop/balancer/consistent_hashing.so'
        no file './kong/runloop/balancer/consistent_hashing.so'
        no file '/usr/local/lib/lua/5.1/kong/runloop/balancer/consistent_hashing.so'
        no file '/opt/bitnami/kong/openresty/luajit/lib/lua/5.1/kong/runloop/balancer/consistent_hashing.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/.luarocks/lib/lua/5.1/kong/runloop/balancer/consistent_hashing.so'
        no file '/opt/bitnami/kong/openresty/site/lualib/kong.so'
        no file '/opt/bitnami/kong/openresty/lualib/kong.so'
        no file './kong.so'
        no file '/usr/local/lib/lua/5.1/kong.so'
        no file '/opt/bitnami/kong/openresty/luajit/lib/lua/5.1/kong.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/.luarocks/lib/lua/5.1/kong.so', client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "127.0.0.1:8001"
2021/08/17 13:47:06 [error] 91#0: *9 [lua] handler.lua:342: config flip failed: ...luajit/share/lua/5.1/kong/runloop/balancer/balancers.lua:108: module 'kong.runloop.balancer.consistent_hashing' not found:No LuaRocks module found for kong.runloop.balancer.consistent_hashing
        no field package.preload['kong.runloop.balancer.consistent_hashing']
        no file './kong/runloop/balancer/consistent_hashing.lua'
        no file './kong/runloop/balancer/consistent_hashing/init.lua'
        no file '/opt/bitnami/kong/openresty/site/lualib/kong/runloop/balancer/consistent_hashing.ljbc'
        no file '/opt/bitnami/kong/openresty/site/lualib/kong/runloop/balancer/consistent_hashing/init.ljbc'
        no file '/opt/bitnami/kong/openresty/lualib/kong/runloop/balancer/consistent_hashing.ljbc'
        no file '/opt/bitnami/kong/openresty/lualib/kong/runloop/balancer/consistent_hashing/init.ljbc'
        no file '/opt/bitnami/kong/openresty/site/lualib/kong/runloop/balancer/consistent_hashing.lua'
        no file '/opt/bitnami/kong/openresty/site/lualib/kong/runloop/balancer/consistent_hashing/init.lua'
        no file '/opt/bitnami/kong/openresty/lualib/kong/runloop/balancer/consistent_hashing.lua'
        no file '/opt/bitnami/kong/openresty/lualib/kong/runloop/balancer/consistent_hashing/init.lua'
        no file '/opt/bitnami/kong/openresty/luajit/share/luajit-2.1.0-beta3/kong/runloop/balancer/consistent_hashing.lua'
        no file '/usr/local/share/lua/5.1/kong/runloop/balancer/consistent_hashing.lua'
        no file '/usr/local/share/lua/5.1/kong/runloop/balancer/consistent_hashing/init.lua'
        no file '/opt/bitnami/kong/openresty/luajit/share/lua/5.1/kong/runloop/balancer/consistent_hashing.lua'
        no file '/opt/bitnami/kong/openresty/luajit/share/lua/5.1/kong/runloop/balancer/consistent_hashing/init.lua'
        no file '/.luarocks/share/lua/5.1/kong/runloop/balancer/consistent_hashing.lua'
        no file '/.luarocks/share/lua/5.1/kong/runloop/balancer/consistent_hashing/init.lua'
        no file '/opt/bitnami/kong/openresty/site/lualib/kong/runloop/balancer/consistent_hashing.so'
        no file '/opt/bitnami/kong/openresty/lualib/kong/runloop/balancer/consistent_hashing.so'
        no file './kong/runloop/balancer/consistent_hashing.so'
        no file '/usr/local/lib/lua/5.1/kong/runloop/balancer/consistent_hashing.so'
        no file '/opt/bitnami/kong/openresty/luajit/lib/lua/5.1/kong/runloop/balancer/consistent_hashing.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/.luarocks/lib/lua/5.1/kong/runloop/balancer/consistent_hashing.so'
        no file '/opt/bitnami/kong/openresty/site/lualib/kong.so'
        no file '/opt/bitnami/kong/openresty/lualib/kong.so'
        no file './kong.so'
        no file '/usr/local/lib/lua/5.1/kong.so'
        no file '/opt/bitnami/kong/openresty/luajit/lib/lua/5.1/kong.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/.luarocks/lib/lua/5.1/kong.so', context: ngx.timer
2021/08/17 13:51:46 [notice] 90#0: *2191 [lua] init.lua:260: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "127.0.0.1:8001"
2021/08/17 13:51:46 [notice] 90#0: *2191 [lua] init.lua:260: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "127.0.0.1:8001"
2021/08/17 13:52:15 [warn] 90#0: *3109 using uninitialized "kong_proxy_mode" variable while logging request, client: 10.0.61.110, server: kong, request: "GET / HTTP/1.1", host: "xxxxxxxxxxxxxx-xxxxxx.eu-west-3.elb.amazonaws.com"
2021/08/17 13:52:15 [warn] 90#0: *3109 [lua] reports.lua:80: log(): [reports] could not determine log suffix (scheme=http, proxy_mode=) while logging request, client: 10.0.61.110, server: kong, request: "GET / HTTP/1.1", host: "xxxxxxxxxxxxxx-xxxxxx.eu-west-3.elb.amazonaws.com"
2021/08/17 13:52:16 [crit] 90#0: *2191 [lua] balancers.lua:250: create_balancers(): failed creating balancer for :echo.kong.80.svc: timeout waiting for balancer for 1a73d2d7-bdce-5529-8982-16818ef41db9, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "127.0.0.1:8001"
2021/08/17 13:52:21 [warn] 90#0: *3111 using uninitialized "kong_proxy_mode" variable while logging request, client: 10.0.39.151, server: kong, request: "GET /foo HTTP/1.1", host: "xxxxxxxxxxxxxx-xxxxxx.eu-west-3.elb.amazonaws.com"
2021/08/17 13:52:21 [warn] 90#0: *3111 [lua] reports.lua:80: log(): [reports] could not determine log suffix (scheme=http, proxy_mode=) while logging request, client: 10.0.39.151, server: kong, request: "GET /foo HTTP/1.1", host: "xxxxxxxxxxxxxx-xxxxxx.eu-west-3.elb.amazonaws.com"
2021/08/17 13:52:47 [crit] 91#0: *2928 [lua] balancers.lua:250: create_balancers(): failed creating balancer for :echo.kong.80.svc: timeout waiting for balancer for 1a73d2d7-bdce-5529-8982-16818ef41db9, context: ngx.timer
2021/08/17 14:01:16 [error] 90#0: *11196 [lua] balancers.lua:222: get_balancer(): balancer not found for echo.kong.80.svc, will create it, client: 10.0.61.110, server: kong, request: "GET /foo HTTP/1.1", host: "xxxxxxxxxxxxxx-xxxxxx.eu-west-3.elb.amazonaws.com"
```

**To Reproduce**

Values file applied:

```yaml
image:
  registry: docker.io
  repository: bitnami/kong
  tag: 2.5.0
  pullPolicy: IfNotPresent
  debug: false

replicaCount: 1

useDaemonset: false

containerSecurityContext:
  runAsUser: 1001
  runAsNonRoot: true

service:
  type: LoadBalancer
  proxyHttpPort: 80
  proxyHttpsPort: 443
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
ingress.enabled: false

kong:
  extraEnvVars:
    - name: KONG_DATABASE
      value: "off"
    - name: KONG_ADMIN_ACCESS_LOG
      value: /dev/stdout
  resources: {}

ingressController:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/kong-ingress-controller
    tag: 1.3.1
    pullPolicy: IfNotPresent
  proxyReadyTimeout: 300
  rbac:
    create: true
  ingressClass: kong
  resources: {}

database: "none"
postgresql.enabled: false

migration:
  annotations:
    argocd.argoproj.io/hook: Skip
```

An ELB is created automatically with the following listener conf:

Load Balancer Protocol | Load Balancer Port | Instance Protocol | Instance Port | Cipher | SSL Certificate
-- | -- | -- | -- | -- | --
TCP | 443 | TCP | 31052 | N/A | N/A
TCP | 80 | TCP | 31790 | N/A | N/A

The [example service](https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/getting-started) is deployed as follows:

```bash
> kubectl apply -f https://bit.ly/echo-service
service/echo created
deployment.apps/echo created
> echo "
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: echo
          servicePort: 80
" | kubectl apply -f -
```

The ingress controller makes the association with the ELB address:

```bash
> kubectl get ingress
NAME   CLASS    HOSTS   ADDRESS                                                                  PORTS   AGE
demo   <none>   *       xxxxxxxxxxxxxx-xxxxxx.eu-west-3.elb.amazonaws.com   80      31m
```

**Expected behavior**
curl request to HTTP endpoint should respond with status 200 OK.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment] 2021-08-18 09:18
Hi,

I was able to reproduce the issue with the module missing. I will open a task for this. Thanks for reporting.

**Comment by blakelead** [comment] 2021-08-20 09:26
Hi @javsalgar,
Do you know a way to workaround this issue for know?

**Comment by javsalgar** [comment] 2021-08-23 10:24
It's not clear to me. Maybe forking the container and executing luarocks install with the missing package may work, but I couldn't test it at the moment.

**Comment by javsalgar** [comment] 2021-09-13 07:45
Not stale

**Comment by FraPazGal** [comment] 2022-05-09 12:23
Hello @blakelead,

We were reviewing the internal task related to this ticket and we haven't been able to reproduce the issue. We obtained the expected `200` and kong logs were clean:

```
$ k get svc
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                      AGE
echo         ClusterIP      10.144.61.140   <none>          8080/TCP,80/TCP              20s
kong         LoadBalancer   10.144.56.178   35.196.28.187   80:32697/TCP,443:30550/TCP   11m
kubernetes   ClusterIP      10.144.48.1     <none>          443/TCP                      27m

$ k get ingress
NAME   CLASS    HOSTS   ADDRESS         PORTS   AGE
demo   <none>   *       35.196.28.187   80      8s

$ curl -LI 35.196.28.187/foo
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Connection: keep-alive
Date: Mon, 09 May 2022 12:00:31 GMT
Server: echoserver
X-Kong-Upstream-Latency: 1
X-Kong-Proxy-Latency: 0
Via: kong/2.8.1
```

This may have been fixed in a version released since this ticket was created. Could you please confirm the error is no longer present?

**Closed** 2022-05-20 12:41 UTC
