### ISSUE TITLE
[bitnami/postgresql] parse error at (postgresql/templates/_helpers.tpl:164): unclosed action

### ISSUE THREAD

**Issue by GaryGlobality** [bitnami/charts#17488] opened 2023-07-05 09:19 UTC
### Name and Version

bitnami/postgresql

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Using Skaffold to deploy with helm:

```
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: infra
build:
  local: {}
deploy:
  helm:
    releases:
    - name: postgres
      remoteChart: postgresql
      repo: https://charts.bitnami.com/bitnami
      namespace: "{{ .NAMESPACE_NAME }}"
      createNamespace: true
      valuesFiles:
        - skaffold/postgres_values.yaml
```

`skaffold run -f skaffold/infra.yaml`

### Are you using any custom parameters or values?

Values:

```
image:
  tag: 11
primary:
  pgHbaConfiguration: |-
    host     all             all             0.0.0.0/0               trust
    host     all             all             ::/0                    trust
    local    all             all                                     trust
    host     all             all        127.0.0.1/32                 trust
    host     all             all        ::1/128                      trust
  persistence:
    size: 500Mi
```

### What is the expected behavior?

There should not be a parse error.

### What do you see instead?

`Error: parse error at (postgresql/templates/_helpers.tpl:164): unclosed action`

### Additional information

Possibly related to https://github.com/bitnami/charts/issues/17472

**Comment by gongomgra** [comment] 2023-07-05 11:02
Hi @GaryGlobality,

Thanks for using Bitnami. I'm afraid I can't reproduce your issue. I used the same `values.yaml` you provided and it has worked for me

```
$ cat custom-values.yaml
image:
  tag: 11
primary:
  pgHbaConfiguration: |-
    host     all             all             0.0.0.0/0               trust
    host     all             all             ::/0                    trust
    local    all             all                                     trust
    host     all             all        127.0.0.1/32                 trust
    host     all             all        ::1/128                      trust
  persistence:
    size: 500Mi

$ helm install -n postgresql postgresql bitnami/postgresql --values custom-values.yaml
NAME: postgresql
LAST DEPLOYED: Wed Jul  5 12:55:08 2023
NAMESPACE: postgresql
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: postgresql
CHART VERSION: 12.6.2
(...)

$ kubectl -n postgresql get all
NAME               READY   STATUS    RESTARTS   AGE
pod/postgresql-0   1/1     Running   0          6m19s

NAME                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/postgresql      ClusterIP   10.111.254.243   <none>        5432/TCP   6m19s
service/postgresql-hl   ClusterIP   None             <none>        5432/TCP   6m19s

NAME                          READY   AGE
statefulset.apps/postgresql   1/1     6m19s

$ kubectl -n postgresql describe po postgresql-0 | grep -i image
    Image:          docker.io/bitnami/postgresql:11
    Image ID:       docker-pullable://bitnami/postgresql@sha256:c2476f36b88829444b8dabbb0ed7a111e27853aba87d103a3518522863a7d482
  Normal   Pulled            23s   kubelet            Container image "docker.io/bitnami/postgresql:11" already present on machine
```

Can you check you are using the `12.6.2` chart version? I'm also sharing the output of running `helm template` command (sharing as `.yaml.txt` file due to GitHub restrictions).

[postgresql-template.yaml.txt](https://github.com/bitnami/charts/files/11957070/postgresql-template.yaml.txt)

**Comment by vhppp** [comment] 2023-07-06 21:21
Using an older version such as 12.6.0 does get around this for the time being.

**Comment by gongomgra** [comment] 2023-07-10 08:54
Hi @vhppp,

Did you have any chance to test latest version? https://github.com/bitnami/charts/pull/17502

**Comment by KiBrunner** [comment] 2023-07-11 21:44
Had a similar issue when deploying with Argocd. I am guessing, if you edit the _helpers.tpl file to put line 164 and line 165 on one line, it will work (ensuring no open statements from line to line). I had a similar issue with a line in a Vault deployment and it worked. Unfortunately, I can't test it here because argocd throws an OCI error when trying to pull in the files.

**Comment by migruiz4** [comment] 2023-07-14 08:43
Hi @KiBrunner @GaryGlobality,

Thank you for your feedback! It shouldn't be a problem moving these lines in a single line if that fixes the issue:

https://github.com/bitnami/charts/blob/961d1d23f76bcf88e462c6902aa5ec0767302f59/bitnami/postgresql/templates/_helpers.tpl#L164-L165

I wasn't aware that those multi-line sentences could cause issues with other tools such as ArgoCD or Skaffold

**Comment by shivamkm07** [comment] 2023-07-25 17:14
Hi, We have the same issue for us in [Dapr](https://github.com/dapr/dapr). We are just using the default values for installing postgres via helm: `helm upgrade --install dapr-postgres bitnami/postgresql -f ./tests/config/postgres_override.yaml --namespace $(DAPR_TEST_NAMESPACE) --wait --timeout 5m0s`
The config file `postgres_override.yaml` can be found here: https://github.com/dapr/dapr/blob/master/tests/config/postgres_override.yaml

An example workflow run failing due to installation issue of postgres: https://github.com/dapr/dapr/actions/runs/5652573279/job/15314823520?pr=6601

Many of our test workflows are failing due to this installation issue. Is there any estimate by when this could be resolved? Thanks!

**Comment by jakoberpf** [comment] 2023-07-27 12:49
We have the same issue. Any idea when this will be merged? https://github.com/bitnami/charts/pull/17711

**Closed** 2023-07-31 13:12 UTC
Labels: in-progress, tech-issues, postgresql
