### ISSUE TITLE
Auto-resharding not happening when scaling up a redis-cluster with persistence enabled

### ISSUE THREAD

**Issue by ganeshjaju** [bitnami/charts#6381] opened 2021-05-17 06:00 UTC
**Which chart**:
bitnami/redis-cluster

**Describe the bug**

I am running a Redis Cluster with 6 nodes (3 master, 3 slaves) with persistence enabled. I scaled up to 8 nodes (4 master, 4 slaves) using "helm upgrade". But, the cluster slots are not auto resharded. Although all 8 nodes are connected to cluster, the slots are distributed among older 3 masters only.

**To Reproduce**

When a persistent redis cluster is scaled up, I don't see auto resharding happening to accomodate the new master.
Is this support available or planned in the future?

Install the redis-cluster:

```console
$ helm install my-release --set "containerSecurityContext.runAsUser=0"  --set "persistence.size=1Gi" --set "persistence.storageClass=local-storage"  ./bitnami/redis-cluster

$ kubectl get pods
NAME                         READY   STATUS    RESTARTS   AGE
my-release-redis-cluster-0   1/1     Running   2          101s
my-release-redis-cluster-1   1/1     Running   2          101s
my-release-redis-cluster-2   1/1     Running   2          101s
my-release-redis-cluster-3   1/1     Running   2          100s
my-release-redis-cluster-4   1/1     Running   2          100s
my-release-redis-cluster-5   1/1     Running   2          100s

$ kubectl exec --stdin --tty my-release-redis-cluster-0 -- redis-cli -c
127.0.0.1:6379> cluster slots
1) 1) (integer) 0
   2) (integer) 5460
   3) 1) "10.244.0.23"
      2) (integer) 6379
      3) "d9e57452cee5facf41706ea43da4e662c9a4eb87"
   4) 1) "10.244.0.26"
      2) (integer) 6379
      3) "65ed8f13c58d1b2d79586e11ee6cd3054338c2ab"
2) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "10.244.0.24"
      2) (integer) 6379
      3) "ecd10373a8d9aa93914969f57c084d8b30fdd392"
   4) 1) "10.244.0.25"
      2) (integer) 6379
      3) "6b020725817bb7c8707df026fbdc4394147bb7de"
3) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "10.244.0.21"
      2) (integer) 6379
      3) "613e337ffdc866e15982e6cd7cacd646490b4097"
   4) 1) "10.244.0.22"
      2) (integer) 6379
      3) "81d3a16c7ff55a69384425ad16e234c353823307"

$ export REDIS_PASSWORD=$(kubectl get secret --namespace "default" my-release-redis-cluster -o jsonpath="{.data.redis-password}" | base64 --decode)
```

Scale up the cluster to 8 nodes:

```console
$ helm upgrade  my-release --set "containerSecurityContext.runAsUser=0" --set "persistence.size=1Gi" --set "persistence.storageClass=local-storage"  --set "password=${REDIS_PASSWORD},cluster.nodes=8,cluster.update.addNodes=true,cluster.update.currentNumberOfNodes=6" ./bitnami/redis-cluster

$ kubectl exec --stdin --tty my-release-redis-cluster-0 -- redis-cli -c
127.0.0.1:6379> cluster nodes
ecd10373a8d9aa93914969f57c084d8b30fdd392 10.244.0.34:6379@16379 master - 0 1621230044000 2 connected 5461-10922
af940c97ae931896e8a34841fda73620b3f3ff49 10.244.0.28:6379@16379 master - 0 1621230044000 8 connected 0-5460
d9e57452cee5facf41706ea43da4e662c9a4eb87 10.244.0.35:6379@16379 myself,slave af940c97ae931896e8a34841fda73620b3f3ff49 0 1621230045000 8 connected
613e337ffdc866e15982e6cd7cacd646490b4097 10.244.0.33:6379@16379 slave 81d3a16c7ff55a69384425ad16e234c353823307 0 1621230044678 7 connected
6b020725817bb7c8707df026fbdc4394147bb7de 10.244.0.30:6379@16379 slave ecd10373a8d9aa93914969f57c084d8b30fdd392 0 1621230043000 2 connected
65ed8f13c58d1b2d79586e11ee6cd3054338c2ab 10.244.0.31:6379@16379 slave af940c97ae931896e8a34841fda73620b3f3ff49 0 1621230039000 8 connected
81d3a16c7ff55a69384425ad16e234c353823307 10.244.0.32:6379@16379 master - 0 1621230045683 7 connected 10923-16383
d2b246aa0d1a93f6c837017866b64ffb3f5e6a00 10.244.0.29:6379@16379 master - 0 1621230041654 0 connected
127.0.0.1:6379>
127.0.0.1:6379> cluster slots
1) 1) (integer) 0
   2) (integer) 5460
   3) 1) "10.244.0.28"
      2) (integer) 6379
      3) "af940c97ae931896e8a34841fda73620b3f3ff49"
   4) 1) "10.244.0.35"
      2) (integer) 6379
      3) "d9e57452cee5facf41706ea43da4e662c9a4eb87"
   5) 1) "10.244.0.31"
      2) (integer) 6379
      3) "65ed8f13c58d1b2d79586e11ee6cd3054338c2ab"
2) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "10.244.0.34"
      2) (integer) 6379
      3) "ecd10373a8d9aa93914969f57c084d8b30fdd392"
   4) 1) "10.244.0.30"
      2) (integer) 6379
      3) "6b020725817bb7c8707df026fbdc4394147bb7de"
3) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "10.244.0.32"
      2) (integer) 6379
      3) "81d3a16c7ff55a69384425ad16e234c353823307"
   4) 1) "10.244.0.33"
      2) (integer) 6379
      3) "613e337ffdc866e15982e6cd7cacd646490b4097"
```

**Expected behavior**

Cluster slots should be rebalanced among all new masters (in this case the 4th master).

**Comment by juan131** [comment] 2021-05-17 09:02
Closing as duplicate of https://github.com/bitnami/charts/issues/2573
Reopening original issue.

**Closed by juan131** 2021-05-17 09:02 UTC
