### ISSUE TITLE
Missing access to coordination.k8s.io in last version

### ISSUE THREAD

**Issue by Kamaradeivanov** [bitnami/charts#11248] opened 2022-07-15 16:05 UTC
### Name and Version

bitnami/nginx-ingress-controller:9.2.20

### What steps will reproduce the bug?

According to the last official nginx ingress controller [available here](https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.3.0/deploy/static/provider/baremetal/deploy.yaml), we need more access to create, update and get leases for coordination.k8s.io api.

Something like that : 

```
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - ingress-controller-leader
  resources:
  - leases
  verbs:
  - get
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
```

### What is the expected behavior?

A leader should be ellected 

### What do you see instead?

The following error :

`error retrieving resource lock nginx-ingress/ingress-controller-leader-private: leases.coordination.k8s.io "ingress-controller-leader-private" is forbidden: User "system:serviceaccount:nginx-ingress:ingress-controller-private-nginx-ingress-controller" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "nginx-ingress" `

**Comment by fmulero** [comment] 2022-07-19 13:58
Hi @Kamaradeivanov I moved the issue to bitnami charts becuasee I think it can be easily fixed here

**Comment by HerHde** [comment] 2022-07-26 20:46
Possible duplicate of #11192

**Comment by alemorcuq** [comment] 2022-08-01 07:12
Closing as a duplicate of #11192

**Closed by alemorcuq** 2022-08-01 07:12 UTC
Labels: in-progress, nginx, tech-issues
