### ISSUE TITLE
[bitnami/postgresql] chart complains about secret not provided when using existingSecret on upgrade

### ISSUE THREAD

**Issue by stephenc** [bitnami/charts#24290] opened 2024-03-08 15:50 UTC
### Name and Version

bitnami/postgresql 12.11.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Configure a secret with the password to provision a user with
2. Deploy the chart with `auth.existingSecret` configured and the corresponding `auth.secretKeys`
3. Upgrade the chart. 

### What is the expected behavior?

The chart is supposed to upgrade as an existing secret has been provided via an existing secret

### What do you see instead?

```
Error: Failed to render chart: exit status 1: Error: execution error at (postgresql/templates/secrets.yaml:23:16): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
    'global.postgresql.auth.password' must not be empty, please add '--set global.postgresql.auth.password=$KEYCLOAK_PASSWORD' to the command. To get the current value:
        export KEYCLOAK_PASSWORD=$(kubectl get secret --namespace "postgresql-cloudbees" postgresql-credentials -o jsonpath="{.data.keycloak-password}" | base64 -d)
Use --debug flag to render out invalid YAML
```

### Additional information

The root cause is that the check for the password error is happening outside of the if condition around creating the secret to hold chart generated passwords, i.e.

https://github.com/bitnami/charts/blob/9407892e59e1004bd702c03587fb4782c9949e48/bitnami/postgresql/templates/secrets.yaml#L23 is outside of https://github.com/bitnami/charts/blob/9407892e59e1004bd702c03587fb4782c9949e48/bitnami/postgresql/templates/secrets.yaml#L26

This issue seems to still be present on `main` at the time of reporting this bug, i.e. 

https://github.com/bitnami/charts/blob/9186bd922bcfc60919c98bc9c0613fb3d2bbe329/bitnami/postgresql/templates/secrets.yaml#L23 is above https://github.com/bitnami/charts/blob/9186bd922bcfc60919c98bc9c0613fb3d2bbe329/bitnami/postgresql/templates/secrets.yaml#L26

**Comment by stephenc** [comment] 2024-03-08 15:53
Workaround is to specify `auth.password` with a dummy value. Note that the dummy value is thereafter ignored as the secret is not created. I suggest `https://github.com/bitnami/charts/issues/24290` as the dummy value to use 🤣

**Comment by andresbono** [comment] 2024-03-21 16:11
Hi, thank you for opening this issue. Would you like to contribute with a PR improving the chart? Our team will be more than happy to review it. Thank you again!

**Comment by stephenc** [comment] 2024-03-21 20:06
I do not have the bandwidth to work on this myself at present.

**Comment by andresbono** [comment] 2024-04-02 09:39
In fact @stephenc, I'm not sure if I can reproduce your issue:

```console
$ kubectl create secret generic mysecret --from-literal=myadminpassword=secretadminpassword --from-literal=myuserpassword=secretuserpassword

$ helm install postgresql oci://registry-1.docker.io/bitnamicharts/postgresql --version 15.2.0 --set auth.username=myusername --set auth.existingSecret=mysecret --set auth.secretKeys.adminPasswordKey=myadminpassword --set auth.secretKeys.userPasswordKey=myuserpassword

$ kubectl exec -it postgresql-0 -- bash -c "PGPASSWORD=secretadminpassword psql -U postgres -c 'SELECT 1;'"
$ kubectl exec -it postgresql-0 -- bash -c "PGPASSWORD=secretuserpassword psql postgres -U myusername -c 'SELECT 1;'"

$ helm upgrade postgresql oci://registry-1.docker.io/bitnamicharts/postgresql --version 15.2.0 --set auth.username=myusername --set auth.existingSecret=mysecret --set auth.secretKeys.adminPasswordKey=myadminpassword --set auth.secretKeys.userPasswordKey=myuserpassword

$ kubectl exec -it postgresql-0 -- bash -c "PGPASSWORD=secretadminpassword psql -U postgres -c 'SELECT 1;'"
$ kubectl exec -it postgresql-0 -- bash -c "PGPASSWORD=secretuserpassword psql postgres -U myusername -c 'SELECT 1;'"
```

The commands above work as expected...

**Comment by stephenc** [comment] 2024-04-02 11:30
Looks to be a dup of https://github.com/bitnami/charts/issues/19202

**Comment by andresbono** [comment] 2024-04-03 10:31
Oh, thank you for pointing to the original issue. Please, if you consider that there has been some sort of regression in the fix of https://github.com/bitnami/charts/issues/19202, could you share the details there? I proceed to close this one.

Although https://github.com/bitnami/charts/issues/19202#issuecomment-1721376330 confirms that the same chart version you are using works as expected... And I cannot reproduce your issue either with a newer version (`15.2.0`), see my comment above.

**Closed by andresbono** 2024-04-03 10:31 UTC
Labels: in-progress, tech-issues, postgresql
