### ISSUE TITLE
[bitnami/redis-cluster] no password issue

### ISSUE THREAD

**Issue by mojixcoder** [bitnami/charts#17338] opened 2023-06-24 09:44 UTC
### Name and Version

bitnami/redis-cluster

### What architecture are you using?

None

### What steps will reproduce the bug?

Here is my manifest:
```
nameOverride: "redis-cluster"
fullnameOverride: "redis-cluster"

commonLabels:
  app: redis-cluster

usePassword: false

image:
  tag: 6.2-debian-11

podSecurityContext:
  enabled: true
  sysctls:
    - name: "net.core.somaxconn"
      value: "65535"
    - name: "net.ipv4.ip_local_port_range"
      value: "15000 60999"

containerSecurityContext:
  enabled: true

persistence:
  enabled: true
  path: /redis/data
  size: 500Mi

service:
  type: ClusterIP

volumePermissions:
  enabled: true
  image:
    tag: 11-debian-11-r118

redis:
  resources:
    limits:
      memory: 500Mi
      cpu: 200m
  defaultConfigOverride: |
    dir /redis/data
    appendonly yes
    save 60 500
    maxmemory 450mb
    maxmemory-policy allkeys-lru
    cluster-enabled yes
    cluster-config-file nodes.conf
    cluster-node-timeout 15000
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit slave 800mb 800mb 180
    client-output-buffer-limit pubsub 32mb 8mb 60
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 9
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 9
    successThreshold: 1
    failureThreshold: 5

cluster:
  nodes: 6
  replicas: 1
  update:
    currentNumberOfNodes: 6
    currentNumberOfReplicas: 1

metrics:
  enabled: true
  tag: 1.50.0-debian-11-r13
  resources:
    limits:
      memory: 150Mi
      cpu: 100m
  containerSecurityContext:
    enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s
```

The cluster is deployed and there is no error at the first sight.
But when I look at the logs of `redis-cluster-0` pod I see lots of this error log:
```
AUTH failed: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
2321
Node redis-cluster-0.redis-cluster-headless not ready, waiting for all the nodes to be ready... 
```

Therefore, in the client-side when I do redis commands some of them are failed because of this error:
```
dial tcp ip:6379: connect: no route to host
```

And the IP changes over time.

Has anyone had this issue before?

### What is the expected behavior?

There should be no AUTH error since it's disabled.

### What do you see instead?

I see AUTH error.

**Comment by ivan901229** [comment] 2023-06-28 07:37
I have the same problem.

**Comment by xrow** [comment] 2023-06-28 08:47
I can confirm this too. Found no workaround yet.

**Comment by xrow** [comment] 2023-06-28 09:18
A down grade to version 8.3.4 fixed my issue.

**Comment by ivan901229** [comment] 2023-06-28 10:42
@xrow 
I resolved my issue by downgrading to version 8.6.3. However, starting from version 8.6.4, I encountered an AUTH error and subsequent versions also exhibit the same problem.
```
AUTH failed: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
```

**Comment by xrow** [comment] 2023-06-28 11:11
I see there must be a regression in the docker image https://github.com/bitnami/charts/commit/42d380e48c864ad8d92a9af2dbdd7c0a67d93cd7

**Comment by joancafom** [comment] 2023-07-04 09:07
Hi everyone, thanks for reporting! 

Yes, I can confirm this seems to be a regression introduced in the docker-image at https://github.com/bitnami/containers/pull/35992. Let me check it with the team, I will keep this thread updated 🚀

**Comment by joancafom** [comment] 2023-07-04 15:55
Hi again! 

Just to inform you that a new version of the chart (`8.6.6`) has been released in https://github.com/bitnami/charts/pull/17471. Could you please confirm it addresses the issue?

**Comment by joancafom** [comment] 2023-07-05 10:18
The issue should be addressed by now:

```console
$ helm install redis-cluster oci://registry-1.docker.io/bitnamicharts/redis-cluster --set usePassword=false
NAME: redis-cluster
...
CHART VERSION: 8.6.6

$ k get pods
NAME              READY   STATUS    RESTARTS      AGE
redis-cluster-0   1/1     Running   2 (3m34s ago)   4m43s
redis-cluster-1   1/1     Running   1 (3m31s ago)   4m43s
redis-cluster-2   1/1     Running   1 (3m31s ago)   4m43s
redis-cluster-3   1/1     Running   1 (3m40s ago)   4m43s
redis-cluster-4   1/1     Running   3 (4m12s ago)   4m43s
redis-cluster-5   1/1     Running   1 (3m32s ago)   4m43s

```

Thanks everyone for the report!

**Closed by joancafom** 2023-07-05 10:18 UTC
Labels: in-progress, tech-issues, redis-cluster

**Comment by mojixcoder** [comment] 2023-07-05 10:34
Thanks for fixing the issue.
