### ISSUE TITLE
[bitnami/postgresql] cannot create regular file '/opt/bitnami/postgresql/conf/postgresql.conf': Permission denied

### ISSUE THREAD

**Issue by alemorcuq** [bitnami/charts#1780] opened 2019-12-27 08:49 UTC
_Originally posted by @kpirateone in https://github.com/bitnami/charts/issues/1722#issuecomment-569074303_

```
postgresql 14:06:32.20
postgresql 14:06:32.20 Welcome to the Bitnami postgresql container
postgresql 14:06:32.21 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 14:06:32.22 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 14:06:32.22 Send us your feedback at containers@bitnami.com
postgresql 14:06:32.22
postgresql 14:06:32.26 INFO  ==> ** Starting PostgreSQL setup **
postgresql 14:06:32.41 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 14:06:32.42 INFO  ==> Loading custom pre-init scripts...
postgresql 14:06:32.43 INFO  ==> Initializing PostgreSQL database...
postgresql 14:06:32.46 INFO  ==> postgresql.conf file not detected. Generating it...
cp: cannot create regular file '/opt/bitnami/postgresql/conf/postgresql.conf': Permission denied
```

 I am overriding the the following inputs - everything else is from the base Values.yml:
image.tag=9.6.16-debian-9-r26
volumePermissions.securityContext.runAsUser=1001
volumePermissions.enabled=true

using postresql chart 8.0.0.

also, just to note that the init-chmod-data does not complete without a small hack which could be representative of the problem, basically i add a command at the end of the init-chmod-data script so that the  init container completes successfully, otherwise the init-chmod-data does not complete:

```
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p /bitnami/postgresql/data
              chmod 700 /bitnami/postgresql/data
              find /bitnami/postgresql -mindepth 0 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | \
                xargs chown -R 1001:1001
              chmod -R 777 /dev/shm
              ls -al
```
init-chmod-data ouput:

> chown: changing ownership of '/bitnami/postgresql/lost+found': Operation not permitted
> chown: changing ownership of '/bitnami/postgresql': Operation not permitted
> chmod: changing permissions of '/dev/shm': Operation not permitted

**Comment by alemorcuq** [comment] 2019-12-27 08:55
Hi, @kpirateone.

Can you try again without overriding `volumePermissions.securityContext.runAsUser`? That way the init container will be run as `root` and will be able to modify the permissions of the files in the volume.

**Comment by kpirateone** [comment] 2019-12-27 13:02
> Hi, @kpirateone.
> 
> Can you try again without overriding `volumePermissions.securityContext.runAsUser`? That way the init container will be run as `root` and will be able to modify the permissions of the files in the volume.

The issue is that our environment does not allow containers (even init-containers) to run as root.  do you think this is the issue?  its odd that there is an option to run as user (volumePermissions.securityContext.runAsUser) if you need to run as root for it to work.

**Comment by marcosbc** [comment] 2019-12-30 15:49
Hi @kpirateone, that is probably going to cause issues.

In your case, would a non-root user have permissions to create files/directories inside the volume? If not, what would be the approach? 

Since the `chown` failes, our understanding is that it would not be possible in your scenario without allowing for `root`-run init containers for fixing the permissions.

**Comment by zendril** [comment] 2020-01-13 17:06
In most kubernetes installations (especially multi-tenant ones) it is best practice to run all containers as non-root. 

See: [Kubernetes.io How not to get hacked](https://kubernetes.io/blog/2018/07/18/11-ways-not-to-get-hacked/#8-run-containers-as-a-non-root-user)

Also to note, bitnami themselves have an article linked from there about the work they have done to enable non-root running on k8s platforms: [Bitnami Engineering](https://engineering.bitnami.com/articles/running-non-root-containers-on-openshift.html)

What needs to happen is that these directories are created and owned to the proper non-root user (like postgres, or nobody) at the time the image itself is created.

**Comment by marcosbc** [comment] 2020-01-28 22:50
@zendril Ideally all containers should run as root user, however, in some cluster configurations the persistent volumes don't have write-privileges for the non-root user.

In this specific scenario, running a sidecar root container to fix the permissions is the only approach to be able to write to the volume, unless you can configure such settings during its deployment but this isn't always supported (i.e. using NFS). This container exclusively runs commands with the sole purpose of changing permissions and ownership of files inside of it, and although not ideal, there isn't any alternative to it so in the end you're forced to support root-run containers (unless there is an option to configure user/group ownership for the volume during deployment).

What I'm wondering in @kpirateone's case is how non-root users can actually write to those volumes in the current cluster configuration, as we assume it is correct and they do have other applications and services using persistent volumes.

**Comment by kpirateone** [comment] 2020-01-29 15:50
In the end modified (created my own image with the appropriate permissions)

`
FROM <container registry>/bitnami/postgresql:9.6.15-debian-9-r77
USER 0
RUN groupadd --gid 1001 postgresql && useradd --uid 1001 --gid 1001 postgresql
RUN chown -R 1001:1001 /opt/bitnami/postgresql
USER 1001
`

this addressed the original issue.

and I will likely, since im in there, add the init-chmod-data commands to this customer container as well since this init container cannot run as root

**Comment by zendril** [comment] 2020-01-30 01:16
@marcosbc I believe what @kpirateone has done is the right approach and is what should be done for the base container itself.

The 1001 user and group should be added to the system, the dir should be owned to that user and then the container should run as that user.

That should be the default way of running it.

Are you saying there is a scenario/reason this shouldn't be done?

**Comment by marcosbc** [comment] 2020-01-31 14:04
@zendril The main reason for this is supporting OpenShift, which runs containers with a random uid. This also adds some additional security in the sense that you cannot escalate to another user with more privileges (i.e. `su` does not work so you cannot switch users).

When running a container with a non-existent UID, you automatically belong to the root group and therefore there is an easy way to add read and write permissions (supposing they belong to `root:root`):

```
chmod -R g+rwX /path/to/dir-or-file
```
_____

Aside from this, I just noticed that @kpirateone is using PostgreSQL container `9.6.16-debian-9-r26`. Lots of improvements have been made since, including a recent bugfix that was affecting very specific permissions issue on certain kernel/OS configurations (see https://github.com/bitnami/bitnami-docker-postgresql/issues/192#issuecomment-579947295). We recommend you to check out the latest release in the 9.6 branch (`9.6.16-debian-10-r6`) as it could fix your issues.

**Comment by hytromo** [comment] 2020-03-24 13:32
I am getting a very similar issue, using postgresql-ha chart version 1.4.12 (the latest as of now AFAIK). My cluster is on GKE.

```
> kubectl logs psql-postgresql-ha-postgresql-0
postgresql-repmgr 13:19:05.85 
postgresql-repmgr 13:19:05.95 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 13:19:06.05 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 13:19:06.15 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 13:19:06.15 Send us your feedback at containers@bitnami.com
postgresql-repmgr 13:19:06.25 
postgresql-repmgr 13:19:06.45 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
repmgr 13:19:08.75 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql 13:19:08.85 INFO  ==> Validating settings in POSTGRESQL_* env vars..
repmgr 13:19:09.05 INFO  ==> Querying all partner nodes for common upstream node...
repmgr 13:19:10.45 INFO  ==> There are no nodes with primary role. Assuming the primary role...
repmgr 13:19:10.75 INFO  ==> Preparing PostgreSQL configuration...
postgresql 13:19:10.94 INFO  ==> postgresql.conf file not detected. Generating it...
cp: cannot create regular file '/bitnami/postgresql/conf/postgresql.conf': Permission denied
postgresql 13:19:13.18 INFO  ==> Stopping PostgreSQL...
```

This is triggered when I add options to `postgresql.extendedConf` and not triggered when it's left unspecified.

So, if `postgresql.extendedConf` is **not** specified, then pods start normally. If I get a bash prompt inside the pod and run stuff as the simple 1001 user, I don't have problems writing in there:

```
postgresql-repmgr@psql-postgresql-ha-postgresql-0:/$ echo $UID
1001
postgresql-repmgr@psql-postgresql-ha-postgresql-0:/$ cd bitnami/postgresql/conf/
postgresql-repmgr@psql-postgresql-ha-postgresql-0:/bitnami/postgresql/conf$ echo canIWrite > test
postgresql-repmgr@psql-postgresql-ha-postgresql-0:/bitnami/postgresql/conf$ cat test
canIWrite
postgresql-repmgr@psql-postgresql-ha-postgresql-0:/bitnami/postgresql/conf$
```

which I find weird.

Making `volumePermissions.enabled` true did not help.

**Comment by marcosbc** [comment] 2020-03-25 16:15
Hi @hytromo, thank you for reporting this.

We were finally able to reproduce this issue, the key was `postgresql.extendedConf` which was not working even with `volumePermissions.enabled` set to true.

I've created a couple of PRs at #2140 and #2141, which fixes the issues for `bitnami/postgresql-ha` and `bitnami/postgresql` respectively. Hopefully they will be merged by tomorrow.

**Closed** 2020-03-30 14:55 UTC

**Comment by marcosbc** [comment] 2020-03-30 14:57
@hytromo We just merged the changes that should fix this issue.
