### ISSUE TITLE
[bitnami/zookeeper] readinessProbe and livenessProbe failed after enable Zookeeper TLS

### ISSUE THREAD

**Issue by shenqinb** [bitnami/charts#4811] opened 2020-12-22 06:47 UTC
**Which chart**:
[bitnami/zookeeper]: 6.2.0

**Describe the bug**
After enabling Zookeeper TLS, the livenessProbe and readinessProbe failed, the zookeeper Pod keep READY=0/1, but the Pod is actually working which can be connected via zkCli.  currently it works well after I disable the livenessProbe and readinessProbe. 

**Screen Shut for Pods status:**
![image](https://user-images.githubusercontent.com/5157526/102857493-7b899f80-4463-11eb-885e-2f58f1d3043b.png)

**Output of describing a Pod (kubectl describe pod zookeeper-0 -n zookeeper):**
![image](https://user-images.githubusercontent.com/5157526/102857581-a83db700-4463-11eb-8eb4-a97fc93d8c2e.png)

**TLS configurations in values.yaml:**
```
service:
  type: ClusterIP
  port: 2181
  followerPort: 2888
  electionPort: 3888
  publishNotReadyAddresses: true
  tls:
    client_enable: true
    quorum_enable: true
    disable_base_client_port: true

    client_port: 3181

    client_keystore_path: path/zookeeper-keystore.p12
    client_keystore_password: ****************
    client_truststore_path: path/zookeeper-truststore.jks
    client_truststore_password: ******************

    quorum_keystore_path: path/zookeeper-keystore.p12
    quorum_keystore_password: ******************
    quorum_truststore_path: path/zookeeper-truststore.jks
    quorum_truststore_password: ******************
  annotations: {}
  headless:
    annotations: {}
```

**livenessProbe and readinessProbe configurations in values.yaml:**
```
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  probeCommandTimeout: 5

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
  probeCommandTimeout: 5
```

**Comment by rafariossaa** [comment] 2020-12-22 18:55
Hi,
  I am not sure but I think that zookeeper is not using the certs files and hence not starting in a TLS mode.
  Could you put a long liveness and readiness timeout and check that the certs files and in place and run the liveness command by hand ?.

**Comment by shenqinb** [comment] 2020-12-23 02:49
@rafariossaa thanks for your quick reply, 
1. I have increased to 30s and 60s,  it still failed
2. I run the  thee command inside the Pod, it returned as expected.

**Comment by rafariossaa** [comment] 2020-12-23 10:59
OK,
  I think that the problem is that the CA for the certificate is not included in the default CA certs. 
  Could you run the following command ? I am interested in checking which CA is used.
```
openssl s_client - -connect localhost:3181 -showcerts
```

It should return something similar to this other test:
```
openssl s_client -connect www.google.com:443 -showcerts                    
CONNECTED(00000003)
depth=2 OU = GlobalSign Root CA - R2, O = GlobalSign, CN = GlobalSign
verify return:1
depth=1 C = US, O = Google Trust Services, CN = GTS CA 1O1
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google LLC, CN = www.google.com
verify return:1
---
...
```

**Comment by shenqinb** [comment] 2020-12-24 02:16
@rafariossaa Hi, we are using self-signed CA, below are the output of the command:
```
CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 C = US, OU = IBM, CN = MROIO-ZOOKEEPER-K8S-OPS
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = US, OU = IBM, CN = MROIO-ZOOKEEPER-K8S-OPS
verify error:num=21:unable to verify the first certificate
verify return:1
139983509345408:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../ssl/record/rec_layer_s3.c:1544:SSL alert number 42
---
Certificate chain
 0 s:C = US, OU = IBM, CN = MROIO-ZOOKEEPER-K8S-OPS
   i:CN = maximomro.ibm-ca
-----BEGIN CERTIFICATE-----
******************************************
******************************************
******************************************
-----END CERTIFICATE-----
---
Server certificate
subject=C = US, OU = IBM, CN = MROIO-ZOOKEEPER-K8S-OPS

issuer=CN = maximomro.ibm-ca

---
Acceptable client certificate CA names
CN = maximomro.ibm-ca
Client Certificate Types: ECDSA sign, RSA sign, DSA sign
Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:DSA+SHA256:ECDSA+SHA224:RSA+SHA224:DSA+SHA224:ECDSA+SHA1:RSA+SHA1:DSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:DSA+SHA256:ECDSA+SHA224:RSA+SHA224:DSA+SHA224
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1462 bytes and written 421 bytes
Verification error: unable to verify the first certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 25FF2F834F3356914998FA96702DCBA04CAFCAC8BECD6B46BF5871AEB89489EE
    Session-ID-ctx: 
    Master-Key: F3EFDA3D228FD29B424F337D44772113BDCB5C90BED873A410D2CBB012DF09CFB82217C9A826E6BB5B8AF973D7A5E591
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1608775997
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: yes
---
```

**Comment by rafariossaa** [comment] 2020-12-28 10:53
HI,
  Thanks for sharing.
  The issue is that the `openssl` command in the tests is failing because it can not find the CA for the certificate. 
  I am opening a internal task to look for a fix for this.

**Comment by shenqinb** [comment] 2021-01-04 03:07
@rafariossaa, Thank you for your support.

**Comment by fksimon** [comment] 2021-03-22 17:28
FYI we ran into the same problem with TLS enabled.    The solution appears to be to tweak the openssl call used by the health checks.   If I manually specify the cert and key it works, otherwise I get the same error as originally reported.

echo "ruok" | openssl s_client -crlf -quiet -connect localhost:3181 -cert /tls_client_key/tls.crt -key /tls_client_key/tls.key  2>/dev/null

**Comment by fksimon** [comment] 2021-03-22 17:35
As a note we hit this issue with 5.23.0 and 6.5.2

The current failures in TLS mode are caused by the health check. The new chart will run either a openssl or a nc health check designing on the value of zookeeper.service.tls.disable_base_client_port.

If this is set to true it runs below against the 3181 TLS port. This check is failing with a certificate error

```
echo "ruok" | timeout 2 openssl s_client -quiet -crlf -connect localhost:3181 | grep imok
```

If this is set to false it runs against the 2181 non-TLS port. Everything works as expected. The only issue here is the 2181 port is exposed for client usage.

```
echo "ruok" | timeout 2 nc -w 2 localhost 2181 | grep imok
```

Below is the certificate error that the health check gets:
```
echo "ruok" | timeout 2 openssl s_client -quiet -crlf -connect localhost:3181 | grep imok
Can't use SSL_get_servername
depth=0 CN = fran-zookeeper-2
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = fran-zookeeper-2
verify error:num=21:unable to verify the first certificate
verify return:1
139975603790976:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../ssl/record/rec_layer_s3.c:1544:SSL alert number 42
```

**Comment by rafariossaa** [comment] 2021-03-23 16:37
Hi @fksimon 
  Thanks for providing your ideas.
  I am adding these to the internal task.

**Closed** 2021-03-30 09:11 UTC
Labels: on-hold

**Comment by alvneiayu** [comment] 2021-03-30 09:16
Hi @shenqinb

I included a change fixing the problem. This change provides two new values that you can set up in your own values.yaml. Those new values allow you to set up the path of the pem files inside the container to execute the liveness and readiness probes. Example:

```
service:
    client_key_pem_path: /tls_key_store/key.pem
    client_cert_pem_path: /tls_key_store/cert.pem
```

Let me know if you still have problems.

Thanks for your help and your time

Álvaro
