### ISSUE TITLE
DAGs are not running

### ISSUE THREAD

**Issue by Jagadeepkosuri** [bitnami/charts#6369] opened 2021-05-14 12:04 UTC
**Which chart**:
Airflow 8.0.4

**Describe the bug**
When i try to run the DAGs using K8s Executor , I get the below error

![image](https://user-images.githubusercontent.com/25528123/118264684-adb0a200-b4d5-11eb-8ac2-4632ae6a651a.png)
 

New worker pods which are created are terminated showing Error. The last line says `"dag_id could not be found. Either the dag did not exist or it failed to parse"`. I'm not sure why this error comes. I have given the volumeMounts and volumes path to worker pods also (specified in the templates/config/config.yaml volumeMounts and volumes) . 

![image](https://user-images.githubusercontent.com/25528123/118267478-c458f800-b4d9-11eb-9bd1-cc01f43eef19.png)

In the above picture, DAG marked green is an independent DAG and it runs succesfully. 

And all the other DAGs are linked. DAG marked in red color is the main DAG, once that red DAG is triggered all the other DAGs  will run behind. When i trigger this red DAG, I get the above error like `"dag_id could not be found. Either the DAG did not exist or it failed to parse"`

**To Reproduce**
Same as above.

**Expected behavior**
This DAG also should run . 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Helm3
```

- Output of `kubectl version`:

```
K3s 1.20
```

**Additional context**

**Comment by marcosbc** [comment] 2021-05-14 15:31
Duplicate of #6362

**Closed by marcosbc** 2021-05-14 15:31 UTC

**Comment by Jagadeepkosuri** [comment] 2021-05-15 10:55
@marcosbc I would like this issue to be reopened. Because the other duplicate issues is not clear. This one seems to be more precise and understandable.

**Comment by javsalgar** [comment] 2021-05-17 08:04
Hi,

Could you provide a repsoitory with the DAGs so we can use for reproducing the issue. A minimal example that triggers the issue should work.

**Comment by Jagadeepkosuri** [comment] 2021-05-17 09:23
> Hi,
> 
> Could you provide a repsoitory with the DAGs so we can use for reproducing the issue. A minimal example that triggers the issue should work.

This is the repository https://github.com/Jagadeepkosuri/test/tree/master (check in master branch) . It has dags, custom plugins and additional python packages to be installed in requirements.txt 
I'm putting dags under /opt/bitnami/airflow/dags, plugins under /opt/bitnami/airflow/plugins

I'm mounting azure fileshares containing dags and plugins to my pods at the above mentioned dags and plugins  folder. 

airflow_benchmark_dag and add_airflow_variables_and_connections are running as expected. But the dag demo_delta_data_ingestion_to_order_items_job is not running as expected (we cannot find any logs also under the logs section in UI ). What i understood from the above error (dag_id couldn't be found is , tasks are itself not starting)

**Comment by Jagadeepkosuri** [comment] 2021-05-17 09:53
> Hi,
> 
> Could you provide a repsoitory with the DAGs so we can use for reproducing the issue. A minimal example that triggers the issue should work.

Can it be because of  missing python packages. I have logged into one of the running worker pod and checked if all my packages in requirements.txt are installed or not. But, they were not installed. 

How can we install the packages in requirements.txt to the dynamically spinned up pods?

**Comment by javsalgar** [comment] 2021-05-18 08:29
Hi,

You should mount a requirements.txt in `/bitnami/python/`, as the container logic shows

https://github.com/bitnami/bitnami-docker-airflow/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/airflow/entrypoint.sh#L28


In order to do so, you could use the extraVolumes and extraVolumeMouns section of the chart. Another option could be to override the default container command so it executes the proper pip install and then launches `/entrypoint.sh /run.sh`. Would that work for your case?
