### ISSUE TITLE
Error: Your previous request to create the named bucket succeeded and you already own it

### ISSUE THREAD

**Issue by sa-cloud** [bitnami/charts#1387] opened 2019-09-03 08:06 UTC
I used the bitnami minio helm chart to install minio on Openshift cluster v1.11 (Openshift 3.11). Minio worked as expected, untill there was a restart to the pod for some reason. After the pod restarted it keeps failing and restarting constantly. The log is this:
```
Welcome to the Bitnami minio container
  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-minio
  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-minio/issues
  | Send us your feedback at containers@bitnami.com
  |  
  | INFO ==> ** Starting MinIO setup **
  | INFO ==> Starting MinIO in background...
  | INFO ==> Adding local Minio host to 'mc' configuration...
  | Added local successfully.
  | INFO ==> Creating default buckets...
  | mc: Unable to make bucket local/icptest. Your previous request to create the named bucket succeeded and you already own it.
  | INFO ==> Stopping MinIO...
  | Stopped local successfully.
```
icptest is the name of my default bucket.

**Comment by javsalgar** [comment] 2019-09-04 08:46
Hi,

I see what the issue is. I think we should add a check whether the bucket already exists or not. I will create a task for it.

**Comment by javsalgar** [comment] 2019-09-04 08:49
For the time being, what you can do is set the env var `MINIO_SKIP_CLIENT` to yes

**Comment by javsalgar** [comment] 2019-09-09 10:02
Hi. Just a quick note to let you know that a new revision of the container was released.

https://github.com/bitnami/bitnami-docker-minio/commit/23109dcd6f0cc1b0d8f9700d6689909e3e613628

**Comment by javsalgar** [comment] 2019-09-09 10:11
Chart updated as well 

https://github.com/bitnami/charts/commit/c6ceb861b98060b4729bfc7253f02763e48231ea

Closing the issue

**Closed by javsalgar** 2019-09-09 10:11 UTC

**Comment by sa-cloud** [comment] 2019-09-09 12:21
Hi, thanks for the quick response, just another question:
