### ISSUE TITLE
[bitnami/rabbitmq] After deleting release nd then re-installing the pods never get past "Waiting for Mnesia tables"

### ISSUE THREAD

**Issue by zenbones** [bitnami/charts#3783] opened 2020-09-25 21:53 UTC
Chart: 7.6.8

rabbitmq:
  service:
    type: NodePort
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: gp2
    accessMode: ReadWriteOnce
    size: 2Gi
  resources:
    limits:
      cpu: 1000m
      memory: 2048M

Always works the first time. After shut down and restart works about half the time, the other half never restarts due to the waiting error on the db.

**Comment by andresbono** [comment] 2020-09-28 14:38
Hi @zenbones, where do you find the error? Do you find it in the container logs? Can you share the specific message?

**Comment by kristinnardal2** [comment] 2020-09-29 10:26
This sounds like an issue with persistent volumes, I've run into this a few times, try deleting the old PVCs and then reinstalling.

**Comment by andresbono** [comment] 2020-09-30 08:13
It might be the cause of the issue, @kristinnardal2. Thanks for pointing out.

**Comment by maxisam** [comment] 2020-10-20 21:24
It seems like it can be solved by force boot

https://github.com/helm/charts/pull/14149

This is a very annoying issue. It shows up every now and then.

#3974 #3697  #3074  #2868

**Comment by javsalgar** [comment] 2020-10-21 07:35
Hi,

Looking at the cases, I see that several times the persistent volumes are the cause of the issue. We test the persistent storage providers of major Kubernetes distributions and we do not see that issue. Could you provide more details about the persisent volumes you are using?

**Comment by maxisam** [comment] 2020-10-21 16:21
I use longhorn but I don't think that is the problem. It is kinda odd you can't reproduce it because it is a common issue on both helm chart repo. Did you try to shut down the nodes without draining them first? I don't have this issue until I accidently shut down the nodes.

**Comment by javsalgar** [comment] 2020-11-09 08:59
By shutting down the nodes, you mean the k8s nodes or the rabbitmq nodes?

**Comment by maxisam** [comment] 2020-11-09 21:05
> By shutting down the nodes, you mean the k8s nodes or the rabbitmq nodes?

K8S. like unexpected shut down

**Comment by javsalgar** [comment] 2020-11-10 08:59
Hi,

I've been unable to reproduce the issue. Which is your Kubernetes setup so we can try mimicking it.

**Comment by maxisam** [comment] 2020-11-10 15:05
Well, it is an issue existing in 2 repos and multiple people reported it already. So I am pretty sure it is there. 

I used Rancher to create the cluster and use Longhorn for storage. I have 3 rabbit nodes with HA policy

```json
        "policies": [
          {
            "vhost": "/",
            "name": "HA",
            "pattern": "^(?!amq\\.).*",
            "apply-to": "all",
            "definition": { "ha-mode": "all", "ha-sync-mode": "automatic" },
            "priority": 0
          }
        ]
```

**Comment by mltsy** [comment] 2020-11-10 19:33
I'm having the same issue.  My setup is:

Kubernetes platform: GKE
Kubernetes master version: 1.15.12-gke.20
PersistentVolume type: Google Compute Engine persistent disk
Chart version: 7.7.1

I'm using Terraform's [helm provider](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release) to deploy this chart to the cluster.

**Steps to reproduce:**
1. Deploy the chart (values.yaml below)
2. Destroy and recreate the release:
    - I'm not sure how the TF helm provider implements this, but I assume it's just a `helm delete` followed by a `helm create`

After this, I can see that not only the old volumes, but also the old PVCs still exist in the K8s cluster.  I'm not sure whether this normal or part of the problem.  But in any case, this is the error I get over and over until the container restarts:

```
Error while waiting for Mnesia tables:
  {timeout_waiting_for_tables,
    ['rabbit@rabbitmq-2.rabbitmq-headless.rabbitmq.svc.cluster.local','rabbit@rabbitmq-1.rabbitmq-headless.rabbitmq.svc.cluster.local','rabbit@rabbitmq-0.rabbitmq-headless.rabbitmq.svc.cluster.local'],
    [rabbit_durable_queue]
  }
```

I wonder... do I need to define `persistence.existingClaim` for this to work?

**values.yaml**
```yaml
image:
  tag: "3.8.9"
replicaCount: 3

rabbitmq:
  loadDefinition:
    enabled: true
    existingSecret: load-definitions
  extraConfiguration: |
    management.load_definitions = /app/load_definitions.json
    vm_memory_high_watermark.relative = 0.6
    vm_memory_high_watermark_paging_ratio = 0.75
    total_memory_available_override_value = 2000MiB
    disk_free_limit.absolute = 1GiB
persistence:
  size: 6Gi
resources:
  requests:
    memory: 2000Mi
    cpu: 300m
  limits:
    memory: 2000Mi
    cpu: 500m
pdb:
  create: true
```

**Comment by mltsy** [comment] 2020-11-10 19:34
I wonder... do I need to define `persistence.existingClaim` for this to work?

Or perhaps the `erlangCookie` or something else, given that it's trying to use the old persistent volumes?

**Comment by mltsy** [comment] 2020-11-10 22:50
Oh wow - actually adding a static erlangCookie solved the problem for me!  I guess this makes sense - I just wasn't clear on the importance of the erlangCookie until now.  According to [the RabbitMQ docs](https://www.rabbitmq.com/clustering.html#erlang-cookie):

"For two nodes to be able to communicate they must have the same shared secret called the Erlang cookie. [...] It is usually stored in a local file."

If this is the same problem others are having, it might be worthwhile to add a bit to the documentation of the `auth.erlangCookie` attribute indicating that it should be set manually if you want to be able to recover from server deletion/failure using the same data volumes you started with.

I guess I'm not sure whether this also applies to release upgrades or not - I haven't gotten that far yet... ??

**Comment by andresbono** [comment] 2020-11-11 15:15
Hi @mltsy, thanks for shedding some light on this issue!!

@maxisam, can you try to specify a static erlangCookie and let us know about the results of your testing?

**Comment by maxisam** [comment] 2020-11-11 15:32
@andresbono yeah, I will test that some time this week. Thx @mltsy !

**Comment by maxisam** [comment] 2020-11-11 15:49
@mltsy @andresbono I just realized I did set existingErlangSecret before. So no, this solution doesn't fix my issue.

**Comment by mltsy** [comment] 2020-11-11 21:48
@maxisam and are you sure that secret is the same one used when the original release was created? Or is it possible it was deleted along with the release and reinitialized with the new one or something?

**Comment by maxisam** [comment] 2020-11-13 03:29
I am sure. I have used that secret for couple times. It is not my first time to tear down and rebuild. But somehow it was the first time it didn't work. I think it might have something to do with the policies I set. I didn't have that before. But I can't be sure either.

**Comment by javsalgar** [comment] 2020-11-13 08:58
Which policies did you set in the cluster?

**Comment by maxisam** [comment] 2020-11-13 14:37
https://github.com/bitnami/charts/issues/3783#issuecomment-724760680

**Comment by maxisam** [comment] 2020-11-16 15:11
@andresbono I did bump into the same account issue as well

**Comment by mltsy** [comment] 2020-11-16 18:30
@andresbono my `load_definiteions.json` file looks like this:
```
{
  "users":
    [
      {
        "name": "username",
        "password": "password",
        "tags": "administrator"
      }
    ],
  "vhosts": [
    {
      "name": "/"
    },
    {
      "name": "ss-queue"
    }
  ],
  "permissions": [
    {
      "user": "username",
      "vhost": "/",
      "configure": ".*",
      "write": ".*",
      "read": ".*"
    },
    {
      "user": "username",
      "vhost": "ss-queue",
      "configure": ".*",
      "write": ".*",
      "read": ".*"
    }
  ]
}
```

(The users block is actually dynamically generated, but it comes out looking something like that)

Two other causes I encountered while resolving this issue myself that resulted in the same issue:
1. A new password being generated, so the erlang secret was static, but the password wasn't.
2. A Kubernetes pod was in an error state, so even after I fixed the problem, when I tried to upgrade the chart, it wouldn't deploy because one pod was stuck in a retry-loop and had to be deleted before there was a pod available to begin the upgrade.

**Comment by the-redback** [comment] 2020-11-30 09:55
Changing the readiness probe command solved my problem,

```yaml
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -ec
              - rabbitmq-diagnostics -q ping
```

Also, there is another workaround (without touching the readiness probe manually),  if this is not a fresh install but other nodes are unavailable,
1. Install with readiness probe disabled
2. Once all the nodes are up and running, run `helm upgrade` command with readiness probe enabled.

Here, 'not fresh' means, pvc or pv already exists.

**Comment by javsalgar** [comment] 2020-11-30 10:06
Hi,

Thanks for the input. Do you think it makes sense to change the default probes to `rabbitmq-diagnostics -q ping`?

**Comment by the-redback** [comment] 2020-11-30 10:12
I got the probe command from their website. https://www.rabbitmq.com/monitoring.html#readiness-probes 

As the liveness probe already checks for `check_running`, the readinesss probe should be simple as 'ping'.
But, if there is another valid way to bypass this deadlock situation, that will be better I guess.

**Comment by mltsy** [comment] 2020-11-30 17:37
This readiness probe seems to bypass the deadlock issue, right? (`rabbitmq-diagnostics -q ping`)

Since it's documented, and avoids the issue, it seems like a good default!  I guess the documentation recommends this check for cases where the node may be "waiting for a peer to sync schema from".  I'm assuming that may be the case for... all clustered nodes...?  But I'm not totally sure I understand (maybe there are some cases where a "master node" doesn't need to wait for peers to sync)  In any case, it seems like using the `check_running` health check is likely the cause of the deadlock issue, if and when there are nodes that need to wait for peers to boot in order to sync schemas.

**Comment by javsalgar** [comment] 2020-12-01 09:48
Hi,

Thanks for the info. We will work on changing the probe. If you want to speed up the process feel free to send a PR and we will review it :D

**Comment by javsalgar** [comment] 2020-12-03 14:06
Hi,

Could you please check this PR? Per the conversation, this is what we're looking for, right?

https://github.com/bitnami/charts/pull/4598

**Closed** 2020-12-04 10:13 UTC

**Comment by mltsy** [comment] 2020-12-09 22:02
I actually looked into this more, and I think changing the default here is not advisable.  Theoretically, the situation where you might get into a deadlock is an exceptional one where the nodes shutdown unexpectedly and are not able to reassign masters appropriately.  See my comments on https://github.com/bitnami/charts/pull/4598 for details.

I think there just needs to be some documentation about how to start up a cluster after it was shut down improperly, or for some other reason is running into a waiting-to-sync deadlock. (Which is by adding the custom Readiness probe mentioned above, or possibly setting the new parameter flag I proposed in https://github.com/bitnami/charts/pull/4598

**Comment by andresbono** [comment] 2020-12-11 10:22
Hi @mltsy, thanks for raising your concerns. It seems they are being discussed in #4598.

**Comment by razvanphp** [comment] 2024-04-13 15:31
> Oh wow - actually adding a static erlangCookie solved the problem for me! I guess this makes sense - I just wasn't clear on the importance of the erlangCookie until now. According to [the RabbitMQ docs](https://www.rabbitmq.com/clustering.html#erlang-cookie):
> 
> "For two nodes to be able to communicate they must have the same shared secret called the Erlang cookie. [...] It is usually stored in a local file."
> 
> If this is the same problem others are having, it might be worthwhile to add a bit to the documentation of the `auth.erlangCookie` attribute indicating that it should be provided a known value if you want to be able to recover from server deletion/failure using the same data volumes you started with (i.e. if you don't want to lose all your data!)
> 
> I guess I'm not sure whether this also applies to release upgrades or not - I haven't gotten that far yet... ??

I also got into this problem after a server reset. My cluster had 3 replicas.

But... do we really need to add the cookie in `values.yaml` given that the chart by default uses a Secret to store it? It should be common then, right?

https://github.com/bitnami/charts/blob/94ce52ab08a89a7881e8d443f153e284a3f65229/bitnami/rabbitmq/templates/statefulset.yaml#L221-L225

In my case, I tried to add `podManagementPolicy: Parallel`

and got this:
```
helmrelease/rabbitmq	12.15.0 	False    	False	Helm upgrade failed for release vampirebyte/rabbitmq with chart rabbitmq@12.15.0: cannot patch "rabbitmq" with kind StatefulSet: StatefulSet.apps "rabbitmq" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

but probably this is something specific to TrueNAS k3s.

Very strange and worrying that the cluster can just get corrupted like this only after one server reboot....
