### ISSUE TITLE
Bitnami Spark Enabling Metrics

### ISSUE THREAD

**Issue by gkulkarni32** [bitnami/charts#4429] opened 2020-11-19 10:04 UTC
**Which chart**:
bitnami/spark

**Is your feature request related to a problem? Please describe.**
Currently the bitnami helm chart does not support enabling metrics. I did not find any option to enable the metrics exporters. Can we have this added to the spark chart

**Describe the solution you'd like**
Add the option in the values.yaml to enable metrics exporters and have the metrics emiting to a prometheus endpoint. We can then scrape the prometheus endpoint to collect the metrics to wavefront etc. 

**Describe alternatives you've considered**

**Additional context**

**Comment by marcosbc** [comment] 2020-11-19 16:16
Hi @gkulkarni32, thanks for the suggestion!

I agree, it would be great to add support for Monitoring in the Bitnami Kafka container image. I've created an internal task for evaluating it.

Do you have any particular exporter in mind? Or were you thinking about https://github.com/banzaicloud/spark-metrics?

**Comment by gkulkarni32** [comment] 2020-11-20 03:27
Hi @marcosbc 
Thanks for your response. I do not have any exporters in mind. But I tried the helm chart - `incubator/sparkoperator` which enables the metrics by default. 

Thanks
Geeta

**Comment by marcosbc** [comment] 2020-11-20 15:26
Thanks for sharing! I'll add those notes to our internal task.

We'll keep you posted with any progress.

**Comment by rafariossaa** [comment] 2020-12-03 09:33
Hi,
  I added some needed changes to the spark image to configure and expose the metrics. 
  I have some changes for the chart that I am testing in our development environment, so if all goes well it could be released soon.
  I will update this thread with the progress.

**Comment by rafariossaa** [comment] 2020-12-03 17:15
Hi,
  I have just sent a PR to enable the metrics.
  Let's wait for the reviewing process and then we will merge it

**Comment by rafariossaa** [comment] 2020-12-04 14:42
Hi,
  I have just merged the chart PR.
  Could you give it a try ?

**Comment by gkulkarni32** [comment] 2020-12-07 04:12
@rafariossaa Thank you, let me try this today and get back.

**Comment by gkulkarni32** [comment] 2020-12-07 06:35
Hi @rafariossaa I was trying to test this out. Few observations: 
1. When I did `helm pull bitnami/spark`, I dont see the updated README.md and the updated values.yaml/values-production.yaml. 
2. Also, I ran `helm install dp bitnami/spark -n spark-operator --set image.registry=harbor-repo.vmware.com/dockerhub-proxy-cache --set image.repository=gkulkarni32/custom-bitnami-spark --set image.tag=v15 --set service.type=LoadBalancer --set metrics.enabled=true` without doing helm pull, but the metrics did not get enabled. Is there anything I'm missing? 

Thanks
Geeta

**Comment by beltran-rubo** [comment] 2020-12-07 07:45
Hi Geeta, there is an issue in the pipeline we are working on and the new tgz is not in the Helm repository yet. Could you please try those changes from the source code itself? We are working on fixing this to make it available the latest version in the Helm repository.

**Comment by gkulkarni32** [comment] 2020-12-08 03:03
Thanks Beltran. I installed the chart from the github source code. It worked fine and I'm able to see the metrics from within the pod at 8080/8081 ports in master and worker nodes respectively. But when I configure the wavefront collectors for these endpoints, I get the below error: 

time="2020-12-08T03:01:45Z" level=error msg="reading text format failed: text format parsing error in line 1: invalid metric name"

Just wanted to check if you have faced this issue with the format with grafana?

**Comment by gkulkarni32** [comment] 2020-12-08 08:25
Hi, I ran the below command to install the helm chart: 

```helm install -n spark-operator --set image.registry=harbor-repo.vmware.com/dockerhub-proxy-cache --set image.repository=gkulkarni32/custom-bitnami-spark --set image.tag=v15 --set service.type=LoadBalancer --set metrics.enabled=true dp .```

I see the below specification in my master pod. 

```Name:         dp-spark-master-0
Namespace:    spark-operator
Priority:     0
Node:         gc-workers-nkbnw-7b4d8487b6-6qwd6/172.31.41.67
Start Time:   Tue, 08 Dec 2020 13:25:22 +0530
Labels:       app.kubernetes.io/component=master
              app.kubernetes.io/instance=dp
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=spark
              controller-revision-hash=dp-spark-master-6468dfdfd7
              helm.sh/chart=spark-4.2.1
              statefulset.kubernetes.io/pod-name=dp-spark-master-0
Annotations:  cni.projectcalico.org/podIP: 192.168.60.119/32
              cni.projectcalico.org/podIPs: 192.168.60.119/32
              kubernetes.io/psp: vmware-system-privileged
              prometheus.io/port: 8080
              prometheus.io/scrape: true
Status:       Running
IP:           192.168.60.119
IPs:
  IP:           192.168.60.119
Controlled By:  StatefulSet/dp-spark-master
Containers:
  spark-master:
    Container ID:   docker://0c1bbbbf6e063445fa8f945e1e42c1890f50a7d583e594dac76b94eeb94709f2
    Image:          harbor-repo.vmware.com/dockerhub-proxy-cache/gkulkarni32/custom-bitnami-spark:v15
    Image ID:       docker-pullable://harbor-repo.vmware.com/dockerhub-proxy-cache/gkulkarni32/custom-bitnami-spark@sha256:7131f434d262f98ad8cda6a23d6f3e047731c342ba8c796bc948e20b34ef660b
    Ports:          8080/TCP, 7077/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Tue, 08 Dec 2020 13:25:23 +0530
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8080/ delay=180s timeout=5s period=20s #success=1 #failure=6
    Readiness:      http-get http://:8080/ delay=30s timeout=5s period=10s #success=1 #failure=6
    Environment:
      SPARK_MODE:               master
      SPARK_METRICS_ENABLED:    true
      SPARK_DAEMON_MEMORY:      
      SPARK_MASTER_PORT:        7077
      SPARK_MASTER_WEBUI_PORT:  8080
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-q5g5c (ro)```

If I look at the values.yaml file, I see the below based on which we should have had the prometheus endpoint at port 9117 to scrape the metrics from, but i only see the web port 8080 annotation in the pod description. Due to this, I get the metrics only in html format, I dont see them in the prometheus format. Could you please help me in this?

Values.yaml config

```## Metrics configuration
##
metrics:
  enabled: true

  ## Prometheus metrics service parameters
  ##
  service:
    ## Metrics port
    ##
    port: 9117
    ## Annotations for the Prometheus metics service
    ##
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.port }}"

  ## Prometheus Service Monitor
  ## ref: https://github.com/coreos/prometheus-operator
  ##      https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
  ##
  podMonitor:
    ## If the operator is installed in your cluster, set to true to create a Service Monitor Entry
    ##
    enabled: false
    ## Specify the namespace in which the podMonitor resource will be created
    # namespace: ""
    ## Specify the interval at which metrics should be scraped
    ##
    # interval: 30s
    ## Specify the timeout after which the scrape is ended
    # scrapeTimeout: 10s

  masterAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "{{ .Values.master.webPort }}"

  workerAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "{{ .Values.worker.webPort }}"```

**Comment by juan131** [comment] 2020-12-08 16:02
Hi @gkulkarni32 !!

Juan Ariza here, core maintainer of the Bitnami charts repo.

First, let me tell you that we're still debugging the issue in the pipeline, and we should have the Spark chart released in the chart repository soon. Yesterday and today is a bank holiday where most of the team is based and hence, the delay addressing this.

Regarding the issue with the metrics.. The problem is not in the port (which is fine) but the prometheus endpoint (which is `/metrics/` instead of `metrics`, the final `/` is required). I fixed in this PR: https://github.com/bitnami/charts/pull/4647

Could you please pull the latest changes from master and give it a try? You should be able to access the metrics running:

```console
$ k port-forward dp-spark-master-0 8080:8080 &
$ curl http://127.0.0.1:8080/metrics/
```

**Comment by beltran-rubo** [comment] 2020-12-08 18:53
@gkulkarni32 version 4.2.2 is now available into the Helm repository.

**Comment by gkulkarni32** [comment] 2020-12-09 05:01
Thanks @juan131  and @beltran-rubo for your response. No worries on the holidays!

Few observations from my side: 
1. I did see the /metrics/ path being added to the annotation, but the format is still html. so I continue to get the following error in wavefront collectors. Wont this be coming in the plain format? My assumption was port 8080 was the webport and would have the data in html format, but for the metrics in plain format, it would be available at port 9117 as per below. I'm unable to see the below annotation. With port 8080, wavefront is failing with the following error: 
`time="2020-12-09T04:46:36Z" level=error msg="reading text format failed: text format parsing error in line 1: invalid metric name"`

 ``` ## Prometheus metrics service parameters
  ##
  service:
    ## Metrics port
    ##
    port: 9117
    ## Annotations for the Prometheus metics service
    ##
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "{{ .Values.metrics.service.port }}"
```

2. Just a small observation on the helm repo: I pulled the helm chart from the repo, I see that the values.yaml and values-production.yaml are not latest with metrics values. This is not an issue as of now as long as the metrics get enabled!

Thanks
Geeta

**Comment by beltran-rubo** [comment] 2020-12-09 06:58
Could you please ensure you ran 'helm repo update' before getting the latest version of Spark? I pulled the 4.2.2 and it includes the metrics into the values files.

**Comment by juan131** [comment] 2020-12-09 07:19
@gkulkarni32 please ignore that block of the values that was included in previous versions since it was a result of copy-pasting but it wasn't used anywhere in the code. The important annotations are:

```
  ## Annotations for the Prometheus metrics on master nodes
  ##
  masterAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics/"
    prometheus.io/port: "{{ .Values.master.webPort }}"
  ## Annotations for the Prometheus metrics on worker nodes
  ##
  workerAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics/"
    prometheus.io/port: "{{ .Values.worker.webPort }}"
``` 

Regarding the issue with HTML format. I wasn't able to reproduce it using these commands:

```
$ helm search repo bitnami/spark
NAME         	CHART VERSION	APP VERSION	DESCRIPTION
$ helm install spark bitnami/spark --set metrics.enabled=true
... 
$ k port-forward dp-spark-master-0 8080:8080 &
$ curl http://127.0.0.1:8080/metrics/
metrics_master_aliveWorkers_Number{type="gauges"} 2
metrics_master_aliveWorkers_Value{type="gauges"} 2
metrics_master_apps_Number{type="gauges"} 0
metrics_master_apps_Value{type="gauges"} 0
metrics_master_waitingApps_Number{type="gauges"} 0
metrics_master_waitingApps_Value{type="gauges"} 0
metrics_master_workers_Number{type="gauges"} 2
metrics_master_workers_Value{type="gauges"} 2
metrics_HiveExternalCatalog_fileCacheHits_Count{type="counters"} 0
metrics_HiveExternalCatalog_filesDiscovered_Count{type="counters"} 0
metrics_HiveExternalCatalog_hiveClientCalls_Count{type="counters"} 0
metrics_HiveExternalCatalog_parallelListingJobCount_Count{type="counters"} 0
metrics_HiveExternalCatalog_partitionsFetched_Count{type="counters"} 0
metrics_CodeGenerator_compilationTime_Count{type="histograms"} 0
metrics_CodeGenerator_compilationTime_Max{type="histograms"} 0
metrics_CodeGenerator_compilationTime_Mean{type="histograms"} 0.0
metrics_CodeGenerator_compilationTime_Min{type="histograms"} 0
metrics_CodeGenerator_compilationTime_50thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_compilationTime_75thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_compilationTime_95thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_compilationTime_98thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_compilationTime_99thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_compilationTime_999thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_compilationTime_StdDev{type="histograms"} 0.0
metrics_CodeGenerator_generatedClassSize_Count{type="histograms"} 0
metrics_CodeGenerator_generatedClassSize_Max{type="histograms"} 0
metrics_CodeGenerator_generatedClassSize_Mean{type="histograms"} 0.0
metrics_CodeGenerator_generatedClassSize_Min{type="histograms"} 0
metrics_CodeGenerator_generatedClassSize_50thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_generatedClassSize_75thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_generatedClassSize_95thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_generatedClassSize_98thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_generatedClassSize_99thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_generatedClassSize_999thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_generatedClassSize_StdDev{type="histograms"} 0.0
metrics_CodeGenerator_generatedMethodSize_Count{type="histograms"} 0
metrics_CodeGenerator_generatedMethodSize_Max{type="histograms"} 0
metrics_CodeGenerator_generatedMethodSize_Mean{type="histograms"} 0.0
metrics_CodeGenerator_generatedMethodSize_Min{type="histograms"} 0
metrics_CodeGenerator_generatedMethodSize_50thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_generatedMethodSize_75thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_generatedMethodSize_95thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_generatedMethodSize_98thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_generatedMethodSize_99thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_generatedMethodSize_999thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_generatedMethodSize_StdDev{type="histograms"} 0.0
metrics_CodeGenerator_sourceCodeSize_Count{type="histograms"} 0
metrics_CodeGenerator_sourceCodeSize_Max{type="histograms"} 0
metrics_CodeGenerator_sourceCodeSize_Mean{type="histograms"} 0.0
metrics_CodeGenerator_sourceCodeSize_Min{type="histograms"} 0
metrics_CodeGenerator_sourceCodeSize_50thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_sourceCodeSize_75thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_sourceCodeSize_95thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_sourceCodeSize_98thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_sourceCodeSize_99thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_sourceCodeSize_999thPercentile{type="histograms"} 0.0
metrics_CodeGenerator_sourceCodeSize_StdDev{type="histograms"} 0.0
```

As you can see the response is obtained in plaintext.

**Comment by gkulkarni32** [comment] 2020-12-09 08:33
Thank you @juan131 @beltran-rubo for your help. Appreciate it. 

I pulled the latest helm repo (version 4.2.2) and was able to get the metrics in the plain format. 

Basically 2 main issues that we encountered: 
1. Fix for adding `/metrics/` in the path and removing the unused code block with service annotation
2. I also had to ensure I pulled the latest `bitnami/spark:3-debian-10` image while building my custom image as it was using the older version in cache. @juan131  thanks for pointing it out. 

```
docker pull http://docker.io/bitnami/spark:3-debian-10
docker build . -t <image name>
docker push <image name>
```
I'm now able to see the metrics in the plain format. Thank you so much! Appreciate it!

**Comment by juan131** [comment] 2020-12-09 11:27
Great @gkulkarni32 !! I proceed to close the issue as "Solved", but please feel free to reopen it if you require further help with the metrics.

**Closed by juan131** 2020-12-09 11:27 UTC

**Comment by gkulkarni32** [comment] 2020-12-09 12:27
Thank you @juan131 !

**Comment by arezvani** [comment] 2022-04-10 08:27
I think these metrics not complete and when i check metrics.properties i saw some lines that contains driver and executer are commented. So i created configMap and mount it to metrics.properties then i got this error:
mv: cannot move '/opt/bitnami/spark/conf/metrics.properties.template' to '/opt/bitnami/spark/conf/metrics.properties': Device or resource busy
what should i do?

**Comment by carrodher** [comment] 2022-04-11 06:59
Hi @arezvani can you please create a new issue with the information about your specific use case?
