### ISSUE TITLE
[bitnami/kafka] Invalid value for configuration message.max.bytes: Not a number of type INT

### ISSUE THREAD

**Issue by Lucasor99** [bitnami/charts#22552] opened 2024-01-22 17:06 UTC
### Name and Version

bitnami/kafka:3.4

### What architecture are you using?

None

### What steps will reproduce the bug?

I am experiencing an issue with a Kafka container that was working fine before but has started failing to start after the image update to Bitnami Kafka 3.4. The container fails to start with the following error:
```
org.apache.kafka.common.config.ConfigException: Invalid value for configuration message.max.bytes: Not a number of type INT
```
### Are you using any custom parameters or values?
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka:3.4
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami
      volumes:
        - name: kafka-data
          emptyDir: {}
```
### What do you see instead?
```
kafka 16:40:33.25 INFO  ==> 
kafka 16:40:33.25 INFO  ==> Welcome to the Bitnami kafka container
kafka 16:40:33.25 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
kafka 16:40:33.25 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
kafka 16:40:33.26 INFO  ==> 
kafka 16:40:33.26 INFO  ==> ** Starting Kafka setup **
kafka 16:40:33.35 INFO  ==> ** Kafka setup finished! **

kafka 16:40:33.36 INFO  ==> ** Starting Kafka **
[2024-01-22 16:40:34,591] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
[2024-01-22 16:40:35,055] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
org.apache.kafka.common.config.ConfigException: Invalid value  for configuration message.max.bytes: Not a number of type INT
        at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:742)
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:112)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:145)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1531)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1534)
        at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1457)
        at kafka.Kafka$.buildServer(Kafka.scala:73)
        at kafka.Kafka$.main(Kafka.scala:93)
        at kafka.Kafka.main(Kafka.scala)
```

**Comment by grinderz** [comment] 2024-01-22 18:04
same error with bitnami/kafka:3.6.1
no error on 3.6.0

**Comment by kchamz** [comment] 2024-01-22 19:29
same on 3.5.2 but not on 3.5.1

**Comment by mwalser** [comment] 2024-01-23 09:21
I would suspect that bitnami/containers#55255 might be the cause for that. At least it contains a reference to `KAFKA_CFG_MESSAGE_MAX_BYTES` which is the setting that is causing the failure.

**Comment by devenpatel2** [comment] 2024-01-23 10:14
Seems like this param is no longer optional. a quick fix for this was to add 

`KAFKA_CFG_MESSAGE_MAX_BYTES=1048588`

in the env vars

**Comment by fmulero** [comment] 2024-01-24 10:53
The problem was introduced on https://github.com/bitnami/containers/pull/54458. We definitely need to improve our testing strategy.

@devenpatel2  [workaround](https://github.com/bitnami/charts/issues/22552#issuecomment-1905721850) works perfectly setting the default value for `message.max.bytes`. A new version is ready to fix this issue, it will be released in a few hours. Sorry for the inconveniences

**Comment by OrtegaJose** [comment] 2024-01-24 10:59
I'm using version `3.3.2` and had the same issue as well caused by the [latest revision](https://github.com/bitnami/containers/pull/55245/files). @devenpatel2's suggestion worked perfectly

**Comment by fmulero** [comment] 2024-01-25 10:29
Thanks also to @yves-tutti for this PR https://github.com/bitnami/containers/pull/55276!

New versions with the fix has been released and they are ready for use:
* 3.6.1-debian-11-r3
* 3.5.2-debian-11-r3
* 3.4.1-debian-11-r119
* 3.3.2-debian-11-r245
* 3.2.3-debian-11-r231

Tags affected by the issue:
* 3.6.1-debian-11-r2
* 3.5.2-debian-11-r2
* 3.4.1-debian-11-r118
* 3.3.2-debian-11-r244
* 3.2.3-debian-11-r230

**Closed** 2024-01-25 10:29 UTC
Labels: in-progress, tech-issues, kafka
