### ISSUE TITLE
[rabbitmq] Chart version missing from Helm repository

### ISSUE THREAD

**Issue by nitrag** [bitnami/charts#2085] opened 2020-03-19 02:10 UTC
The [Chart.yaml](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/Chart.yaml#L3) in bitnami/rabbitmq says the version is 6.19.9. However the latest version in the your Repo is 6.18.9.

```
# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "bitnami-repo" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
# helm search rabbitmq
WARNING: Repo "local" is corrupt or missing. Try 'helm repo update'.
NAME                               	CHART VERSION	APP VERSION	DESCRIPTION                                                 
bitnami-repo/rabbitmq              	6.18.9       	3.8.3      	Open source message broker software that implements the A...
```

**Comment by xin053** [comment] 2020-03-19 03:03
works fine in my case

```shell
root@k8s1:/opt/kubespray# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "harbor" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈ Happy Helming!⎈
root@k8s1:/opt/kubespray# helm pull bitnami/rabbitmq
root@k8s1:/opt/kubespray# tar zvxf rabbitmq-6.18.9.tgz
rabbitmq/Chart.yaml
rabbitmq/values.yaml
rabbitmq/templates/NOTES.txt
rabbitmq/templates/_helpers.tpl
rabbitmq/templates/certs.yaml
rabbitmq/templates/configuration.yaml
rabbitmq/templates/healthchecks.yaml
rabbitmq/templates/ingress.yaml
rabbitmq/templates/networkpolicy.yaml
rabbitmq/templates/pdb.yaml
rabbitmq/templates/prometheusrule.yaml
rabbitmq/templates/role.yaml
rabbitmq/templates/rolebinding.yaml
rabbitmq/templates/secrets.yaml
rabbitmq/templates/serviceaccount.yaml
rabbitmq/templates/servicemonitor.yaml
rabbitmq/templates/statefulset.yaml
rabbitmq/templates/svc-headless.yaml
rabbitmq/templates/svc.yaml
rabbitmq/.helmignore
rabbitmq/README.md
rabbitmq/ci/affinity-toleration-values.yaml
rabbitmq/ci/default-values.yaml
rabbitmq/ci/networkpolicy-values.yaml
rabbitmq/values-production.yaml
rabbitmq/values.schema.json
```

maybe delete repo, add repo again, then update

**Comment by nitrag** [comment] 2020-03-19 03:16
@xin053 Yes you are correct. However the latest chart version, according to the repo, is 6.19.9. See my link to Chart.yaml.

**Comment by xin053** [comment] 2020-03-19 03:50
@nitrag ok, I know what you mean. 6.19.9 should be a mistake caused by https://github.com/bitnami/charts/commit/4b06e0f54d15656fd219626ade7e77c48246557f#diff-4445aad230fabc437688b8f2e1640f9c, 6.18.9 instead from commit history https://github.com/bitnami/charts/commits/master/bitnami/rabbitmq

**Comment by carrodher** [comment] 2020-03-19 17:13
Hi,

Sorry, there were a couple of unrelated issues:

On one side, the last PR was merged with a typo in the chart version. In [this commit](https://github.com/bitnami/charts/commit/4b06e0f54d15656fd219626ade7e77c48246557f#diff-af9eaad5c920e6c0cf1be34c33f0ccdcR3) the chart version was bumped from `6.18.9` to `6.19.9` (instead of `6.19.0`). I just fixed this typo in [this commit](https://github.com/bitnami/charts/commit/e2e8b292e217f034ca5e42469427507ca01d793a).

Apart from that, although a wrong version but it should appear in the Index, but in fact, it doesn't appear:
```
helm search repo bitnami/rabbitmq
NAME            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/rabbitmq	6.18.9       	3.8.3      	Open source message broker software that implem...
```
while the version that should appear is `6.19.9` (the one with the typo).

In Bitnami, when we merge PRs here, in GitLab, we don't publish those changes to the registry immediately, we need to test the changes in our automated pipeline where we execute different functional and verification tests, CVEs scanners, etc; and if everything works as expected, the chart is published in the registry.

In that case, this part was not executed, that is the reason why the code appears in GitHub but the new version doesn't appear in the registry.

To solve both things I just fixed the version in the code (GitHub level) and I also triggered the process in our internal pipeline so if everything works as expected a new RabbitMQ version (`6.19.0`) should appear soon in the registry (remember to run `helm repo update`).

Please, don't hesitate to ping me if you have any question

**Comment by carrodher** [comment] 2020-03-20 07:52
Hi,

Testing and publishing worked fine, you can find the new version in the registry:
```
▶ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈ Happy Helming!⎈

▶ helm search repo bitnami/rabbitmq
NAME            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/rabbitmq	6.19.1       	3.8.3      	Open source message broker software that implem...
```

In the same way, the version is `6.19.1` because the container images were updated (https://github.com/bitnami/charts/commit/3a01d4510f03a1387881e233b709277e54108702)

Thanks again for reporting this issue; and please, don't hesitate to reopen it if you find something wrong.

**Closed by carrodher** 2020-03-20 07:52 UTC
