### ISSUE TITLE
[bitnami/zookeeper] Prometheus no longer reports pod name in JVM metrics

### ISSUE THREAD

**Issue by ddcprg** [bitnami/charts#3301] opened 2020-08-03 09:42 UTC
**Which chart**:
bitnami/zookeeper: 5.21.0

**Describe the bug**
Some metrics tags are no longer reported in Prometheus, for example `kubernetes_pod_name` used to be added to the metric `jvm_memory_bytes_used` and all the other JVM metrics but that's not longer the case. 

**To Reproduce**
1. Deploy chart version 5.21.0
2. Go to Prometheus dashboard and search for a JVM metric or add a new chart in Grafana for a JVM metric
3. `kubernetes_pod_name` and other tags are not longer set

**Expected behavior**
Additional Kubernetes tags should be included as they used to be in version 5.16.0 for example

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by ddcprg** [comment] 2020-08-03 11:54
not an issue I think

**Comment by ddcprg** [comment] 2020-08-03 12:30
Actually I think this is being caused by the change that has been introduced in this commit https://github.com/bitnami/charts/commit/3e06faf941c68ae8f83e7ad6a00f95b5804830ad 

If I try to annotate the pod I get this error:

```
Error: Failed to render chart: exit status 1: Error: template: zookeeper/templates/statefulset.yaml:13:19: executing "zookeeper/templates/statefulset.yaml" at <include "zookeeper.tplvalue" (dict "value" .Values.commonAnnotations "context" $)>: error calling include: template: no template "zookeeper.tplvalue" associated with template "gotpl"
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error
```

Please let me know if this makes sense

**Comment by carrodher** [comment] 2020-08-03 16:37
Hi, thanks for reporting the issue. We are going to take a look; please, stay tunned.

**Comment by carrodher** [comment] 2020-08-04 11:13
According to the [notable changes section in the README](https://github.com/bitnami/charts/tree/master/bitnami/zookeeper#to-5210), it seems those parameters are named in a different way: 

> **To 5.21.0**
>
> A couple of parameters related to Zookeeper metrics were renamed or disappeared in favor of new ones:
> - `metrics.port` is renamed to `metrics.containerPort`.
> - `metrics.annotations` is deprecated in favor of `metrics.service.annotations`.

Are you able to reproduce the issue by using the new values?

**Comment by ddcprg** [comment] 2020-08-04 13:22
Hi @carrodher I'm using the new parameter, however I can see that Prometheus annotations are set only in the metrics service and they've been removed from the pods which is why I think the scrapper won't tag the metric with the pod name - because services don't have that meta attribute

**Comment by carrodher** [comment] 2020-08-05 10:03
Taking a look at https://github.com/bitnami/charts/commit/3e06faf941c68ae8f83e7ad6a00f95b5804830ad#diff-6b063ad92827264b128cc05c45bd9232 it seems previously the annotations was included by default:
```yaml
      {{- if or .Values.podAnnotations .Values.metrics.enabled }}
      annotations: {{- include "zookeeper.podAnnotations" . | nindent 8 }}
      {{- end }}
```
so just enabling the metrics, the `{{- if ... }}` condition was true and the annotations were set.
And what annotations were set? According to the `zookeeper.podAnnotations` helper
```
{{/*
Return podAnnotations
*/}}
{{- define "zookeeper.podAnnotations" -}}
{{- if .Values.podAnnotations }}
{{- toYaml .Values.podAnnotations | nindent 0 }}
{{- end }}
{{- if .Values.metrics.podAnnotations }}
{{- include "zookeeper.tplValue" ( dict "value" .Values.metrics.podAnnotations "context" $) | nindent 0 }}
{{- end }}
{{- end -}}
```
if `podAnnotations` was not set by default (that was not), it was using the `metrics.podAnnotations` that were set to
```yaml
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.port }}"
```

With the mentioned changes, now
```yaml
      {{- if .Values.podAnnotations }}
      annotations: {{- include "zookeeper.tplvalue" ( dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
```
it is needed to set the [`podAnnotations`](https://github.com/bitnami/charts/tree/master/bitnami/zookeeper#statefulset-parameters) value to be applied at pod level. There is also a [`commonAnnotation`](https://github.com/bitnami/charts/tree/master/bitnami/zookeeper#common-parameters) value available

**Comment by ddcprg** [comment] 2020-08-05 10:22
This is why I initially closed the ticket but then when I tried to use `commonAnnotations` I got the error above

**Comment by carrodher** [comment] 2020-08-06 08:27
But the `commonAnnotations` are not applied to the pod, they are applying to the "top level" object, in that case to the statefulset (see [statefulset.yaml#L12](https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/templates/statefulset.yaml#L12)); then the `podAnnotations` are set into the pod (see [statefulset.yaml#L38](https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/templates/statefulset.yaml#L38))

**Comment by ddcprg** [comment] 2020-08-06 13:51
I've tried both indeed, with `podAnnotations` I get a similar error:

```
STDERR:
  Error: Failed to render chart: exit status 1: install.go:159: [debug] Original chart version: "5.21.0"
  install.go:176: [debug] CHART PATH: <path_to_caches>/helm/repository/zookeeper-5.21.0.tgz
  Error: template: zookeeper/templates/statefulset.yaml:39:23: executing "zookeeper/templates/statefulset.yaml" at <include "zookeeper.tplvalue" (dict "value" .Values.podAnnotations "context" $)>: error calling include: template: no template "zookeeper.tplvalue" associated with template "gotpl"
  helm.go:84: [debug] template: zookeeper/templates/statefulset.yaml:39:23: executing "zookeeper/templates/statefulset.yaml" at <include "zookeeper.tplvalue" (dict "value" .Values.podAnnotations "context" $)>: error calling include: template: no template "zookeeper.tplvalue" associated with template "gotpl"
  Error: plugin "diff" exited with error
  helm.go:84: [debug] plugin "diff" exited with error
```

using:

```
podAnnotations:
  custom: val
```

A similar error happens using `commonAnnotations` which is the one that I originally posted:

```
commonAnnotations:
  custom: val
```

If you think I'm doing something wrong could you suggest a configuration that works? It may well be due to my Helm version.

**Comment by carrodher** [comment] 2020-08-07 08:21
I just found what can be the source of the issue, it was related to the PR we were talking about since the beginning but the typo was so evident that we did not see it.

I am going to create a PR fixing it, once merged and released in our internal CI/CD pipeline (it can take a while) the issue should disappear using the new version.

Please, note that this issue is going to be closed automatically once merged the PR but comments are still enabled, also feel free to reopen it if using the new version once released the issue persists.

**Comment by ddcprg** [comment] 2020-08-07 08:33
Thanks @carrodher I didn't spot that either, it is a very subtle typo

**Closed** 2020-08-07 08:46 UTC
