### ISSUE TITLE
[bitnami/redis] using with ioredis

### ISSUE THREAD

**Issue by meodemsao** [bitnami/charts#2799] opened 2020-06-10 07:46 UTC
**Which chart**:
bitnami/redis 6.0.3

**Describe the bug**
 I can't connect to redis 
I using ioredis 4.17.1

when i install chart log return 

```
NOTES:
** Please be patient while the chart is being deployed **
Redis can be accessed via port 6379 on the following DNS name from within your cluster:

redis.redis.svc.cluster.local for read only operations

For read/write operations, first access the Redis Sentinel cluster, which is available in port 26379 using the same domain name above.



To connect to your Redis server:

1. Run a Redis pod that you can use as a client:

   kubectl run --namespace redis redis-client --rm --tty -i --restart='Never' \
   --labels="redis-client=true" \
   --image docker.io/bitnami/redis:6.0.3-debian-10-r2 -- bash

2. Connect using the Redis CLI:
   redis-cli -h redis -p 6379 # Read only operations
   redis-cli -h redis -p 26379 # Sentinel access


Note: Since NetworkPolicy is enabled, only pods with label
redis-client=true"
will be able to connect to redis.
```

My config ios redis 

```
export const cache = new Redis.Cluster(
  [{  
        host: redis.redis.svc.cluster.local,
        port: 26379,
        db: 0,
 }],
  {
    scaleReads: 'slave',
    slotsRefreshTimeout: 2000,
    dnsLookup: (address, callback) => callback(null, address)
  }
```

output log

```
[ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.
    at tryNode (/app/node_modules/ioredis/built/cluster/index.js:359:31)
    at /app/node_modules/ioredis/built/cluster/index.js:376:21
    at /app/node_modules/ioredis/built/cluster/index.js:624:24
    at run (/app/node_modules/ioredis/built/utils/index.js:156:22)
    at tryCatcher (/app/node_modules/standard-as-callback/built/utils.js:11:23)
    at /app/node_modules/standard-as-callback/built/index.js:30:51
    at runMicrotasks (<anonymous>)
```

**Comment by marcosbc** [comment] 2020-06-11 10:34
Hi @meodemsao, first of all can you confirm you have connectivity to your Redis cluster in the computer you're running ioredis?

I.e.:

```
$ curl redis.redis.svc.cluster.local:26379
-ERR wrong number of arguments for 'get' command
```

If you get a different error such as `curl: (6) Could not resolve host ...` then it means it does not resolve.

In addition to that, does the `redis-cli` work as instructed in the NOTES? If so, I would say the issue is related to your ioredis configuration, and unfortunately we're not familiar with that tool so we cannot provide support for its usage/configuration.

**Comment by meodemsao** [comment] 2020-06-17 01:44
I using redis-cli like output after install and everthing working
But i resolve problem by disable sentinel ( temporary )
Now i can connect to master as well

**Comment by marcosbc** [comment] 2020-06-18 09:38
I understand your issues were resolved by using redis-cli, so I'm going to close this. Let me know if you continue to find issues with the Bitnami chart.

**Closed by marcosbc** 2020-06-18 09:38 UTC
