### ISSUE TITLE
[redis] 11.0.0  sentinel.conf is wrong and causes fatal crash on installation

### ISSUE THREAD

**Issue by damienwebdev** [bitnami/charts#3716] opened 2020-09-19 02:13 UTC
**Which chart**:
The name (and version) of the affected chart

`bitnami/redis:11.0.0`

**Describe the bug**
When deploying the `11.0.0` chart into a fresh cluster with `cluster.enabled=true` and `sentinel.enabled=true`, the sentinel containers will not start due to a misconfigured `sentinel.conf`.

1. `helm install my-release bitnami/redis ---set=cluster.enabled=true --set=sentinel.enabled=false`
2. Watch pods
3. `redis-node-*` pods go into `CrashLoopBackOff`
4. `kubectl log redis-node-0 -c sentinel`

5. See the following in logs:

```
*** FATAL CONFIG FILE ERROR (Redis 6.0.8) ***
Reading the configuration file, at line 4
>>> 'sentinel monitor mymaster ERR unknown 2'
Can't resolve master instance hostname.
```

6. `kubectl describe configmap redis`

```
dir "/tmp"
bind 0.0.0.0
port 26379
sentinel monitor mymaster redis-master-0.redis-headless.default.svc.cluster.local 6379 2
```

**Expected behavior**
I expected to be able to install Redis with sentinel.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T00:06:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

The [configmap](https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/configmap.yaml#L45) appears to be the issue. There's no more "master-0" FQDN as a result of 11.0.0, as far as I can tell, so this just needs a special config for `11.0.0`.

I believe the appropriate fix here is to change :

```yaml
{{ template "redis.fullname" . }}-master-0
```
to
```yaml
{{ template "redis.fullname" . }}-node-0
```

cc: @rafariossaa

**Comment by FraPazGal** [comment] 2020-09-21 11:43
Hi @damienwebdev,

My colleague is on holidays, so I have been looking into your issue but I haven't been able to reproduce it. After updating the bitnami repo and using a fresh cluster, both `redis-node-*` pods run without issue with `kubectl logs redis-node-0 -c sentinel` having the following output:

```
1:X 21 Sep 2020 09:01:35.305 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:X 21 Sep 2020 09:01:35.305 # Redis version=6.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
1:X 21 Sep 2020 09:01:35.305 # Configuration loaded
1:X 21 Sep 2020 09:01:35.306 * Running mode=sentinel, port=26379.
1:X 21 Sep 2020 09:01:35.306 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:X 21 Sep 2020 09:01:35.307 # Sentinel ID is 63f132bdd4181e53fabcf061a4b294816132559d
1:X 21 Sep 2020 09:01:35.307 # +monitor master mymaster 172.17.0.3 6379 quorum 2
1:X 21 Sep 2020 09:01:48.215 * +sentinel sentinel f34c1638b3a57714963049ef4d458af758d4fd98 172.17.0.4 26379 @ mymaster 172.17.0.3 6379
1:X 21 Sep 2020 09:01:55.358 * +slave slave 172.17.0.4:6379 172.17.0.4 6379 @ mymaster 172.17.0.3 6379
```

Regarding the configmap change, I believe it is not necessary, as the chart is now using [`configmaps-scripts.yaml`](https://github.com/bitnami/charts/blob/1c9a9aaf51823f2f08ce30c3b8b10ad00ab4ea9a/bitnami/redis/templates/configmap-scripts.yaml#L211), which configures sentinel.

If you are still having this issue, could you please provide more info regarding the cluster you are using and whether you are using a custom `values.yaml`? 

Thanks in advance.

**Comment by damienwebdev** [comment] 2020-09-21 14:02
@FraPazGal Yep, I misread what was going on.

I have two instances of the chart installed in my namespace, one which boots, the other which doesn't. 

The sentinel.conf on the one which starts:

```txt
dir "/tmp"
bind 0.0.0.0
port 26379
sentinel myid REDACTED
sentinel deny-scripts-reconfig yes
sentinel monitor mymaster 10.244.5.72 6379 2
sentinel down-after-milliseconds mymaster 60000
sentinel failover-timeout mymaster 18000
requirepass REDACTED
# Generated by CONFIG REWRITE
protected-mode no
user default on #REDACTED~* +@all
sentinel auth-pass mymaster REDACTED
sentinel config-epoch mymaster 0
sentinel leader-epoch mymaster 0
sentinel known-replica mymaster 10.244.4.29 6379
sentinel known-sentinel mymaster 10.244.4.29 26379 REDACTED
sentinel current-epoch 0

```

Unfortunately, I can't introspect what is finally generated on the sentinel container which crashes:

```yaml
redis:
  slave:
    affinity:
      nodeAffinity: ...
  sysctlImage:
    command:
    - /bin/sh
    - -c
    - |-
      install_packages procps
      sysctl -w net.core.somaxconn=10000
      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
    enabled: true
    mountHostSys: true
  password: REDACTED
```

**Comment by haljin** [comment] 2020-09-21 14:27
I'm seeing the same issue - Bumped our chart version to 11 and cannot deploy anymore with the same error in the logs

**Comment by damienwebdev** [comment] 2020-09-21 14:34
@FraPazGal this appears to only occur when usePassword is false, unrelated to having two charts in the namespace.

**Comment by haljin** [comment] 2020-09-21 14:48
It looks like on my deployment (with TLS)
```
sentinel_info_command="redis-cli -a $REDIS_PASSWORD -h {{ template "redis.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }} -p {{ .Values.sentinel.port }} --tls --cert ${REDIS_TLS_CERT_FILE} --key ${REDIS_TLS_KEY_FILE} --cacert ${REDIS_TLS_CA_FILE} sentinel get-master-addr-by-name {{ .Values.sentinel.masterSet }}"
``` 
is resolving to nothing causing the `sentinel monitor` command to fail. It does seem to execute correctly on `node-0` but not on `node-1`. Unfortunately the pods immediately so I cannot try to run this and see if there's any output

**Comment by haljin** [comment] 2020-09-21 15:11
Actually it looks like 
```
sentinel_info_command="redis-cli -a $REDIS_PASSWORD -h {{ template "redis.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }} -p {{ .Values.sentinel.port }} info"
```

is the one that is returning `(nil)` and is the one that non-masters call - that causes the `monitor` command to be empty

**Comment by haljin** [comment] 2020-09-21 15:28
Ok, I found what the problem is. 

In `start-sentinel.sh` you refer to `REDIS_TLS_ENABLED` however the env variable is called `REDIS_SENTINEL_TLS_ENABLED` - this is the same for the key paths. After creatively `kubectl edit`ing the config file it came up now

**Comment by lucasclerissepro** [comment] 2020-09-21 15:42
@haljin Can you submit a pr ? :)

**Comment by haljin** [comment] 2020-09-21 15:44
Just did :)

**Comment by FraPazGal** [comment] 2020-09-21 15:53
Lots of comments since this morning!

Thanks for the additional info @damienwebdev! It was indeed something related to the password. It actually was a bug in the `sentinel_info_command` that @haljin was working with. There was no `if`  for `usePassword=false`.

I'll review @haljin PR (thanks a lot for it) and create a new one to fix the other problem.

**Comment by FraPazGal** [comment] 2020-09-21 16:14
Reopened until second PR es merged.

**Closed** 2020-09-23 08:30 UTC
