### ISSUE TITLE
MongoDB Primary node restart fails to come back live.

### ISSUE THREAD

**Issue by binnythomas-1989** [bitnami/charts#4302] opened 2020-11-10 13:55 UTC
Kubernetes Version:
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

MongoDB Image: bitnami/mongodb:4.2.6-debian-10-r13

The Primary node was on a crashloopbackoff  when checking the logs found the below error. The primary logs stated secondary pod was not reachable too.
```
2020-11-10T03:28:59.484+0000 W  STORAGE  [FlowControlRefresher] Flow control is engaged and the sustainer point is not moving. Please check the health of all secondaries.
2020-11-10T03:28:59.643+0000 I  REPL_HB  [replexec-6814] Heartbeat to codesigning-mongodb-secondary-0.codesigning-mongodb-headless.code-signing:27017 failed after 2 retries, response status: InvalidReplicaSetConfig: Our replica set configuration is invalid or does not include us
2020-11-10T03:29:01.645+0000 I  REPL_HB  [replexec-6814] Heartbeat to codesigning-mongodb-secondary-0.codesigning-mongodb-headless.code-signing:27017 failed after 2 retries, response status: InvalidReplicaSetConfig: Our replica set configuration is invalid or does not include us
2020-11-10T03:29:03.647+0000 I  REPL_HB  [replexec-6814] Heartbeat to codesigning-mongodb-secondary-0.codesigning-mongodb-headless.code-signing:27017 failed after 2 retries, response status: InvalidReplicaSetConfig: Our replica set configuration is invalid or does not include us
```

Tried restarting the primary node pod and then started facing the below issue. 
Note: I had to update the liveness probe: InitialDelaySeconds : 900  to get it up and running since it starts the Sync up and takes more time that expected to bring the mongo db up and running.

Then i faced Error on the primary pod log

```
2020-11-10T13:35:13.245+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:50680 #182 (11 connections now open)
2020-11-10T13:35:13.245+0000 I  NETWORK  [conn182] received client metadata from 127.0.0.1:50680 conn182: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.6" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 10 (buster)"", architecture: "x86_64", version: "Kernel 5.4.0-37-generic" } }
2020-11-10T13:35:13.250+0000 I  NETWORK  [conn182] end connection 127.0.0.1:50680 (10 connections now open)
2020-11-10T13:35:13.738+0000 W  NETWORK  [ReplicaSetMonitor-TaskExecutor] Unable to reach primary for set rs0
2020-11-10T13:35:13.738+0000 I  CONTROL  [LogicalSessionCacheRefresh] Sessions collection is not set up; waiting until next sessions refresh interval: Could not find host matching read preference { mode: "primary" } for set rs0
2020-11-10T13:35:13.738+0000 I  CONTROL  [LogicalSessionCacheReap] Failed to reap transaction table: FailedToSatisfyReadPreference: Could not find host matching read preference { mode: "primary" } for set rs0
```

Arbiter log:

```
bintho01@C02YH0BNJHD5 dev ((HEAD detached from FETCH_HEAD)) $ kubectl logs codesigning-mongodb-arbiter-0 -n code-signing
mongodb 13:51:50.63
mongodb 13:51:50.64 Welcome to the Bitnami mongodb container
mongodb 13:51:50.64 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
mongodb 13:51:50.64 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
mongodb 13:51:50.65 Send us your feedback at containers@bitnami.com
mongodb 13:51:50.65
mongodb 13:51:50.65 INFO  ==> ** Starting MongoDB setup **
mongodb 13:51:50.66 INFO  ==> Validating settings in MONGODB_* env vars...
mongodb 13:51:50.72 INFO  ==> Initializing MongoDB...
mongodb 13:51:50.74 INFO  ==> Deploying MongoDB from scratch...
mongodb 13:51:51.46 INFO  ==> Creating users...
mongodb 13:51:51.46 INFO  ==> Users created
mongodb 13:51:51.46 INFO  ==> Writing keyfile for replica set authentication...
mongodb 13:51:51.49 INFO  ==> Configuring MongoDB replica set...
mongodb 13:51:51.50 INFO  ==> Stopping MongoDB...
mongodb 13:51:53.81 INFO  ==> Trying to connect to MongoDB server codesigning-mongodb...
mongodb 13:51:53.82 INFO  ==> Found MongoDB server listening at codesigning-mongodb:27017 !
mongodb 13:54:52.55 ERROR ==> Node codesigning-mongodb did not become available
mongodb 13:54:52.56 INFO  ==> Stopping MongoDB.
```
Please help this is our production.

**Comment by carrodher** [comment] 2020-11-11 15:41
Are you using the bitnami/mongodb Helm Chart default installation or are you customizing some parameters? In the second case, can you share with us what values did you modify in the _values.yaml_ or set by using `--set`?

In the same way, the issue you're describing appears after an upgrade, just installing the chart from scratch, or is there any other condition producing the issue?

**Comment by binnythomas-1989** [comment] 2020-11-11 16:55
This helm installation was running for the past month and the primary node crashed 2 days back with those errors. We are customizing parameters 

```
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName
#   storageClass: myStorageClass
## Override the namespace for resource deployed by the chart, but can itself be overridden by the local namespaceOverride
#   namespaceOverride: my-global-namespace

image:
  ## Bitnami MongoDB registry
  ##
  registry: docker.io
  ## Bitnami MongoDB image name
  ##
  repository: bitnami/mongodb
  ## Bitnami MongoDB image tag
  ## ref: https://hub.docker.com/r/bitnami/mongodb/tags/
  ##
  tag: 4.2.6-debian-10-r13
  ## Specify a imagePullPolicy
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

  ## Set to true if you would like to see extra information on logs
  ## It turns on Bitnami debugging in minideb-extras-base
  ## ref:  https://github.com/bitnami/minideb-extras-base
  debug: false

## String to partially override mongodb.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override mongodb.fullname template
##
# fullnameOverride:

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  # name:

# Add custom extra environment variables to all the MongoDB containers
# extraEnvVars:

## Init containers parameters:
## volumePermissions: Change the owner and group of the persistent volume mountpoint to runAsUser:fsGroup values from the securityContext section.
##
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnami/minideb
    tag: buster
    pullPolicy: Always
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName
  resources: {}

## Enable authentication
## ref: https://docs.mongodb.com/manual/tutorial/enable-authentication/
#
usePassword: true
# existingSecret: name-of-existing-secret

## MongoDB admin password
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#setting-the-root-password-on-first-run
##
mongodbRootPassword: xxx

## MongoDB custom user and database
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#creating-a-user-and-database-on-first-run
##
mongodbUsername: xxxx
mongodbPassword: xxxxx
mongodbDatabase: xxx

## Whether enable/disable IPv6 on MongoDB
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#enabling/disabling-ipv6
##
mongodbEnableIPv6: false

## Whether enable/disable DirectoryPerDB on MongoDB
## ref: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#enabling/disabling-directoryperdb
##
mongodbDirectoryPerDB: false

## MongoDB System Log configuration
## ref: https://github.com/bitnami/bitnami-docker-mongodb#configuring-system-log-verbosity-level
##
mongodbSystemLogVerbosity: 0
mongodbDisableSystemLog: false

## MongoDB additional command line flags
##
## Can be used to specify command line flags, for example:
##
## mongodbExtraFlags:
##  - "--wiredTigerCacheSizeGB=2"
mongodbExtraFlags: []

## Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  enabled: true
  fsGroup: 1001
  runAsUser: 1001

## Kubernetes Cluster Domain
#clusterDomain: cluster.local

## Kubernetes service type
service:
  ## Specify an explicit service name.
  # name: svc-mongo
  ## Provide any additional annotations which may be required.
  ## The value is evaluated as a template, so, for example, the value can depend on .Release or .Chart
  annotations: {}
  type: ClusterIP
  # clusterIP: None
  port: 27017

  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort:
  ## Specify the externalIP value ClusterIP service type.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#external-ips
  # externalIPs: []
  ## Specify the loadBalancerIP value for LoadBalancer service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
  ##
  # loadBalancerIP:
  ## Specify the loadBalancerSourceRanges value for LoadBalancer service types.
  ## ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ##
  # loadBalancerSourceRanges: []

## Use StatefulSet instead of Deployment when deploying standalone
useStatefulSet: false

## Setting up replication
## ref: https://github.com/bitnami/bitnami-docker-mongodb#setting-up-a-replication
#
replicaSet:
  ## Whether to create a MongoDB replica set for high availability or not
  enabled: true
  useHostnames: true

  ## Name of the replica set
  ##
  name: rs0

  ## Key used for replica set authentication
  ##
  # key: key

  ## Number of replicas per each node type
  ##
  replicas:
    secondary: 2
    arbiter: 1

  ## Pod Disruption Budget
  ## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
  pdb:
    enabled: true
    minAvailable:
      secondary: 2
      arbiter: 1
      # maxUnavailable:
      # secondary: 1
      # arbiter: 1

# Annotations to be added to the deployment or statefulsets
annotations: {}

# Additional labels to apply to the deployment or statefulsets
labels: {}

# Annotations to be added to MongoDB pods
podAnnotations:
  backup.velero.io/backup-volumes: datadir

# Additional pod labels to apply
podLabels: {}

## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName:

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}

# Define separate resources per arbiter, which are less then primary or secondary
# used only when replica set is enabled
resourcesArbiter: {}
# limits:
#   cpu: 500m
#   memory: 512Mi
# requests:
#   cpu: 100m
#   memory: 256Mi

## Pod priority
## https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
# priorityClassName: ""

## Node selector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

## Define Separate nodeSelector for arbiter
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelectorArbiter: {}

## Affinity
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
# Define separate affinity for arbiter pod
affinityArbiter: {}

## Tolerations
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Add sidecars to the pod
##
## For example:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
sidecars: []
## Array to add extra volumes
##
extraVolumes: []
## Array to add extra mounts (normally used with extraVolumes)
##
extraVolumeMounts: []

## Add sidecars to the arbiter pod
# used only when replica set is enabled
##
## For example:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
sidecarsArbiter: []
## Array to add extra volumes to the arbiter
# used only when replica set is enabled
##
extraVolumesArbiter: []
## Array to add extra mounts (normally used with extraVolumes) to the arbiter
# used only when replica set is enabled
##
extraVolumeMountsArbiter: []

## updateStrategy for MongoDB Primary, Secondary and Arbitrer statefulsets
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
updateStrategy:
  type: RollingUpdate

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  ##
  # existingClaim:

  ## The path the volume will be mounted at, useful when using different
  ## MongoDB images.
  ##
  mountPath: /bitnami/mongodb

  ## The subdirectory of the volume to mount to, useful in dev environments
  ## and one PV for multiple services.
  ##
  subPath: ""

  ## mongodb data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}

## HTTPProxy
httpproxy:
  enabled: true
  fqdn: xxxx
  secretName: k8s-tls-secret
  service:
    name: codesigning-mongodb
    port: 27017

## Configure the options for init containers to be run before the main app containers
## are started. All init containers are run sequentially and must exit without errors
## for the next one to be started.
## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
# extraInitContainers: |
#   - name: do-something
#     image: busybox
#     command: ['do', 'something']

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

# Define custom config map with init scripts
initConfigMap: {}
#  name: "init-config-map"

## Entries for the MongoDB config file. For documentation of all options, see:
##   http://docs.mongodb.org/manual/reference/configuration-options/
##
configmap:
#  # where and how to store data.
#  storage:
#    dbPath: /bitnami/mongodb/data/db
#    journal:
#      enabled: true
#    directoryPerDB: false
#  # where to write logging data.
#  systemLog:
#    destination: file
#    quiet: false
#    logAppend: true
#    logRotate: reopen
#    path: /opt/bitnami/mongodb/logs/mongodb.log
#    verbosity: 0
#  # network interfaces
#  net:
#    port: 27017
#    unixDomainSocket:
#      enabled: true
#      pathPrefix: /opt/bitnami/mongodb/tmp
#    ipv6: false
#    bindIpAll: true
#  # replica set options
#  #replication:
#    #replSetName: replicaset
#    #enableMajorityReadConcern: true
#  # process management options
#  processManagement:
#     fork: false
#     pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid
#  # set parameter options
#  setParameter:
#     enableLocalhostAuthBypass: true
#  # security options
#  security:
#    authorization: disabled
#    #keyFile: /opt/bitnami/mongodb/conf/keyfile

## Prometheus Exporter / Metrics
##
metrics:
  enabled: true

  image:
    registry: docker.io
    repository: bitnami/mongodb-exporter
    tag: 0.11.0-debian-10-r1
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName

  ## String with extra arguments to the metrics exporter
  ## ref: https://github.com/percona/mongodb_exporter/blob/master/mongodb_exporter.go
  extraArgs: ""

  ## Metrics exporter resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  # resources: {}

  ## Metrics exporter liveness and readiness probes
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
  livenessProbe:
    enabled: true
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

  ## Metrics exporter pod Annotation
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9216"

  ## Prometheus Service Monitor
  ## ref: https://github.com/coreos/prometheus-operator
  ##      https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md
  serviceMonitor:
    ## If the operator is installed in your cluster, set to true to create a Service Monitor Entry
    enabled: false

    ## Specify a namespace if needed
    # namespace: monitoring

    ## Used to pass Labels that are used by the Prometheus installed in your cluster to select Service Monitors to work with
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
    additionalLabels: {}

    ## Specify Metric Relabellings to add to the scrape endpoint
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
    # relabellings:

    alerting:
      ## Define individual alerting rules as required
      ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#rulegroup
      ##      https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
      rules: {}

      ## Used to pass Labels that are used by the Prometheus installed in your cluster to select Prometheus Rules to work with
      ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
      additionalLabels: {}


#Velero backup options, the namespace should be where the velero service is running
velero:
  enabled: true
  schedule: "45 1 * * *"
  namespace: velero
  ttl: 72h0m0s
```

**Comment by carrodher** [comment] 2020-11-12 11:23
I was trying to reproduce the issue but there are several things that make it difficult to reproduce, according to the values you provided, it seems you are using an old version of the MongoDB Helm Chart, it seems older than 8.0.0, right? Because there was a big refactor in that version and I am missing some parameters from that refactor. Apart from that the image (also should work and I am almost sure the issue is not related to the image itself) is an old version.

I don't know what is the current status of the cluster if you have the pods up and running but are not reachable. As you have some backup mechanism, do you think it can be a good option to deploy the newest version restoring the existing data?

**Comment by binnythomas-1989** [comment] 2020-11-12 11:31
I just tried doing that. Used the latest helm chart from master and then deployed it with external and without tls.

I get these errors, mostly when trying to login. Am i missing something?

```
mongo --host xxxx.eu02.abc.xyz.com:27017
conn = new Mongo("xxxx.eu02.abc.xyz.com:27017")
db = conn.getDB("popy)
db.auth("abcde","cdefg")

```
{"t":{"$date":"2020-11-12T10:55:49.462+00:00"},"s":"I",  "c":"CONTROL",  "id":20714,   "ctx":"LogicalSessionCacheRefresh","msg":"Failed to refresh session cache, will try again at the next refresh interval","attr":{"error":"NotYetInitialized: Replication has not yet been configured"}}
{"t":{"$date":"2020-11-12T10:55:49.462+00:00"},"s":"I",  "c":"CONTROL",  "id":20711,   "ctx":"LogicalSessionCacheReap","msg":"Failed to reap transaction table","attr":{"error":"NotYetInitialized: Replication has not yet been configured"}}
{"t":{"$date":"2020-11-12T11:08:23.386+00:00"},"s":"I",  "c":"ACCESS",   "id":20436,   "ctx":"conn176","msg":"Checking authorization failed","attr":{"error":{"code":13,"codeName":"Unauthorized","errmsg":"not authorized on admin to execute command { replSetGetStatus: 1.0, forShell: 1.0, $clusterTime: { clusterTime: Timestamp(1605179294, 1), signature: { hash: BinData(0, EE8D6C10237A4DFBC9CD0382CB5C80DAFCA1EB67), keyId: 6894189251936649220 } }, $db: \"admin\" }"}}}
```

**Comment by carrodher** [comment] 2020-11-13 11:26
There are 4 scenarios to configure MongoDB for external access, see https://github.com/bitnami/charts/tree/master/bitnami/kafka#accessing-kafka-brokers-from-outside-the-cluster

- Using LoadBalancer services and random load balancer IPs
- Using LoadBalancer services and manually specify the load balancer IPs
- Using NodePort services and random node ports
- Using NodePort services and manually specify the node ports

Maybe the option you are using is not working in this specific environment, please, take into account some of the methods requires RBAC rules and policies. What is the configuration you're using? Can you give a try to another method?

**Comment by binnythomas-1989** [comment] 2020-11-13 12:49
Im using the second option. Reason being i have enabled tls: true Please track the follow up here.

https://github.com/bitnami/charts/issues/4182#issuecomment-725991507

**Comment by franklin432** [comment] 2020-11-16 16:34
@binnythomas-1989 off topic question. But what does your Velero image/config do as far as backups? Is it performing backups of the mongo databases/collections to a separate PV?

**Comment by binnythomas-1989** [comment] 2020-11-16 21:33
it does a backup of the k8s resources and takes a snapshot of the pv, which we could restore later.

**Comment by franklin432** [comment] 2020-11-16 21:40
@binnythomas-1989 interesting. Can these backups and snapshots be sent to another container containing a pv or does it have to be sent to one of the cloud providers like a S3 bucket

**Comment by binnythomas-1989** [comment] 2020-11-17 08:03
It could create to S3 Buckets and local s3 buckets using restic. You could then restore the similar k8s resource to a different namespace using velero restore xxxxx --namespace-mappings  oldnamespace=newnamespace.

**Comment by binnythomas-1989** [comment] 2020-11-17 08:58
@franklin432 I have been having errors on bringing the mongo + tls + external up and running.

I have explained the situation on the link below
https://github.com/bitnami/charts/issues/4182#issuecomment-725991507

Any help would be appreciated.

**Comment by carrodher** [comment] 2020-11-20 08:38
It seems the conversation was moved to a different thread, let's keep the conversation at a single point in order to avoid duplications. I am closing this issue in favor of the other one.

**Closed by carrodher** 2020-11-20 08:38 UTC
