### ISSUE TITLE
[postgresql-ha]: Default pgpool configuration does not follow primary after failover ?

### ISSUE THREAD

**Issue by somejfn** [bitnami/charts#5589] opened 2021-02-22 18:58 UTC
**Which chart**:
bitnami/postgresql-ha 6.5.1   

Installed on K8s 1.19 with:
```
helm install pgkeycloak bitnami/postgresql-ha \
  --set postgresqlImage.tag=11.10.0-debian-10-r78  \
  --set pgpoolImage.tag=4.2.1-debian-10-r37  \
  --set metricsImage.tag=0.8.0-debian-10-r346 \
  --set metrics.enabled=true \
  --set postgresql.pdb.create=true \
  --set pgpool.replicaCount=2 \
  --set pgpool.customUsersSecret=pgpool-passwd \
  --set pgpool.pdb.create=true
```

A test keycloak instance is the connecting application,  installed with

```
helm install keycloak bitnami/keycloak \
  --set image.tag=12.0.2-debian-10-r6  \
  --set metrics.enabled=true \
  --set postgresql.enabled=false \
  --set externalDatabase.host=pgkeycloak-postgresql-ha-pgpool.default.svc \
  --set replicaCount=2 \
  --set serviceDiscovery.enabled=true \
  --set rbac.create=true \
  --set externalDatabase.user=keycloak \
  --set externalDatabase.password=password \
  --set externalDatabase.database=keycloak \
  --set pdb.create=true
```

See above external DB is set to the pgpool svc

**Describe the bug**

Following a primary PG pod restart (i.e. because of a K8s node is drained), and this is triggering the standby to take the role of primary, then the client application is apparently still getting connected to the now read-only instance and create/update/delete SQL statements are failing.

Looking at the generated /opt/bitnami/pgpool/conf/pgpool.conf ,  I was surprised to see what these parameters were set to:

```
follow_primary_command = ''
failover_command = 'echo ">>> Failover - that will initialize new primary node search!"'
failback_command = ''
```

Im new to pgpool....  but shouldn't these point to a script so that backend connections follow the new primary ?  

**To Reproduce**

Create a 2 node HA cluster as above
Connect a keycloak instance to the pgpool svc
Drain the k8s node  running the primary PG instance
Try an action cause a create statement in keycloak (such as creating an internal user)

**Expected behavior**

Client applications should be shielded from PG instance failover/failback by default configuration.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by alemorcuq** [comment] 2021-02-23 16:01
I think I've reproduced your issue. Could you execute this command in one of your psql pods to see if we are having the same error?

```
/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show
```

This is what I get: the two nodes are running as primary.

```
 ID   | Name                          | Role    | Status               | Upstream | Location | Priority | Timeline | Connection string
------+-------------------------------+---------+----------------------+----------+----------+----------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | pg-postgresql-ha-postgresql-0 | primary | * running            |          | default  | 100      | 1        | user=repmgr password=izmiyBM1Jb host=pg-postgresql-ha-postgresql-0.pg-postgresql-ha-postgresql-headless.amorenoc.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | pg-postgresql-ha-postgresql-1 | standby | ! running as primary |          | default  | 100      | 2        | user=repmgr password=izmiyBM1Jb host=pg-postgresql-ha-postgresql-1.pg-postgresql-ha-postgresql-headless.amorenoc.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

WARNING: following issues were detected
  - node "pg-postgresql-ha-postgresql-1" (ID: 1001) is registered as standby but running as primary
```

In fact, one of the nodes has all the new users I've tried to create after provoking the failure.

**Comment by somejfn** [comment] 2021-02-23 18:15
Hi,

Please see below how each replica have a different view of the cluster after the primary pod was evicted by a node drain and restarted:

```
### REPLICA 0 ###
$ k exec -n saas-platform-a2 -it pgkeycloak-postgresql-ha-postgresql-0 -- /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr cluster show -f  "/opt/bitnami/repmgr/conf/repmgr.conf"
Defaulting container name to postgresql.
Use 'kubectl describe pod/pgkeycloak-postgresql-ha-postgresql-0 -n saas-platform-a2' to see all of the containers in this pod.
postgresql-repmgr 16:17:26.99 
postgresql-repmgr 16:17:26.99 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 16:17:26.99 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 16:17:26.99 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 16:17:27.00 

 ID   | Name                                  | Role    | Status    | Upstream | Location | Priority | Timeline | Connection string                                                                                                                                                                                   
------+---------------------------------------+---------+-----------+----------+----------+----------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | pgkeycloak-postgresql-ha-postgresql-0 | primary | * running |          | default  | 100      | 3        | user=repmgr password=TEC5caL9M5 host=pgkeycloak-postgresql-ha-postgresql-0.pgkeycloak-postgresql-ha-postgresql-headless.saas-platform-a2.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | pgkeycloak-postgresql-ha-postgresql-1 | primary | ! running |          | default  | 100      | 2        | user=repmgr password=TEC5caL9M5 host=pgkeycloak-postgresql-ha-postgresql-1.pgkeycloak-postgresql-ha-postgresql-headless.saas-platform-a2.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

WARNING: following issues were detected
  - node "pgkeycloak-postgresql-ha-postgresql-1" (ID: 1001) is running but the repmgr node record is inactive

command terminated with exit code 25

### REPLICA 1 ###
$ k exec -n saas-platform-a2 -it pgkeycloak-postgresql-ha-postgresql-1 -- /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr cluster show -f  "/opt/bitnami/repmgr/conf/repmgr.conf"
Defaulting container name to postgresql.
Use 'kubectl describe pod/pgkeycloak-postgresql-ha-postgresql-1 -n saas-platform-a2' to see all of the containers in this pod.
postgresql-repmgr 16:17:38.79 
postgresql-repmgr 16:17:38.80 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 16:17:38.80 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 16:17:38.80 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 16:17:38.80 

 ID   | Name                                  | Role    | Status               | Upstream | Location | Priority | Timeline | Connection string                                                                                                                                                                                   
------+---------------------------------------+---------+----------------------+----------+----------+----------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | pgkeycloak-postgresql-ha-postgresql-0 | standby | ! running as primary |          | default  | 100      | 3        | user=repmgr password=TEC5caL9M5 host=pgkeycloak-postgresql-ha-postgresql-0.pgkeycloak-postgresql-ha-postgresql-headless.saas-platform-a2.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | pgkeycloak-postgresql-ha-postgresql-1 | primary | * running            |          | default  | 100      | 2        | user=repmgr password=TEC5caL9M5 host=pgkeycloak-postgresql-ha-postgresql-1.pgkeycloak-postgresql-ha-postgresql-headless.saas-platform-a2.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

WARNING: following issues were detected
  - node "pgkeycloak-postgresql-ha-postgresql-0" (ID: 1000) is registered as standby but running as primary

command terminated with exit code 25
```

And I did notice something additionally.   If I want to provoke a failover gracefully,  I can call the /pre-stop.sh pre-stop lifecycle hook in the primary pod myself and the failover will go perfectly.

But if you delete the pod (or drain a node)... for some reason the lifecycle hook is not capable of doing the same job maybe because of was was reported here: https://github.com/kubernetes/kubernetes/issues/87016

Thoughts ?

**Comment by somejfn** [comment] 2021-02-23 21:00
Apparently the /pre-stop.sh script exits prematurely.   Added a sleep 15 after it so it leaves more time for PG to stop and at least graceful node draining is possible.  It's not addressing the issue of unplanned maintenance tho but prolly we'd need to fix the script for this case.

**Comment by alemorcuq** [comment] 2021-02-26 14:52
As noted in https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues/66, we have created an internal task to investigate the issue.

**Comment by suridaddy** [comment] 2021-03-02 08:07
@alemorcuq  same issue in my 3-nodes environment.
```
[root@bjdemo-bastion ~]# oc rsh -n eco-common pgha-postgresql-ha-postgresql-1
$ /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show
postgresql-repmgr 08:03:14.05
postgresql-repmgr 08:03:14.05 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 08:03:14.06 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 08:03:14.06 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 08:03:14.06

 ID   | Name                            | Role    | Status               | Upstream | Location | Priority | Timeline | Connection string
------+---------------------------------+---------+----------------------+----------+----------+----------+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | pgha-postgresql-ha-postgresql-0 | standby | ! running as primary |          | default  | 100      | 3        | user=repmgr password=passw0rd host=pgha-postgresql-ha-postgresql-0.pgha-postgresql-ha-postgresql-headless.eco-common.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | pgha-postgresql-ha-postgresql-1 | primary | * running            |          | default  | 100      | 2        | user=repmgr password=passw0rd host=pgha-postgresql-ha-postgresql-1.pgha-postgresql-ha-postgresql-headless.eco-common.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1002 | pgha-postgresql-ha-postgresql-2 | standby | ! running as primary |          | default  | 100      | 4        | user=repmgr password=passw0rd host=pgha-postgresql-ha-postgresql-2.pgha-postgresql-ha-postgresql-headless.eco-common.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

WARNING: following issues were detected
  - node "pgha-postgresql-ha-postgresql-0" (ID: 1000) is registered as standby but running as primary
  - node "pgha-postgresql-ha-postgresql-2" (ID: 1002) is registered as standby but running as primary

$ exit
command terminated with exit code 25
[root@bjdemo-bastion ~]# oc rsh -n eco-common pgha-postgresql-ha-postgresql-2
$  /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show
postgresql-repmgr 08:03:51.71
postgresql-repmgr 08:03:51.71 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 08:03:51.71 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 08:03:51.72 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 08:03:51.72

 ID   | Name                            | Role    | Status    | Upstream | Location | Priority | Timeline | Connection string
------+---------------------------------+---------+-----------+----------+----------+----------+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | pgha-postgresql-ha-postgresql-0 | primary | ! running |          | default  | 100      | 3        | user=repmgr password=passw0rd host=pgha-postgresql-ha-postgresql-0.pgha-postgresql-ha-postgresql-headless.eco-common.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | pgha-postgresql-ha-postgresql-1 | primary | ! running |          | default  | 100      | 2        | user=repmgr password=passw0rd host=pgha-postgresql-ha-postgresql-1.pgha-postgresql-ha-postgresql-headless.eco-common.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1002 | pgha-postgresql-ha-postgresql-2 | primary | * running |          | default  | 100      | 4        | user=repmgr password=passw0rd host=pgha-postgresql-ha-postgresql-2.pgha-postgresql-ha-postgresql-headless.eco-common.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

WARNING: following issues were detected
  - node "pgha-postgresql-ha-postgresql-0" (ID: 1000) is running but the repmgr node record is inactive
  - node "pgha-postgresql-ha-postgresql-1" (ID: 1001) is running but the repmgr node record is inactive

$ exit
command terminated with exit code 25
[root@bjdemo-bastion ~]# oc rsh -n eco-common pgha-postgresql-ha-postgresql-0
$  /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show
postgresql-repmgr 08:04:11.14
postgresql-repmgr 08:04:11.15 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 08:04:11.15 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 08:04:11.16 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 08:04:11.16

 ID   | Name                            | Role    | Status               | Upstream | Location | Priority | Timeline | Connection string
------+---------------------------------+---------+----------------------+----------+----------+----------+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | pgha-postgresql-ha-postgresql-0 | primary | * running            |          | default  | 100      | 3        | user=repmgr password=passw0rd host=pgha-postgresql-ha-postgresql-0.pgha-postgresql-ha-postgresql-headless.eco-common.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | pgha-postgresql-ha-postgresql-1 | primary | ! running            |          | default  | 100      | 2        | user=repmgr password=passw0rd host=pgha-postgresql-ha-postgresql-1.pgha-postgresql-ha-postgresql-headless.eco-common.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1002 | pgha-postgresql-ha-postgresql-2 | standby | ! running as primary |          | default  | 100      | 4        | user=repmgr password=passw0rd host=pgha-postgresql-ha-postgresql-2.pgha-postgresql-ha-postgresql-headless.eco-common.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

WARNING: following issues were detected
  - node "pgha-postgresql-ha-postgresql-1" (ID: 1001) is running but the repmgr node record is inactive
  - node "pgha-postgresql-ha-postgresql-2" (ID: 1002) is registered as standby but running as primary
```

**Comment by alemorcuq** [comment] 2021-03-04 07:44
You can run `repmgr node check` in the nodes. The info you get there may help fixing your case:

```
/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf node check
```

**Comment by suridaddy** [comment] 2021-03-08 01:18
@alemorcuq every nodes take itself as primary.
```
[root@bjdemo-bastion ~]# oc rsh -n eco-common pgha-postgresql-ha-postgresql-0
$ /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf node check
postgresql-repmgr 01:09:44.65
postgresql-repmgr 01:09:44.66 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 01:09:44.66 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 01:09:44.66 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 01:09:44.67

WARNING: node "pgha-postgresql-ha-postgresql-2" not found in "pg_stat_replication"
Node "pgha-postgresql-ha-postgresql-0":
	Server role: OK (node is primary)
	Replication lag: OK (N/A - node is primary)
	WAL archiving: OK (0 pending archive ready files)
	Upstream connection: OK (N/A - node is primary)
	Downstream servers: CRITICAL (1 of 1 downstream nodes not attached; missing: pgha-postgresql-ha-postgresql-2 (ID: 1002))
	Replication slots: CRITICAL (1 of 1 physical replication slots are inactive)
	Missing physical replication slots: OK (node has no missing physical replication slots)
	Configured data directory: OK (configured "data_directory" is "/bitnami/postgresql/data")
$ exit
command terminated with exit code 25
[root@bjdemo-bastion ~]# oc rsh -n eco-common pgha-postgresql-ha-postgresql-1
$ /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf node check
postgresql-repmgr 01:15:35.81
postgresql-repmgr 01:15:35.81 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 01:15:35.82 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 01:15:35.82 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 01:15:35.82

WARNING: node "pgha-postgresql-ha-postgresql-0" not found in "pg_stat_replication"
WARNING: node "pgha-postgresql-ha-postgresql-2" not found in "pg_stat_replication"
Node "pgha-postgresql-ha-postgresql-1":
	Server role: OK (node is primary)
	Replication lag: OK (N/A - node is primary)
	WAL archiving: OK (0 pending archive ready files)
	Upstream connection: OK (N/A - node is primary)
	Downstream servers: CRITICAL (2 of 2 downstream nodes not attached; missing: pgha-postgresql-ha-postgresql-0 (ID: 1000), pgha-postgresql-ha-postgresql-2 (ID: 1002))
	Replication slots: CRITICAL (2 of 2 physical replication slots are inactive)
	Missing physical replication slots: OK (node has no missing physical replication slots)
	Configured data directory: OK (configured "data_directory" is "/bitnami/postgresql/data")
$ exit
command terminated with exit code 25
[root@bjdemo-bastion ~]# oc rsh -n eco-common pgha-postgresql-ha-postgresql-2
$ /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf node check
postgresql-repmgr 01:15:47.32
postgresql-repmgr 01:15:47.33 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 01:15:47.33 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 01:15:47.33 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 01:15:47.33

Node "pgha-postgresql-ha-postgresql-2":
	Server role: OK (node is primary)
	Replication lag: OK (N/A - node is primary)
	WAL archiving: OK (0 pending archive ready files)
	Upstream connection: OK (N/A - node is primary)
	Downstream servers: OK (this node has no downstream nodes)
	Replication slots: OK (node has no physical replication slots)
	Missing physical replication slots: OK (node has no missing physical replication slots)
	Configured data directory: OK (configured "data_directory" is "/bitnami/postgresql/data")
```

Seems this is one blocking issue for us to deliver some feature(base on postgresql) at the end of this month. Do we have a plan when this issue will be fixed?

**Comment by alemorcuq** [comment] 2021-03-11 10:56
We are working on it, but due to our limited resources we can't give you an ETA.

**Comment by vishrantgupta** [comment] 2021-11-08 02:11
Is there a workaround for this issue @alemorcuq? I am having the same issue:

```
PRIMARY:

 ID   | Name                        | Role    | Status               | Upstream | Location | Priority | Timeline | Connection string
------+-----------------------------+---------+----------------------+----------+----------+----------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | tcops-postgres-postgresql-0 | primary | * running            |          | default  | 100      | 3        | user=repmgr password=postgres host=tcops-postgres-postgresql-0.tcops-postgres-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | tcops-postgres-postgresql-1 | standby | ! running as primary |          | default  | 100      | 4        | user=repmgr password=postgres host=tcops-postgres-postgresql-1.tcops-postgres-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

WARNING: following issues were detected
  - node "tcops-postgres-postgresql-1" (ID: 1001) is registered as standby but running as primary
 ```

```
SECONDARY:

NOTICE: using provided configuration file "./opt/bitnami/repmgr/conf/repmgr.conf"
 ID   | Name                        | Role    | Status    | Upstream | Location | Priority | Timeline | Connection string
------+-----------------------------+---------+-----------+----------+----------+----------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | tcops-postgres-postgresql-0 | primary | ! running |          | default  | 100      | 3        | user=repmgr password=postgres host=tcops-postgres-postgresql-0.tcops-postgres-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | tcops-postgres-postgresql-1 | primary | * running |          | default  | 100      | 4        | user=repmgr password=postgres host=tcops-postgres-postgresql-1.tcops-postgres-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

WARNING: following issues were detected
  - node "tcops-postgres-postgresql-0" (ID: 1000) is running but the repmgr node record is inactive
  ```

`kubectl describe pod tcops-postgres-pgpool-54d48f8549-76vch`

```
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  20m   default-scheduler  Successfully assigned default/tcops-postgres-pgpool-54d48f8549-76vch to node3
  Warning  Unhealthy  20m   kubelet            Liveness probe failed: pgpool 01:49:04.35 INFO  ==> Checking pgpool health...
psql: FATAL:  failed to create a backend 0 connection
DETAIL:  not executing failover because failover_on_backend_error is off
  Warning  Unhealthy  19m (x5 over 20m)  kubelet  Readiness probe failed: psql: FATAL:  failed to create a backend 0 connection
DETAIL:  not executing failover because failover_on_backend_error is off
  Normal   Pulled     18m (x2 over 20m)  kubelet  Container image "10.180.13.96:30001/tcx/postgresql-ha@sha256:15ec8a651f6d742ae5671958eb2c8fc211915d7ed8575eb1f3c2d6c89c3b1064" already present on machine
  Normal   Created    18m (x2 over 20m)  kubelet  Created container pgpool
  Normal   Started    18m (x2 over 20m)  kubelet  Started container pgpool
  Warning  Unhealthy  18m                kubelet  Liveness probe errored: rpc error: code = Unknown desc = container not running (931e06cd333347a64a4e81c663a883841c4d19fd05380b0ddec6b8fffa350bdd)
```

**Comment by alemorcuq** [comment] 2021-11-11 09:53
This was suggested recently: https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues/66#issuecomment-945656214

**Comment by vishrantgupta** [comment] 2021-11-11 15:36
Thanks @alemorcuq, I will try that out, the edge case here would be if we lose the kubernetes node then will the `preStop` hook execute?

**Comment by vishrantgupta** [comment] 2021-11-15 17:42
I induced a network partition between two PostgreSQL nodes and the logic as suggested by [this comment](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues/66#issuecomment-945656214) failed, also please note adding 3rd node is not helping either.

**Comment by alemorcuq** [comment] 2021-11-19 14:37
Thanks for your feedback, we have a task to solve this but unfortunately I can't give you an ETA.

**Comment by nmousouros** [comment] 2022-02-21 13:59
seems like the latest merge fixed the issue for us.

**Comment by nmousouros** [comment] 2022-02-21 15:03
Not with --grace-period=0 but I deleted the pods and  they now elected a master successfully instead of both them becoming masters

**Comment by nmousouros** [comment] 2022-02-21 15:38
It makes sense sice the pre-stop hook is what fixes this issue because killing it without grace period wouldn't trigger the script, I might try this scenario later. However even if that is true, it's better than before that I couldn't get the nodes to recognize the master with any kind of restart, now after deleting the pod it's coming back to normal. 

Maybe adding some "pre-start" stuff to do those checks would help for those incidents, I am nowhere near being able to contribute to this yet though.

**Comment by vishrantgupta** [comment] 2022-02-21 18:12
This issue https://github.com/bitnami/charts/issues/8062 will make it tricky to implement the pre-start hook. The pgpool should fence the failed primary before doing the failover.

**Comment by carrodher** [comment] 2022-04-11 12:31
I'm closing this issue since different PRs were merged in order to solve this issue (for example https://github.com/bitnami/charts/pull/9035).
Please, don't hesitate to reopen it if you are still facing this issue using the latest Helm chart version. If you face a different issue, please create a new ticket.

**Closed by carrodher** 2022-04-11 12:31 UTC
Labels: on-hold
