### ISSUE TITLE
Node is now a standby, switching to standby monitoring

### ISSUE THREAD

**Issue by vishrantgupta** [bitnami/charts#8034] opened 2021-11-05 23:40 UTC
**Which chart**:
```
docker  tag: 11.11.0-debian-10-r70

chart : 11.11.0
```

**Describe the bug**
I am using a two node cluster (active-standby mode) and the state of the cluster is as follows:

```
~> k get pods | grep postgres
tcops-postgres-pgpool-6f56cf95f8-8x47h                   1/1     Running            3          28m
tcops-postgres-pgpool-6f56cf95f8-zgnd6                   1/1     Running            3          28m
tcops-postgres-postgresql-0                              1/1     Running            0          28m
tcops-postgres-postgresql-1                              0/1     CrashLoopBackOff   9          28m
```

The logs of `tcops-postgres-postgresql-1` are:

```
ERROR: connection to database failed
DETAIL:
could not connect to server: Connection refused
	Is the server running on host "tcops-postgres-postgresql-1.tcops-postgres-postgresql-headless.default.svc.cluster.local" (10.233.90.109) and accepting
	TCP/IP connections on port 5432?

DETAIL: attempted to connect using:
  user=repmgr password=postgres connect_timeout=5 dbname=repmgr host=tcops-postgres-postgresql-1.tcops-postgres-postgresql-headless.default.svc.cluster.local port=5432 fallback_application_name=repmgr options=-csearch_path=
ERROR: unable to connect to primary node
```

I understand pod tcops-postgres-postgresql-1 is unable to reach tcops-postgres-postgresql-0 (and vice-versa), but why tcops-postgres-postgresql-0 is not acting as master, the logs says:

```
2021-11-05 23:00:15.499 GMT [162] LOG:  database system was shut down in recovery at 2021-11-05 19:04:39 GMT
2021-11-05 23:00:15.499 GMT [162] LOG:  entering standby mode
2021-11-05 23:00:15.504 GMT [162] LOG:  redo starts at 0/90012C8
2021-11-05 23:00:15.504 GMT [162] LOG:  consistent recovery state reached at 0/9001C00
2021-11-05 23:00:15.504 GMT [162] LOG:  invalid record length at 0/9001C00: wanted 24, got 0
2021-11-05 23:00:15.505 GMT [160] LOG:  database system is ready to accept read only connections
2021-11-05 23:00:15.513 GMT [167] ERROR:  replication slot "repmgr_slot_1001" does not exist
2021-11-05 23:00:15.513 GMT [166] FATAL:  could not start WAL streaming: ERROR:  replication slot "repmgr_slot_1001" does not exist
2021-11-05 23:00:15.518 GMT [169] ERROR:  replication slot "repmgr_slot_1001" does not exist
2021-11-05 23:00:15.518 GMT [168] FATAL:  could not start WAL streaming: ERROR:  replication slot "repmgr_slot_1001" does not exist
 done
server started
postgresql-repmgr 23:00:15.57 INFO  ==> ** Starting repmgrd **
[2021-11-05 23:00:15] [NOTICE] repmgrd (repmgrd 5.2.1) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2021-11-05 23:00:15] [NOTICE] starting monitoring of node "tcops-postgres-postgresql-0" (ID: 1000)
[2021-11-05 23:00:15] [NOTICE] monitoring cluster primary "tcops-postgres-postgresql-0" (ID: 1000)
[2021-11-05 23:00:15] [NOTICE] node is now a standby, switching to standby monitoring
[2021-11-05 23:00:15] [WARNING] unable to determine a new primary node
[2021-11-05 23:00:17] [NOTICE] node is now a standby, switching to standby monitoring
[2021-11-05 23:00:17] [WARNING] unable to determine a new primary node
[2021-11-05 23:00:19] [NOTICE] node is now a standby, switching to standby monitoring
[2021-11-05 23:00:19] [WARNING] unable to determine a new primary node
2021-11-05 23:00:20.521 GMT [193] ERROR:  replication slot "repmgr_slot_1001" does not exist
2021-11-05 23:00:20.521 GMT [192] FATAL:  could not start WAL streaming: ERROR:  replication slot "repmgr_slot_1001" does not exist
```

I have set `syncReplication` to true.

This is making database to go in the read-only mode. I tried to create the table and I am getting:

```
ERROR: cannot execute CREATE TABLE in a read-only transaction
```

**Cluster status**

```
 ID   | Name                        | Role    | Status               | Upstream                      | Location | Priority | Timeline | Connection string
------+-----------------------------+---------+----------------------+-------------------------------+----------+----------+----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | tcops-postgres-postgresql-0 | primary | ! running as standby |                               | default  | 100      | 1        | user=repmgr password=postgres host=tcops-postgres-postgresql-0.tcops-postgres-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | tcops-postgres-postgresql-1 | standby | ? unreachable        | ? tcops-postgres-postgresql-0 | default  | 100      |          | user=repmgr password=postgres host=tcops-postgres-postgresql-1.tcops-postgres-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

WARNING: following issues were detected
  - node "tcops-postgres-postgresql-0" (ID: 1000) is registered as primary but running as standby
  - when attempting to connect to node "tcops-postgres-postgresql-1" (ID: 1001), following error encountered :
"could not translate host name "tcops-postgres-postgresql-1.tcops-postgres-postgresql-headless.default.svc.cluster.local" to address: Name or service not known"
  - node "tcops-postgres-postgresql-1" (ID: 1001) is registered as an active standby but is unreachable
  ```

- Is it done to avoid the split brain issue?
- Why tcops-postgres-postgresql-1 is not marked as failed so that tcops-postgres-postgresql-0 can continue to work as master?
- What is the potential solution?

**To Reproduce**

1. Deploy postgres using the HELM chart
2. Delete the service to simulate network unreachable

**Expected behavior**
One of the two node should act as master (in this case tcops-postgres-postgresql-0) so that the cluster is not in READ only state and the other node is marked as failed.

**Comment by vishrantgupta** [comment] 2021-11-05 23:47
This happened during the startup of the cluster, I think the leader/ master election never happened.

**Comment by juan131** [comment] 2021-11-08 07:27
Closing as duplicate of https://github.com/bitnami/charts/issues/7458

---

Please try the workarounds suggested in the original issue, and feel free to add a new comment describing your scenario if none of them work for you. Thanks in advance.

**Closed by juan131** 2021-11-08 07:27 UTC
