### ISSUE TITLE
[bitnami/mariadb] bitnami helm chart not compatible with k8s 1.24

### ISSUE THREAD

**Issue by natehouk** [bitnami/charts#13831] opened 2022-12-04 13:48 UTC
### Name and Version

bitnami/mediawiki:14.3.9

### What steps will reproduce the bug?

1. k8s 1.24
2. Deploy mediawiki helm chart
3. mariadb container doesn't stay running and shuts down 15 seconds after starting being killed by the orchestrator with no errors in logs.
4. mariadb container crasherrorloops infinitely due to above.

### What is the expected behavior?

1. mariadb container stays up and running

### What do you see instead?

1. mariadb crashes/shutsdown after running for 15s

### Additional information

Same setup runs perfectly fine on k8s 1.23

**Comment by javsalgar** [comment] 2022-12-05 08:53
Hi,

Just to confirm that the issue lies en MariaDB and not in Mediawiki. Could you try deploying the MariaDB chart on its own?

```
helm install mariadb bitnami/mariadb
```

**Comment by natehouk** [comment] 2022-12-05 15:28
Yes I will do so and get back to you soon. Thank you for your response.

**Comment by natehouk** [comment] 2022-12-07 21:34
A fresh install of the mariadb chart also results in a CrashLoopBackOff infinite loop.

Here are the logs
```
2022-12-07 21:32:57 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-12-07 21:32:57 0 [Note] mysqld: O_TMPFILE is not supported on /opt/bitnami/mariadb/tmp (disabling future attempts)
2022-12-07 21:32:58 0 [Note] InnoDB: Using Linux native AIO
2022-12-07 21:32:58 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
2022-12-07 21:32:58 0 [Note] InnoDB: Completed initialization of buffer pool
2022-12-07 21:32:58 0 [Note] InnoDB: 128 rollback segments are active.
2022-12-07 21:32:58 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-12-07 21:32:58 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-12-07 21:32:58 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-12-07 21:32:58 0 [Note] InnoDB: 10.6.11 started; log sequence number 1124607141; transaction id 5243067
2022-12-07 21:32:58 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-12-07 21:32:58 0 [Note] InnoDB: Loading buffer pool(s) from /bitnami/mariadb/data/ib_buffer_pool
2022-12-07 21:32:58 0 [Note] Server socket created on IP: '127.0.0.1'.
2022-12-07 21:32:58 0 [Warning] 'proxies_priv' entry '@% root@wiki-mariadb-0' ignored in --skip-name-resolve mode.
2022-12-07 21:32:58 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
Version: '10.6.11-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
2022-12-07 21:32:58 0 [Note] InnoDB: Buffer pool(s) load completed at 221207 21:32:58
2022-12-07 21:32:59 3 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
mariadb 21:32:59.97 INFO  ==> Stopping mariadb
2022-12-07 21:32:59 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (initiated by: unknown): Normal shutdown
2022-12-07 21:32:59 0 [Note] InnoDB: FTS optimize thread exiting.
2022-12-07 21:32:59 0 [Note] InnoDB: Starting shutdown...
2022-12-07 21:32:59 0 [Note] InnoDB: Dumping buffer pool(s) to /bitnami/mariadb/data/ib_buffer_pool
2022-12-07 21:32:59 0 [Note] InnoDB: Restricted to 2028 pages due to innodb_buf_pool_dump_pct=25
2022-12-07 21:32:59 0 [Note] InnoDB: Buffer pool(s) dump completed at 221207 21:32:59
2022-12-07 21:33:00 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
2022-12-07 21:33:00 0 [Note] InnoDB: Shutdown completed; log sequence number 1124607153; transaction id 5243068
2022-12-07 21:33:00 0 [Note] /opt/bitnami/mariadb/sbin/mysqld: Shutdown complete
```

**Comment by natehouk** [comment] 2022-12-07 21:53
This is on the Linode k8s cluster version 1.24

Here is the debug output, looks like the upgrade is failing:

```
Phase 4/7: Running 'mysql_fix_privilege_tables'
ERROR 130 (HY000) at line 25: Incorrect file format 'help_topic'
ERROR 130 (HY000) at line 29: Incorrect file format 'table_stats'
ERROR 130 (HY000) at line 30: Incorrect file format 'column_stats'
ERROR 130 (HY000) at line 31: Incorrect file format 'index_stats'
ERROR 130 (HY000) at line 53: Incorrect file format 'column_stats'
ERROR 130 (HY000) at line 72: Incorrect file format 'column_stats'
ERROR 130 (HY000) at line 141: Incorrect file format 'column_stats'
ERROR 130 (HY000) at line 159: Incorrect file format 'column_stats'
ERROR 130 (HY000) at line 232: Incorrect file format 'column_stats'
ERROR 130 (HY000) at line 294: Incorrect file format 'column_stats'
ERROR 130 (HY000) at line 361: Incorrect file format 'index_stats'
ERROR 130 (HY000) at line 500: Incorrect file format 'help_topic'
ERROR 130 (HY000) at line 501: Incorrect file format 'column_stats'
FATAL ERROR: Upgrade failed
mariadb 21:43:25.40 INFO  ==> Stopping mariadb
```

**Comment by natehouk** [comment] 2022-12-07 22:06
I have tried adding this to the top of my.cnf but it still doesn't work:

```
innodb_force_recovery = 1
```

Is there anyway to get mariadb to skip the upgrade?

**Comment by javsalgar** [comment] 2022-12-09 10:02
Closing this as duplicate of https://github.com/bitnami/charts/issues/13832

**Closed by javsalgar** 2022-12-09 10:02 UTC
Labels: in-progress, tech-issues, mariadb
