### ISSUE TITLE
[bitnami/jenkins] Jenkins home must be /bitnami/jenkins/jenkins_home

### ISSUE THREAD

**Issue by jdolitsky** [bitnami/charts#2361] opened 2020-04-20 02:52 UTC
**Which chart**:
jenkins (latest/5.0.6)

**Describe the bug**
Overriding the `jenkinsHome` value to some path other than "/bitnami/jenkins/jenkins_home" causes persistence not to work.

When a pod is killed, all configuration and jobs/job history is lost.

**To Reproduce**
1. Install Jenkins Helm chart, with `--set persistence.enabled=true --set jenkins_home="/var/jenkins_home"`
2. Wait for Jenkins to come up, add a new job
3. Manually kill running pod(s) with `kubectl delete pod <podname>`
4. Go to Jenkins UI, see missing state

**Expected behavior**
When pods killed, Jenkins state is maintained.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**Additional context**
My guess is this is a requirement based on the Docker image. If it is truly not configurable, maybe the most straightforward thing to do is to remove it as a chart value.

**Comment by Mauraza** [comment] 2020-04-20 13:22
Hi @jdolitsky,

I'm not able to reproduce could you give more information? what environment are you running Kubernetes?

**Comment by jdolitsky** [comment] 2020-04-20 16:33
Sorry the solution/issue is actually that for persistence to work, need home prefixed by "/bitnami/jenkins".

If you take a look at the templates, its actually hardcoded: https://github.com/bitnami/charts/blob/master/bitnami/jenkins/templates/deployment.yaml#L111

I'm not sure how the default of "/opt/bitnami/jenkins/jenkins_home" would even persist. I must be missing some detail.

This is Amazon EKS, k8s v1.14.9. In any case, was able to get to work by using `jenkinsHome: /bitnami/jenkins/jenkins_home`.

**Comment by Mauraza** [comment] 2020-04-21 10:28
Hi @jdolitsky,

The `jenkins_home` must be in the path `/bitnami/jenkins` to persist. You can see the [README.md of the container](https://github.com/bitnami/bitnami-docker-jenkins#persisting-your-application) for more information. 
I hope that information helps you.

**Comment by jdolitsky** [comment] 2020-04-21 13:32
@Mauraza thanks for pointing that out, did not see. I think the larger issue is that the default values of the Helm chart do not provide persistence support just by setting `persistence.enabled=true`.  At the very least it'd be helpful to have this documented in the table of values.

I've opened #2377 to modify the default, and happy to submit another to just add some note in the README.

**Comment by Mauraza** [comment] 2020-04-22 14:58
This issue will be closed when the PR is closed.

**Comment by jdolitsky** [comment] 2020-05-13 02:05
:(

**Comment by marcosbc** [comment] 2020-05-13 17:04
Sorry, I'm re-opening and marking this as on-hold.

**Comment by juan131** [comment] 2021-06-04 07:49
Hi everyone,

We currently support setting any custom home directory by setting the **JENKINS_HOME** env. variable. See:

- https://github.com/bitnami/charts/blob/master/bitnami/jenkins/templates/deployment.yaml#L106

However, as @Mauraza mentioned before, to ensure your data is persisted you should choose a path under the `/bitnami/jenkins` directory (since that's the point where we are mounting the data volume when `persistence.enabled=true`). Another alternative consists on using the `extraVolumes` and `extraVolumeMounts` parameters to mount a custom volume in any custom path, this why you can set any desired value for Jenkins home. 

Have in mind that, by default, the container runs as the user 1001 (unprivileged user) that belongs to "root" group, so you need to ensure that whatever directory you set in the **JENKINS_HOME** has writing permissions for the group.

**Closed by juan131** 2021-06-04 07:49 UTC
Labels: on-hold
