### ISSUE TITLE
[bitnami/mlflow] support GCS

### ISSUE THREAD

**Issue by Apachaika** [bitnami/charts#25372] opened 2024-04-24 16:31 UTC
### Name and Version

bitnami/mlflow:2.11.3-debian-12-r3

### What is the problem this feature will solve?

The main issue is that it doesn't support GCS values, but S3 values are supported.

### What is the feature you are proposing to solve the problem?

Please write GCS support because writing your own manifest for your image is uncomfortable. This will help all GCP community

**Comment by javsalgar** [comment] 2024-04-25 07:46
Hi!

Thank you so much for opening the ticket! Closing it as a duplicate of https://github.com/bitnami/containers/issues/65108

**Closed by javsalgar** 2024-04-25 07:46 UTC
Labels: triage, feature-request, mlflow
