### ISSUE TITLE
ARM64 images in public ECR

### ISSUE THREAD

**Issue by gtirloni** [bitnami/charts#20002] opened 2023-10-10 12:19 UTC
### Name and Version

All

### What is the problem this feature will solve?

It seems ARM64 images are pushed to DockerHub but not to public.ecr.aws

Companies using AWS would benefit from having those images closer to them and also not incur in DockerHub costs.

### What is the feature you are proposing to solve the problem?

Push ARM64 to both DockerHub and public.ecr.aws

**Comment by javsalgar** [comment] 2023-10-11 09:36
Hi! Thank you for opening the ticket. Closing it as a duplicate of https://github.com/bitnami/containers/issues/49895

**Closed by javsalgar** 2023-10-11 09:36 UTC
Labels: triage, feature-request
