### ISSUE TITLE
MongoDB -> Kafka (Source Connector)

### ISSUE THREAD

**Issue by Laurianti** [bitnami/charts#6335] opened 2021-05-11 21:52 UTC
I followed this guideliness:
https://docs.bitnami.com/tutorials/build-messaging-cluster-apache-kafka-mongodb-kubernetes/

I adapted the configuration with the latest version of Kafka helm chart:

```
  auth:
    clientProtocol: sasl
    interBrokerProtocol: plaintext
    sasl:
      jaas:
        clientUsers:
          - KAFKA-USERNAME
        clientPasswords:
          - KAFKA-PASSWORD
  extraDeploy:
    - |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: {{ include "kafka.fullname" . }}-connect
        labels: {{- include "common.labels.standard" . | nindent 4 }}
          app.kubernetes.io/component: connector
      spec:
        replicas: 1
        selector:
          matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
            app.kubernetes.io/component: connector
        template:
          metadata:
            labels: {{- include "common.labels.standard" . | nindent 8 }}
              app.kubernetes.io/component: connector
          spec:
            containers:
              - name: connect
                image: bitnami/kafka:latest
                imagePullPolicy: IfNotPresent
                command:
                  - /bin/bash
                  - -ec
                  - |
                    mkdir -p /opt/bitnami/kafka/plugins && \
                    cd /opt/bitnami/kafka/plugins && \
                    curl --remote-name --location --silent https://search.maven.org/remotecontent?filepath=org/mongodb/kafka/mongo-kafka-connect/1.5.0/mongo-kafka-connect-1.5.0-all.jar
                    /opt/bitnami/kafka/bin/connect-standalone.sh /opt/bitnami/kafka/config/connect-standalone.properties /opt/bitnami/kafka/config/mongodb.properties
                ports:
                  - name: connector
                    containerPort: 8083
                volumeMounts:
                  - name: configuration
                    mountPath: /opt/bitnami/kafka/config
            volumes:
              - name: configuration
                configMap:
                  name: {{ include "kafka.fullname" . }}-connect
    - |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: {{ include "kafka.fullname" . }}-connect
        labels: {{- include "common.labels.standard" . | nindent 4 }}
          app.kubernetes.io/component: connector
      data:
        connect-standalone.properties: |-
          bootstrap.servers = {{ include "kafka.fullname" . }}-0.{{ include "kafka.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.port }}
          key.converter=org.apache.kafka.connect.json.JsonConverter
          value.converter=org.apache.kafka.connect.json.JsonConverter
          key.converter.schemas.enable=true
          value.converter.schemas.enable=true
          offset.storage.file.filename=/tmp/connect.offsets
          offset.flush.interval.ms=10000
          plugin.path=/opt/bitnami/kafka/plugins
          sasl.mechanism=PLAIN
          security.protocol=SASL_PLAINTEXT
          sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
            username="KAFKA-USERNAME" \
            password="KAFKA-PASSWORD";
          consumer.sasl.mechanism=PLAIN
          consumer.security.protocol=SASL_PLAINTEXT
          consumer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
            username="KAFKA-USERNAME" \
            password="KAFKA-PASSWORD";
        mongodb.properties: |-
          name=mongo-source
          connector.class=com.mongodb.kafka.connect.MongoSourceConnector
          connection.uri=mongodb://root:rootPassword@customer-area-projects-api-mongodb
          database=database_source_1
          collection=collection_source_1
        connect-log4j.properties: |-
          log4j.rootLogger=INFO, stdout
          
          log4j.appender.stdout=org.apache.log4j.ConsoleAppender
          log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
          
          connect.log.pattern=[%d] %p %m (%c:%L)%n
          
          log4j.appender.stdout.layout.ConversionPattern=${connect.log.pattern}
          log4j.appender.connectAppender.layout.ConversionPattern=${connect.log.pattern}
          
          # suppress noisy logs from dependencies
          log4j.logger.org.reflections=ERROR
          log4j.logger.org.eclipse.jetty=ERROR
          log4j.logger.kafka=ERROR
          log4j.logger.org.apache.kafka=ERROR
          log4j.logger.org.apache.zookeeper=ERROR
          
          # Uncomment the following line when enabling debug on source connectors:
          log4j.logger.org.apache.kafka.connect.runtime.WorkerSourceTask=DEBUG
          
          # Uncomment the following line when the problem may be with Connect, SMTs, converters:
          log4j.logger.org.apache.kafka.connect=DEBUG

    - |
      apiVersion: v1
      kind: Service
      metadata:
        name: {{ include "kafka.fullname" . }}-connect
        labels: {{- include "common.labels.standard" . | nindent 4 }}
          app.kubernetes.io/component: connector
      spec:
        ports:
          - protocol: TCP
            port: 8083
            targetPort: connector
        selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
          app.kubernetes.io/component: connector

```

But I have this error:

`[2021-05-11 21:47:37,829] INFO Creating Kafka admin client (org.apache.kafka.connect.util.ConnectUtils:49)
[2021-05-11 21:47:38,061] DEBUG Looking up Kafka cluster ID (org.apache.kafka.connect.util.ConnectUtils:56)
[2021-05-11 21:47:38,064] DEBUG Fetching Kafka cluster ID (org.apache.kafka.connect.util.ConnectUtils:63)
[2021-05-11 21:47:38,909] ERROR [AdminClient clientId=adminclient-1] Connection to node -1 (kafka1-0.kafka1-headless.default.svc.cluster.local/172.17.0.9:9092) failed authentication due to: Authentication failed: Invalid username or password (org.apache.kafka.clients.NetworkClient:746)
[2021-05-11 21:47:38,916] ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectStandalone:130)
org.apache.kafka.connect.errors.ConnectException: Failed to connect to and describe Kafka cluster. Check worker's broker connection and security properties.
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:70)
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:51)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:83)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed: Invalid username or password
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:64)
        ... 2 more
Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed: Invalid username or password`

With Kafka helm chart 11.6.6 version works. Can you help me please?

**Comment by migruiz4** [comment] 2021-05-12 07:45
Hi @Laurianti,

I was able to configure everything using the latest version of Kafka, Mongodb and the mongodb-kafka-connector, so I'd like to share with you my configuration.

Before starting, I'd recommend uninstalling the previous chart ensuring there is no PVC from the previous configuration.
```
helm uninstall kafka
helm uninstall mongodb
kubectl delete pvc data-kafka-0 data-kafka-zookeeper-0 mongodb
```

First, install and configure MongoDB as describe in the step 1 from the documentation (https://docs.bitnami.com/tutorials/build-messaging-cluster-apache-kafka-mongodb-kubernetes/)

```bash
#Install Mongodb chart
helm install mongodb bitnami/mongodb --set auth.rootPassword=MONGODB-ROOT-PASSWORD
#Start a MongoDB client
kubectl run --namespace default mongodb-client --rm --tty -i --restart='Never' --image docker.io/bitnami/mongodb:4.2.8-debian-10-r39 --command -- bash
mongo admin --host "mongodb" --authenticationDatabase admin -u root -p MONGODB-ROOT-PASSWORD
# Inside the mongo shell, create a new user
use mydb
db.createUser(
  {
    user: "user",
    pwd: "MONGODB-USER-PASSWORD",
    roles: [ { role: "dbOwner", db: "mydb" } ]
  }
)
```
 
Next step, create your kafka-connector image:
```Dockerfile
FROM bitnami/kafka:latest

RUN mkdir -p /opt/bitnami/kafka/plugins && \
    cd /opt/bitnami/kafka/plugins && \
    curl --remote-name --location --silent https://repo1.maven.org/maven2/org/mongodb/kafka/mongo-kafka-connect/1.5.0/mongo-kafka-connect-1.5.0-all.jar

CMD /opt/bitnami/kafka/bin/connect-standalone.sh /opt/bitnami/kafka/config/connect-standalone.properties /opt/bitnami/kafka/config/mongo.properties
```
I updated the connector plugin to its latest version 1.5.0

```
docker build -t DOCKER-USERNAME/mykafka:1.0 .
docker login
docker push DOCKER-USERNAME/mykafka:1.0
```

Finally, configure Kafka using this values.yaml:
```
auth:
  clientProtocol: sasl
  interBrokerProtocol: plaintext
  sasl:
    jaas:
      clientUsers:
        - my_user
      clientPasswords:
        - my_password
extraDeploy:
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{ include "kafka.fullname" . }}-connect
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        app.kubernetes.io/component: connector
    spec:
      replicas: 1
      selector:
        matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
          app.kubernetes.io/component: connector
      template:
        metadata:
          labels: {{- include "common.labels.standard" . | nindent 8 }}
            app.kubernetes.io/component: connector
        spec:
          containers:
            - name: connect
              image: mykafka:1.0
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -ec
                - |
                  /opt/bitnami/kafka/bin/connect-standalone.sh /config/connect-standalone.properties /config/mongodb.properties
              ports:
                - name: connector
                  containerPort: 8083
              volumeMounts:
                - name: configuration
                  mountPath: /config
          volumes:
            - name: configuration
              configMap:
                name: {{ include "kafka.fullname" . }}-connect
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ include "kafka.fullname" . }}-connect
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        app.kubernetes.io/component: connector
    data:
      connect-standalone.properties: |-
        bootstrap.servers = {{ include "kafka.fullname" . }}-0.{{ include "kafka.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.port }}
        key.converter=org.apache.kafka.connect.json.JsonConverter
        value.converter=org.apache.kafka.connect.json.JsonConverter
        key.converter.schemas.enable=true
        value.converter.schemas.enable=true
        offset.storage.file.filename=/tmp/connect.offsets
        offset.flush.interval.ms=10000
        plugin.path=/opt/bitnami/kafka/plugins
        sasl.mechanism=PLAIN
        security.protocol=SASL_PLAINTEXT
        sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
          username="my_user" \
          password="my_password";
        consumer.sasl.mechanism=PLAIN
        consumer.security.protocol=SASL_PLAINTEXT
        consumer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
          username="my_user" \
          password="my_password";
      mongodb.properties: |-
        connection.uri=mongodb://user:MONGODB-USER-PASSWORD@mongodb.default.svc.cluster.local:27017/mydb
        name=mongo-sink
        topics=mytopic
        connector.class=com.mongodb.kafka.connect.MongoSinkConnector
        tasks.max=1
        key.converter=org.apache.kafka.connect.json.JsonConverter
        value.converter=org.apache.kafka.connect.json.JsonConverter
        key.converter.schemas.enable=false
        value.converter.schemas.enable=false
        database=mydb
        collection=sink
  - |
    apiVersion: v1
    kind: Service
    metadata:
      name: {{ include "kafka.fullname" . }}-connect
      labels: {{- include "common.labels.standard" . | nindent 4 }}
        app.kubernetes.io/component: connector
    spec:
      ports:
        - protocol: TCP
          port: 8083
          targetPort: connector
      selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
        app.kubernetes.io/component: connector
```

Make sure you replace the following placeholders:
- my_user
- my_password
- MONGODB-USER-PASSWORD
- MONGODB-ROOT-PASSWORD

The steps to test if the configuration was successful are the same described in the documentation.

Below my testing output:
```
I have no name!@mongodb-client:/$ mongo admin --host "mongodb" --authenticationDatabase mydb -u user -p MONGODB-USER-PASSWORD
MongoDB shell version v4.4.6
connecting to: mongodb://mongodb:27017/admin?authSource=mydb&compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("b3ab0a97-5eff-4b6e-b463-32393f324a2a") }
MongoDB server version: 4.4.6
> use mydb
switched to db mydb
> db.sink.find()
{ "_id" : ObjectId("609b849d88d4b95455e3cee4"), "hello" : "world" }
{ "_id" : ObjectId("609b84a188d4b95455e3cee6"), "foo" : "bar" }
```

If you find any issues please let me know.

**Comment by Laurianti** [comment] 2021-05-12 21:14
Thank you for your help, I followed your procedure step by step (copy & paste) but unfortunately I still have the same error.
I've tested it on both AKS and Minikube.

**Comment by migruiz4** [comment] 2021-05-13 07:34
Hi @Laurianti,

I received your message via email but I don't see it on Github, are you still facing the same issue?

**Comment by Laurianti** [comment] 2021-05-13 07:51
Hi @migruiz4, authentication problem was solved with your help.
Now I'm trying to make it work with these values:

```
        mongodb.properties: |-
          name=mongo-source
          plugin.path=/opt/bitnami/kafka/plugins
          connector.class=com.mongodb.kafka.connect.MongoSourceConnector
          connection.uri=mongodb://root:rootPassword@{{ include "mongodb.fullname" . }}-mongodb:27017
          database=database_source_1
          collection=collection_source_1
          key.converter=org.apache.kafka.connect.json.JsonConverter
          key.converter.schemas.enable=false
          value.converter=org.apache.kafka.connect.json.JsonConverter
          value.converter.schemas.enable=false
          publish.full.document.only=true
          topic.prefix=aprefix
```

But I have this error:

```
[2021-05-13 07:47:13,746] INFO Started o.e.j.s.ServletContextHandler@2e53b094{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:916)
[2021-05-13 07:47:13,747] INFO REST resources initialized; server is started and ready to handle requests (org.apache.kafka.connect.runtime.rest.RestServer:319)
[2021-05-13 07:47:13,748] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:57)
[2021-05-13 07:47:13,814] ERROR Failed to create job for /config/mongodb.properties (org.apache.kafka.connect.cli.ConnectStandalone:107)
[2021-05-13 07:47:13,815] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:117)
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/apache/avro/Schema
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:115)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:99)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:114)
Caused by: java.lang.NoClassDefFoundError: org/apache/avro/Schema
        at com.mongodb.kafka.connect.source.MongoSourceConfig.createConfigDef(MongoSourceConfig.java:681)
        at com.mongodb.kafka.connect.source.MongoSourceConfig.<clinit>(MongoSourceConfig.java:327)
        at com.mongodb.kafka.connect.MongoSourceConnector.config(MongoSourceConnector.java:91)
        at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:391)
        at org.apache.kafka.connect.runtime.AbstractHerder.lambda$validateConnectorConfig$2(AbstractHerder.java:351)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.apache.avro.Schema
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 10 more
```

**Comment by migruiz4** [comment] 2021-05-13 08:03
Using `{{ include "mongodb.fullname" . }}` won't work because the additional manifests are added to the Kafka Chart, while `mongodb.fullname` is a helper defined in the MongoDB chart.

You can not access variables and helpers defined in the Mongo chart from the Kafka chart because they are installed separately.

To accomplish that, you would have to clone the Kafka chart and add the MongoDB chart as a subchart. That way you would be able to call the helper `mongodb.fullname` and other MongoDB helpers and values.

**Comment by Laurianti** [comment] 2021-05-13 08:09
You are right, but I also tried setting the correct name manually, and I have the same error.

**Comment by migruiz4** [comment] 2021-05-13 08:32
Mmm a second look at your issue made me notice you are also trying to use `MongoSourceConnector` which causes this error:
```
Caused by: java.lang.ClassNotFoundException: org.apache.avro.Schema
```

A quick search about MongoDB connector and Apache Avro took me to this other case: https://stackoverflow.com/questions/64403447/cant-start-kafka-connect-with-mongodb-plugin-with-apache-kafka

Looks like the MongoDB connector does not bundle the Avro jar and Kafka does not include it by default either.

You will need to modify the Kafka connector image to also include the dependency `org.apache.avro`

**Comment by Laurianti** [comment] 2021-05-18 21:11
Thank you for your help.
The problem was that _mongo-kafka-connect_ needed the _avro_ jar and they must be inside the same folder, contained inside the plugin folder, as following:

```
                command:
                  - /bin/bash
                  - -ec
                  - |
                    mkdir -p /opt/bitnami/kafka/plugins/mongo-kafka-connect-1.5.0-all && \
                    cd /opt/bitnami/kafka/plugins/mongo-kafka-connect-1.5.0-all && \
                    curl --remote-name --location --silent https://repo1.maven.org/maven2/org/mongodb/kafka/mongo-kafka-connect/1.5.0/mongo-kafka-connect-1.5.0-all.jar && \
                    curl --remote-name --location --silent https://repo1.maven.org/maven2/org/apache/avro/avro/1.10.2/avro-1.10.2.jar && \
                    /opt/bitnami/kafka/bin/connect-standalone.sh /config/connect-standalone.properties /config/mongodb.properties
```

**Comment by migruiz4** [comment] 2021-05-19 06:18
Thank you for sharing!

I'm glad you were able to resolve your issue and configure `MongoSourceConnector` after adding the Avro jar.

If the issue is solved, I will proceed now to close this.

**Closed by migruiz4** 2021-05-19 06:18 UTC
