### ISSUE TITLE
[bitnami/redis-cluster] Does Bitnami package for Redis® Cluster support Redis Stack?

### ISSUE THREAD

**Issue by folprates** [bitnami/charts#17812] opened 2023-07-21 12:25 UTC
### Name and Version

bitnamicharts/redis-cluster

### What architecture are you using?

None

### What steps will reproduce the bug?

I'm using the latest bitnami chart for Redis Cluster (oci://registry-1.docker.io/bitnamicharts/redis-cluster) and it does not seem to support Redis Search (redis/redis-stack-server docker image).

### What do you see instead?

Using the docker image provided by oci://registry-1.docker.io/bitnamicharts/redis-cluster, I'm not able to perform vector commands such as creating an index:

From terminal:
```
127.0.0.1:6379> FT.CREATE my_idx SCHEMA vec_field VECTOR FLAT 6 TYPE FLOAT32 DIM 128 DISTANCE_METRIC L2
(error) ERR unknown command 'FT.CREATE', with args beginning with: 'my_idx' 'SCHEMA' 'vec_field' 'VECTOR' 'FLAT' '6' 'TYPE' 'FLOAT32' 'DIM' '128' 'DISTANCE_METRIC' 'L2' 

From RedisInsight.
![Screenshot 2023-07-21 092255](https://github.com/bitnami/charts/assets/9536152/5d5db015-6aed-40d8-b2ad-d6dafbce6ff5)
```

**Comment by javsalgar** [comment] 2023-07-24 07:09
Hi!

Thank you for opening the ticket, closing this ticket as it seems a duplicate of https://github.com/bitnami/containers/issues/41169

**Closed by javsalgar** 2023-07-24 07:09 UTC
Labels: triage, tech-issues, redis
