### ISSUE TITLE
[bitnami/postgres] - extendedConfiguration is faulty

### ISSUE THREAD

**Issue by qdupuy** [bitnami/charts#8891] opened 2022-02-03 10:32 UTC
Hello,

I am deploying a postgres on my cluster and when I want to add an additional configuration via the "extendedConfiguration" condition, I get the following return:

```
Error: template: postgresql/templates/primary/statefulset.yaml:548:21: executing "postgresql/templates/primary/statefulset.yaml" at <include "postgresql.primary.extendedConfigmapName" .>: error calling include: template: postgresql/templates/_helpers.tpl:161:15: executing "postgresql.primary.extendedConfigmapName" at <printf>: wrong number of args for printf: want at least 1 got 0
```

My extended configuration :

```
  extendedConfiguration: |
    max_connections = 1024
    shared_buffers = 512MB
    effective_cache_size = 1536MB
    maintenance_work_mem = 128MB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 256kB
    min_wal_size = 1GB
    max_wal_size = 4GB
    log_directory = '/bitnami/postgresql/pg_log'
    logging_collector = on
    log_min_duration_statement = 500
    max_standby_streaming_delay = -1
    tcp_keepalives_idle = 180
    tcp_keepalives_interval = 10
    tcp_keepalives_count = 3
```

The helper section that sends me the message : 

```
{{/*
Get the PostgreSQL primary extended configuration ConfigMap name.
*/}}
{{- define "postgresql.primary.extendedConfigmapName" -}}
{{- if .Values.primary.existingExtendedConfigmap -}}
    {{- printf "%s" (tpl .Values.primary.existingExtendedConfigmap $) -}}
{{- else -}}
    {{- printf "%s-extended-configuration" (include "postgresql.primary.fullname" .) -}}
{{- end -}}
{{- end -}}
```

Is this a problem with the helm charts or my configuration?

**Comment by juan131** [comment] 2022-02-03 14:17
Duplicate of https://github.com/bitnami/charts/issues/8884

**Closed by juan131** 2022-02-03 14:17 UTC
