### ISSUE TITLE
Airflow - Kubernetes executor log handling not working

### ISSUE THREAD

**Issue by jagusztinl** [bitnami/charts#5413] opened 2021-02-06 09:33 UTC
**Which chart**:
The name (and version) of the affected chart
bitnami/airflow

**Describe the bug**
DAGS are failing, unable to get the reason

**To Reproduce**
helm repo add bitnami https://charts.bitnami.com/bitnami

helm install my-release --set executor=KubernetesExecutor --set redis.enabled=false --set rbac.create=true --set serviceaccount.create=true --namespace airflow  --set auth.username=my-user --set auth.password=my-passsword  --set loadExamples=true --set web.baseUrl=http://127.0.0.1:8080 bitnami/airflow 

DAGs
Start example_kubernetes_executor

unable to see the logs

**Expected behavior**
logs present

**Version of Helm and Kubernetes**:
Helm
Kberenetes 1.20.2

- Output of `helm version`:
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

```
(paste your output here)
```

- Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```
(paste your output here)
```

**Additional context**

**Comment by jagusztinl** [comment] 2021-02-06 18:44
I am unable to get logs because of this:
*** Trying to get logs (last 100 lines) from worker pod  ***

*** Unable to fetch logs from worker pod  ***
(400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Sat, 06 Feb 2021 18:42:58 GMT', 'Content-Length': '136'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"name must be provided","reason":"BadRequest","code":400}\n'

**Comment by jagusztinl** [comment] 2021-02-06 19:55
Tried to set this annotation to avoid deleting the pod, but not working(values.yaml)

## Add annotations to all the deployed resources
##
commonAnnotations:
   - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS
     value: "false"
##

helm install -f values_debug.yaml my-release --set executor=KubernetesExecutor --set redis.enabled=false --set rbac.create=true --set serviceaccount.create=true --namespace airflow  --set auth.username=my-user --set auth.password=my-passsword  --set loadExamples=true --set web.baseUrl=http://127.0.0.1:8080 bitnami/airflow

Error: YAML parse error on airflow/templates/config/configmap.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field .metadata.annotations of type map[string]string

**Comment by marcosbc** [comment] 2021-02-08 18:11
It seems like this issue could be related to https://github.com/apache/airflow/issues/11696, for which a PR was sent: https://github.com/apache/airflow/pull/12598. I've created an internal task to fix this issue, but unfortunately I cannot give an ETA for when this would be fixed.

However, if you want to speed up the process, you could always contribute by sending a PR, we'd be happy to review it and help release the chart with the fix.

>Error: YAML parse error on airflow/templates/config/configmap.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field .metadata.annotations of type map[string]string

Note that `AIRFLOW__KUBERNETES__DELETE_WORKER_PODS` is an environment variable, not an annotation, so you would need to add it to the specific `extraEnvVars` field.

**Comment by janvaca92** [comment] 2021-02-10 13:50
Would be option to enable remote logging to avoid this issue ?

**Comment by marcosbc** [comment] 2021-02-11 13:27
> Would be option to enable remote logging to avoid this issue ?



@janvaca92 That could be an option yes. @jagusztinl could you try it?

**Comment by raefezzeldin** [comment] 2021-02-14 23:22
@jagusztinl Have you find a solution for that as I a facing the same issue.

**Comment by marcosbc** [comment] 2021-02-15 16:19
@raefezzeldin Could you try to enable remove logging like the user mentioned?

**Comment by mukubi01** [comment] 2021-02-18 18:43
I am facing the same issue and would like some help. Not sure how to enable remove the logging.

**Comment by marcosbc** [comment] 2021-02-19 16:37
@mukubi01 It was mentioned to use "remote" logging (not remove logs). See here for official Airflow docs on remote logging: https://airflow.apache.org/docs/apache-airflow/1.10.2/howto/write-logs.html (skipping the "Writing Logs Locally" section)

**Comment by sparkleGoat** [comment] 2021-02-24 18:46
I have tried with s3 remote logging and am still getting that "name must be provided".  I am fine with working with another version of the image/Airflow. If someone could point me to the one that works with the KubernetesOperator and does not include a Redis pod.  Also if there is an update on this issue since the last post?

Also, I was read about this error in airflow issues https://www.mail-archive.com/commits@airflow.apache.org/msg109786.html, and the user here made it sound like it may be related to the Docker image user? Do you all have any insight into that?

If there is a configuration workaround, for the time being, that would be appreciated as well. 

Thank you

**Comment by marcosbc** [comment] 2021-02-25 17:30
>I am using the 8.0.4 Bitnami Airflow Helm Charts. I have tried with s3 remote logging and am still getting that "name must be provided". I am fine with working with another version of the image/Airflow. If someone could point me to the one that works with the KubernetesOperator and does not include a Redis pod. Also if there is an update on this issue since the last post?

Unfortunately we haven't fixed this in bitnami/airflow yet. However, the official Airflow chart seems to include these changes, if you need these changes urgently and don't mind using non-Bitnami charts.

>Also, I was read about this error in airflow issues https://www.mail-archive.com/commits@airflow.apache.org/msg109786.html, and the user here made it sound like it may be related to the Docker image user? I see the Docker images have a uid and guid (1001:0). Do you all have any insight into that?

In this case, I don't think so because the issue is referring to logs for Kubernetes executors. Reading those logs requires access via RBAC.

>If there is a configuration workaround, for the time being, that would be appreciated as well.

Currently the known fix for this issue involves adapting https://github.com/apache/airflow/pull/12598 into the Bitnami AirFlow chart. If you're up for contributing the changes, feel free to do so, we'd be happy to review and make the release and others would be able to benefit from it.

**Comment by jagusztinl** [comment] 2021-03-01 18:43
> Would be option to enable remote logging to avoid this issue ?

Yes, but how to configure it? I install bitnami Airflow on Azure with helm. Ai can set the environment variables in values.yaml, but how to add the extra .py template files??  (should I rebuild the bitnami docker images??) 

https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/logging.html

**Comment by jagusztinl** [comment] 2021-03-01 18:46
> @mukubi01 It was mentioned to use "remote" logging (not remove logs). See here for official Airflow docs on remote logging: https://airflow.apache.org/docs/apache-airflow/1.10.2/howto/write-logs.html (skipping the "Writing Logs Locally" section)

**Comment by mukubi01** [comment] 2021-03-02 03:30
> @mukubi01 It was mentioned to use "remote" logging (not remove logs). See here for official Airflow docs on remote logging: https://airflow.apache.org/docs/apache-airflow/1.10.2/howto/write-logs.html (skipping the "Writing Logs Locally" section)

I tried setting up the S3 connection  and followed the instructions. 
However get this message
*** Log file does not exist: /opt/bitnami/airflow/logs/AWS_S3_FileTransfer/config/2021-02-28T00:00:00+00:00/1.log
*** Fetching from: http://my-release-airflow-worker-0.my-release-airflow-worker-headless.marketview.svc.cluster.local:8793/log/AWS_S3_FileTransfer/config/2021-02-28T00:00:00+00:00/1.log

There are no log files in S3. Not sure why/how it is getting the log from the my-release-airflow-worker-0. 
Note - I set the config as environment variables in values.yaml (hopefully this is the correct)

extraEnvVars: 
## ConfigMap with common settings for all Airflow containers
##
   - name: AIRFLOW__REMOTE_LOGGING
     value: "True"
   - name: AIRFLOW__REMOTE_LOG_CONN_ID
     value: "s3://xxxxx/airflow-logs"
   - name: AIRFLOW__REMOTE_BASE_LOG_FOLDER
     value: "MyS3Connection"

**Comment by mukubi01** [comment] 2021-03-02 03:39
> @mukubi01 It was mentioned to use "remote" logging (not remove logs). See here for official Airflow docs on remote logging: https://airflow.apache.org/docs/apache-airflow/1.10.2/howto/write-logs.html (skipping the "Writing Logs Locally" section)

I tried setting up the S3 connection and followed the instructions.
However get this message
*** Log file does not exist: /opt/bitnami/airflow/logs/AWS_S3_FileTransfer/config/2021-02-28T00:00:00+00:00/1.log
*** Fetching from: http://my-release-airflow-worker-0.my-release-airflow-worker-headless.marketview.svc.cluster.local:8793/log/AWS_S3_FileTransfer/config/2021-02-28T00:00:00+00:00/1.log

There are no log files in S3. Not sure why/how it is getting the log from the my-release-airflow-worker-0.
Note - I set the config as environment variables in values.yaml (hopefully this is the correct)

extraEnvVars:
_ConfigMap with common settings for all Airflow containers_

name: AIRFLOW__REMOTE_LOGGING
value: "True"
name: AIRFLOW__REMOTE_LOG_CONN_ID
value: "MyS3Connection"
name: AIRFLOW__REMOTE_BASE_LOG_FOLDER
value: "s3://xxxxx/airflow-logs"

**Comment by marcosbc** [comment] 2021-03-02 16:56
@mukubi01 You seem to be using wrong environment variable names. Refer to the official [configuration reference page](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#base-log-folder) for more info (i.e. they should start with `AIRFLOW__LOGGING__`).

@jagusztinl Please check above.

_____

Also, we wanted to let you all know that we're soon going to start the investigation on some of the issues with KubernetesExecutor with the Bitnami chart for Airflow. There is a similar error reported in #5569 that may also be related to this. Hopefully we'll be able to provide any update soon.

**Comment by mukubi01** [comment] 2021-03-02 21:09
Thanks @marcosbc . It worked after fixing the variables.

It now fails with a Forbidden error. Working on trying to determine the failure. 
*** Failed to verify remote log exists s3://xxxxx/airflow-logs/AWS_S3_FileTransfer/Check_config_files/2021-03-02T21:00:51.870295+00:00/1.log.
An error occurred (403) when calling the HeadObject operation: Forbidden

**Comment by marcosbc** [comment] 2021-03-03 14:05
Hi @mukubi01, I would say that could be happening because of using wrong credentials. Could you verify that your connection "MyS3Connection" is properly set up, with proper access/secret keys and all that?

**Comment by agessner** [comment] 2021-03-03 20:23
Hello @marcosbc, just to make sure I'm not missing anything. 
I've configured the remote logging and I can see the files being saved there just fine. 

But I'm also facing the issue when loading from the UI interface, as it keeps looking for the pod and, as the pod is not there, it does not find it (as expected). 

Any reason for not trying to go to s3? Is it the same problem you are investigating in 5569 or am I missing something?

**Comment by marcosbc** [comment] 2021-03-04 10:14
@agessner The issue you mention seems to be heavily related to KubernetesExecutor usage, so it should be fixed via #5569. We have increased the priority of the internal task, and we have started work on it. I cannot give an ETA unfortunately, as it will depend on the amount of issues we find.

**Comment by jagusztinl** [comment] 2021-03-04 12:39
Changed to ELK logging

**Closed** 2021-03-04 12:39 UTC
Labels: on-hold

**Comment by gowthamprabhus** [comment] 2022-07-02 09:56
Is this solved? Anyone could help me with what was done to solve this ?

**Comment by javsalgar** [comment] 2022-07-04 10:31
Hi,

As this issue has some time, could you share the values you used to reproduce the issue? We've done changes since then
