### ISSUE TITLE
Keycloak postgres dependency nameOverride and fullnameOverride parameters render invalid resource names

### ISSUE THREAD

**Issue by ghost** [bitnami/charts#12920] opened 2022-10-12 11:25 UTC
### Name and Version

bitnami/keycloak 7.1.18

### What steps will reproduce the bug?

1. Create umbrella helm chart (include 2 subcharts as dependencies that both have keycloak as a dependency specified in their own chart)
2. Create values.yaml file and override the names with nameOverride or fullnameOverride parameters:

```yaml
subchart1:
  enabled: true
  keycloak:
    nameOverride: "subchart1-keycloak"
    postgresql:
      nameOverride: "subchart1-postgresql"

subchart2:
  enabled: true
  keycloak:
    nameOverride: "subchart2-keycloak"
    postgresql:
      nameOverride: "subchart2-postgresql"
```

3. Run `helm dependency update`
4. Run `helm template umbrella .`
5. Check the rendered templates. Many of the postgresql resources will be named like the following:

- umbrella-subchart2-postgresql-%!s(<nil>)
- umbrella-subchart1-postgresql-%!s(<nil>)-hl

When installing the rendered resource with helm (or running helm test tool), the following error message is displayed: 

`
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource Service "umbrella-subchart1-postgresql-%!s(<nil>)-hl" in namespace "umbrella": invalid resource name "umbrella-subchart1-postgresql-%!s(<nil>)-hl": [may not contain '%']
`

I've also tried the fullnameOverride instead of nameOverride.

### What is the expected behavior?

Template names should be rendered without issues.

### What do you see instead?

Rendered template names are wrong, containing invalid characters. [may not contain '%']

**Comment by gabor-almadi** [comment] 2022-10-12 12:58
Looks like it only occures when `.Values.architecture` is set to `"replication"`. The `"primary"` and `"read"` names are replaced with ` %!s(<nil>) ` as if they were null.

**Comment by marcosbc** [comment] 2022-10-20 09:51
Hi, I have also not been able to reproduce this:

```
$ helm template mykeycloak --set nameOverride=subchart1-keycloak,postgresql.nameOverride=subchart1-postgresql bitnami/keycloak
...
# Source: keycloak/charts/postgresql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mykeycloak-subchart1-postgresql
  namespace: "default"
...
```

You can see that the template does not include any `nil` text. It also seems like your account got deleted, so I'm proceeding to close this issue.

If you think it is still applicable, please let us know.

**Closed by marcosbc** 2022-10-20 09:51 UTC
Labels: in-progress, tech-issues, keycloak
