### ISSUE TITLE
[bitnami/redis] Sentinel + SSL deployment

### ISSUE THREAD

**Issue by jaudiger** [bitnami/charts#10826] opened 2022-06-21 09:17 UTC
### Name and Version

bitnami/redis 16.12.2

### What steps will reproduce the bug?

1. Deploy Redis with Sentinel with 3 pods
2. Use custom certificates (the certificates have been created by Cert Manager)

### Are you using any custom parameters or values?

Chart value:

```yaml
auth:
  enabled: false
  sentinel: false

# Statefulset parameters
sentinel:
  enabled: true
  masterSet: redis-master
  downAfterMilliseconds: 4000
  failoverTimeout: 8000
  quorum: 2
  parallelSyncs: 1

replica:
  replicaCount: 3

tls:
  enabled: true
  authClients: true
  existingSecret: alaska-redis-tls-server
  certFilename: tls.crt
  certCAFilename: ca.crt
  certKeyFilename: tls.key
```

### What is the expected behavior?

No warning should be seen in the sentinel logs.

### What do you see instead?

The sentinel pods sometimes produce the following logs:

```log
1:X 21 Jun 2022 09:00:34.006 # Error accepting a client connection: (null)
1:X 21 Jun 2022 09:00:40.489 # Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (conn: fd=10)
```

Full log below:

```console
$ k logs redis-node-0
Defaulted container "redis" out of: redis, sentinel
 08:58:03.76 INFO  ==> about to run the command: timeout 220 redis-cli -h redis.default.svc.cluster.local -p 26379 sentinel get-master-addr-by-name redis-master
Could not connect to Redis at redis.default.svc.cluster.local:26379: Connection refused
 08:58:04.79 INFO  ==> Configuring the node as master
1:C 21 Jun 2022 08:58:04.808 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 21 Jun 2022 08:58:04.808 # Redis version=6.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 21 Jun 2022 08:58:04.808 # Configuration loaded
1:M 21 Jun 2022 08:58:04.809 * monotonic clock: POSIX clock_gettime
1:M 21 Jun 2022 08:58:04.810 # A key '__redis__compare_helper' was added to Lua globals which is not on the globals allow list nor listed on the deny list.
1:M 21 Jun 2022 08:58:04.810 * Running mode=standalone, port=6379.
1:M 21 Jun 2022 08:58:04.810 # Server initialized
1:M 21 Jun 2022 08:58:04.810 * Ready to accept connections
1:M 21 Jun 2022 08:58:24.009 # Error accepting a client connection: (null) (conn: fd=9)
1:M 21 Jun 2022 09:00:51.163 * Replica redis-node-1.redis-headless.default.svc.cluster.local:6379 asks for synchronization
1:M 21 Jun 2022 09:00:51.164 * Partial resynchronization not accepted: Replication ID mismatch (Replica asked for '17074f72b33762553a6d79a2c89821999fa5dadd', my replication IDs are 'acb0c6aca62edccec646f1b5f211afcf2e0bab52' and '0000000000000000000000000000000000000000')
1:M 21 Jun 2022 09:00:51.164 * Replication backlog created, my new replication IDs are '7b3a6c61bf2ec13976bf458548673326740d3fee' and '0000000000000000000000000000000000000000'
1:M 21 Jun 2022 09:00:51.164 * Starting BGSAVE for SYNC with target: disk
1:M 21 Jun 2022 09:00:51.165 * Background saving started by pid 727
727:C 21 Jun 2022 09:00:51.172 * DB saved on disk
727:C 21 Jun 2022 09:00:51.176 * RDB: 0 MB of memory used by copy-on-write
1:M 21 Jun 2022 09:00:51.249 * Background saving terminated with success
1:M 21 Jun 2022 09:00:51.249 * Synchronization with replica redis-node-1.redis-headless.default.svc.cluster.local:6379 succeeded
1:M 21 Jun 2022 09:01:16.700 * Replica redis-node-2.redis-headless.default.svc.cluster.local:6379 asks for synchronization
1:M 21 Jun 2022 09:01:16.700 * Partial resynchronization not accepted: Replication ID mismatch (Replica asked for 'a34b47e8a468f7c990e5892428ffa3ac75528c28', my replication IDs are '7b3a6c61bf2ec13976bf458548673326740d3fee' and '0000000000000000000000000000000000000000')
1:M 21 Jun 2022 09:01:16.700 * Starting BGSAVE for SYNC with target: disk
1:M 21 Jun 2022 09:01:16.700 * Background saving started by pid 845
845:C 21 Jun 2022 09:01:16.711 * DB saved on disk
845:C 21 Jun 2022 09:01:16.711 * RDB: 0 MB of memory used by copy-on-write
1:M 21 Jun 2022 09:01:16.817 * Background saving terminated with success
1:M 21 Jun 2022 09:01:16.817 * Synchronization with replica redis-node-2.redis-headless.default.svc.cluster.local:6379 succeeded

$ k logs redis-node-1
Defaulted container "redis" out of: redis, sentinel
 09:00:40.45 INFO  ==> about to run the command: timeout 220 redis-cli -h redis.default.svc.cluster.local -p 26379 sentinel get-master-addr-by-name redis-master
Error: Connection reset by peer
 09:00:40.49 INFO  ==> Configuring the node as master
1:C 21 Jun 2022 09:00:40.526 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 21 Jun 2022 09:00:40.526 # Redis version=6.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 21 Jun 2022 09:00:40.526 # Configuration loaded
1:M 21 Jun 2022 09:00:40.527 * monotonic clock: POSIX clock_gettime
1:M 21 Jun 2022 09:00:40.531 # A key '__redis__compare_helper' was added to Lua globals which is not on the globals allow list nor listed on the deny list.
1:M 21 Jun 2022 09:00:40.531 * Running mode=standalone, port=6379.
1:M 21 Jun 2022 09:00:40.531 # Server initialized
1:M 21 Jun 2022 09:00:40.532 * Ready to accept connections
1:S 21 Jun 2022 09:00:51.150 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
1:S 21 Jun 2022 09:00:51.150 * Connecting to MASTER redis-node-0.redis-headless.default.svc.cluster.local:6379
1:S 21 Jun 2022 09:00:51.151 * MASTER <-> REPLICA sync started
1:S 21 Jun 2022 09:00:51.151 * REPLICAOF redis-node-0.redis-headless.default.svc.cluster.local:6379 enabled (user request from 'id=3 addr=10.42.0.50:36084 laddr=10.42.0.50:6379 fd=9 name=sentinel-2e7e425b-cmd age=10 idle=0 flags=x db=0 sub=0 psub=0 multi=4 qbuf=255 qbuf-free=40699 argv-mem=4 obl=45 oll=0 omem=0 tot-mem=61468 events=r cmd=exec user=default redir=-1')
1:S 21 Jun 2022 09:00:51.158 * Non blocking connect for SYNC fired the event.
1:S 21 Jun 2022 09:00:51.163 * Master replied to PING, replication can continue...
1:S 21 Jun 2022 09:00:51.163 * Trying a partial resynchronization (request 17074f72b33762553a6d79a2c89821999fa5dadd:1).
1:S 21 Jun 2022 09:00:51.165 * Full resync from master: 7b3a6c61bf2ec13976bf458548673326740d3fee:0
1:S 21 Jun 2022 09:00:51.166 * Discarding previously cached master state.
1:S 21 Jun 2022 09:00:51.249 * MASTER <-> REPLICA sync: receiving 175 bytes from master to disk
1:S 21 Jun 2022 09:00:51.249 * MASTER <-> REPLICA sync: Flushing old data
1:S 21 Jun 2022 09:00:51.250 * MASTER <-> REPLICA sync: Loading DB in memory
1:S 21 Jun 2022 09:00:51.253 * Loading RDB produced by version 6.2.7
1:S 21 Jun 2022 09:00:51.253 * RDB age 0 seconds
1:S 21 Jun 2022 09:00:51.253 * RDB memory usage when created 1.95 Mb
1:S 21 Jun 2022 09:00:51.254 # Done loading RDB, keys loaded: 0, keys expired: 0.
1:S 21 Jun 2022 09:00:51.255 * MASTER <-> REPLICA sync: Finished with success
1:S 21 Jun 2022 09:00:51.255 * Background append only file rewriting started by pid 30
1:S 21 Jun 2022 09:00:51.286 * AOF rewrite child asks to stop sending diffs.
30:C 21 Jun 2022 09:00:51.286 * Parent agreed to stop sending diffs. Finalizing AOF...
30:C 21 Jun 2022 09:00:51.286 * Concatenating 0.00 MB of AOF diff received from parent.
30:C 21 Jun 2022 09:00:51.286 * SYNC append only file rewrite performed
30:C 21 Jun 2022 09:00:51.287 * AOF rewrite: 0 MB of memory used by copy-on-write
1:S 21 Jun 2022 09:00:51.290 * Background AOF rewrite terminated with success
1:S 21 Jun 2022 09:00:51.290 * Residual parent diff successfully flushed to the rewritten AOF (0.00 MB)
1:S 21 Jun 2022 09:00:51.290 * Background AOF rewrite finished successfully
1:S 21 Jun 2022 09:00:59.417 # Error accepting a client connection: (null)

$ k logs redis-node-2
Defaulted container "redis" out of: redis, sentinel
 09:01:05.74 INFO  ==> about to run the command: timeout 220 redis-cli -h redis.default.svc.cluster.local -p 26379 sentinel get-master-addr-by-name redis-master
Error: Connection reset by peer
 09:01:05.77 INFO  ==> Configuring the node as master
1:C 21 Jun 2022 09:01:05.794 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 21 Jun 2022 09:01:05.797 # Redis version=6.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 21 Jun 2022 09:01:05.797 # Configuration loaded
1:M 21 Jun 2022 09:01:05.798 * monotonic clock: POSIX clock_gettime
1:M 21 Jun 2022 09:01:05.801 # A key '__redis__compare_helper' was added to Lua globals which is not on the globals allow list nor listed on the deny list.
1:M 21 Jun 2022 09:01:05.801 * Running mode=standalone, port=6379.
1:M 21 Jun 2022 09:01:05.801 # Server initialized
1:M 21 Jun 2022 09:01:05.801 * Ready to accept connections
1:S 21 Jun 2022 09:01:16.675 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
1:S 21 Jun 2022 09:01:16.675 * Connecting to MASTER redis-node-0.redis-headless.default.svc.cluster.local:6379
1:S 21 Jun 2022 09:01:16.678 * MASTER <-> REPLICA sync started
1:S 21 Jun 2022 09:01:16.678 * REPLICAOF redis-node-0.redis-headless.default.svc.cluster.local:6379 enabled (user request from 'id=3 addr=10.42.0.52:55040 laddr=10.42.0.52:6379 fd=9 name=sentinel-3907ec64-cmd age=10 idle=0 flags=x db=0 sub=0 psub=0 multi=4 qbuf=255 qbuf-free=40699 argv-mem=4 obl=45 oll=0 omem=0 tot-mem=61468 events=r cmd=exec user=default redir=-1')
1:S 21 Jun 2022 09:01:16.682 * Non blocking connect for SYNC fired the event.
1:S 21 Jun 2022 09:01:16.689 * Master replied to PING, replication can continue...
1:S 21 Jun 2022 09:01:16.700 * Trying a partial resynchronization (request a34b47e8a468f7c990e5892428ffa3ac75528c28:1).
1:S 21 Jun 2022 09:01:16.701 * Full resync from master: 7b3a6c61bf2ec13976bf458548673326740d3fee:7620
1:S 21 Jun 2022 09:01:16.701 * Discarding previously cached master state.
1:S 21 Jun 2022 09:01:16.817 * MASTER <-> REPLICA sync: receiving 176 bytes from master to disk
1:S 21 Jun 2022 09:01:16.817 * MASTER <-> REPLICA sync: Flushing old data
1:S 21 Jun 2022 09:01:16.817 * MASTER <-> REPLICA sync: Loading DB in memory
1:S 21 Jun 2022 09:01:16.823 * Loading RDB produced by version 6.2.7
1:S 21 Jun 2022 09:01:16.828 * RDB age 0 seconds
1:S 21 Jun 2022 09:01:16.829 * RDB memory usage when created 2.05 Mb
1:S 21 Jun 2022 09:01:16.829 # Done loading RDB, keys loaded: 0, keys expired: 0.
1:S 21 Jun 2022 09:01:16.829 * MASTER <-> REPLICA sync: Finished with success
1:S 21 Jun 2022 09:01:16.830 * Background append only file rewriting started by pid 33
1:S 21 Jun 2022 09:01:16.913 * AOF rewrite child asks to stop sending diffs.
33:C 21 Jun 2022 09:01:16.913 * Parent agreed to stop sending diffs. Finalizing AOF...
33:C 21 Jun 2022 09:01:16.913 * Concatenating 0.00 MB of AOF diff received from parent.
33:C 21 Jun 2022 09:01:16.913 * SYNC append only file rewrite performed
33:C 21 Jun 2022 09:01:16.914 * AOF rewrite: 0 MB of memory used by copy-on-write
1:S 21 Jun 2022 09:01:16.973 * Background AOF rewrite terminated with success
1:S 21 Jun 2022 09:01:16.973 * Residual parent diff successfully flushed to the rewritten AOF (0.00 MB)
1:S 21 Jun 2022 09:01:16.973 * Background AOF rewrite finished successfully
1:S 21 Jun 2022 09:01:24.781 # Error accepting a client connection: (null)

$ k logs redis-node-0 --cont
--container  --context    

$ k logs redis-node-0 --container sentinel
 08:58:21.98 INFO  ==> about to run the command: redis-cli -h redis.default.svc.cluster.local -p 26379 --tls --cert /opt/bitnami/redis/certs/tls.crt --key /opt/bitnami/redis/certs/tls.key --cacert /opt/bitnami/redis/certs/ca.crt sentinel get-master-addr-by-name redis-master
Could not connect to Redis at redis.default.svc.cluster.local:26379: Connection refused
1:X 21 Jun 2022 09:00:32.650 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:X 21 Jun 2022 09:00:32.650 # Redis version=6.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:X 21 Jun 2022 09:00:32.650 # Configuration loaded
1:X 21 Jun 2022 09:00:32.652 * monotonic clock: POSIX clock_gettime
1:X 21 Jun 2022 09:00:32.652 # A key '__redis__compare_helper' was added to Lua globals which is not on the globals allow list nor listed on the deny list.
1:X 21 Jun 2022 09:00:32.652 * Running mode=sentinel, port=26379.
1:X 21 Jun 2022 09:00:32.653 # Sentinel ID is f1e0b468e5f85946a322ca4d55d2e657c11073c4
1:X 21 Jun 2022 09:00:32.653 # +monitor master redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379 quorum 2
1:X 21 Jun 2022 09:00:34.006 # Error accepting a client connection: (null)
1:X 21 Jun 2022 09:00:40.489 # Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (conn: fd=10)
1:X 21 Jun 2022 09:00:43.133 * +sentinel sentinel 2e7e425b02d1c978d123c4c6ef287405e306ef31 redis-node-1.redis-headless.default.svc.cluster.local 26379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379
1:X 21 Jun 2022 09:00:56.321 # +tilt #tilt mode entered
1:X 21 Jun 2022 09:00:56.336 * +slave slave redis-node-1.redis-headless.default.svc.cluster.local:6379 redis-node-1.redis-headless.default.svc.cluster.local 6379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379
1:X 21 Jun 2022 09:00:56.403 # waitpid() returned a pid (120) we can't find in our scripts execution queue!
1:X 21 Jun 2022 09:01:05.763 # Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (conn: fd=13)
1:X 21 Jun 2022 09:01:08.624 * +sentinel sentinel 3907ec64d3b20ba45124791ff23640c70d0a1f9a redis-node-2.redis-headless.default.svc.cluster.local 26379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379
1:X 21 Jun 2022 09:01:26.376 # -tilt #tilt mode exited
1:X 21 Jun 2022 09:01:26.457 * +slave slave redis-node-2.redis-headless.default.svc.cluster.local:6379 redis-node-2.redis-headless.default.svc.cluster.local 6379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379
1:X 21 Jun 2022 09:01:42.000 # +sdown sentinel 2e7e425b02d1c978d123c4c6ef287405e306ef31 redis-node-1.redis-headless.default.svc.cluster.local 26379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379
1:X 21 Jun 2022 09:01:42.172 # -sdown sentinel 2e7e425b02d1c978d123c4c6ef287405e306ef31 redis-node-1.redis-headless.default.svc.cluster.local 26379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379

$ k logs redis-node-1 --container sentinel
 09:00:40.81 INFO  ==> about to run the command: redis-cli -h redis.default.svc.cluster.local -p 26379 --tls --cert /opt/bitnami/redis/certs/tls.crt --key /opt/bitnami/redis/certs/tls.key --cacert /opt/bitnami/redis/certs/ca.crt sentinel get-master-addr-by-name redis-master
redis-node-0.redis-headless.default.svc.cluster.local
6379
 09:00:40.85 INFO  ==> about to run the command: redis-cli -h redis.default.svc.cluster.local -p 26379 --tls --cert /opt/bitnami/redis/certs/tls.crt --key /opt/bitnami/redis/certs/tls.key --cacert /opt/bitnami/redis/certs/ca.crt sentinel get-master-addr-by-name redis-master
 09:00:40.89 INFO  ==> printing REDIS_SENTINEL_INFO=(redis-node-0.redis-headless.default.svc.cluster.local,6379)
1:X 21 Jun 2022 09:00:41.089 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:X 21 Jun 2022 09:00:41.089 # Redis version=6.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:X 21 Jun 2022 09:00:41.089 # Configuration loaded
1:X 21 Jun 2022 09:00:41.090 * monotonic clock: POSIX clock_gettime
1:X 21 Jun 2022 09:00:41.092 # A key '__redis__compare_helper' was added to Lua globals which is not on the globals allow list nor listed on the deny list.
1:X 21 Jun 2022 09:00:41.093 * Running mode=sentinel, port=26379.
1:X 21 Jun 2022 09:00:41.093 # Sentinel ID is 2e7e425b02d1c978d123c4c6ef287405e306ef31
1:X 21 Jun 2022 09:00:41.093 # +monitor master redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379 quorum 2
1:X 21 Jun 2022 09:00:51.149 * +convert-to-slave slave redis-node-1.redis-headless.default.svc.cluster.local:6379 redis-node-1.redis-headless.default.svc.cluster.local 6379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379
1:X 21 Jun 2022 09:00:55.729 # +sdown sentinel f1e0b468e5f85946a322ca4d55d2e657c11073c4 redis-node-0.redis-headless.default.svc.cluster.local 26379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379
1:X 21 Jun 2022 09:00:56.384 # -sdown sentinel f1e0b468e5f85946a322ca4d55d2e657c11073c4 redis-node-0.redis-headless.default.svc.cluster.local 26379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379
1:X 21 Jun 2022 09:00:59.410 # Error accepting a client connection: (null) (conn: fd=14)
1:X 21 Jun 2022 09:01:08.625 * +sentinel sentinel 3907ec64d3b20ba45124791ff23640c70d0a1f9a redis-node-2.redis-headless.default.svc.cluster.local 26379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379
1:X 21 Jun 2022 09:01:21.293 * +slave slave redis-node-2.redis-headless.default.svc.cluster.local:6379 redis-node-2.redis-headless.default.svc.cluster.local 6379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379
1:X 21 Jun 2022 09:01:22.142 # +sdown sentinel 3907ec64d3b20ba45124791ff23640c70d0a1f9a redis-node-2.redis-headless.default.svc.cluster.local 26379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379
1:X 21 Jun 2022 09:01:23.085 # -sdown sentinel 3907ec64d3b20ba45124791ff23640c70d0a1f9a redis-node-2.redis-headless.default.svc.cluster.local 26379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379
1:X 21 Jun 2022 09:01:42.060 # +tilt #tilt mode entered
1:X 21 Jun 2022 09:01:42.136 # waitpid() returned a pid (233) we can't find in our scripts execution queue!
1:X 21 Jun 2022 09:02:12.111 # -tilt #tilt mode exited

$ k logs redis-node-2 --container sentinel
 09:01:06.26 INFO  ==> about to run the command: redis-cli -h redis.default.svc.cluster.local -p 26379 --tls --cert /opt/bitnami/redis/certs/tls.crt --key /opt/bitnami/redis/certs/tls.key --cacert /opt/bitnami/redis/certs/ca.crt sentinel get-master-addr-by-name redis-master
redis-node-0.redis-headless.default.svc.cluster.local
6379
 09:01:06.34 INFO  ==> about to run the command: redis-cli -h redis.default.svc.cluster.local -p 26379 --tls --cert /opt/bitnami/redis/certs/tls.crt --key /opt/bitnami/redis/certs/tls.key --cacert /opt/bitnami/redis/certs/ca.crt sentinel get-master-addr-by-name redis-master
 09:01:06.37 INFO  ==> printing REDIS_SENTINEL_INFO=(redis-node-0.redis-headless.default.svc.cluster.local,6379)
1:X 21 Jun 2022 09:01:06.565 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:X 21 Jun 2022 09:01:06.565 # Redis version=6.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:X 21 Jun 2022 09:01:06.565 # Configuration loaded
1:X 21 Jun 2022 09:01:06.568 * monotonic clock: POSIX clock_gettime
1:X 21 Jun 2022 09:01:06.570 # A key '__redis__compare_helper' was added to Lua globals which is not on the globals allow list nor listed on the deny list.
1:X 21 Jun 2022 09:01:06.570 * Running mode=sentinel, port=26379.
1:X 21 Jun 2022 09:01:06.570 # Sentinel ID is 3907ec64d3b20ba45124791ff23640c70d0a1f9a
1:X 21 Jun 2022 09:01:06.570 # +monitor master redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379 quorum 2
1:X 21 Jun 2022 09:01:16.673 * +convert-to-slave slave redis-node-2.redis-headless.default.svc.cluster.local:6379 redis-node-2.redis-headless.default.svc.cluster.local 6379 @ redis-master redis-node-0.redis-headless.default.svc.cluster.local 6379
1:X 21 Jun 2022 09:01:22.999 # +tilt #tilt mode entered
1:X 21 Jun 2022 09:01:24.793 # Error accepting a client connection: (null)
1:X 21 Jun 2022 09:01:53.006 # -tilt #tilt mode exited
```

**Comment by javsalgar** [comment] 2022-06-22 08:30
Does the same issue happen with autogenerated certificates? Just to see if the issue is in the redis configuration or the certificates.

**Comment by jaudiger** [comment] 2022-06-22 09:59
I just tested it with the following chart values:

```yml
auth:
  enabled: false
  sentinel: false

# Statefulset parameters
sentinel:
  enabled: true
  masterSet: redis-master
  downAfterMilliseconds: 4000
  failoverTimeout: 8000
  quorum: 2
  parallelSyncs: 1

replica:
  replicaCount: 3

tls:
  enabled: true
  autoGenerated: true
  authClients: true
```

And I got the same logs.

**Comment by carrodher** [comment] 2022-07-06 12:10
I was able to reproduce the issue as well by using the auto-generated certificate and a custom one. I just created an internal task to investigate the issue. I will add the `on-hold` label to prevent the Stale Bot from closing this issue.

Due to other priorities the team has, we can't provide an ETA for when this task will be completed, in case you would like to collaborate, PRs are welcome and the Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by HighWatersDev** [comment] 2022-07-22 19:16
In case it helps, I deployed redis-cluster chart v8.1.1 and seeing exact same behavior

values.yaml
```yaml
existingSecret: redis-password
existingSecretPasswordKey: redis-password
cluster:
  externalAccess:
    enabled: true
    service:
      loadBalancerIP: [10.x.x.20,10.x.x.21,10.x.x.22,10.x.x.23,10.x.x.24,10.x.x.25,10.x.x.26]
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
tls:
  enabled: true
  autoGenerated: true
  authClients: true
metrics:
  enabled: true
```

logs
```
1:M 22 Jul 2022 19:15:03.625 # Server initialized
1:M 22 Jul 2022 19:15:03.628 * DB loaded from append only file: 0.000 seconds
1:M 22 Jul 2022 19:15:03.628 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
1:M 22 Jul 2022 19:15:03.628 * Ready to accept connections
1:M 22 Jul 2022 19:15:15.594 # Error accepting a client connection: (null)
```

**Comment by rafariossaa** [comment] 2022-09-16 09:44
Hi @jaudiger ,
  Could you give it a try ?

**Comment by jaudiger** [comment] 2022-09-16 10:00
Hi @rafariossaa,

I'll let you know as soon as possible :smile: 
I'll deploy next week an environment with the updated chart, thanks for your PR.

**Comment by jaudiger** [comment] 2022-09-19 07:12
Hi @rafariossaa, I just tested it, and those logs are now gone ! Thanks, the issue has been fixed.

**Comment by rafariossaa** [comment] 2022-09-19 08:06
Hi,
  Thanks for confirming it. 
  I am closing this issue.

**Closed by rafariossaa** 2022-09-19 08:06 UTC
Labels: triage, tech-issues, redis
