### ISSUE TITLE
bitnami/grafana

### ISSUE THREAD

**Issue by StianHaugland1** [bitnami/charts#8370] opened 2021-12-10 15:45 UTC
**Which chart**:
bitnami/grafana 1.5.1 and newer

**Describe the bug**
When installing the helm chart:
`grafana-deployment-5cb67bd6b7-gz8wh   0/1     Init:CrashLoopBackOff   5          4m11s`

`kubectl logs grafana-deployment-db99cbddf-blqx6 grafana-plugins-init`
```
grafana 15:36:14.63 
grafana 15:36:14.63 Welcome to the Bitnami grafana container
grafana 15:36:14.64 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-grafana
grafana 15:36:14.64 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-grafana/issues
grafana 15:36:14.64 
grafana 15:36:14.66 INFO  ==> Detected mounted plugins directory at '/opt/plugins'. The container will exit after installing plugins as grafana-operator.
grafana 15:36:14.66 WARN  ==> There are no plugins to install
grafana 15:36:14.66 INFO  ==> ** Grafana setup finished! **

grafana 15:36:14.67 INFO  ==> ** Starting Grafana **
Error checking server process execution privilege. error: could not get current OS user to detect process privileges
t=2021-12-10T15:36:14+0000 lvl=info msg="The state of unified alerting is still not defined. The decision will be made during as we run the database migrations" logger=settings
t=2021-12-10T15:36:14+0000 lvl=warn msg="falling back to legacy setting of 'min_interval_seconds'; please use the configuration option in the `unified_alerting` section if Grafana 8 alerts are enabled." logger=settings
t=2021-12-10T15:36:14+0000 lvl=info msg="Config loaded from" logger=settings file=/opt/bitnami/grafana/conf/defaults.ini
t=2021-12-10T15:36:14+0000 lvl=info msg="Config loaded from" logger=settings file=/opt/bitnami/grafana/conf/grafana.ini
t=2021-12-10T15:36:14+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/opt/bitnami/grafana/data"
t=2021-12-10T15:36:14+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/opt/bitnami/grafana/logs"
t=2021-12-10T15:36:14+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/opt/bitnami/grafana/data/plugins"
t=2021-12-10T15:36:14+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/opt/bitnami/grafana/conf/provisioning"
t=2021-12-10T15:36:14+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.log.mode=console"
t=2021-12-10T15:36:14+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_DATA=/opt/bitnami/grafana/data"
t=2021-12-10T15:36:14+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_LOGS=/opt/bitnami/grafana/logs"
t=2021-12-10T15:36:14+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PLUGINS=/opt/bitnami/grafana/data/plugins"
t=2021-12-10T15:36:14+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_PATHS_PROVISIONING=/opt/bitnami/grafana/conf/provisioning"
t=2021-12-10T15:36:14+0000 lvl=info msg="Path Home" logger=settings path=/opt/bitnami/grafana
t=2021-12-10T15:36:14+0000 lvl=info msg="Path Data" logger=settings path=/opt/bitnami/grafana/data
t=2021-12-10T15:36:14+0000 lvl=info msg="Path Logs" logger=settings path=/opt/bitnami/grafana/logs
t=2021-12-10T15:36:14+0000 lvl=info msg="Path Plugins" logger=settings path=/opt/bitnami/grafana/data/plugins
t=2021-12-10T15:36:14+0000 lvl=info msg="Path Provisioning" logger=settings path=/opt/bitnami/grafana/conf/provisioning
t=2021-12-10T15:36:14+0000 lvl=info msg="App mode production" logger=settings
t=2021-12-10T15:36:14+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2021-12-10T15:36:14+0000 lvl=info msg="Creating SQLite database file" logger=sqlstore path=/opt/bitnami/grafana/data/grafana.db
Failed to start grafana. error: failed to connect to database: failed to create SQLite database file "/opt/bitnami/grafana/data/grafana.db": open /opt/bitnami/grafana/data/grafana.db: permission denied
failed to connect to database: failed to create SQLite database file "/opt/bitnami/grafana/data/grafana.db": open /opt/bitnami/grafana/data/grafana.db: permission denied
```

**To Reproduce**
`helm upgrade --install grafana-operator bitnami/grafana-operator --version=1.5.3`

**Expected behavior**
Grafana-deployment should get a running status

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I suspect that the change i the grafana docker image from: _8.2.2-debian-10-r5_ to _8.2.5-debian-10-r6_ causes this problem

**Comment by juan131** [comment] 2021-12-13 08:04
Duplicate of https://github.com/bitnami/bitnami-docker-grafana/issues/17

**Closed by juan131** 2021-12-13 08:04 UTC
