### ISSUE TITLE
[bitnami/minio] provisioning-job command error

### ISSUE THREAD

**Issue by clcc2019** [bitnami/charts#15758] opened 2023-03-28 01:33 UTC
### Name and Version

bitnami/minio:12.2.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/46099295/228103531-fcb831ac-d02c-4b03-9f17-f2a576982acc.png">

### What do you see instead?

mc: <ERROR> Incorrect command. Please use 'mc admin policy create'.

**Comment by clcc2019** [comment] 2023-03-28 01:33
and
```
mc: <ERROR> `create` is not a recognized command. Get help using `--help` flag.
```

**Comment by clcc2019** [comment] 2023-03-28 01:35
```
mc: <ERROR> Incorrect command. Please use 'mc admin policy attach'.
```

**Comment by javsalgar** [comment] 2023-03-28 08:26
Hi!

Thank you for opening the ticket. Closing it as a duplicate of https://github.com/bitnami/charts/issues/15675

**Closed by javsalgar** 2023-03-28 08:26 UTC
Labels: triage, tech-issues, minio
