### ISSUE TITLE
[bitnami/mongodb] Logging to stdout no longer default

### ISSUE THREAD

**Issue by lasseoe** [bitnami/charts#27150] opened 2024-06-13 11:03 UTC
### Name and Version

bitnami/mongodb 14.12.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy MongoDB chart >=14.12.0

### Are you using any custom parameters or values?

No, happens with the most basic setup possible.

### What is the expected behavior?

Logging to stdout instead of /opt/bitnami/mongodb/logs/mongodb.log

### What do you see instead?

In 14.12.0 a new empty-dir was introduced, MongoDB now logs to a file instead of stdout, meaning the default behavior has changed.

```yaml
  - name: empty-dir
    mountPath: /opt/bitnami/mongodb/logs
    subPath: app-logs-dir
```

### Additional information

I see no way of overriding this behavior, except by perhaps adding a custom configuration section, ie.

```yaml
configuration: |-
  systemLog:
    quiet: false
```

but no matter how I structure it, MongoDB errors out immediately.

There's no mention of this change in the commit message, README or CHANGELOG.

**Comment by blaluc** [comment] 2024-06-14 19:57
...and the empty-dir volume gets filled soon causing the mongodb pod to crash. Moreover, if you try to change the configuration to send the log to syslog, the users/databases declared in the auth.* values don't get to authenticate.

**Comment by jotamartos** [comment] 2024-06-24 13:38
Thank you for taking the time to report this issue. As you mentioned, the issue is caused by the introduction of the new empty dir volume that removes the symlink to stdout that the container creates.

https://github.com/bitnami/containers/blob/main/bitnami/mongodb/7.0/debian-12/rootfs/opt/bitnami/scripts/mongodb/postunpack.sh#L39

Let me work on creating a PR to solve this issue. We will let you know when it's ready. 

Thanks

**Comment by jotamartos** [comment] 2024-06-24 14:08
Hi,

Can you take a look at the attached PR and confirm that everything works as expected? 

https://github.com/bitnami/charts/pull/27510

Thanks

**Comment by lasseoe** [comment] 2024-06-25 08:29
> Hi,
> 
> Can you take a look at the attached PR and confirm that everything works as expected?
> 
> #27510
> 
> Thanks

Works as expected, thanks 👍 😃

**Comment by jotamartos** [comment] 2024-06-25 11:26
Great! I just merged the changes and a new version of the chart will be released soon.

**Closed** 2024-06-25 11:26 UTC
Labels: in-progress, tech-issues, mongodb
