### ISSUE TITLE
[bitnami/kafka] Kafka cannot start after upgrading, causing serious losses to our company

### ISSUE THREAD

**Issue by zjf88865** [bitnami/charts#25840] opened 2024-05-14 06:56 UTC
### Name and Version

bitnami/kafka 3.7.0

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Please refer to this serious bug. I have been raising it for a long time but have no plans to solve it. This bug has been bothering me for half a year and has seriously affected my testing environment. If used in a production environment, the severity can be imagined
`https://github.com/bitnami/charts/issues/25129`

### Are you using any custom parameters or values?

Can someone help me deal with this issue? Many people have encountered this bug, but why do administrators turn a blind eye to it
`https://github.com/bitnami/charts/issues/25129`

### What is the expected behavior?

Can someone help me deal with this issue? Many people have encountered this bug, but why do administrators turn a blind eye to it
`https://github.com/bitnami/charts/issues/25129`

### What do you see instead?

`https://github.com/bitnami/charts/issues/25129`

### Additional information

Can someone help me deal with this issue? Many people have encountered this bug, but why do administrators turn a blind eye to it
`https://github.com/bitnami/charts/issues/25129`

**Comment by javsalgar** [comment] 2024-05-14 07:51
Hi,

Thanks you for opening the issue. As I see this is a duplicate of https://github.com/bitnami/charts/issues/25129, let's continue the conversation there.

**Closed by javsalgar** 2024-05-14 07:51 UTC
Labels: triage, tech-issues, kafka
