### ISSUE TITLE
[bitnami/grafana-loki] gateway.ingress backend is pointing to wrong serviceName and servicePort

### ISSUE THREAD

**Issue by sandeeprohokale** [bitnami/charts#12195] opened 2022-08-29 23:05 UTC
### Name and Version

bitnami/grafana-loki 2.6.1

### What steps will reproduce the bug?

1. create aws eks cluster and have alb-controller running in cluster
2. deploy bitnami/grafana-loki helm-chart of version 2.6.1 with following overridden values
```
    gateway:
      ingress:`
	   enabled: true`
		pathType: ImplementationSpecific
		hostname: <domain_name>.com
		path: /*
		annotations:
			kubernetes.io/ingress.class: alb
			alb.ingress.kubernetes.io/load-balancer-name: your-load-balancer-name
			alb.ingress.kubernetes.io/scheme: internal
			alb.ingress.kubernetes.io/target-type: ip
			alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:<region>:<account_number>:certificate/<id_string>"
			external-dns.alpha.kubernetes.io/hostname: "<domain_name>.com"
```

3. check gateway-ingress object created in eks cluster. you will notice it is not pointing to gateway service.. for example, if deployed helm-chart name is grafana-loki. then gateway-ingress object backend service name is 'grafana-loki' and port is 'http'.  correct backend service name should be 'grafana-loki-gateway' and service port should be '80' (default)

### Are you using any custom parameters or values?

```
gateway:
	ingress:
	   enabled: true
		pathType: ImplementationSpecific
		hostname: <domain_name>.com
		path: /*
		annotations:
			kubernetes.io/ingress.class: alb
			alb.ingress.kubernetes.io/load-balancer-name: your-load-balancer-name
			alb.ingress.kubernetes.io/scheme: internal
			alb.ingress.kubernetes.io/target-type: ip
			alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:<region>:<account_number>:certificate/<id_string>"
			external-dns.alpha.kubernetes.io/hostname: "<domain_name>.com"


```
### What is the expected behavior?

deployed gateway.ingress  object should have backend service name as 'grafana-loki-gateway' and service port should be '80' (default value).
and when we try to access loki using http/https url, we should not get error message 'backend service is not available'

### What do you see instead?

deployed gateway.ingress  object should have backend service name as 'grafana-loki-gateway' and service port should be '80' (default value).

**Comment by fmulero** [comment] 2022-08-30 06:36
Hi @sandeeprohokale,

Could you edit the yaml code in the description? Please use [GitHub markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax), the yaml pasted in the description is not correct and we can not use it to reproduce your issue.

**Comment by sandeeprohokale** [comment] 2022-08-30 06:48
Hi Fran,
I updated yaml with correct formatting. note this yaml is just small
snippet of values.yaml from bitnami/grafana-loki chart

Thanks,
Sandeep

**Comment by sandeeprohokale** [comment] 2022-08-30 06:48
Hi Fran,I updated yaml with correct formatting. note this yaml is just small snippet of values.yaml from bitnami/grafana-loki chart

**Comment by fmulero** [comment] 2022-09-02 16:02
Thanks @sandeeprohokale  for opening this issue.

Yes it seems you are right about the backend service. The `ingress` object created for the gateway component should use as `backend`, the `service` created for that component. About using the 80 instead of `http`, I am not sure what you mean because we are using the named port and it should work.  Could you create a PR with your suggested changes? That would be great and we could see better your point

**Comment by sandeeprohokale** [comment] 2022-09-02 16:23
I already created PR (Pull Request) with suggested changes.. please let me know if you mean meaning something by PR

**Comment by fmulero** [comment] 2022-09-13 11:46
Please @sandeeprohokale  have look to your PR, you have little things to improve but I think is worth it to include your changes in the main branch

**Comment by erSitzt** [comment] 2022-09-20 14:09
Are you sure the PR is a fix for this problem ?

only enabling the ingress for the gateway and setting a hostname i end up with this 👍 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: loki2
    meta.helm.sh/release-namespace: loki
  labels:
    app.kubernetes.io/instance: loki2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana-loki
    helm.sh/chart: grafana-loki-2.4.0
    manager: helm
  name: loki2-grafana-loki-gateway
  namespace: loki
spec:
  ingressClassName: kong
  rules:
  - host: loki2.rke2-zentrale-monitoring.kong.mydomain.com
    http:
      paths:
      - backend:
          service:
            name: loki2-grafana-loki
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
```

Which refers to a service which does not exist.

And this is the list of services available after deploying
<img width="309" alt="image" src="https://user-images.githubusercontent.com/1625376/191279606-b1c83401-4c55-49ca-b13d-a73931efe6bb.png">

Using `loki2-grafana-loki-query-frontend` as the target service works, but thats not the change i can see in the PR, or is it ?

**Comment by fmulero** [comment] 2022-09-22 09:30
Hi

PR #12608 was merged yesterday. Could you check if chart version 2.4.1 solves the problem?

**Comment by fmulero** [comment] 2022-09-23 07:18
Is there something we can do from chart side?

**Comment by erSitzt** [comment] 2022-09-23 11:23
@fmulero if you are referring to the nginx config, im still not sure if this even is a problem or intentional 

I was just wondering that, when testing if the gateway is working it did not return "OK" directly in the browser, but triggered a download.

The nginx config is in your template here

https://github.com/bitnami/charts/blob/master/bitnami/grafana-loki/templates/gateway/configmap-http.yaml

but its the same config as in the grafana chart...

**Comment by fmulero** [comment] 2022-09-26 14:10
You right!, good catch! As you said the `default_type` is  `application/octet-stream` as in the oficial chart, probably is intentional. I think this is a question for grafana.

**Comment by erSitzt** [comment] 2022-09-26 14:53
I will open an issue and ask/let them know about this.
But their charts seem to be poorly tested... i already have two issues open there.. thats why i switched to bitnami :)

**Closed** 2022-09-28 11:05 UTC
Labels: solved, tech-issues, grafana-loki
