### ISSUE TITLE
[bitnami/kafka] Not able to setup a external kafka brokers with auth enabled

### ISSUE THREAD

**Issue by joaom182** [bitnami/charts#2112] opened 2020-03-22 14:15 UTC
**Which chart**:

Chart: kafka-8.0.1
App version: 2.4.1

**Description**

I'm trying to install a production ready kafka on my K8s cluster, but the Kafka container throw the follow exception.

```
2020-03-22T13:37:41.478971502Z [2020-03-22 13:37:41,474] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
2020-03-22T13:37:41.479010928Z org.apache.kafka.common.KafkaException: Exception while loading Zookeeper JAAS login context [java.security.auth.login.config=/opt/bitnami/kafka/conf/kafka_jaas.conf, zookeeper.sasl.client=default:true, zookeeper.sasl.clientconfig=default:Client]
2020-03-22T13:37:41.479017937Z 	at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:64)
2020-03-22T13:37:41.479023573Z 	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:384)
2020-03-22T13:37:41.479045328Z 	at kafka.server.KafkaServer.startup(KafkaServer.scala:207)
2020-03-22T13:37:41.479067855Z 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
2020-03-22T13:37:41.479073318Z 	at kafka.Kafka$.main(Kafka.scala:84)
2020-03-22T13:37:41.479078342Z 	at kafka.Kafka.main(Kafka.scala)
2020-03-22T13:37:41.479083234Z Caused by: java.lang.SecurityException: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
2020-03-22T13:37:41.479088535Z 	at java.base/sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137)
2020-03-22T13:37:41.479093816Z 	at java.base/sun.security.provider.ConfigFile.<init>(ConfigFile.java:102)
2020-03-22T13:37:41.479098912Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2020-03-22T13:37:41.479109991Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2020-03-22T13:37:41.479140903Z 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2020-03-22T13:37:41.479146332Z 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
2020-03-22T13:37:41.479151371Z 	at java.base/java.lang.Class.newInstance(Class.java:584)
2020-03-22T13:37:41.479156256Z 	at java.base/javax.security.auth.login.Configuration$2.run(Configuration.java:255)
2020-03-22T13:37:41.479161221Z 	at java.base/javax.security.auth.login.Configuration$2.run(Configuration.java:246)
2020-03-22T13:37:41.479166371Z 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2020-03-22T13:37:41.47917136Z 	at java.base/javax.security.auth.login.Configuration.getConfiguration(Configuration.java:245)
2020-03-22T13:37:41.479176496Z 	at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:60)
2020-03-22T13:37:41.479181414Z 	... 5 more
2020-03-22T13:37:41.479186244Z Caused by: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
2020-03-22T13:37:41.479192303Z 	at java.base/sun.security.provider.ConfigFile$Spi.ioException(ConfigFile.java:665)
2020-03-22T13:37:41.479214554Z 	at java.base/sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:262)
2020-03-22T13:37:41.479220285Z 	at java.base/sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:135)
2020-03-22T13:37:41.479225694Z 	... 16 more
2020-03-22T13:37:41.479927662Z [2020-03-22 13:37:41,479] INFO shutting down (kafka.server.KafkaServer)
2020-03-22T13:37:41.48791745Z [2020-03-22 13:37:41,487] INFO shut down completed (kafka.server.KafkaServer)
2020-03-22T13:37:41.488530219Z [2020-03-22 13:37:41,488] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
2020-03-22T13:37:41.500896133Z [2020-03-22 13:37:41,493] INFO shutting down (kafka.server.KafkaServer)
```

**Steps to reproduce the issue:**

1. Deploy a secret with kafka.keystore.jks and kafka.truststore.jks:
```
kubectl create secret generic kafka-certificates --from-file=./keystore/kafka.keystore.jks --from-file=./truststore/kafka.truststore.jks -n kafka-system
```
2. Install the cart:
```
helm install --name kafka --namespace kafka-system -f values-production.yml bitnami/kafka
```

Follow the [values-production.yml](https://gist.github.com/joaom182/02c46a1b990bfb077f1f3eac39ca6ac7) file sample that i've used

**Describe the results you received:**

```
NAME:   kafka
LAST DEPLOYED: Sun Mar 22 10:33:59 2020
NAMESPACE: kafka-system
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                     AGE
kafka-jmx-configuration  1s
kafka-scripts            1s

==> v1/Deployment
NAME                      AGE
kafka-exporter            1s
kafka-zookeeper-exporter  1s

==> v1/Pod(related)
NAME                                       AGE
kafka-0                                    1s
kafka-1                                    1s
kafka-2                                    0s
kafka-exporter-5c44bc5bbd-6mztk            1s
kafka-zookeeper-0                          1s
kafka-zookeeper-exporter-6b6566f584-w44wg  1s

==> v1/Secret
NAME             AGE
kafka            1s
kafka-zookeeper  1s

==> v1/Service
NAME                      AGE
kafka                     1s
kafka-0-external          1s
kafka-1-external          1s
kafka-2-external          1s
kafka-headless            1s
kafka-jmx-metrics         1s
kafka-metrics             1s
kafka-zookeeper           1s
kafka-zookeeper-exporter  1s
kafka-zookeeper-headless  1s

==> v1/ServiceAccount
NAME   AGE
kafka  1s

==> v1/StatefulSet
NAME             AGE
kafka            1s
kafka-zookeeper  1s

==> v1beta1/PodDisruptionBudget
NAME   AGE
kafka  1s


NOTES:


** Please be patient while the chart is being deployed **

Kafka can be accessed via port 9092 on the following DNS name from within your cluster:

    kafka.kafka-system.svc.cluster.local

To create a topic run the following command:

    export POD_NAME=$(kubectl get pods --namespace kafka-system -l "app.kubernetes.io/name=kafka,app.kubernetes.io/instance=kafka,app.kubernetes.io/component=kafka" -o jsonpath="{.items[0].metadata.name}")
    kubectl --namespace kafka-system exec -it $POD_NAME -- kafka-topics.sh --create --zookeeper kafka-zookeeper:2181 --replication-factor 1 --partitions 1 --topic test

To list all the topics run the following command:

    export POD_NAME=$(kubectl get pods --namespace kafka-system -l "app.kubernetes.io/name=kafka,app.kubernetes.io/instance=kafka,app.kubernetes.io/component=kafka" -o jsonpath="{.items[0].metadata.name}")
    kubectl --namespace kafka-system exec -it $POD_NAME -- kafka-topics.sh --list --zookeeper kafka-zookeeper:2181

To start a kafka producer run the following command:

    export POD_NAME=$(kubectl get pods --namespace kafka-system -l "app.kubernetes.io/name=kafka,app.kubernetes.io/instance=kafka,app.kubernetes.io/component=kafka" -o jsonpath="{.items[0].metadata.name}")
    kubectl --namespace kafka-system exec -it $POD_NAME -- kafka-console-producer.sh --broker-list 127.0.0.1:9092 --topic test --producer.config /opt/bitnami/kafka/conf/producer.properties

To start a kafka consumer run the following command:

    export POD_NAME=$(kubectl get pods --namespace kafka-system -l "app.kubernetes.io/name=kafka,app.kubernetes.io/instance=kafka,app.kubernetes.io/component=kafka" -o jsonpath="{.items[0].metadata.name}")
    kubectl --namespace kafka-system exec -it $POD_NAME -- kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9092 --topic test --consumer.config /opt/bitnami/kafka/conf/consumer.properties

To connect to your Kafka server from outside the cluster check the following information:

    Kafka brokers domain: Use your provided hostname to reach Kafka brokers, mydomain.com

    Kafka brokers port: You should have a different node port for each Kafka broker. The list of configured node ports is [31090 31091 31092]

    PRODUCER:
        kafka-console-producer.sh --broker-list 127.0.0.1:9092 --topic test --producer.config /opt/bitnami/kafka/conf/producer.properties
    CONSUMER:
        kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9092 --topic test --from-beginning --consumer.config /opt/bitnami/kafka/conf/consumer.properties

  NOTE: In order to connect to the cluster with an external client you need to properly specify the credentials stored in the JAAS file generated in the Kafka image.
        You should get the content of that file and write it in your host machine:

        export POD_NAME=$(kubectl get pods --namespace kafka-system -l "app.kubernetes.io/name=kafka,app.kubernetes.io/instance=kafka,app.kubernetes.io/component=kafka" -o jsonpath="{.items[0].metadata.name}")
        kubectl --namespace kafka-system exec -it $POD_NAME -- cat /opt/bitnami/kafka/conf/kafka_jaas.conf >> kafka_jaas.conf

        Finally, before using your client you need to export the following env var:

        export KAFKA_OPTS="-Djava.security.auth.login.config=/path/to/kafka_jaas.conf"

```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by marcosbc** [comment] 2020-03-23 10:58
Hi @joaom182, in your error we could see the error below:

```
2020-03-22T13:37:41.479083234Z Caused by: java.lang.SecurityException: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
```

Please note the message in the Helm chart's notes below:

```
  NOTE: In order to connect to the cluster with an external client you need to properly specify the credentials stored in the JAAS file generated in the Kafka image.
        You should get the content of that file and write it in your host machine:

        export POD_NAME=$(kubectl get pods --namespace kafka-system -l "app.kubernetes.io/name=kafka,app.kubernetes.io/instance=kafka,app.kubernetes.io/component=kafka" -o jsonpath="{.items[0].metadata.name}")
        kubectl --namespace kafka-system exec -it $POD_NAME -- cat /opt/bitnami/kafka/conf/kafka_jaas.conf >> kafka_jaas.conf

        Finally, before using your client you need to export the following env var:

        export KAFKA_OPTS="-Djava.security.auth.login.config=/path/to/kafka_jaas.conf"
```

Once you run those commands, it should work for you.

**Comment by joaom182** [comment] 2020-03-24 22:16
@marcosbc The problem is not on the client side, is on the server side, at the container of kafka broker.

```
2020-03-22T13:37:41.478971502Z [2020-03-22 13:37:41,474] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
2020-03-22T13:37:41.479010928Z org.apache.kafka.common.KafkaException: Exception while loading Zookeeper JAAS login context [java.security.auth.login.config=/opt/bitnami/kafka/conf/kafka_jaas.conf, zookeeper.sasl.client=default:true, zookeeper.sasl.clientconfig=default:Client]
2020-03-22T13:37:41.479017937Z 	at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:64)
2020-03-22T13:37:41.479023573Z 	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:384)
2020-03-22T13:37:41.479045328Z 	at kafka.server.KafkaServer.startup(KafkaServer.scala:207)
2020-03-22T13:37:41.479067855Z 	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
2020-03-22T13:37:41.479073318Z 	at kafka.Kafka$.main(Kafka.scala:84)
2020-03-22T13:37:41.479078342Z 	at kafka.Kafka.main(Kafka.scala)
2020-03-22T13:37:41.479083234Z Caused by: java.lang.SecurityException: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
2020-03-22T13:37:41.479088535Z 	at java.base/sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137)
2020-03-22T13:37:41.479093816Z 	at java.base/sun.security.provider.ConfigFile.<init>(ConfigFile.java:102)
2020-03-22T13:37:41.479098912Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2020-03-22T13:37:41.479109991Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2020-03-22T13:37:41.479140903Z 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2020-03-22T13:37:41.479146332Z 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
2020-03-22T13:37:41.479151371Z 	at java.base/java.lang.Class.newInstance(Class.java:584)
2020-03-22T13:37:41.479156256Z 	at java.base/javax.security.auth.login.Configuration$2.run(Configuration.java:255)
2020-03-22T13:37:41.479161221Z 	at java.base/javax.security.auth.login.Configuration$2.run(Configuration.java:246)
2020-03-22T13:37:41.479166371Z 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2020-03-22T13:37:41.47917136Z 	at java.base/javax.security.auth.login.Configuration.getConfiguration(Configuration.java:245)
2020-03-22T13:37:41.479176496Z 	at org.apache.kafka.common.security.JaasUtils.isZkSecurityEnabled(JaasUtils.java:60)
2020-03-22T13:37:41.479181414Z 	... 5 more
2020-03-22T13:37:41.479186244Z Caused by: java.io.IOException: /opt/bitnami/kafka/conf/kafka_jaas.conf (No such file or directory)
2020-03-22T13:37:41.479192303Z 	at java.base/sun.security.provider.ConfigFile$Spi.ioException(ConfigFile.java:665)
2020-03-22T13:37:41.479214554Z 	at java.base/sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:262)
2020-03-22T13:37:41.479220285Z 	at java.base/sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:135)
2020-03-22T13:37:41.479225694Z 	... 16 more
2020-03-22T13:37:41.479927662Z [2020-03-22 13:37:41,479] INFO shutting down (kafka.server.KafkaServer)
2020-03-22T13:37:41.48791745Z [2020-03-22 13:37:41,487] INFO shut down completed (kafka.server.KafkaServer)
2020-03-22T13:37:41.488530219Z [2020-03-22 13:37:41,488] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
2020-03-22T13:37:41.500896133Z [2020-03-22 13:37:41,493] INFO shutting down (kafka.server.KafkaServer)
```

**Comment by marcosbc** [comment] 2020-03-31 11:00
@joaom182 I could finally reproduce your issue.

After some investigation, I could determine that it is happening because of enabling `externalAccess` in the chart.

Enabling it has a secondary effect, and it is that the initialization command is changed to `/scripts/setup.sh` and Kafka environment variables for listeners are getting overridden to INTERNAL/EXTERNAL values instead of SASL/SSL/PLAINTEXT listeners. KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP is also getting overwritten. See [scripts-configmap.yaml](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/scripts-configmap.yaml) for more information.

Therefore it seems like `setup.sh` does not support non-standard listeners and therefore `externalAccess` would not support your use case (yet). It seems like Kafka [supports](https://cwiki.apache.org/confluence/display/KAFKA/KIP-103%3A+Separation+of+Internal+and+External+traffic) internal/external listeners for SASL/Plaintext/SSL so it should not be easy to add support for, depending on the values enabled in the chart.

We understand this is a bug, so I have created an internal task for fixing this. Unfortunately, I'm unable to give an ETA for when this would be fixed. In any case, we're open to contributions so if you are able to identify a fix for this, we would be glad to review it.

**Comment by carrodher** [comment] 2022-10-20 13:19
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.

**Closed by carrodher** 2022-10-20 13:19 UTC
Labels: on-hold
