### ISSUE TITLE
[bitnami/mlflow] Add support for Azure Storage

### ISSUE THREAD

**Issue by hatemhamad** [bitnami/charts#28569] opened 2024-07-29 19:08 UTC
### Name and Version

bitnami/mlflow 1.4.12

### What is the problem this feature will solve?

The MLFlow chart uses a docker image that do not support using azure storage accounts for storing artifacts, while MLFlow itself does support it.

Adding such support will make it easier to integrate MLFlow artifacts into the Microsoft cloud storage. Currently there is support for Amazon S3 and newly for Google GCS in the `2.14.1-debian-12-r1` image tag, see #22720.

### What is the feature you are proposing to solve the problem?

Adding the missing Python module `azure-storage-blob` to the mlflow image will fix the issue since MLFlow already provides support

### What alternatives have you considered?

I have built a light image using the original bitnami mlflow image as base while including the `azure-storage-blob` module

**Comment by Adam-D-Lewis** [comment] 2024-09-02 04:46
I'm also interested in this.

**Comment by jotamartos** [comment] 2024-09-03 08:49
Sorry for the late reply here. We are going to review this request and will update the ticket once we have more information.

**Comment by jotamartos** [comment] 2024-09-17 09:21
Hi @hatemhamad,

We just added "azure-storage-blob" to our compilation recipe. The next docker image and chart will include support for Azure storage. 

I'll close this ticket but please reopen it if necessary.

**Closed by jotamartos** 2024-09-17 09:21 UTC
Labels: in-progress, feature-request, mlflow

**Comment by eriadam** [comment] 2024-09-19 14:09
hi @jotamartos, should this already be available? 
I still only see GCS and S3 in the [helm chart values](https://artifacthub.io/packages/helm/bitnami/mlflow/1.5.7?modal=values).

**Comment by jotamartos** [comment] 2024-09-19 14:27
[The image the chart is using](https://github.com/bitnami/charts/pull/29534) includes the azure pip package

```
root@d0a5f3feab46:/app# pip list | grep azure
azure-core                         1.31.0
azure-storage-blob                 12.22.0
``` 

[Would you like to contribute](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) to the project and update the chart with the Azure storage settings? You would need to perform similar changes to these ones 

https://github.com/bitnami/charts/commit/2c6d076252331b0ab641750cb0f742a5b3bb41d6

**Comment by eriadam** [comment] 2024-09-19 15:31
Thanks! Sure, let me give it a try.

**Comment by eriadam** [comment] 2024-09-20 07:44
@jotamartos I was able to [make the modifications](https://github.com/bitnami/charts/compare/main...golden-whale-productions:charts:feature/mlflow-azure-storage), but while testing it, I get this error message.

It looks like `azure-identity` is a required package.

```
    return repository(artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.12/site-packages/mlflow/store/artifact/azure_blob_artifact_repo.py", line 74, in __init__
    raise ImportError(
ImportError: Using DefaultAzureCredential requires the azure-identity package. Please install it via: pip install azure-identity
2024/09/20 07:38:55 ERROR mlflow.server: Exception on /api/2.0/mlflow-artifacts/artifacts/1/4699c470f1644995b54cd437629bab44/artifacts/sklearn-model/python_env.yaml [PUT]
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.12/site-packages/mlflow/store/artifact/azure_blob_artifact_repo.py", line 72, in __init__
    from azure.identity import DefaultAzureCredential
ModuleNotFoundError: No module named 'azure.identity'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.12/site-packages/mlflow/server/handlers.py", line 574, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.12/site-packages/mlflow/server/handlers.py", line 596, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.12/site-packages/mlflow/server/handlers.py", line 2186, in _upload_artifact
    artifact_repo = _get_artifact_repo_mlflow_artifacts()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.12/site-packages/mlflow/server/handlers.py", line 206, in _get_artifact_repo_mlflow_artifacts
    _artifact_repo = get_artifact_repository(os.environ[ARTIFACTS_DESTINATION_ENV_VAR])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.12/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 132, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.12/site-packages/mlflow/store/artifact/artifact_repository_registry.py", line 77, in get_artifact_repository
    return repository(artifact_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bitnami/python/lib/python3.12/site-packages/mlflow/store/artifact/azure_blob_artifact_repo.py", line 74, in __init__
    raise ImportError(
ImportError: Using DefaultAzureCredential requires the azure-identity package. Please install it via: pip install azure-identity
```

**Comment by jotamartos** [comment] 2024-09-20 11:52
>It looks like azure-identity is a required package. I did not find where to change the compilation recipe.

Can you rebuild the bitnami/mlflow image adding the pip command to install azure-identity and confirm that everything works as expected?

**Comment by eriadam** [comment] 2024-09-20 14:23
I can confirm that it works, [here is my image](https://hub.docker.com/layers/blackmirrormedia/mlflow/amd64/images/sha256-9899ebb092a5493e03b83f4b492d6743da38286e579eadd23dfb602a86aad165?context=repo).

**Comment by eriadam** [comment] 2024-09-26 14:50
@jotamartos Hi, here is a draft PR for the change, would you mind having a look at it?
https://github.com/bitnami/charts/pull/29626

I am also not sure how to add the missing `azure-identity` package in the base image. Your help would be appreciated there. 

Thanks!
