### ISSUE TITLE
[Bitnami] External Access fails on Liveness/Readiness

### ISSUE THREAD

**Issue by ThePoipoi** [bitnami/charts#2765] opened 2020-06-05 10:42 UTC
**Which chart**:
kafka-10.3.3

**Describe the bug**
We have two Kubernetes cluster (A and B); Kafka server is running on the cluster A. We want to allow access to a Kafka client from cluster B. To do that, we try to use the "ExternalAccess" option but fails on several points. Our last step : Readiness and Liveness probe both failed, even if we do not change anything on this point (except activate ExternalAccess).
We didn't change a lot of thing from the original values.yaml, except:

- service.type: NodePort
- service.nodePorts: kafka: "31999"
- externalAccess.enabled: true
- externalAccess.service.type: NodePort
- externalAccess.service.nodePorts: [31998]
- persistence.enabled: false
- volumePermissions.enabled: false
- zookeeper.enabled: false
- externalZookeeper.servers: kafka-zookeeper:2181

(we did use your own Zookeeper to disable persistence, because we don't want it and have some troubles with Persistent Volumes)

**To Reproduce**
Use our values.yaml config file. The installation result on:
`Liveness probe failed: dial tcp 10.233.110.120:9092: connect: connection refused; 
Container kafka failed liveness probe, will be restarted; 
Readiness probe failed: dial tcp 10.233.110.120:9092: connect: connection refused
`
[values.txt](https://github.com/bitnami/charts/files/4735530/values.txt)

**Expected behavior**
Have a running Kafka cluster that allowing external access

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Thanks for your help :)

**Comment by javsalgar** [comment] 2020-06-08 13:29
Hi,

Do the logs show anything meaningful regarding the configuration? Does it work when you try to use the shipped zookeeper (even though it is not the one you want to use, it is for discarding causes of the issue)?

**Comment by ThePoipoi** [comment] 2020-06-08 13:53
There is no log on this case, cause the pod doesn't even start.
And it's not working either with shipped Zookeeper, cause we can't instantiate Persistance Volume on those environnements (we don't have right access and we're not supposed to be on our project).

Here is two file : the first one (logs) are what we see at deployment, and the second one is the result of a "describe" command on the kafka pod

[kafka_describe.txt](https://github.com/bitnami/charts/files/4746346/kafka_describe.txt)
[kafka_logs.txt](https://github.com/bitnami/charts/files/4746347/kafka_logs.txt)

I know there is a warning is the logs, but we don't want any authentication process from external access

Thanks

**Comment by javsalgar** [comment] 2020-06-08 13:59
Hi,

Could you try it using the shipped zookeeper with zookeeper.persistence.enabled=false? With that you shouldn't see any PVC.

**Comment by ThePoipoi** [comment] 2020-06-08 15:55
Same behavior :/

**Comment by javsalgar** [comment] 2020-06-09 09:17
This is very strange. Is the application usable when disabling the liveness/readiness probes? I want to know if the issue is in the probe or in the application startup.

**Comment by ThePoipoi** [comment] 2020-06-09 09:39
That's the point that triggered me...even if I disabled both (or only one) liveness/readiness parameter, I have both error probes messages...
And the kafka pod never start because of that, I can't see its logs and only can use the describe command on it.

It's a weird behavior, and I've tried to disabled one or both parameter because I've found an issue on it logged on StackOverflow. But even with this solution, it doesn't work

**Comment by javsalgar** [comment] 2020-06-10 10:45
That's weird. Could you execute kubectl get pods -o yaml (with the name of the pod) to see if the readiness/liveness probes are set?

**Comment by javsalgar** [comment] 2020-06-11 10:05
Hi,

I think I see what the issue is, even though if you set the livenessProbe as null it will be included anyway. I will work on fixing the issue, as it is a bug in our side. I will let you know when I have a PR.

**Comment by javsalgar** [comment] 2020-06-11 10:18
Hi,

I created this PR https://github.com/bitnami/charts/pull/2809

**Comment by ThePoipoi** [comment] 2020-06-11 14:13
Good news that you have fix the liveness/readiness issue.

But does this will also fix this External Access problem ? Because my first purpose is to have 2 K8S cluster with 2 kafka that can communicate

**Closed** 2020-06-12 13:43 UTC
