### ISSUE TITLE
Wordpress chart with NFS can't launch more than 1 pod

### ISSUE THREAD

**Issue by fcortijo-waldo** [bitnami/charts#908] opened 2018-11-01 16:27 UTC
I'm using NFS storage class and ReadWriteMany accessMode. The chart can create the first WP pod without any problem, but when I try to scale the deployment the second pod fails with the error:
```
 Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
**Error executing 'postInstallation': EINVAL: invalid argument, open '/opt/bitnami/apache/conf/vhosts/00_status-vhost.conf'**
```

**Comment by juan131** [comment] 2018-11-06 08:13
Hi @fcortijo-waldo 

Could you share the NFS provider you're using and parameters you setup when deploying the chart? 
Please also let us know the version of Kubernetes and Helm you're using. I just want to reproduce the issue.

Interesting read: https://engineering.bitnami.com/articles/scaling-wordpress-in-kubernetes.html

**Comment by fcortijo-waldo** [comment] 2018-11-07 14:46
Hi Juan, 
To deploy the NFS I used:
helm install stable/nfs-server-provisioner --set persistence.enabled=true,persistence.size=20Gi

Helm version:
 Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

And to deploy WP chart I set persistence.storageClass=nfs,persistence.accessMode=ReadWriteMany,persistence.size=15Gi

**Comment by fcortijo-waldo** [comment] 2018-11-07 14:48
Inpecting WP PV:
kubectl get pv pvc-daeb83e0-ddf0-11e8-a542-027545120590 -o json | jq .spec
{
  "accessModes": [
    "ReadWriteMany"
  ],
  "capacity": {
    "storage": "15Gi"
  },
  "claimRef": {
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "name": "waldo-marcom-next-waldo-marcom-next",
    "namespace": "default",
    "resourceVersion": "77927176",
    "uid": "daeb83e0-ddf0-11e8-a542-027545120590"
  },
  "nfs": {
    "path": "/export/pvc-daeb83e0-ddf0-11e8-a542-027545120590",
    "server": "100.65.36.1"
  },
  "persistentVolumeReclaimPolicy": "Retain",
  "storageClassName": "nfs"
}

**Comment by juan131** [comment] 2018-11-09 09:35
Hi @fcortijo-waldo 

I was unable to reproduce the issue. These are the steps I followed:

- Ensure my cluster has NFS packages installed: `sudo apt-get install nfs-common`
- Install NFS provider:

```
$ helm install --name nfs-server-provisioner stable/nfs-server-provisioner --set persistence.enabled=true,persistence.size=5Gi
```

- Once the NFS provide is running, install WP chart:

```
$ helm install --name wordpress stable/wordpress --set persistence.storageClass=nfs --set persistence.accessMode=ReadWriteMany --set persistence.size=2Gi
```

- Wait for WordPress to be initialised on first pod:


```
$ kubectl logs -f $(kubectl get pods -l app=wordpress-wordpress -o jsonpath='{.items[0].metadata.name}')
...
nami    INFO  wordpress successfully initialized
INFO  ==> Starting wordpress...
...
```

- Scale WP deployment:

```
$ kubectl scale deploy wordpress-wordpress --replicas 2
deployment.extensions/wordpress-wordpress scaled
```

- Get logs from second pod:

```
$ kubectl logs -f $(kubectl get pods -l app=wordpress-wordpress -o jsonpath='{.items[1].metadata.name}')

Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
apache  INFO  ==> Configuring dummy certificates...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing libphp
nami    INFO  libphp successfully initialized
nami    INFO  Initializing wordpress
wordpre INFO  WordPress has been already initialized, restoring...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at wordpress-mariadb:3306
mysql-c INFO  MySQL server listening and working at wordpress-mariadb:3306
wordpre INFO  Upgrading WordPress Database ...
wordpre INFO
wordpre INFO  ########################################################################
wordpre INFO   Installation parameters for wordpress:
wordpre INFO     Persisted data and properties have been restored.
wordpre INFO     Any input specified will not take effect.
wordpre INFO   This installation requires no credentials.
wordpre INFO  ########################################################################
wordpre INFO
nami    INFO  wordpress successfully initialized
INFO  ==> Starting wordpress...
```

As you can see everything is working as expected.

More info:

```
$ kubectl get pvc
NAME                                                       STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-illocutionary-umbrellabird-nfs-server-provisioner-0   Pending                                                                        fast-disks     18m
data-nfs-server-provisioner-0                              Bound     local-pv-5de620da                          19Gi       RWO            fast-disks     14m
data-wordpress-mariadb-0                                   Bound     local-pv-b4f1ccac                          19Gi       RWO            fast-disks     6m
wordpress-wordpress                                        Bound     pvc-e2ea5beb-e401-11e8-b8a0-0abeb86b59b0   2Gi        RWX            nfs            6m
$ kubectl get pv pvc-e2ea5beb-e401-11e8-b8a0-0abeb86b59b0
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                         STORAGECLASS   REASON    AGE
pvc-e2ea5beb-e401-11e8-b8a0-0abeb86b59b0   2Gi        RWX            Delete           Bound     default/wordpress-wordpress   nfs                      6m17s
```

**Comment by juan131** [comment] 2018-11-29 07:59
Hi @PhilippeDupont 

Did you set `--set persistence.accessMode=ReadWriteMany` when deploying the chart? The PVC should be configured with `ReadWriteMany` if you do so.

**Comment by PhilippeDupont** [comment] 2018-11-29 09:01
Hi @juan131
Like @fcortijo-waldo I use the nfs provisioner with a ReadWriteMany PVC. But I had the same error.
I was just pointing that when you was unable to reproduce, this is because you created a ReadWriteOnce PVC.

I ended up by creating a ReadWriteOnce PVC to make it work but this doen't allow me to use more replicas.

**Comment by varsis** [comment] 2018-12-04 19:59
same issue here would like to know a solution if there is one.

**Comment by brosner** [comment] 2018-12-04 20:20
I hate to leave yet another comment basically saying me too, but me too! I followed the chart documentation and ended up in the same situation and came across this issue.

I will point out that @juan131 comment showing this a non-issue could have been the same pod both times (or perhaps it did work then), but I can say with a lot of confidence there is a real issue here.

I am hoping to find time very soon to dig in and provide more details, but please don't rely on me.

**Comment by grischa** [comment] 2018-12-04 20:57
FWIW, you can actually run multiple replicas and auto-scaling right now by just deleting the file that causes the error regularly, e.g. using a "while true; sleep" loop or a cron job in the NFS pod.
However, when several pods start at the same time there can still be a problem and it can take time for them all to start up successfully.

**Comment by juan131** [comment] 2018-12-12 08:05
Hi everyone, 

Did you install the chart with several replicas or did you install the chart with just one replica and then you scale it?

The first method should work without issues. I mean:
 - Install the cart with 1 replica.
 - Wait for it to initialise the first pod
 - Scale the deployment

If you install the chart with several replicas, there could be conflicts since several pods could consider they need to initialise WordPress

**Comment by kirkre** [comment] 2018-12-12 08:57
I am also seeing this issue. I used RWO for the default nfs provisioner PVC, and RWX for the WP PVC as recommended by bitnami. PhilippeDupont seemed to imply this was the reason  juan131 could not duplicate the issue, but I have the same configuration as juan131 used, and I still have the issue everyone else is seeing. 

I think juan131 accurately requested the logs for the second pod specifically. When I tried the same syntax for reading the logs on my cluster, I got the logs for the first pod with .items[1] and the second pod with .items[0], so I am not  completely sure this couldn't have been mixed up as brosner suggested. However, juan131 showed that .items[0] did call the status of the first pod initially. Unless the positions of his pods could have been switched the other way around by the time he got the logs, I have to assume there was also no reason to doubt the test results in this regard. 

Some additional options I found were needed for the nfs provisioner, which are spelled out in the  nfs provisoner readme, were 'persistence.storageClass="standard"' and 'storageClass.defaultClass=true'. I can only guess this might be needed now due to a change in the nfs provisoner defaults, since I see others have recently had the same issues I had before adding these options. Specifically the nfs provisioner silently failed to provide a pvc for wordpress, although it worked for mariadb before I added the additional options. I don't think this will throw any light on the issue being outlined here, but just to document how I set this up.

Not sure I understand grischa's suggestion. In the hopes of finding something out, I tried deleting 00_status-vhost.conf and keeping it deleted as the file was automatically replaced, while trying to scale up pods, but it did not help. 

As far as I can guess so far, new pods are simply unable to access the PVC. 00_status-vhost.conf is the first file the postInstallation tries to access, and the pod/container simply can not access the PVC.

**Comment by kirkre** [comment] 2018-12-12 09:01
> Hi everyone,
> 
> Did you install the chart with several replicas or did you install the chart with just one replica and then you scale it?
> 
> The first method should work without issues. I mean:
> 
> * Install the cart with 1 replica.
> * Wait for it to initialise the first pod
> * Scale the deployment
> 
> If you install the chart with several replicas, there could be conflicts since several pods could consider they need to initialise WordPress

I installed the chart with one replica, and then only tried to scale it up with more replicas after it was fully deployed.

**Comment by PhilippeDupont** [comment] 2018-12-12 14:07
@juan131 I was successfully able to scale up the deployment as you suggested.
I had my chart deployed with 1 replica and a ReadWriteOnce PVC created by the nfs-server-provisioner

The problem is still when using a ReadWriteMany as wordpress does not start

**Comment by kirkre** [comment] 2018-12-12 20:48
@PhilippeDupont, your WP was deployed with a RWO PVC not RWX? For me the whole point of using NFS is to be able to have a RWX PVC for WP. @juan131 did I misunderstand and you also had to use a RWO PVC for WP in order for scaling to work?

**Comment by kirkre** [comment] 2018-12-13 01:19
> FWIW, you can actually run multiple replicas and auto-scaling right now by just deleting the file that causes the error regularly, e.g. using a "while true; sleep" loop or a cron job in the NFS pod.
> However, when several pods start at the same time there can still be a problem and it can take time for them all to start up successfully.

I was able to get this to work after all, thanks! I noticed later that when 00_status-vhost.conf was deleted it got stuck instead on php-fpm-apache.conf which you also mentioned earlier. By deleting both in a loop as you suggest, multiple replicas spin up instantly with no other issues. This proves it's not a PVC access issue and allows me to move ahead testing other things pending a better resolution for this.

**Comment by juan131** [comment] 2018-12-13 12:30
Hi @kirkre 

> @PhilippeDupont, your WP was deployed with a RWO PVC not RWX?

No, I used a RWX:

```
kubectl get pvc wordpress-wordpress -o jsonpath='{.spec.accessModes}'
[ReadWriteMany]
```

To do so, I used the flags below when installing the chart:

```
--set persistence.storageClass=nfs --set persistence.accessMode=ReadWriteMany
```

I'd like to understand what's the problem with **00_status-vhost.conf** and **php-fpm-apache.conf**.  The configuration file `httpd.conf` contains the line:

```
IncludeOptional /opt/bitnami/apache/conf/vhosts/*.conf
```

And.. `/opt/bitnami/apache/conf` it's a symlink to `/bitnami/apache/conf` where the configuration files should be persisted. For some reason, Apache can't open the file and it makes the initialisation to fail:

```
nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
Error executing 'postInstallation': EINVAL: invalid argument, open '/opt/bitnami/apache/conf/vhosts/00_status-vhost.conf'
```

Could it be related with NFS sync the files? It seems that after some pod restart it works fine.. Maybe it's trying to initialise Apache before the files are totally sync.

**Comment by kirkre** [comment] 2018-12-13 22:06
Hi juan131. I have been thinking the same thing about the error occurring before the PVC is completely attached, but I didn't realize the error was simply caused by Apache failing to open the files. Personally I could live with the Apache config files being outside of the NSF if needed, but as far as the project goes that would probably leave something to be desired. If this is caused by a delay in syncing to the PVC then that could depend on the environment and explain why not everyone gets the error. I'm running this right now on GKE for what it's worth. 

Delaying the startup of Apache might be one way of testing this. If that solved the issue I wonder would it compromise website performance during scaling? Do you know of any way to delay Apache startup without requiring a new container image?

**Comment by kirkre** [comment] 2018-12-14 09:44
On second thought this wouldn't explain why deleting the problem conf files fixes the issue. If the NSF is not available, how does Apache even tell whether the files are there or not? If I delete the problem conf files manually, without a script that keeps the files deleted, then when the first replica comes on line it replaces the files and starts without issues. But the second replica fails now that the files exist. This seems more like a permission issue to me.  Could Apache have the wrong credentials to open or overwrite the files when the replica first starts up?

**Comment by kirkre** [comment] 2018-12-17 00:57
Changing the permissions did not help for me either, only changing the config files owner and group to 1001 allowed replicas to start with the problem config files in place. My understanding is that the bitnami images are set up to connect with user id 1001 by default, but the permissions needed for this are only in place when a container is deployed, which might explain why not everyone seems to have the issue. The deployment timing could differ by environment.

After reading over the  docs you linked I'm going to try turning on squash and setting the gid to 1001 when I get a chance. When I tried to find a way to turn off squash I remember finding the kubernetes-incubator/nfs-provisioner docs, but at the time I thought it was an unrelated project. Now I see this is what is used by /stable/nfs-server-provisioner. Squash with gid 1001 may be exactly what the original bitnami developer intended to be in place for the containers. We will see.

**Comment by juan131** [comment] 2018-12-17 14:42
> chown the problem files to 1001:1001 and replicas start up no problems
> ...
> Changing the permissions did not help for me either, only changing the config files owner and group to 1001 allowed replicas to start with the problem config files in place. My understanding is that the bitnami images are set up to connect with user id 1001 by default, but the permissions needed for this are only in place when a container is deployed

Most Bitnami images have been moved to a "non-root" approach (more info about the reason on this [link](https://docs.bitnami.com/containers/how-to/work-with-non-root-containers/). Those non-root images use the user `1001` to run their daemons and, therefore, charts like MariaDB configure the proper securityContext to do so (see for instance: https://github.com/helm/charts/blob/master/stable/mariadb/templates/master-statefulset.yaml#L35)

However, WordPress **hasn't been moved non-root** yet (see https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-9/Dockerfile). Therefore, there's no need of modifying the owner/group to 1001:1001.

I already identified the issue and I'm working a new release of WP image fixing it.

**Comment by juan131** [comment] 2018-12-17 15:01
JFYI it's related to an error on PHP & Apache initialisations scripts. It assumes it has to render some template but it shouldn't render it since the file already exist and has been sync via NFS.

I'll update this issue as soon as the new image it's released.

Thanks so much for reporting this issue!!

**Comment by juan131** [comment] 2018-12-17 17:19
Hi everyone,

Could you try using the latest image `bitnami/wordpress:5.0.1-r2`?? The problem should be fixed now.

```
$ helm install --name wordpress stable/wordpress --set persistence.storageClass=nfs --set persistence.accessMode=ReadWriteMany --set image.repository=bitnami/wordpress --set image.tag=5.0.1-r2
$ kubectl scale deploy wordpress-wordpress --replicas 2
```

**Comment by kirkre** [comment] 2018-12-17 21:07
Thanks juan131. Scaling works out of the box now. The default Wordpress site formatting is messed up however. Is that a problem with the container image? 

I started to realize last night the Wordpress container could not be running as non root. All the other bitnami images that run as non-root have this documented from the beginning, and if that were the issue here it would not only be two files that had an access issue. I wonder why changing the ownership of these files to 1001:1001 resolved the issue though. Do you have an explanation for that, just to satisfy my curiosity?

**Comment by juan131** [comment] 2018-12-18 08:31
Hi @kirkre 

I did not find any issue with CSS (check the screenshot below). Did you obtain any error in your browser console?

<img width="1277" alt="screenshot 2018-12-18 at 09 30 09" src="https://user-images.githubusercontent.com/6740773/50141400-b0c4eb00-02a7-11e9-8813-4508a20b24b5.png">

> I wonder why changing the ownership of these files to 1001:1001 resolved the issue though. Do you have an explanation for that, just to satisfy my curiosity?

I don't know how that could be working for you. I understand the solution @grischa shared about deleting the files but the ownership solution it's a mystery to me.

**Comment by kirkre** [comment] 2018-12-18 09:23
> Hi @kirkre
> 
> I did not find any issue with CSS (check the screenshot below). Did you obtain any error in your browser console?
> 

I get the same appearance and no console errors regardless of browser:

![defaultwp](https://user-images.githubusercontent.com/17855643/50143292-43e72c00-027a-11e9-9f61-a45caeaab26d.png)

**Comment by juan131** [comment] 2018-12-18 16:14
Hi @kirkre 

That's how WP 5 looks like! It's just the base theme which is not very beautiful to be honest. You can customize the default theme in the Admin Panel:

<img width="1271" alt="screenshot 2018-12-18 at 17 12 15" src="https://user-images.githubusercontent.com/6740773/50166915-3f595c80-02e8-11e9-8fa4-e60064d2ed93.png">

**Comment by kirkre** [comment] 2018-12-18 20:13
> Hi @kirkre
> 
> That's how WP 5 looks like! It's just the base theme which is not very beautiful to be honest. You can customize the default theme in the Admin Panel:
> 
Thanks I didn't realize this was WP5 or that the default WP5 site was so bare bones. In the end I will migrate existing Wordpress sites rather than build a new site, just noted this in case it could be an issue with the container.

**Comment by juan131** [comment] 2018-12-19 07:48
Great!! Could we considered this issue solved? Please feel free to close it in case you think the latest images fix the issue with NFS

**Comment by kirkre** [comment] 2018-12-19 20:33
Everything is solved for me thanks, but I didn't open the issue and wonder whether this fixes scaling for everyone.

**Comment by juan131** [comment] 2018-12-20 08:48
Great!! I'll proceed to close the issue, but please do hot hesitate to reopen it if you face issues with replication with NFS providers.

**Closed by juan131** 2018-12-20 08:48 UTC
