### ISSUE TITLE
[bitnami/redis] NodePort configuration can point user to wrong direction for redis sentinel setup

### ISSUE THREAD

**Issue by kuzm1ch** [bitnami/charts#4622] opened 2020-12-06 21:54 UTC
**chart name**:
redis

**Bug/feature request**
NodePort configuration can point the user in the wrong direction for Redis sentinel setup. 

As I understood sentinel should work as on picture below. 
<img width="664" alt="Screenshot 2020-12-06 at 23 38 06" src="https://user-images.githubusercontent.com/32264674/101293088-2bcc9680-381c-11eb-9091-c65208f7c01a.png">
Client try to get  retrieve master ip from sentinel and it will receive private pod ip.
```
127.0.0.1:26379> SENTINEL get-master-addr-by-name mymaster 
1) "10.0.1.35"
2) "6379"
127.0.0.1:26379> SENTINEL get-master-addr-by-name mymaster 
1) "10.0.1.72"
2) "6379"
```
 After the first replacement of Redis master, user will receive an error:
```
# when master "10.0.1.35"
127.0.0.1:6379> set  test 123
OK
# when master "10.0.1.72"
127.0.0.1:6379> set newtest 123 
(error) READONLY You can't write against a read only replica.
```

What do you think about removing NodePort configuration part, as is in redis-cluster chart, to do not give wrong direction to the user(as from my point of view NodePort will not work properly in this setup)? 
https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L126-L127

**Comment by juan131** [comment] 2020-12-08 11:45
You're totally right @kuzm1ch ! This is something we already discussed on other issues.
Closing this issue as a duplicate of https://github.com/bitnami/charts/issues/4082

**Closed by juan131** 2020-12-08 11:45 UTC
