### ISSUE TITLE
[bitnami/spark] Does not expose spark application stdout/stderr executor logs

### ISSUE THREAD

**Issue by aidan-melen** [bitnami/charts#5997] opened 2021-04-02 18:14 UTC
**Which chart**:
bitrami/spark 5.4.0

**Describe the bug**
The ingress section in the chart successfully exposes the spark master UI as `spark.local`. However, when I attempt to view the spark applications stdout/stderr, I get redirected to the headless service, which is not exposed via the ingress, resulting in a inaccessible link.

**To Reproduce**

0. Start up a Docker Desktop Kubernetes cluster on MacOS

1. Deploy the bitrami spark chart with the following overrides

```yaml
ingress:
  enabled: true
```

2. Ensure that your local machine can resolve spark.local by appending the following to the `/etc/hosts` file.

```
127.0.0.1 spark.local
```

3. Create a pyspark application

https://pythonexamples.org/pyspark-sparkcontext-example/

4. Open the spark master UI in your local browser and navigate to the application

![Screen Shot 2021-04-02 at 12 07 11 PM](https://user-images.githubusercontent.com/54326778/113441721-060b6480-93ac-11eb-8d34-ddd9acba6ec5.png)

Great, we can see our worker and our first application.

5. click the `stdout` link to see the top most executor logs

![Screen Shot 2021-04-02 at 11 55 18 AM](https://user-images.githubusercontent.com/54326778/113441780-1e7b7f00-93ac-11eb-91d1-fea00f4cf368.png)

6. failure state

![Screen Shot 2021-04-02 at 11 55 30 AM](https://user-images.githubusercontent.com/54326778/113441885-436ff200-93ac-11eb-948d-e93fb432370f.png)

As you can see, we are getting redirected to `http://10.1.0.24:8081` which is one of the endpoints for the `spark-headless` service in my cluster.

**Expected behavior**
I would expect the ingress to expose all of the spark services deployed by the helm chart.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Docker Desktop Version:

```
3.2.2 (61853)
```

Kuberenetes Version

```
v1.19.7
```

**Comment by carrodher** [comment] 2021-04-05 08:27
Thanks for the detailed description. Apart from that, can you see any information/errors in the logs of the pods/containers?

**Comment by aidan-melen** [comment] 2021-04-05 16:31
No logs are generated on either the master or worker nodes when I click on the link. The chart is creating all the services, webPort 8080 for the master and port 8081 workers. But the spark UI running on the master isn't networked with the headless worker nodes such that we can route to the service endpoint at webPort 8081.

**Comment by aidan-melen** [comment] 2021-04-05 17:42
@carrodher are you able to reproduce the chart issue? I just launched the chart with the default values, opened the master UI in the browser and clicked the link to the worker and I got the same redirect issue.

Here is the the spark UI. I am going to click the worker link.
![Screen Shot 2021-04-05 at 11 03 08 AM](https://user-images.githubusercontent.com/54326778/113602765-42370300-9600-11eb-85a1-da3ae6d2686c.png)

This link redirects me to `http://10.1.0.91:8081/` which is a dead page.
![Screen Shot 2021-04-05 at 11 09 07 AM](https://user-images.githubusercontent.com/54326778/113602823-58dd5a00-9600-11eb-97cb-d00f6a49ca73.png)

So what is `10.1.0.91:8081`? Let's check the services created by the chart.

![Screen Shot 2021-04-05 at 11 07 41 AM](https://user-images.githubusercontent.com/54326778/113602893-79a5af80-9600-11eb-950b-99c81fa9a3c7.png)

Here we can see that `10.1.0.91` is the endpoint for the worker. That looks right so why are we not getting redirected to the worker UI from the master UI?

**Comment by flaper87** [comment] 2021-05-17 05:24
@carrodher Do you think this issue can be re-opened? I'm facing the same issue as the one reported.

Chart version: 5.4.2
Application version: 3.1.1
Kubernetes Version: 1.19

**Comment by carrodher** [comment] 2021-05-17 07:27
Yes, sure, due to other priorities in the team we didn't have time to take a look at the task I created to investigate this issue.
I will reopen the issue by adding the on-hold label to prevent the bot from closing the issue.

We will update the thread with more information once we take a look at the task, although I can't provide an ETA.

**Comment by flaper87** [comment] 2021-05-17 08:58
> Yes, sure, due to other priorities in the team we didn't have time to take a look at the task I created to investigate this issue.
> I will reopen the issue by adding the on-hold label to prevent the bot from closing the issue.
> 
> We will update the thread with more information once we take a look at the task, although I can't provide an ETA.

If it can help with anything, setting the `SPARK_PUBLIC_DNS` to the ingress domain helps to correct the use of the headless service's IP but the worker port is still used. I've tried to go through the ingress to get the logs but that has not worked.

I'm not super familiar with Spark so I'm not really sure whether it allows for worker logs to be retrieved from the master or if they have to be served by the workers themselves.

Thank you very much for re-opening this issue and commenting. I will keep you posted with my findings.

**Comment by carrodher** [comment] 2021-05-18 07:34
Yes, sure, PRs are more than welcome and the team will be happy to review them, providing feedback and merging it when it's ready.

**Comment by flaper87** [comment] 2021-05-18 07:51
> Yes, sure, PRs are more than welcome and the team will be happy to review them, providing feedback and merging it when it's ready.

To be completely honest, I am quite new to spark and the bitnami charts for it. Allow me to ask a few questions so I can move a bit faster:

* Are these logs supposed to be served through the Ingress pointing to the master's sts?
* Should there be a service or an ingress for the workers?  

Maybe it would be easier if you could dedicate a few minutes to describe how this should be working.

**Comment by carrodher** [comment] 2021-05-20 09:50
I am trying to find if the issue is related to the chart configuration or the container itself (https://github.com/bitnami/bitnami-docker-spark) not sending the logs to the proper destination.

Regarding services, there are two different services, the regular one, and a headless service. Ingress is optional and, by default, it's disabled.
- https://github.com/bitnami/charts/blob/master/bitnami/spark/templates/svc-master.yaml
- https://github.com/bitnami/charts/blob/master/bitnami/spark/templates/headless-svc.yaml

**Comment by brsolomon-deloitte** [comment] 2021-12-17 16:25
This is essentially the same issue as https://github.com/bitnami/charts/issues/8417.

One solution is to use a single proxy service to sit in front of the entire Spark cluster.

We have this working on our cluster and it is on my to-do list to open a PR here with a reproducible example.

**Comment by juan131** [comment] 2021-12-21 08:20
Thanks so much @brsolomon-deloitte ! A PR adding support for a Spark Proxy would be awesome.

**Comment by brsolomon-deloitte** [comment] 2021-12-21 13:09
@juan131 to be clear, would you support a new template for a dedicated proxy deployment/statefulset + service, or just a docs PR illustrating the use of `extraDeploy`?

**Comment by juan131** [comment] 2021-12-22 07:29
Hi @brsolomon-deloitte 

We would accept new manifests under `spark/templates/` to include the Proxy deployment + service. That said, as it's mentioned in our [Contributing Guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md), we have a limitation that forces us to use exclusively Bitnami images in our charts. Therefore, since we don't have a Spark Proxy image in the catalog, you'll have to open in parallel an issue requesting us to add this image to the catalog.

**Closed** 2022-02-01 14:21 UTC
Labels: on-hold
