### ISSUE TITLE
[bitnami/rabbitmq] problem with permissions

### ISSUE THREAD

**Issue by uk1988** [bitnami/charts#16737] opened 2023-05-18 18:18 UTC
### Name and Version

bitnami/rabbitmq:11.10.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. 
Env: k8s: v1.23.16+rke2r1
2. 
We are deploying RabbitMQ with the helm chart that is provided by Bitnami.
Our deployment worked OK with rabbit: 3.10.7-debian-11-r11 and helm chart: 10.3.5.

We have recently tried to migrate to rabbit: 3.11.9 and helm chart: 11.10.1.
We can deploy like before, but with one problem we can not set permissions in load_definition.json file.

If we set permissions we get an error that the user does not exist in rabbitMQ. 
Which is not true. After some trial and error we have seen that the "problem" started with rabbitMQ: 3.11.5 

3. Configuration:
[rabbitValues.txt](https://github.com/bitnami/charts/files/11510484/rabbitValues.txt)

4. Error:
[rabbitmq-0.log](https://github.com/bitnami/charts/files/11510487/rabbitmq-0.log)

### Are you using any custom parameters or values?

    load_definition.json: |
      {
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "permissions": [
          {
            "user": "sam",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "global_parameters": [
          {
            "name": "cluster_name",
            "value": "SAM_Rabbit"
          }
        ],
        "policies": [
          {
            "vhost": "/",
            "name": "HA",
            "pattern": "^sam.*v1$",
            "apply-to": "all",
            "definition": {
                "ha-mode": "all",
                "ha-sync-mode": "automatic"
            },
            "priority": 0
          }
        ]
      }

 

### What is the expected behavior?

Working deployment with correct permissions for the default user. 

### What do you see instead?

![image](https://github.com/bitnami/charts/assets/66792788/c9cdd1d5-92a3-4f23-9ddb-0c99cd6f67e5)

### Additional information

If we remove the permissions part from the load_definition.json then deployment works.
However, we then need to manually create the appropriate permission.

**Comment by fevisera** [comment] 2023-06-02 05:25
Hi @uk1988, sorry for the delay.

I tried to reproduce your error but I could not:

```
$ helm -n rabbitmq install rabbitmq bitnami/rabbitmq --version 10.3.5
$ kubectl -n rabbitmq get po -w
NAME         READY   STATUS    RESTARTS   AGE
rabbitmq-0   0/1     Running   0          4s
rabbitmq-0   1/1     Running   0          32s
$ 
$ PASSWORD=$(kubectl get secret --namespace rabbitmq rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 -d)
$ RABBITMQ_ERLANG_COOKIE=$(kubectl get secret --namespace rabbitmq rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 -d)
$ 
$ helm upgrade -n rabbitmq rabbitmq bitnami/rabbitmq --version 11.10.1 -f my-values.yaml --set auth.password=$PASSWORD --set auth.erlangCookie=$RABBITMQ_ERLANG_COOKIE
$ kubectl -n rabbitmq get po -w
NAME         READY   STATUS        RESTARTS   AGE
rabbitmq-0   0/1     Terminating   0          72s
rabbitmq-0   0/1     Pending       0          0s
rabbitmq-0   0/1     ContainerCreating   0          0s
rabbitmq-0   0/1     Running             0          2s
rabbitmq-0   1/1     Running             0          32s
$ 
$ kubectl -n rabbitmq logs -f pods/rabbitmq-0 | grep no_such_user
```
I also tried using the specific image version for installing (3.10.7-debian-11-r11) and upgrading (3.11.9-debian-11-r5), but no error was found and the container gets up and running.

Could provide some more detail? Which command are you executing to do the upgrade?

**Comment by hotrush** [comment] 2023-06-09 10:59
@fevisera problem is that when you define user/password in `auth` section, but also have `loadDefinition` section enabled and have some `permissions` in the loaded json for user defined in auth section - it fails with error like `Failed to set permissions for user 'foo': the user does not exist `

**Comment by hotrush** [comment] 2023-06-09 11:02
```
  auth:
    username: foo
    existingPasswordSecret: ...
    existingErlangSecret: ...
  extraSecrets:
    load-definition:
      load_definition.json: |
        {
          "vhosts": [
            {
              "name": "vhost1"
            },
            {
              "name": "vhost2"
            }
          ],
          "permissions":[
            {
              "user":"foo",
              "vhost":"vhost1",
              "configure":".*",
              "write":".*",
              "read":".*"
            },
            {
              "user":"foo",
              "vhost":"vhost2",
              "configure":".*",
              "write":".*",
              "read":".*"
            }
          ]
        }
  loadDefinition:
    enabled: true
    existingSecret: 'load-definition'
```

```
│ 2023-06-09 10:47:06.611551+00:00 [warning] <0.611.0> Failed to set permissions for user 'foo': the user does not exist                                                                                                                                                                                                                                     │
│ Error during startup: {error,{no_such_user,<<"foo">>}}                                                                                                                                                                                                                                                                                                     │
│                                                                                                                                                                                                                                                                                                                                                                 │
│ 2023-06-09 10:47:06.611668+00:00 [warning] <0.612.0> Failed to set permissions for user 'foo': the user does not exist  
```

**Comment by fevisera** [comment] 2023-06-13 16:34
Hi @uk1988, 

Sorry for the delay. I have been able to reproduce the issue and I created an internal task in order to address this.

We will reach you back here as soon as we can. Meanwhile, I will mark the issue as on hold.

**Comment by fevisera** [comment] 2023-09-20 15:50
Hi, 

After revising this issue I noticed there were some missing configurations. Both use cases work with the following values content:

`my-values.yaml`:
```
auth:
  username: foo
  password: foopass
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          }
        ],
        "vhosts": [
          {
            "name": "vhost1"
          },
          {
            "name": "vhost2"
          }
        ],
        "permissions":[
          {
            "user":"{{ .Values.auth.username }}",
            "vhost":"vhost1",
            "configure":".*",
            "write":".*",
            "read":".*"
          },
          {
            "user":"{{ .Values.auth.username }}",
            "vhost":"vhost2",
            "configure":".*",
            "write":".*",
            "read":".*"
          }
        ]
      }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
```
or `my-values.yaml`:
```
auth:
  username: foo
  password: foopass
extraSecrets:
  load-definition:
    load_definition.json: |
      {
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "users": [
          {
            "name": "{{ .Values.auth.username }}",
            "password": "{{ .Values.auth.password }}",
            "tags": "administrator"
          }
        ],
        "permissions": [
          {
            "user": "{{ .Values.auth.username }}",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "global_parameters": [
          {
            "name": "cluster_name",
            "value": "SAM_Rabbit"
          }
        ],
        "policies": [
          {
            "vhost": "/",
            "name": "HA",
            "pattern": "^sam.*v1$",
            "apply-to": "all",
            "definition": {
                "ha-mode": "all",
                "ha-sync-mode": "automatic"
            },
            "priority": 0
          }
        ]
      }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
```

And the logs will show:
```
$ kubectl logs -f pods/rabbimq-rabbitmq-0 | grep permissions
2023-09-20 15:40:39.459930+00:00 [info] <0.599.0> Importing concurrently 1 permissions...
2023-09-20 15:40:39.462840+00:00 [info] <0.585.0> Successfully set permissions for user 'foo' in virtual host '/' to '.*', '.*', '.*'
```

You can find more details on how to load custom definitions on our [documentation](https://docs.bitnami.com/kubernetes/infrastructure/rabbitmq/configuration/load-files/).

I'm closing this issue since it appears that the problem has been resolved. However, please do not hesitate to reopen it if you believe I may have overlooked any details.

Thanks.

**Closed by fevisera** 2023-09-20 15:50 UTC
Labels: on-hold, tech-issues, rabbitmq
