### ISSUE TITLE
Chart deployment failure with invalid characters in root password

### ISSUE THREAD

**Issue by Twanfox** [bitnami/charts#8380] opened 2021-12-12 22:46 UTC
**Which chart**:
 MariaDB; chart version 10.1.0

**Describe the bug**
Chart deployment fails when a password using an invalid character (specifically, the double-quote " character) is used. No identification that this is an invalid password is mentioned, and no validation checks are being conducted on first setup. Without debug on, behavior is creation of DB, and immediate stopping of the database without explanation. Subsequent starts will start and fail without logged reason.

**To Reproduce**
Configure chart (image.debug = true for logged messages).
Supply a root password with a " character in it.
Review pod logs during first creation (pods after initial setup/restart will have different error messages indicating access denied for root logon).

Log Fragment without debug:
```
Sun, Dec 12 2021 4:31:58 pm | mariadb 22:31:58.79 Welcome to the Bitnami mariadb container
Sun, Dec 12 2021 4:31:58 pm | mariadb 22:31:58.80 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Sun, Dec 12 2021 4:31:58 pm | mariadb 22:31:58.81 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
Sun, Dec 12 2021 4:31:58 pm | mariadb 22:31:58.81
Sun, Dec 12 2021 4:31:58 pm | mariadb 22:31:58.84 INFO ==> ** Starting MariaDB setup **
Sun, Dec 12 2021 4:31:58 pm | mariadb 22:31:58.92 INFO ==> Validating settings in MYSQL_*/MARIADB_* env vars
Sun, Dec 12 2021 4:31:58 pm | mariadb 22:31:58.93 INFO ==> Initializing mariadb database
Sun, Dec 12 2021 4:31:58 pm | mariadb 22:31:58.97 WARN ==> The mariadb configuration file '/opt/bitnami/mariadb/conf/my.cnf' is not writable. Configurations based on environment variables will not be applied for this file.
Sun, Dec 12 2021 4:31:59 pm | mariadb 22:31:59.00 INFO ==> Installing database
Sun, Dec 12 2021 4:32:04 pm | mariadb 22:32:04.03 INFO ==> Starting mariadb in background
Sun, Dec 12 2021 4:32:06 pm | mariadb 22:32:06.10 INFO ==> Configuring authentication
Sun, Dec 12 2021 4:32:06 pm | mariadb 22:32:06.21 INFO ==> Stopping mariadb
```

Log Fragment with debug (relevant section between Configuring Authentication and Stopping mariadb):
```
Sun, Dec 12 2021 4:12:04 pm | -- create root@localhost user for local admin access
Sun, Dec 12 2021 4:12:04 pm | -- create user 'root'@'localhost' identified by "......."Am";
Sun, Dec 12 2021 4:12:04 pm | -- grant all on *.* to 'root'@'localhost' with grant option;
Sun, Dec 12 2021 4:12:04 pm | -- create admin user for remote access
Sun, Dec 12 2021 4:12:04 pm | create user 'root'@'%' identified by "......."Am";
Sun, Dec 12 2021 4:12:04 pm | grant all on *.* to 'root'@'%' with grant option;
Sun, Dec 12 2021 4:12:04 pm | flush privileges;
Sun, Dec 12 2021 4:12:04 pm | ERROR 1064 (42000) at line 5: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Am";
Sun, Dec 12 2021 4:12:04 pm | grant all on *.* to 'root'@'%' with grant option;
Sun, Dec 12 2021 4:12:04 pm | flush privileges' at line 1
```

**Expected behavior**
Either an error on 'invalid character in password' or sanitizing the password so that it can be used with a " character in it without causing invalid SQL syntax.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6+unreleased", GitCommit:"ee91a121e0aa301fcef2bfbc7184f96edd4b50f5", GitTreeState:"clean", GoVersion:"go1.16.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
A password was previously used in a stand-alone docker setup with bitnami mariadb images without issue, thus leading to an expectation that this chart would be no different. Clearly, a different password may be used so as not to trigger this issue, but providing additional feedback in logs about the error may improve troubleshooting.

**Comment by carrodher** [comment] 2021-12-14 17:59
Thanks for creating this issue, I was able to reproduce it:
- `--set auth.rootPassword='asda"cvvv'` ❌
- `--set auth.rootPassword='asda\cvvv'` ✅
- `--set auth.rootPassword='asda@cvvv'` ✅

The failing container log is:
```
mariadb 17:45:16.80 DEBUG ==> Executing SQL command:
-- create root@localhost user for local admin access
-- create user 'root'@'localhost' identified by "asda"cvvv";
-- grant all on *.* to 'root'@'localhost' with grant option;
-- create admin user for remote access
create user 'root'@'%' identified  by "asda"cvvv";
grant all on *.* to 'root'@'%' with grant option;
flush privileges;
ERROR 1064 (42000) at line 5: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'cvvv";
grant all on *.* to 'root'@'%' with grant option;
flush privileges' at line 1
```
being the important part
```
ERROR 1064 (42000) at line 5: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'cvvv";
```

Checking the secret, it seems the password is properly obtained:
```console
$ kubectl get secret mariadb -o jsonpath="{.data.mariadb-root-password}" | base64 --decode
asda"cvvv
```
In the same way, the password is properly set in the environment variable:
```console
$ kubectl exec -it mariadb-0 -n petete -- env | grep MARIADB_ROOT_PASSWORD
MARIADB_ROOT_PASSWORD=asda"cvvv
```

What it's really weird is that I'm able to reproduce the issue using the container image (without Helm):
```console
$ docker run --name mariadb -e MARIADB_ROOT_PASSWORD='asdasd"rrr' -e BITNAMI_DEBUG=true bitnami/mariadb:latest
...
mariadb 17:56:04.02 DEBUG ==> Executing SQL command:
-- create root@localhost user for local admin access
-- create user 'root'@'localhost' identified by "asdasd"rrr";
-- grant all on *.* to 'root'@'localhost' with grant option;
-- create admin user for remote access
create user 'root'@'%' identified  by "asdasd"rrr";
grant all on *.* to 'root'@'%' with grant option;
flush privileges;
ERROR 1064 (42000) at line 5: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rrr";
grant all on *.* to 'root'@'%' with grant option;
flush privileges' at line 1
mariadb 17:56:04.02 INFO  ==> Stopping mariadb
...
```

Taking a look at the container repository I just discovered this PR (https://github.com/bitnami/bitnami-docker-mariadb/pull/257) which seems to be solving this kind of issue, let's see what is the result once merged.

**Comment by carrodher** [comment] 2022-10-20 10:51
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.

**Closed by carrodher** 2022-10-20 10:51 UTC
Labels: on-hold, mariadb
