### ISSUE TITLE
[mariadb-galera] TLS options are not effective

### ISSUE THREAD

**Issue by horazont** [bitnami/charts#5765] opened 2021-03-12 08:32 UTC
**Which chart**:
mariadb-galera
```
dbtest-tls                      default         1               2021-03-12 09:23:02.112625845 +0100 CET deployed   mariadb-galera-5.5.1     10.5.8
```

**Describe the bug**
The TLS options of the chart are completely ineffective. While the image contains [code to set the SSL variables accordingly](https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/master/10.5/debian-10/rootfs/opt/bitnami/scripts/libmariadbgalera.sh#L341-L348), that code [is not called](https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/master/10.5/debian-10/rootfs/opt/bitnami/scripts/libmariadbgalera.sh#L464-L470) in Kubernetes because the configuration file is mapped from a configmap, and thus read-only.

**To Reproduce**

1. Create the following secret:

    <details>
    <summary>v1/secrets/testcert</summary>

    ```yaml
    apiVersion: v1
    kind: Secret
    metadata:
      name: testcert
    type: kubernetes.io/tls
    data:
      ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCekNDQWUrZ0F3SUJBZ0lVZEpTOG5tWGM2NXkwN3lXKzAxYncxRTJTd1FRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0V6RVJNQThHQTFVRUF3d0lXVUZQVDBzdFEwRXdIaGNOTWpFd01qSTBNVEV3TVRFMVdoY05NekV3TWpJeQpNVEV3TVRFMVdqQVRNUkV3RHdZRFZRUUREQWhaUVU5UFN5MURRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTUNjZGo3bytKVEZ3TWFVWnJ4ZkJBTjZNZU5mNkdveGEwYTBSWnE1cHhsbXZzV1cKa0t2MzBidkdQZHZodzczNGZxU3ZuL0lqOFRBUlVvOG00anExbWVEZCtQSVVvNHgvOG54NUw5aitCblJZbG5YRgp3d0c2NmYzL2xyb2lVMjN3b0ZlSlZlaUZicVhwNEFXY1I0T0ZmbzYrRmJHMnpHYytqQlk2V21ueHA4bkhCVXJECmZ1eUZUYVpqZ1pwNEFTTkpVS3RjTzlrNXUxc1lyWWp5WFpLSVlRWFV6eWNoUGVMdVNtT1BaREFCTlQvL1NZSHoKSzBHUWVMQXM5VHE0VHc3MlJkSWNET0g2M0FTR2NTODhBakV3SmREdUZjdUtrMmF6dFdhL3ZXREJUQjFJSnRWeQpTTHA1TFM0TjVVU0VWMFZ4RGE2ZGlCdEZUVDErTFMvakRhbGFiSjBDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFCkZLSWJmM1owZjZZZkhnL2RNdDBHNDVFQWVsZ0hNQjhHQTFVZEl3UVlNQmFBRktJYmYzWjBmNllmSGcvZE10MEcKNDVFQWVsZ0hNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSG1rTjY0dwpPQ1lZbzdpUGJzRWxxRldSL0pmNjViMDk2NkNhb2U0Z09PY3dyRndwN0lyVnl0ZllCWDlPNkh6VTNyYWwwdlIrCnVha2oxSVBRUWtITFM2cjZTMUp4VHBpenl3OTRHa0l1VFdBUDBFSEdVbnM3Y3NjOUx5RGhjeHVkOEJ4akxUa2cKREdwbW9vczhqSFgzZmVRR0lVeWlybGZoWS9reGRjNVAyK3BRVE1HcE5uNDRKQTYxakhJN2tjaVdEZUZieTN1aApxZlJxeEtYMkQzMEdvRVI3TGUvbDdyVmdmRFo2YnJqYUJhQXZDTkliZTNMek52aUV1eWJlUlpvM0Q2NW9VVzNBCjZ3RFNHM292NCtUWmJmcGYyRFllbmpQMjUxYUErRldXZFVVK0g0T254VGtZOC9DRWRRZGtQNlBiNVMzNitYRlAKV1B4UndhYjJXSW9UbFRJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaRENDQWt5Z0F3SUJBZ0lSQUprd2c4bXpXeEs0ZlJnUVVTUjcybWN3RFFZSktvWklodmNOQVFFTEJRQXcKRXpFUk1BOEdBMVVFQXd3SVdVRlBUMHN0UTBFd0hoY05NakV3TXpFeU1EZ3hNVEl5V2hjTk1qRXdNekUxTURneApNVEl5V2pBNU1RNHdEQVlEVlFRS0V3VjVZVzl2YXpFbk1DVUdBMVVFQXd3ZUtpNXJaWGx6ZEc5dVpTMXNlSGc0Ck5DMWtZaTEwWXpZNGNpMXBiWEJzTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEKcTd6QWJ6dHpheG9UVWtpQ1BRazl0a2d6Mmd2N25ZMkRlNWZ0VTFaQmNRQkJlVkp5Y1h6VmdNdXpoMGs5aTF2Tgo5WjhzdFRpYjg3OGtEcml1WVM1NVVxMUtsaXRoTE9PWTE4V3dkWUFzMnJIMzhwalE0UjhvWFJ6SkMxWFVNczVjClF4bUJJdmJZOVJzQUh6MTJKOWVWSG5qRWs3MncxZW9IRW5hS1dFb0h4ejIwdjVHNVczaTZuRXFyaGRCdVNYSmwKRW5LTWJxRmZjRXByVDQ2dGhqenFpVVNXVm9ib2hpdkY4bWI2ME5TcCtYa2RQWUIzc21GdStIVkEyTlZwb282VApZeTJyQkcrakN6VGExT0hWK3pYbFh3SU1SSlNTRGZ5UUc4NnNXVTB0MTZOUnJHR0NqK2Q4MFJvZC9ILzVyem4rCnEyWkxpRWhMMHFrOHRxTlIxS3lMK3dJREFRQUJvNEdNTUlHSk1BNEdBMVVkRHdFQi93UUVBd0lGb0RBTUJnTlYKSFJNQkFmOEVBakFBTUI4R0ExVWRJd1FZTUJhQUZLSWJmM1owZjZZZkhnL2RNdDBHNDVFQWVsZ0hNRWdHQTFVZApFUVJCTUQrQ0hpb3VhMlY1YzNSdmJtVXRiSGg0T0RRdFpHSXRkR00yT0hJdGFXMXdiSUlkYTJWNWMzUnZibVV0CmJIaDRPRFF0WkdJdGRHTTJPSEl0YlhsemNXd3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSHZwQUpRbXAxNnoKSDlBS3c0WWpXcFdwS0hyYVNYMkpxRk5hMTcvMUhDSFJ3enhXd0U3cGNENVNkNEt5K3Jnby9EdE9pWGh6UXE3Ygp0dFlFK0JjYlVCa2twS0hGSmlUbnpJSmtwNEwxcitHeGlXWk1lSkVMTEtiSE5ORmhWaHI3NWxiTXpabmRFRlJKCm95dVF3L0VpaDVGeXVsaHlnNnQzSk1DZ2FWRmNUdTA2dEp4VDM0Z3JhNXVzRndjNmQxYkw3V3h1bUd2NFRWK24KNDVCejA0N21VNE1SaWpVVVJJVWwyMVV1ak1mME9jc1FuN0xpMXJ2Z1ArUm9qa293NDE4dVV6QjB5RGwzb0pBRgpLeEdTMSt2TGx5N1lrK1NNVW5zbFpLbXpJYmNOZDF5RnZob3Q5UnU2MTQzU0FvRTZ1em5XZ2FjanRpMXJtTE9qCm1IL3VOWDVDMENRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcTd6QWJ6dHpheG9UVWtpQ1BRazl0a2d6Mmd2N25ZMkRlNWZ0VTFaQmNRQkJlVkp5CmNYelZnTXV6aDBrOWkxdk45WjhzdFRpYjg3OGtEcml1WVM1NVVxMUtsaXRoTE9PWTE4V3dkWUFzMnJIMzhwalEKNFI4b1hSekpDMVhVTXM1Y1F4bUJJdmJZOVJzQUh6MTJKOWVWSG5qRWs3MncxZW9IRW5hS1dFb0h4ejIwdjVHNQpXM2k2bkVxcmhkQnVTWEpsRW5LTWJxRmZjRXByVDQ2dGhqenFpVVNXVm9ib2hpdkY4bWI2ME5TcCtYa2RQWUIzCnNtRnUrSFZBMk5WcG9vNlRZeTJyQkcrakN6VGExT0hWK3pYbFh3SU1SSlNTRGZ5UUc4NnNXVTB0MTZOUnJHR0MKaitkODBSb2QvSC81cnpuK3EyWkxpRWhMMHFrOHRxTlIxS3lMK3dJREFRQUJBb0lCQUVJUjJzS3dUNFlMd1JVdAoyaFViUWdlbm5YTXNtditSR3Qxb3BLQWtGZ2NnUHhBcXZPYVdUUmxBeE8rdUtLUTlqRzRMYjhyRVhaTVhuUXFnCjJFMkE4S0h6RXpmVXRvenJmcmk4VUZmVUdPMkYvRXJ6cWFDQ09TZ2hVK010Z1BhTzE0WGxBUDV2a3lZdzNnb20KdmhjejVDV1Y5cUtVSHIwZFROMDRoNTdSMUU0OCtLTHVpeWI4MFh5ZWZ2R0dNVThldWpQUVFSenRYa3luZ2o5TgpkbmpNM1Z5eWM4Nko0MW5Ga292NFg0OUJ4VHRramZ3Z0U4S3lzTjN4K0hEa2l1ZVA4bkVlY1VKRU1lRll6dUk5ClI4ZUdaSWk2R3VUM013ZkMxZzlBa1lTSzRWWVhSSzI2VjlYVGk5V1c5WURMd1dGZm5RNmRQcE5PS2V4a3pNci8KUmVtaWYya0NnWUVBMmJKQnYwaE9rSjBxdkY0cEc1VUdMaGFYd0dDbGdHQzZqeWluNWxJQ2tNU3IvMCtodjljTwpjaFlpcXZGTFltRzNDNE04a1M4OTZiSVBTQ0NtZFV3Z2hyR01YSFlzQkxtL2JEdUhqVjd2QXNvYzROTVh3MzRnCnU0U3lrYlgxMEpjZXRqTUhTbE1jTmF1ajYrS1JHMU12K1RqQjkvdUVYbFdsYkJUVnZGRWIwSWNDZ1lFQXlmUmEKY2JwMnp0V0dxL0xmMXM4R1JUdmJqekZYOWhHQTB0cHdQNkhGUWttUmJUY0dtd3ZZNFRFSGJTRVFRKytXaEYrNQoxWnZtQm50Y1Q4bDhNYkd3NDlYbVNTMWxMSnFPajBDUEIrVGgvVDVVaHVLTHM3eWdkdnY5RHBoS1RFYVMwSHhHCndvYTg4ZE05cG1SSTA2Vnk3dFZzRXZmVGo4NTZxM3VEZVlCYVNlMENnWUVBelZSYXV3YUNROWhaMUsyamJFYVYKTzZkSG5zWUpsQnFvSEJzbXNoQ3NKc3U1eHVmZkVralBjVC83bHV4Y1JBRVNXeU4vWHhrRjlvUmg4WkFLTVJ5SwptVUNodVJ3a3pKZytPdUd6S3Q1ZDVXMm82MDF2WG81NlpTUDJJWVZVdzFlbU9nZkxXb2tsVkdIK0RLRDRhS04vCjNqdHdpR3VOSUVUNzhBTit6VTViUThVQ2dZQTFjOGxraEpmaGtyNThVR0pTZHFVUU9oR1l5dFNmT203QVlEU0oKZ3dXMHo4Z0FBaXByYXkxU0hTbjhCbDVKdk9ZM3p5WmVsVTdDdEcvd1prSEszVjhXVG8wUEhVYkVFWHhlQ2haUgpYcEU1OS85alhCN2h5YkVuRFBjam44YzZmUXRxeHhucmJzSWZ0MnQvMk5jMXZYcTRJQ0RrdkZkd25wUDFRMUcvCkhPdkkyUUtCZ0FFWGFYL1hEWU9HUERpMjRMN2hoaWtSbWU0VW5WaTlJbUhsd01jQjVCYlFnSVU5dXN1WXUzdVkKNlpUKzlFZ0NvSlJUbXljRVNrbDg3LzFybSt1WFlxYlFhSTlZMlpENkFKVnhFanlSZXBDbkgvUWtVSFFRM3A5Vgo5ZXRiYS8wYlZIZlBubENraXFrdkNFNHEyWW8rN2pwVDlMWUhzT0lDamM2RW0xL2FmT3JwCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
    ```

    </details>

    **Note:** The private key in there has been generated for my test setup, as has the CA, so there is no harm in sharing it publicly. Also note that the certificate expires quickly, but that doesn’t hurt this test case.

2. Install the helm chart using the following configuration:

    ```yaml
    replicaCount: 1
    tls:
      enabled: true
      certificatesSecret: testcert
      certFilename: tls.crt
      certKeyFilename: tls.key
      certCAFilename: ca.crt
    ```

3. Verify that the statefulset has been configured with TLS:

    ```
    $ kubectl describe sts dbtest-tls-mariadb-galera | grep TLS
          MARIADB_ENABLE_TLS:                   yes
          MARIADB_TLS_CERT_FILE:                /bitnami/mariadb/certs/tls.crt
          MARIADB_TLS_KEY_FILE:                 /bitnami/mariadb/certs/tls.key
          MARIADB_TLS_CA_FILE:                  /bitnami/mariadb/certs/ca.crt
    ```

4. Wait for the Pod to become ready

5. Verify the SSL settings by either:

    * Entering the Pod using `kubectl exec` and running:

        ```
        I have no name!@dbtest-tls-mariadb-galera-0:/$ grep ssl /opt/bitnami/mariadb/conf/my.cnf
        # ssl_ca=/certs/ca.pem
        # ssl_cert=/certs/server-cert.pem
        # ssl_key=/certs/server-key.pem
        I have no name!@dbtest-tls-mariadb-galera-0:/$ ps -eF | grep ssl
        1001       395   362  0   772   828   0 08:26 pts/0    00:00:00 grep ssl
        ```

        This proves that neither the `mysqld` process flags nor the configuration have been changed to support SSL.

    * Running `mysql --ssl --ssl-verify-server-cert` against the service:

        ```
        root@mysqlclient-5c69dc5ddb-mt8tn:/# mysql --ssl --ssl-verify-server-cert -h dbtest-tls-mariadb-galera -u root
        ERROR 2026 (HY000): SSL connection error: SSL is required, but the server does not support it
        ```

**Expected behavior**

* Either the chart should not advertise support for TLS, or
* TLS support should be fully functional

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.0-rc.1", GitCommit:"0977ded29a00383db5cbfd91ae220d30457f6ddb", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional Context**

* This is made worse by `mysql --ssl` silently falling back to non-SSL unless `--ssl-verify-server-cert` is explicitly requested.
* Other client (libraries) may have similar misbehaviour.

**Comment by rafariossaa** [comment] 2021-03-12 16:41
Hi @horazont ,
  Thank you very much for spotting this and for providing detailed steps to reproduce it !!

  I am opening a internal task to look for a fix for this.
  We are a small team and I can not provide a ETA.  We will come back as soon as we have news.
  In the mean time, don't hesitate to send a PR, we will be glad to review and merge it.

**Comment by gwvandesteeg** [comment] 2021-08-12 06:22
Probably related to: https://github.com/bitnami/charts/issues/7198

**Comment by carrodher** [comment] 2022-10-20 13:25
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.

**Closed by carrodher** 2022-10-20 13:25 UTC
Labels: on-hold
