### ISSUE TITLE
[bitnami/redis-cluster] helm chart not working with 6.2 version

### ISSUE THREAD

**Issue by codervinod** [bitnami/charts#11552] opened 2022-08-03 21:14 UTC
### Name and Version

bitnami/redis-cluster latest

### What steps will reproduce the bug?

1. Use minikube
2. run command `helm install my-redis62 bitnami/redis-cluster --set image.tag=6.2.7-debian-11-r16`
3. It results in CrashLoopBackOff for all containers
4. Logs:
5.
```
redis-cluster 21:12:51.88
redis-cluster 21:12:51.88 Welcome to the Bitnami redis-cluster container
redis-cluster 21:12:51.88 Subscribe to project updates by watching https://github.com/bitnami/containers
redis-cluster 21:12:51.88 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis-cluster 21:12:51.89
redis-cluster 21:12:51.89 INFO  ==> ** Starting Redis setup **
redis-cluster 21:12:51.92 INFO  ==> Initializing Redis
redis-cluster 21:12:51.96 INFO  ==> Setting Redis config file
Changing old IP 172.17.0.13 by the new one 172.17.0.13
sed: can't read /bitnami/redis/data/nodes.conf: No such file or directory
```

### Are you using any custom parameters or values?

`--set image.tag=6.2.7-debian-11-r16`

### What is the expected behavior?

Redis cluster should come into running state

### What do you see instead?

Crashloopback off in all containers for redis-cluster

**Comment by javsalgar** [comment] 2022-08-04 08:54
Hi,

Just a note to let you know that I was able to reproduce it. It seems that the issue is with this value

```
Reading the configuration file, at line 626
>>> 'repl-diskless-sync-max-replicas 0'
```

I will open a task for the team to fix it. Thanks for reporting!

**Comment by uDuCkV** [comment] 2022-08-30 15:41
+1

**Comment by corelevel** [comment] 2022-09-05 22:41
I have the same issue

**Comment by chromevoid** [comment] 2022-09-29 17:14
+1
```shell
*** FATAL CONFIG FILE ERROR (Redis 6.2.7) ***
Reading the configuration file, at line 626
>>> 'repl-diskless-sync-max-replicas 0'
Bad directive or wrong number of arguments
```

**Comment by alphashaw** [comment] 2022-10-07 11:31
I have the same issue:

```bash
** Redis setup finished! **
*** FATAL CONFIG FILE ERROR (Redis 6.2.7) ***
Reading the configuration file, at line 626
>>> 'repl-diskless-sync-max-replicas 0'
Bad directive or wrong number of arguments
```

**Comment by carrodher** [comment] 2022-10-20 10:32
Hi, I'm moving this issue to close as not planned since this is a non-supported scenario. Helm charts are pinned to a specific version. At this moment, the Redis/Redis Cluster Helm charts are designed for Redis 7.0 so we can't guarantee that changing the container images to a previous major version works out of the box

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

**Closed by carrodher** 2022-10-20 10:32 UTC
Labels: on-hold, tech-issues, redis-cluster

**Comment by chromevoid** [comment] 2022-10-20 10:46
Workaround
```
helm install numaflow-redis-cluster --set image.tag=6.2 --set usePassword=false bitnami/redis-cluster --version 8.1.1
```

**Comment by mandrean** [comment] 2023-11-29 18:20
What worked for me was overriding the default config, which tried to set some values incompatible with redis `6.2`

```
  redis:
    defaultConfigOverride: |
      protected-mode no
      tcp-backlog 511
      timeout 0
      daemonize no
      pidfile /run/redis.pid
      dir /bitnami/redis/data
      cluster-enabled yes
      cluster-config-file /bitnami/redis/data/nodes.conf
```
