### ISSUE TITLE
[POSTGRESQL] Wrong owner for public schema in custom database with custom user

### ISSUE THREAD

**Issue by Sebor** [bitnami/charts#6519] opened 2021-05-31 19:05 UTC
**Which chart**:
The name (and version) of the affected chart
```
postgresql-10.4.6
```

**Describe the bug**
When I create custom database with custom user during initialization the owner of public schema in this DB is postgres instead of my user

**To Reproduce**

1. Install chart 
  ```
  helm install --set postgresqlUsername=app --set postgresqlPassword=Password123 --set postgresqlDatabase=app postgres bitnami/postgresql
  ```
2. Login to database with `app` user
3. List schemas
4. Got output
  ```
  List of schemas
  Name  | Owner
--------+-------
 public | postgres
(1 row)
  ```

**Expected behavior**
```
List of schemas
  Name  | Owner
--------+-------
 public | app
(1 row)
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment] 2021-06-01 08:01
Closing as it is a duplicate of https://github.com/bitnami/bitnami-docker-postgresql/issues/289

**Closed by javsalgar** 2021-06-01 08:01 UTC
