### ISSUE TITLE
[elasticsearch] Setting config causes errors of file system being read-only. Cluster won't start (master nodes failed to sync)

### ISSUE THREAD

**Issue by polymorpher** [bitnami/charts#3960] opened 2020-10-08 20:39 UTC
**Which chart**:
Elasticsearch

**Describe the bug**
Setting `config` causes errors on config file system being read-only. Subsequently clusters won't work (master nodes couldn't get synced). See below 
```
20:26:21 safelyRenameFile [ERRO] Failed copying from /tmp/temp554893918 to /opt/bitnami/elasticsearch/config/elasticsearch.yml
20:26:21 safelyRenameFile [ERRO] open /opt/bitnami/elasticsearch/config/elasticsearch.yml: read-only file system
```

**To Reproduce**
Just create a chart with `config:` set for something, e.g.: `reindex.remote.whitelist: http://blah.com`

**Expected behavior**
Chart and cluster should start normally with above configurations set.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:38Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by polymorpher** [comment] 2020-10-08 20:58
I think the issue was caused by `config` completely overriding `elasticsearch.yml`. I examined a standard `elasticsearch.yml` for deployments without any `config` parameter set, and found very cluster-specific setups in the file. I ended up using `initScript` parameter appending to elasticsearch.yml as suggested in https://github.com/bitnami/charts/issues/2646

**Comment by FraPazGal** [comment] 2020-10-12 15:26
Hello @polymorpher,

Thanks for opening this issue! As you said, setting `config` forces you to provide the whole `elasticsearch.yml` file. I'm glad that the answer provided by my colleague worked for you! 

As the problem is now solved, I will close this issue. Please do not doubt to reach out if you encounter any more issues!

**Closed by FraPazGal** 2020-10-12 15:26 UTC
