### ISSUE TITLE
Magento Pod fails without error at install script

### ISSUE THREAD

**Issue by schroedt** [bitnami/charts#7269] opened 2021-08-19 09:36 UTC
Hi there,

I am trying to deploy magento using helm, using Istio (latest) and Rook-Ceph (storage):

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install magento bitnami/magento --namespace magento \
    --set magentoUsername=admin \
    --set magentoPassword=admin \
    --set magentoHost=magento.magento.svc.cluster.local \
    --set magentoAdminUri=admin \
    --set mariadb.enabled=false \
    --set externalDatabase.host=mariadb.db-maria.svc.cluster.local \
    --set externalDatabase.port=3306 \
    --set externalDatabase.user=app_magento \
    --set externalDatabase.password=dbpassword \
    --set externalDatabase.database=app_magento
```

Deployment succeeds, except of `magento` pod. It shifts to `Running`. After a while it switches to state `CrashLoopBack`. I noticed an Unhealthy event, referencing `HTTP probe failed with HTTP 500`:

```
kubectl -n magento describe pod/magento-7d6d6966d7-sgkhw
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Normal   Scheduled               5m53s                  default-scheduler        Successfully assigned magento/magento-7d6d6966d7-sgkhw to kubernetes-worker01
  Normal   SuccessfulAttachVolume  5m52s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-4ceccbf2-ccb6-4932-97ab-fe1351b618a2"
  Normal   Pulled                  5m42s                  kubelet                  Container image "docker.io/istio/proxyv2:1.10.3" already present on machine
  Normal   Created                 5m42s                  kubelet                  Created container istio-init
  Normal   Started                 5m42s                  kubelet                  Started container istio-init
  Normal   Created                 5m39s                  kubelet                  Created container istio-proxy
  Normal   Pulled                  5m39s                  kubelet                  Container image "docker.io/istio/proxyv2:1.10.3" already present on machine
  Normal   Started                 5m38s                  kubelet                  Started container istio-proxy
  Warning  Unhealthy               4m3s (x8 over 5m8s)    kubelet                  Readiness probe failed: HTTP probe failed with statuscode: 500
  Normal   Created                 3m39s (x3 over 5m40s)  kubelet                  Created container magento
  Normal   Started                 3m39s (x3 over 5m39s)  kubelet                  Started container magento
  Normal   Pulled                  3m39s (x3 over 5m40s)  kubelet                  Container image "docker.io/bitnami/magento:2.4.2-debian-10-r135" already present on machine
  Warning  BackOff                 31s (x13 over 4m1s)    kubelet                  Back-off restarting failed container
```

When checking logs, I noticed it's hung at `Running Magento install script`:

```
kubectl -n magento logs -f pod/magento-7d6d6966d7-sgkhw
magento 09:33:33.05
magento 09:33:33.05 Welcome to the Bitnami magento container
magento 09:33:33.05 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-magento
magento 09:33:33.07 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-magento/issues
magento 09:33:33.09
magento 09:33:33.11 INFO  ==> ** Starting Magento setup **
magento 09:33:33.30 INFO  ==> Configuring the HTTP port
magento 09:33:33.42 INFO  ==> Configuring the HTTPS port
magento 09:33:33.62 INFO  ==> Configuring PHP options
magento 09:33:33.77 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
magento 09:33:34.25 INFO  ==> Ensuring Magento directories exist
magento 09:33:34.30 INFO  ==> Trying to connect to the database server
magento 09:33:34.54 INFO  ==> Trying to connect to Elasticsearch
magento 09:33:34.69 INFO  ==> Running Magento install script

» Pod restarts «
```

Pod stays within this loop:
```
NAME                                                          READY   STATUS    RESTARTS      AGE     IP               NODE                  NOMINATED NODE   READINESS GATES
pod/magento-7d6d6966d7-sgkhw                                  1/2     CrashLoopBackOff   4 (31s ago)   5m3s   192.168.1.184    kubernetes-worker01   <none>           <none>
pod/magento-elasticsearch-coordinating-only-986dfdbbd-4kklm   2/2     Running            0             5m3s   192.168.1.186    kubernetes-worker01   <none>           <none>
pod/magento-elasticsearch-data-0                              2/2     Running            0             5m3s   192.168.13.243   kubernetes-worker03   <none>           <none>
pod/magento-elasticsearch-master-0                            2/2     Running            0             5m4s   192.168.1.171    kubernetes-worker01   <none>           <none>

```

Any idea how to find the error?
I think it might be correlated to `--set magentoHost=magento.magento.svc.cluster.local \`. I do want accessing Magento via Istio `VirtualService` behind a reverse proxy at `magento.my-example.de` via Port 443 (internet) / 35000 (intranet). That's fine for any workloads so far. Istio handles TLS offloading (centrally) and re-encrypts via `Citadel` within Kubernetes SDN.

**Comment by pablogalegoc** [comment] 2021-08-20 07:19
Hi @schroedt!

Could you add `--set image.debug=true` to the command? Hopefully it will give us a hint on why it gets stuck there

**Comment by schroedt** [comment] 2021-08-20 12:56
Hi @pablogalegoc,

big thanks for the hint. Now I got the error: My [DB Version](https://mariadb.com/kb/en/release-notes/) (10.5 from 12/2019) is too new. You support up to 10.4 (from 11/201)... **Current stable is 10.6**.

- Any chance getting Magento updated..? Or do you have a specific reason for not supporting later than Major -1?
- Any chance getting this info without debug flag to the logs?

```
magento 12:50:20.19 INFO  ==> Running Magento install script
Starting Magento installation:
File permissions check...
[Progress: 1 / 1314]
Required extensions check...
[Progress: 2 / 1314]
Enabling Maintenance Mode...
[Progress: 3 / 1314]
Installing deployment configuration...
[Progress: 4 / 1314]
Installing database schema:
Schema creation/updates:

In SqlVersionProvider.php line 93:

  Current version of RDBMS is not supported. Used Version: 10.5.6-MariaDB. Su
  pported versions: MySQL-8, MySQL-5.7, MariaDB-(10.2-10.4)


setup:install [--backend-frontname BACKEND-FRONTNAME] [--enable-debug-logging ENABLE-DEBUG-LOGGING] [--enable-syslog-logging ENABLE-SYSLOG-LOGGING] [--remote-storage-driver REMOTE-STORAGE-DRIVER] [--remote-storage-prefix REMOTE-STORAGE-PREFIX] [--remote-storage-bucket REMOTE-STORAGE-BUCKET] [--remote-storage-region REMOTE-STORAGE-REGION] [--remote-storage-key REMOTE-STORAGE-KEY] [--remote-storage-secret REMOTE-STORAGE-SECRET] [--amqp-host AMQP-HOST] [--amqp-port AMQP-PORT] [--amqp-user AMQP-USER] [--amqp-password AMQP-PASSWORD] [--amqp-virtualhost AMQP-VIRTUALHOST] [--amqp-ssl AMQP-SSL] [--amqp-ssl-options AMQP-SSL-OPTIONS] [--consumers-wait-for-messages CONSUMERS-WAIT-FOR-MESSAGES] [--key KEY] [--db-host DB-HOST] [--db-name DB-NAME] [--db-user DB-USER] [--db-engine DB-ENGINE] [--db-password DB-PASSWORD] [--db-prefix DB-PREFIX] [--db-model DB-MODEL] [--db-init-statements DB-INIT-STATEMENTS] [-s|--skip-db-validation] [--http-cache-hosts HTTP-CACHE-HOSTS] [--db-ssl-key DB-SSL-KEY] [--db-ssl-cert DB-SSL-CERT] [--db-ssl-ca DB-SSL-CA] [--db-ssl-verify] [--session-save SESSION-SAVE] [--session-save-redis-host SESSION-SAVE-REDIS-HOST] [--session-save-redis-port SESSION-SAVE-REDIS-PORT] [--session-save-redis-password SESSION-SAVE-REDIS-PASSWORD] [--session-save-redis-timeout SESSION-SAVE-REDIS-TIMEOUT] [--session-save-redis-persistent-id SESSION-SAVE-REDIS-PERSISTENT-ID] [--session-save-redis-db SESSION-SAVE-REDIS-DB] [--session-save-redis-compression-threshold SESSION-SAVE-REDIS-COMPRESSION-THRESHOLD] [--session-save-redis-compression-lib SESSION-SAVE-REDIS-COMPRESSION-LIB] [--session-save-redis-log-level SESSION-SAVE-REDIS-LOG-LEVEL] [--session-save-redis-max-concurrency SESSION-SAVE-REDIS-MAX-CONCURRENCY] [--session-save-redis-break-after-frontend SESSION-SAVE-REDIS-BREAK-AFTER-FRONTEND] [--session-save-redis-break-after-adminhtml SESSION-SAVE-REDIS-BREAK-AFTER-ADMINHTML] [--session-save-redis-first-lifetime SESSION-SAVE-REDIS-FIRST-LIFETIME] [--session-save-redis-bot-first-lifetime SESSION-SAVE-REDIS-BOT-FIRST-LIFETIME] [--session-save-redis-bot-lifetime SESSION-SAVE-REDIS-BOT-LIFETIME] [--session-save-redis-disable-locking SESSION-SAVE-REDIS-DISABLE-LOCKING] [--session-save-redis-min-lifetime SESSION-SAVE-REDIS-MIN-LIFETIME] [--session-save-redis-max-lifetime SESSION-SAVE-REDIS-MAX-LIFETIME] [--session-save-redis-sentinel-master SESSION-SAVE-REDIS-SENTINEL-MASTER] [--session-save-redis-sentinel-servers SESSION-SAVE-REDIS-SENTINEL-SERVERS] [--session-save-redis-sentinel-verify-master SESSION-SAVE-REDIS-SENTINEL-VERIFY-MASTER] [--session-save-redis-sentinel-connect-retries SESSION-SAVE-REDIS-SENTINEL-CONNECT-RETRIES] [--cache-backend CACHE-BACKEND] [--cache-backend-redis-server CACHE-BACKEND-REDIS-SERVER] [--cache-backend-redis-db CACHE-BACKEND-REDIS-DB] [--cache-backend-redis-port CACHE-BACKEND-REDIS-PORT] [--cache-backend-redis-password CACHE-BACKEND-REDIS-PASSWORD] [--cache-backend-redis-compress-data CACHE-BACKEND-REDIS-COMPRESS-DATA] [--cache-backend-redis-compression-lib CACHE-BACKEND-REDIS-COMPRESSION-LIB] [--cache-id-prefix CACHE-ID-PREFIX] [--allow-parallel-generation] [--page-cache PAGE-CACHE] [--page-cache-redis-server PAGE-CACHE-REDIS-SERVER] [--page-cache-redis-db PAGE-CACHE-REDIS-DB] [--page-cache-redis-port PAGE-CACHE-REDIS-PORT] [--page-cache-redis-password PAGE-CACHE-REDIS-PASSWORD] [--page-cache-redis-compress-data PAGE-CACHE-REDIS-COMPRESS-DATA] [--page-cache-redis-compression-lib PAGE-CACHE-REDIS-COMPRESSION-LIB] [--page-cache-id-prefix PAGE-CACHE-ID-PREFIX] [--lock-provider LOCK-PROVIDER] [--lock-db-prefix LOCK-DB-PREFIX] [--lock-zookeeper-host LOCK-ZOOKEEPER-HOST] [--lock-zookeeper-path LOCK-ZOOKEEPER-PATH] [--lock-file-path LOCK-FILE-PATH] [--document-root-is-pub DOCUMENT-ROOT-IS-PUB] [--base-url BASE-URL] [--language LANGUAGE] [--timezone TIMEZONE] [--currency CURRENCY] [--use-rewrites USE-REWRITES] [--use-secure USE-SECURE] [--base-url-secure BASE-URL-SECURE] [--use-secure-admin USE-SECURE-ADMIN] [--admin-use-security-key ADMIN-USE-SECURITY-KEY] [--admin-user [ADMIN-USER]] [--admin-password [ADMIN-PASSWORD]] [--admin-email [ADMIN-EMAIL]] [--admin-firstname [ADMIN-FIRSTNAME]] [--admin-lastname [ADMIN-LASTNAME]] [--search-engine SEARCH-ENGINE] [--elasticsearch-host ELASTICSEARCH-HOST] [--elasticsearch-port ELASTICSEARCH-PORT] [--elasticsearch-enable-auth ELASTICSEARCH-ENABLE-AUTH] [--elasticsearch-username ELASTICSEARCH-USERNAME] [--elasticsearch-password ELASTICSEARCH-PASSWORD] [--elasticsearch-index-prefix ELASTICSEARCH-INDEX-PREFIX] [--elasticsearch-timeout ELASTICSEARCH-TIMEOUT] [--cleanup-database] [--sales-order-increment-prefix SALES-ORDER-INCREMENT-PREFIX] [--use-sample-data] [--enable-modules [ENABLE-MODULES]] [--disable-modules [DISABLE-MODULES]] [--convert-old-scripts [CONVERT-OLD-SCRIPTS]] [-i|--interactive] [--safe-mode [SAFE-MODE]] [--data-restore [DATA-RESTORE]] [--dry-run [DRY-RUN]] [--magento-init-params MAGENTO-INIT-PARAMS]

```

**Comment by schroedt** [comment] 2021-08-22 18:37
I created a dedicated, supported `MariaDB` container for `Magento`. I noticed following issue for every deployment:

```
[…]
magento 18:13:16.79 INFO  ==> Trying to connect to the database server
magento 18:13:16.82 DEBUG ==> Executing SQL command:
SELECT 1
1
magento 18:13:16.93 INFO  ==> Trying to connect to Elasticsearch
magento 18:13:17.04 INFO  ==> Running Magento install script
Starting Magento installation:
[…]
[Progress: 652 / 1314]
Module 'Vertex_AddressValidation':
[Progress: 653 / 1314]
Module 'Yotpo_Yotpo':
[Progress: 654 / 1314]
[Progress: 655 / 1314]
Installing search configuration...
PHP Fatal error:  Uncaught Error: Wrong parameters for Elasticsearch\Common\Exceptions\ServerErrorResponseException([string $message [, long $code [, Throwable $previous = NULL]]]) in /opt/bitnami/magento/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:665
Stack trace:
#0 /opt/bitnami/magento/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(665): Exception->__construct()
#1 /opt/bitnami/magento/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(320): Elasticsearch\Connections\Connection->process5xxError()
#2 /opt/bitnami/magento/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}()
#3 /opt/bitnami/magento/vendor/ezimuel/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then()
#4 /opt/bitnami/magento/vendor/ezimuel/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then()
#5 /opt/bitnami/magento/vendor/elasticsearc in /opt/bitnami/magento/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php on line 665
```

Wanna check the code?

**Comment by schroedt** [comment] 2021-08-22 18:51
I noticed, `Magento` adds its container port to any URL for loading.. Is there any option for disabling that behavior?

I configured access using Istio via Port 443 » `https://magento.my-example.de/`
While initial page is loaded, `css`, `images` etc are requested by `https://magentomy-example.de:8080/, where `8080` is the service port. I would expect port propagating instead of hard-coded service port allocation for requesting resources.. Maybe something else is wrong?

BTW: I updated ` --set magentoHost=magento.my-example.de \`

**Comment by pablogalegoc** [comment] 2021-08-23 07:50
> Any chance getting Magento updated..? Or do you have a specific reason for not supporting Major -1 and newer?

This requirement comes from Magento itself and unfortunately we can't do anything about it: https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

> Wanna check the code?

On our part that step is just doing a `setup:install` with the Magento CLI:
https://github.com/bitnami/bitnami-docker-magento/blob/3ad25ac7772f1fb162ad47f53ea87800ab74f8bb/2/debian-10/rootfs/opt/bitnami/scripts/libmagento.sh#L224

Regarding the HTTPS and port issues, unfortunately our charts are not tested to work with Istio so we can not provide real support for it. Have you tried installing it with the same parameters but without Istio enabled? Just to confirm the issue is not with the chart itself

**Comment by schroedt** [comment] 2021-08-23 08:44
> Regarding the HTTPS and port issues, unfortunately our charts are not tested to work with Istio so we can not provide real support for it. Have you tried installing it with the same parameters but without Istio enabled? Just to confirm the issue is not with the chart itself

That's not configured on Istio-Side from my end and would behave totally different from any other workload deployed using istio. However, your statement is correct; I should formally try it out for verification. Even though non-istio `--set service.port=443`-parameter at `Helm install` defines the value. Further, I off-load TLS-Traffic and route it to magento, having non-TLS route. `/admin`requires TLS, which magento is not aware, since istio is taking care. I guess it would work, if I configure magento to be plain non-TLS for `/admin` as well.

**Comment by pablogalegoc** [comment] 2021-08-24 07:42
If you find further issues configuring HTTPS don't hesitate to open another ticket, for now I will close this one since the original problem is addressed.

**Closed by pablogalegoc** 2021-08-24 07:42 UTC
