### ISSUE TITLE
[bitnami/spark] Cannot mount config files from configmap

### ISSUE THREAD

**Issue by jaumann** [bitnami/charts#1732] opened 2019-12-12 19:39 UTC
**Which chart**:

bitnami/spark v1.1.0

**Description**

If you utilize the `master.configurationConfigMap` or `worker.configurationConfigMap` parameter, the configmap is mounted to `/opt/bitnami/spark/conf` in read-only mode as of kubernetes 1.9.4 (see the commit [here](https://github.com/kubernetes/kubernetes/pull/60258), additional discussion [here](https://github.com/kubernetes/kubernetes/issues/62099)). This prevents `conf/spark-env.sh` from being created when only `conf/spark-defaults.conf` is specified, since the whole conf directory is read-only. 

**Steps to reproduce the issue:**

1. Create a configmap with an entry for `spark-defaults.conf`
2. Deploy the chart, setting the value for `master.configurationConfigMap` to the configmap you created  

**Describe the results you received:**

The master pod fails to startup with the error
 ```
/entrypoint.sh: line 21: /opt/bitnami/spark/conf/spark-env.sh: Read-only file system
```

**Describe the results you expected:**

The `spark-defaults.conf` file contents should be reflected in the `/opt/bitnami/spark/conf/spark-defaults.conf` file, and the pod should start normally

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.23", GitCommit:"81c87c699557fed991e292cd328b2129c2f242a2", GitTreeState:"clean", BuildDate:"2019-11-07T19:23:23Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dani8art** [comment] 2019-12-13 09:06
Hi @jaumann 

Yes, you are right I had reproduced the issue but we consider that it should be fixed on the docker image initialization logic. The team is going to evaluate for fixing this issue. Thanks so much for your feedback. We'll keep you updated about our advances. 

Regards.

**Comment by agarfau** [comment] 2020-03-26 09:08
Hello,
Same issue here. Any updates on it?

Thanks.

**Comment by dani8art** [comment] 2020-03-26 09:29
Hello @agarfau we created an internal task but unfortunately, we can not give you an ETA. However, we are open to community contribution and we would appreciate a lot if you wanted to play a bit with the container https://github.com/bitnami/bitnami-docker-spark. You could inspire on and add this kind of logic to it.
- https://github.com/bitnami/bitnami-docker-cassandra/blob/cf5d38dd21d8af17e739582208dcb6b4669378f6/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L40
- https://github.com/bitnami/bitnami-docker-cassandra/blob/cf5d38dd21d8af17e739582208dcb6b4669378f6/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L322
- https://github.com/bitnami/bitnami-docker-cassandra/blob/cf5d38dd21d8af17e739582208dcb6b4669378f6/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L340

Thank you so much!

**Comment by daniel-mueller** [comment] 2020-12-18 14:14
Is there an update on this issue? Not being able to mount a custom spark-defaults.conf is quite the dealbreaker for me sadly.

**Comment by dani8art** [comment] 2020-12-18 15:11
Hi all, 

While we start working on fixing this issue you can use this other workaround https://github.com/bitnami/charts/issues/4656#issuecomment-742471556

Hopefully, it helps you!

**Comment by daniel-mueller** [comment] 2020-12-21 13:49
It did work, thanks!

**Comment by a-nldisr** [comment] 2021-03-16 14:05
We are running into this issue, we recently made a PR for the hostNetworking. However the master binds on the localhost interface, we, therefore, wanted to set `export SPARK_MASTER_IP=0.0.0.0` the spark-env.sh file and mount it as a config map. We also have a few configuration settings that we can enforce this way. 

```/opt/bitnami/scripts/spark/entrypoint.sh: line 22: /opt/bitnami/spark/conf/spark-env.sh: Permission denied```

We suspect we can fix this with an init container that corrects the permissions (we seen as solutions with other charts), @dani8art if we make a PR would you think this would be the solution? I can implement this quite quickly I think.

**Comment by Mauraza** [comment] 2021-03-17 09:53
Hi @a-nldisr,

Could you tell me if that is similar to this https://github.com/bitnami/charts/issues/4656#issuecomment-742471556  share by @dani8art?

**Comment by a-nldisr** [comment] 2021-03-17 10:03
> Hi @a-nldisr,
> 
> Could you tell me if that is similar to this [#4656 (comment)](https://github.com/bitnami/charts/issues/4656#issuecomment-742471556) share by @dani8art?
@Mauraza 
Sorry it is not the same, we try to execute a bash script here and it doesn't execute because it does not get the right permissions. The pods never start and it goes in a restart loop. From what I understand @dani8art had no issues starting the pod and submitting spark jobs.

**Comment by a-nldisr** [comment] 2021-03-17 13:28
Just a little additional comment: Some of the variables for the master, like port etc are variables in the chart. However, we can configure all the variables 1 by 1 with a PR. Or give people the ability to use the spark-env.sh as intended and configure these environment variables themselves.

**Comment by Mauraza** [comment] 2021-03-17 13:42
Hi @a-nldisr,

Could you add `SPARK_MASTER_IP` in `extraEnvVars` maybe you need to include it in the master and the worker?
```
  extraEnvVars:
  - name: SPARK_MASTER_IP
    value: "0.0.0.0"
```

**Comment by a-nldisr** [comment] 2021-03-23 16:30
Yes, that worked

**Comment by Mauraza** [comment] 2021-03-24 08:42
Hi @a-nldisr,

I'm glad that worked 👏🏻

**Comment by carrodher** [comment] 2022-10-20 13:20
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.

**Closed by carrodher** 2022-10-20 13:20 UTC
Labels: on-hold
