### ISSUE TITLE
[bitnami/moodle] Moodle not working with ReadWriteMany persistent volumes

### ISSUE THREAD

**Issue by chateauvieux** [bitnami/charts#1450] opened 2019-10-01 08:09 UTC
**Which chart**:

bitnami/moodle r3 / tested on Microsoft Azure k8s service (AKS) 1.14.5

**Description**

What happened:
Depolying Moodle on a ReadWriteOnce PV works fine, but when deploying on dynamically created ReadWriteMany PVs (in this case: relying on the azure-file service), the moodle /login/index.php does not become available.

The pod readiness does pass, the log file does not show any specific error, but when connecting to moodle the following message is displayed:

error/An error occurred whilst communicating with the server

The idea behind deploying moodle on such PVs is to be able to scale the app horizontally (by spawning additional pods behind the load balancer)

**Describe the results you expected:**

the /login/index.php should become available.

**Additional information you deem important (e.g. issue happens only occasionally):**

Anything else we need to know:

It works ok with other plugins for getting pvs.
the folders are properly mounted inside the pod:

**Version of Helm and Kubernetes**:

- Output of `helm version`:

helm version --tls
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

- Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by andresbono** [comment] 2019-10-01 13:55
Hi @chateauvieux, does the error occur consistently?

Would you mind sharing the modifications you have done to the chart so we are able to reproduce your particular scenario?

**Comment by chateauvieux** [comment] 2019-10-01 19:36
Yes, the error occurs consistently. I have also tried on IBM Cloud's 
Kubernetes Service, same problem when using ReadWriteMany PVs.

In order to reproduce, simply try deploying Moodle on the following PVC: 
(see extract from values.yaml) after creating a PVC such as the one that 
follows:

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: data-prod-moodle-for-shifters
   annotations:
     volume.beta.kubernetes.io/storage-class: "azurefile"
spec:
   accessModes:
     - ReadWriteMany
   storageClassName: azurefile
   resources:
     requests:
       storage: 8Gi


Extract from the moodle chart values.yaml


(...)
persistence:
   enabled: true
   ## database data Persistent Volume Storage Class
   ## If defined, storageClassName: <storageClass>
   ## If set to "-", storageClassName: "", which disables dynamic 
provisioning
   ## If undefined (the default) or set to null, no storageClassName spec is
   ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
   ##   GKE, AWS & OpenStack)
   ##
   storageClass: "azurefile"
   accessMode: ReadWriteMany
   size: 8Gi
   existingClaim: data-prod-moodle-for-shifters
(...)


Note: for the PVC dynamic provisioning to work, you will first need to 
define a storageclass such as

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
   name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
   - dir_mode=0777
   - file_mode=0777
   - uid=1000
   - gid=1000
   - mfsymlinks
   - nobrl
   - cache=none
parameters:
   skuName: Standard_LRS
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
   name: system:azure-cloud-provider
rules:
- apiGroups: ['']
   resources: ['secrets']
   verbs:     ['get','create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
   name: system:azure-cloud-provider
roleRef:
   kind: ClusterRole
   apiGroup: rbac.authorization.k8s.io
   name: system:azure-cloud-provider
subjects:
- kind: ServiceAccount
   name: persistent-volume-binder
   namespace: kube-system


Hope this helps,

Christian


Le 01/10/2019 à 15:55, Andrés Bono a écrit :

**Comment by andresbono** [comment] 2019-10-02 06:13
Thanks for all the information. We will try to reproduce it.

**Comment by andresbono** [comment] 2019-10-14 06:57
Hi @chateauvieux, we couldn't reproduce your issue.

Any updates on your side?

**Comment by chateauvieux** [comment] 2019-10-14 22:04
I am still facing the same issue.
How did you attempt to reproduce the issue ? Did you use the same YAMLs to create the PVC ?

**Comment by andresbono** [comment] 2019-10-21 14:26
Sorry for the late response @chateauvieux. On my first try, I didn't apply the correct configuration so I wasn't using the `azurefile` storage class.

I'm now testing again. What I observe is a really bad performance in terms of IO throughput in the shared file system. For that reason. the initialization of Moodle is taking some time. I will post an update as soon as the initialization finishes.

**Comment by andresbono** [comment] 2019-10-21 15:23
I got the error now:

![image](https://user-images.githubusercontent.com/1057973/67218792-4466cb00-f427-11e9-9107-b8be64e6d7a9.png)

We will continue investigating why this is happening.

**Comment by andresbono** [comment] 2019-10-22 07:02
The size of the database schema is not as big as the schema of a fully working deployment: `1.1` MB vs `1.9` MB.

I have tried to re-populate the database in several ways (`/opt/bitnami/moodle/admin/cli/upgrade.php`, `/opt/bitnami/moodle/admin/cli/install_database.php`). All the commands finish successfully but none of them make it work.

Have you tried to work with Azure Files before?

**Comment by chateauvieux** [comment] 2019-10-22 07:42
no... first time I try. but i have seen a similar behavior on IBM Cloud
when using their equivalent service

Le mar. 22 oct. 2019 à 09:03, Andrés Bono <notifications@github.com> a
écrit :

**Comment by andresbono** [comment] 2019-10-23 09:28
@chateauvieux, I'm not sure if there is much we can do to solve this issue as the configuration applied in both scenarios (the one that works and the one that doesn't) is the same. Do you have any suggestions?

**Comment by chateauvieux** [comment] 2019-11-07 10:32
you are the specialist... and have reproduced the issue in your lab. i'll
let you investigate. .. no idea on my end

Le mer. 23 oct. 2019 à 11:29, Andrés Bono <notifications@github.com> a
écrit :

**Comment by andresbono** [comment] 2019-11-11 09:56
Ok, thanks for reporting the problem, @chateauvieux. As there is not much we can do on the configuration side, we are going to close this issue. We will comment here if we have any updates.

**Closed by andresbono** 2019-11-11 09:56 UTC
