### ISSUE TITLE
[bitnami/airflow] web pod is failed when LDAP is enabled -- not support Microsoft AD setup

### ISSUE THREAD

**Issue by echang0929** [bitnami/charts#6082] opened 2021-04-13 00:57 UTC
**Which chart**:
airflow

**Describe the bug**
Starting web pod is failed when LDAP is enabled

```
➜ k logs app-aflow-airflow-web-774b59d64f-hjb7v
airflow 00:27:37.84
airflow 00:27:37.84 Welcome to the Bitnami airflow container
airflow 00:27:37.84 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow
airflow 00:27:37.85 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow/issues
airflow 00:27:37.85
airflow 00:27:37.85 INFO  ==> ** Starting Airflow setup **
/opt/bitnami/scripts/libairflow.sh: line 36: print_validation_error: command not found
```

so that other airflow pods could not be initialized.

**To Reproduce**
I've tested either with "--set" or by changing values.yaml

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9+IKS", GitCommit:"7a4d9dfae15cc9e68bb0cb61d7322e7ccfbde865", GitTreeState:"clean", BuildDate:"2021-03-20T11:15:13Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by alvneiayu** [comment] 2021-04-13 16:14
hi @echang0929 

Could you share with me the values that you are setting up, please? Are you enabling only the LDAP or you are setting up more values? If you can share with me the values.yaml or the command line that you are using.

Thanks a lot

Álvaro

**Comment by alvneiayu** [comment] 2021-04-13 18:28
hi @echang0929 

Seems that something is missing in your configuration. The logs that you are sharing shows an error inside our docker image that a function is missing, I am working to fix the problem. With the docker fixed you will see the message telling which LDAP value in your configuration is not properly set up. I am not able to give you an ETA. We will update this thread once we have news.

Thanks

Álvaro

**Comment by echang0929** [comment] 2021-04-14 10:03
Hi @alvneiayu 
Thank you for your reply and messages. I've tested both:
```
helm install app-aflow ./bitnami/airflow \
  --set global.storageClass=ibmc-file-gold \
  --set postgresql.livenessProbe.initialDelaySeconds=200 \
  --set postgresql.readinessProbe.initialDelaySeconds=200 \
  --set postgresql.volumePermissions.enabled=true \
  --set redis.volumePermissions.enabled=true \
  --set ldap.enabled=true \
  --set "ldap.uri=ldap://bluepages.ibm.com:389" \
  --set "ldap.base=c=cn,ou=bluepages,o=ibm.com" \
  --set "ldap.uidField=mail"
```
and 
```
helm install app-aflow ./bitnami/airflow \
  --set global.storageClass=ibmc-file-gold \
  --set postgresql.livenessProbe.initialDelaySeconds=200 \
  --set postgresql.readinessProbe.initialDelaySeconds=200 \
  --set postgresql.volumePermissions.enabled=true \
  --set redis.volumePermissions.enabled=true \
  --set ldap.enabled=true \
  --set ldap.uri="ldap://bluepages.ibm.com:389" \
  --set ldap.base="c=cn,ou=bluepages,o=ibm.com" \
  --set ldap.uidField="mail"
```

Even, I updated values.yaml as:
```
## LDAP configuration
##
ldap:
  ## Enable LDAP authentication
  ##
  enabled: true
  ## Server URI, eg. ldap://ldap_server:389
  ##
  uri: 'ldap://bluepages.ibm.com:389'
  ## Base of the search, eg. ou=example,o=org
  ##
  base: 'c=cn,ou=bluepages,o=ibm.com'
  ## Bind DN
  ##
  binddn: ''
  ## Bind Password
  ##
  bindpw: ''
  ## Field used for uid
  ##
  uidField: 'mail'
  ## SSL/TLS parameters for LDAP
  ##
```
then run:
```
helm install app-aflow ./bitnami/airflow \
  --set global.storageClass=ibmc-file-gold \
  --set postgresql.livenessProbe.initialDelaySeconds=200 \
  --set postgresql.readinessProbe.initialDelaySeconds=200 \
  --set postgresql.volumePermissions.enabled=true \
  --set redis.volumePermissions.enabled=true
```

**Comment by alvneiayu** [comment] 2021-04-14 14:30
hi @echang0929 

I already included the changes in the image but the Chart is not already updated. I checked with this tag (docker image with my change included).

```
diff --git a/bitnami/airflow/values.yaml b/bitnami/airflow/values.yaml
index d50462cf5..94f856653 100644
--- a/bitnami/airflow/values.yaml
+++ b/bitnami/airflow/values.yaml
@@ -65,7 +65,7 @@ web:
   image:
     registry: docker.io
     repository: bitnami/airflow
-    tag: 2.0.1-debian-10-r51
+    tag: 2.0.1-debian-10-r59
     ## Specify a imagePullPolicy
     ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
     ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
```
I executed one of your commands:

```
helm install app-aflow ./bitnami/airflow \
  --set global.storageClass=ibmc-file-gold \
  --set postgresql.livenessProbe.initialDelaySeconds=200 \
  --set postgresql.readinessProbe.initialDelaySeconds=200 \
  --set postgresql.volumePermissions.enabled=true \
  --set redis.volumePermissions.enabled=true \
  --set ldap.enabled=true \
  --set "ldap.uri=ldap://bluepages.ibm.com:389" \
  --set "ldap.base=c=cn,ou=bluepages,o=ibm.com" \
  --set "ldap.uidField=mail"
```
And I can see this inside the web pod:

```
kubectl logs pod/app-aflow-airflow-web-XXXXX
airflow 14:19:40.53 
airflow 14:19:40.53 Welcome to the Bitnami airflow container
airflow 14:19:40.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow
airflow 14:19:40.53 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow/issues
airflow 14:19:40.53 
airflow 14:19:40.53 INFO  ==> ** Starting Airflow setup **
airflow 14:19:40.54 ERROR ==> Missing AIRFLOW_LDAP_BIND_PASSWORD
```

The ldap password is missing in your configuration. Set up the ldap.bindpw and try again. Using the tag change that I included above, you will see the error messages without the "print_validation_error: command not found" error message.

Let me know if I can help you with something else.

Thanks for your time.

Álvaro

**Comment by echang0929** [comment] 2021-04-14 14:43
Hi @alvneiayu,

Thank you for your quick and detailed reply. There is no bind dn and bind password as you see in the values.yaml file I updated. We could use these parameters in other systems.

**Comment by alvneiayu** [comment] 2021-04-15 11:45
hi @echang0929 

I reproduced a problem in our charts. I will create a PR. We will update this thread once I have the PR ready.

Thanks

Álvaro

**Comment by alvneiayu** [comment] 2021-04-16 17:01
hi @echang0929 

I created an internal task and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks again.

Álvaro

**Comment by plume33** [comment] 2021-04-22 12:39
Any new or solution for this issue ?

**Comment by alvneiayu** [comment] 2021-04-23 06:34
hi @plume33 

No news, sorry. We will update this thread once we have news.

Thanks

Álvaro

**Comment by rward27** [comment] 2021-04-30 08:31
Facing same issue... no logs to debug as such in the pod of web... tried with several versions of docker images of bitnami/airflow but no luck with what should we debug/try to resolve...

**Comment by junkiebev** [comment] 2021-05-13 05:43
@alvneiayu - can you give a hint at root cause? Is it database schema related?

**Comment by echang0929** [comment] 2021-05-13 14:07
I have an initial investigation. Firstly, Airflow 1.10.x and Airflow 2 support LDAP differently. 
Version 1.10.15: https://airflow.apache.org/docs/apache-airflow/1.10.15/security.html#ldap
Version 2.0.2: https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-ldap

Focusing on version 2, you see, there are two templates for LDAP configuration: 
1. Microsoft AD : no need for parameters about bind
2. OpenLDAP:  need two parameters bind_user and bind_password. 

I think the current image for this chart only support OpenLDAP: https://github.com/bitnami/bitnami-docker-airflow/blob/4c3e400883616a301f4c0d7c8c537f210d7eba14/2/debian-10/rootfs/opt/bitnami/scripts/libairflow.sh#L43-L45

My configuration needs the type of Microsoft AD. Then I tried to setup local docker env to validate Airflow version 2 for supporting Microsoft AD type LDAP, following the video https://www.youtube.com/watch?v=s6TygwvYdN0, just replacing its OpenLDAP template with my AD configuration. 

Although I logged in our LDAP server there are some issues on the response webpage.  So I doubt Airflow 2 to support AD type LDAP not so good.

**Comment by echang0929** [comment] 2021-05-13 17:29
Good news, I could log in our LDAP server with the following configuration:

```
AUTH_TYPE = AUTH_LDAP
AUTH_LDAP_SERVER = "ldap://bluegroups.ibm.com:389"
AUTH_LDAP_USE_TLS = False

# registration configs
AUTH_USER_REGISTRATION = True  # allow users who are not already in the FAB DB
AUTH_USER_REGISTRATION_ROLE = "Admin"  # this role will be given in addition to any AUTH_ROLES_MAPPING
AUTH_LDAP_FIRSTNAME_FIELD = "givenName"
AUTH_LDAP_LASTNAME_FIELD = "sn"
AUTH_LDAP_EMAIL_FIELD = "mail"  # if null in LDAP, email is set to: "{username}@email.notfound"

# bind username (for password validation)
AUTH_LDAP_USERNAME_FORMAT = "uid=%s,c=cn,ou=bluepages,o=ibm.com"  # %s is replaced with the provided username
# AUTH_LDAP_APPEND_DOMAIN = "example.com"  # bind usernames will look like: {USERNAME}@example.com

# search configs
AUTH_LDAP_SEARCH = "c=cn,ou=bluepages,o=ibm.com"  # the LDAP search base (if non-empty, a search will ALWAYS happen)
#AUTH_LDAP_UID_FIELD = "uid"  # the username field
```

@alvneiayu , I think we need to update both image script and chart template to support it? Or, need we extend it to support configuration file volume?

**Comment by echang0929** [comment] 2021-05-15 00:10
I've posted an issue in the repository of bitnami airflow docker: https://github.com/bitnami/bitnami-docker-airflow/issues/84

Next, we need update codes in: 
1. https://github.com/bitnami/charts/blob/master/bitnami/airflow/templates/web/deployment.yaml
2. https://github.com/bitnami/charts/blob/master/bitnami/airflow/values.yaml

to support this enhancement

**Comment by alvneiayu** [comment] 2021-05-17 07:14
hi all, sorry for the delay

@junkiebev yes, we are facing a problem creating the database. The problem is under investigation. Postgresql is blocked during the bootup with LDAP enabled. I will come back with more information soon.

Thanks @echang0929 for sharing your solution. I saw that you fixed your problem and thanks for creating a new issue to include your solution. Again thanks for sharing your solution.

Álvaro

**Comment by jayaswalayush** [comment] 2021-05-19 11:13
Hello,

I have updated all the LDAP fields in the values.yaml however when i try to install Airflow I get the below error :

Error: Deployment.apps "airflow-web" is invalid: spec.template.spec.containers[1].env[20].valueFrom: Invalid value: "": may not be specified when `value` is not empty

I checked further and found the airflow-web deployment.yaml has both value and valueFrom in the deployment template

- name: AIRFLOW_LDAP_ENABLE
  value: {{ ternary "yes" "no" .Values.ldap.enabled | quote }}
{{- if .Values.ldap.enabled }}
- name: AIRFLOW_LDAP_URI
  value: {{ .Values.ldap.uri }}
- name: AIRFLOW_LDAP_SEARCH
  value: {{ .Values.ldap.base }}
- name: AIRFLOW_LDAP_BIND_USER
  value: {{ .Values.ldap.binddn }}
- name: AIRFLOW_LDAP_BIND_PASSWORD
  value: {{ .Values.ldap.bindpw }}
  valueFrom:
	secretKeyRef:
	  name: {{ include "airflow.ldapSecretName" . }}
	  key: bind-password
- name: AIRFLOW_LDAP_UID_FIELD
  value: {{ .Values.ldap.uidField }}
- name: AIRFLOW_LDAP_USE_TLS
  value: {{ ternary "yes" "no" .Values.ldap.tls.enabled | quote }}
{{- if .Values.ldap.tls.enabled }}
- name: AIRFLOW_LDAP_ALLOW_SELF_SIGNED
  value: {{ .Values.ldap.tls.allowSelfSigned }}
- name: AIRFLOW_LDAP_TLS_CA_CERTIFICATE
  value: {{ include "airflow.ldapCAFilename" . | quote }}
  
 
Ideally we should have only valueFrom for ldap.bindpw field ?

**Comment by cccs-mjs** [comment] 2021-05-19 13:49
> Good news, I could log in our LDAP server with the following configuration:
> 
> ```
> import os
> 
> from flask_appbuilder.security.manager import AUTH_LDAP
> 
> AUTH_TYPE = AUTH_LDAP
> AUTH_LDAP_SERVER = "ldap://ldap.example.com:389"
> AUTH_LDAP_USE_TLS = False
> 
> # registration configs
> AUTH_USER_REGISTRATION = True  # allow users who are not already in the FAB DB
> AUTH_USER_REGISTRATION_ROLE = "Admin"  # this role will be given in addition to any AUTH_ROLES_MAPPING
> AUTH_LDAP_FIRSTNAME_FIELD = "givenName"
> AUTH_LDAP_LASTNAME_FIELD = "sn"
> AUTH_LDAP_EMAIL_FIELD = "mail"  # if null in LDAP, email is set to: "{username}@email.notfound"
> 
> # bind username (for password validation)
> AUTH_LDAP_USERNAME_FORMAT = "uid=%s,ou=users,dc=example,dc=com"  # %s is replaced with the provided username
> # AUTH_LDAP_APPEND_DOMAIN = "example.com"  # bind usernames will look like: {USERNAME}@example.com
> 
> # search configs
> AUTH_LDAP_SEARCH = "ou=users,dc=example,dc=com"  # the LDAP search base (if non-empty, a search will ALWAYS happen)
> #AUTH_LDAP_UID_FIELD = "uid"  # the username field
> ```
@echang0929 Did you configure that via `web.configMap` (i.e. `Name of an existing config map containing the Airflow webserver config file`) in the Helm chart values.yaml?

**Comment by echang0929** [comment] 2021-05-19 23:30
@cccs-mjs Sorry to make confusion. I just used these configuration in docker based Airflow to validate LDAP functions. Actually bitnami's Airflow imgage contains mappings between env variables AIRFLOW_* and Airflow's config keys AUTH_* https://github.com/bitnami/bitnami-docker-airflow/blob/2bb4cac8119e9d0d446cb313056602fd8ea4be1b/2/debian-10/rootfs/opt/bitnami/scripts/libairflow.sh#L241-L249

So I'm trying to add more config keys in bitnami's Airflow image to extend its supports on LDAP.

**Comment by jayaswalayush** [comment] 2021-06-03 13:13
@alvneiayu @juan131 : Please update if there is any update on Postgres Database issue when LDAP is enabled ?

I am getting the below error 👍 

STATEMENT:  SELECT connection.conn_id AS connection_conn_id
        FROM connection GROUP BY connection.conn_id
        HAVING count(*) > 1
2021-05-31 08:04:53.790 GMT [177] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2021-05-31 08:04:53.790 GMT [177] STATEMENT:  SELECT connection.password AS connection_password, connection.extra AS connection_extra, connection.id AS connection_id, connection.conn_id AS connection_conn_id, connection.conn_type AS connection_conn_type, connection.description AS connection_description, connection.host AS connection_host, connection.schema AS connection_schema, connection.login AS connection_login, connection.port AS connection_port, connection.is_encrypted AS connection_is_encrypted, connection.is_extra_encrypted AS connection_is_extra_encrypted
        FROM connection
        WHERE connection.conn_type IS NULL

 ERROR:  relation "connection" does not exist at character 55

**Comment by alvneiayu** [comment] 2021-06-04 06:04
hi @jayaswalayush 

We are working to try to find a solution as soon as possible. As I mentioned, I am not able to give you an ETA. We will update this thread once we have news.

Sorry and thanks for your patience

Álvaro

**Comment by echang0929** [comment] 2021-06-09 02:06
@jayaswalayush I encountered the same error, even I do not configure LDAP. Pls refer to my post: https://github.com/bitnami/bitnami-docker-airflow/issues/84#issuecomment-855329147

**Comment by jayaswalayush** [comment] 2021-06-11 08:02
@echang0929 : Do you have any update on how this issue could be resolved when we use the Helm chart for Airflow Install ?

**Comment by pushkinsk44** [comment] 2021-07-01 20:02
Hi all
I had a similar problem when using Helm (version: 10.2.2)
When LDAP was enabled, the web server did not start.
This thread helped me find the right way to solve my problem.

The reason was that the web server configuration file webserver_config.py was filled incorrectly

The problem was solved by correcting libairflow.sh

`    ########################
    # Configure Airflow webserver authentication
    # Globals:
    #   AIRFLOW_*
    # Arguments:
    #   None
    # Returns:
    #   None
    #########################
    airflow_configure_webserver_authentication() {
        info "Configuring Airflow webserver authentication"
        airflow_conf_set "webserver" "rbac" "true"
        local -r file="$AIRFLOW_WEBSERVER_CONF_FILE"

        if is_boolean_yes "$AIRFLOW_LDAP_ENABLE"; then
            info "Enabling LDAP authentication"
            airflow_webserver_conf_set "AUTH_USER_REGISTRATION" "True"
            airflow_webserver_conf_set "AUTH_TYPE" "AUTH_LDAP"
            airflow_webserver_conf_set "AUTH_LDAP_SERVER" "'$AIRFLOW_LDAP_URI'"
            airflow_webserver_conf_set "AUTH_LDAP_SEARCH" "'$AIRFLOW_LDAP_SEARCH'"
            airflow_webserver_conf_set "AUTH_LDAP_BIND_USER" "'$AIRFLOW_LDAP_BIND_USER'"
            airflow_webserver_conf_set "AUTH_LDAP_BIND_PASSWORD" "'$AIRFLOW_LDAP_BIND_PASSWORD'"
            airflow_webserver_conf_set "AUTH_LDAP_UID_FIELD" "'$AIRFLOW_LDAP_UID_FIELD'"
            airflow_webserver_conf_set "AUTH_LDAP_USE_TLS" "$AIRFLOW_LDAP_USE_TLS"
            airflow_webserver_conf_set "AUTH_LDAP_ALLOW_SELF_SIGNED" "$AIRFLOW_LDAP_ALLOW_SELF_SIGNED"
            airflow_webserver_conf_set "AUTH_LDAP_TLS_CACERTFILE" "'$AIRFLOW_LDAP_TLS_CA_CERTIFICATE'"
            airflow_webserver_conf_set "AUTH_USER_REGISTRATION_ROLE" "'$AIRFLOW_USER_REGISTRATION_ROLE'"

            replace_in_file "$file" "from flask_appbuilder\.security\.manager import AUTH_DB" "from flask_appbuilder\.security\.manager import AUTH_LDAP" false
        fi
    }

    ########################
    # Set properties in Airflow's webserver_config.py
    # Globals:
    #   AIRFLOW_*
    # Arguments:
    #   None
    # Returns:
    #   None
    #########################
    airflow_webserver_conf_set() {
        local -r key="${1:?missing key}"
        local -r value="${2:-}"
        shift 2

        local -r file="$AIRFLOW_WEBSERVER_CONF_FILE"
        # Check if the value was set before
        if [ -z "${value}" ]; then
            info "Variable value with key ${key} is empty, skipping"
        else
            if grep -q "^#*\\s*${key}\\s*=\\s*.*$" "$file"; then
                info "Updating key ${key} with value ${value} in file ${file}"
                # Update the existing key
                replace_in_file "$file" "^#*\\s*${key}\\s*=\\s.*$" "${key} = ${value}" false
            else
                info "Inserting key ${key} with value ${value} in file ${file}"
                # Add a new key
                printf '\n%s = %s' "$key" "$value" >>"$file"
            fi
        fi
    }`

**Comment by Mauraza** [comment] 2021-07-05 06:30
Hi @echang0929, @jayaswalayush @pushkinsk44 

In the nest release of the container of airflow, LDAP will be fixed.

**Comment by pushkinsk44** [comment] 2021-07-05 06:44
Another place where changes were made to fix this problem is web.deployement

Before
```
            - name: AIRFLOW_LDAP_USE_TLS
              value: {{ ternary "yes" "no" .Values.ldap.tls.enabled | quote }}
```

After
```
            - name: AIRFLOW_LDAP_USE_TLS
              value: {{ ternary "True" "False" .Values.ldap.tls.enabled | quote }}
```

**Comment by jayaswalayush** [comment] 2021-07-06 09:20
@Mauraza : Thanks for the update. Does this 2.1.1-debian-10-r0 docker image contains the fix ?

**Comment by Mauraza** [comment] 2021-07-06 09:22
Hi @jayaswalayush 
> Does this 2.1.1-debian-10-r0 docker image contains the fix?

That's right.

**Comment by Mauraza** [comment] 2021-07-06 09:23
Hi @pushkinsk44,

I just create the PR 😄

**Comment by jayaswalayush** [comment] 2021-07-07 08:40
Doesn't work still the same issue 

![image](https://user-images.githubusercontent.com/59866888/124727732-98cc1a00-df2c-11eb-9154-578ce5408793.png)

![image](https://user-images.githubusercontent.com/59866888/124727919-c913b880-df2c-11eb-87c9-8988b66d39a9.png)

![image](https://user-images.githubusercontent.com/59866888/124727988-d761d480-df2c-11eb-940f-c7e0911fa914.png)

I have used docker.io/bitnami/airflow:2.1.1-debian-10-r0 image for airflow web , worker and scheduler

**Comment by pushkinsk44** [comment] 2021-07-07 22:20
Hi @Mauraza, 
I also tried with a new image 2.1.1-debian-10-r0
and it doesn't work because we expect in the final webserver_config.py

this

```
"""Default configuration for the Airflow webserver"""
import os

from flask_appbuilder.security.manager import AUTH_LDAP

basedir = os.path.abspath(os.path.dirname(__file__))

WTF_CSRF_ENABLED = True

AUTH_TYPE = AUTH_LDAP
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE ='Admin'
AUTH_LDAP_SERVER = 'ldaps://***:636'
AUTH_LDAP_SEARCH = 'dc=***,dc=***,dc=***'
AUTH_LDAP_BIND_USER = '***'
AUTH_LDAP_BIND_PASSWORD = '***'
AUTH_LDAP_UID_FIELD = 'uid'
AUTH_LDAP_USE_TLS = False
AUTH_LDAP_ALLOW_SELF_SIGNED = True

```

but we have this

```
"""Default configuration for the Airflow webserver"""
import os

from flask_appbuilder.security.manager import AUTH_DB

from flask_appbuilder.security.manager import AUTH_LDAP

basedir = os.path.abspath(os.path.dirname(__file__))

WTF_CSRF_ENABLED = True

AUTH_TYPE = "AUTH_LDAP"
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = "Admin"
AUTH_LDAP_SERVER = "ldaps://***:636"
AUTH_LDAP_SEARCH="dc=***,dc=***,dc=***"
AUTH_LDAP_BIND_USER="***"
AUTH_LDAP_BIND_PASSWORD="***"
AUTH_LDAP_UID_FIELD="uid"
AUTH_LDAP_USE_TLS="False"
AUTH_LDAP_ALLOW_SELF_SIGNED="True"
```

there are several errors
- quotes around True, False, AUTH_LDAP
-  duplicated string "from flask_appbuilder.security.manager import" with different values

**Comment by Mauraza** [comment] 2021-07-08 09:29
Hi @aandryashin and @pushkinsk44,

I have found the solution when this will released I will update this thready merge the PR.

**Comment by Mauraza** [comment] 2021-07-09 07:47
Hi @aandryashin and @pushkinsk44,

The new version is out, it should work perfectly. Could you check it?

**Closed** 2021-07-09 08:16 UTC
Labels: on-hold

**Comment by pushkinsk44** [comment] 2021-07-09 23:24
Hi @Mauraza,
I tried with a new image 2.1.1-debian-10-r4
and it doesn't work because in webserver_config.py we have:


```
"""Default configuration for the Airflow webserver"""
import os

from flask_appbuilder.security.manager import AUTH_DB

from flask_appbuilder.security.manager import AUTH_LDAP

basedir = os.path.abspath(os.path.dirname(__file__))

WTF_CSRF_ENABLED = True

AUTH_TYPE = "AUTH_LDAP"
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = 'Admin'
AUTH_LDAP_SERVER = 'ldaps://***:636'
AUTH_LDAP_SEARCH=dc=***,dc=***,dc=***
AUTH_LDAP_BIND_USER=***
AUTH_LDAP_BIND_PASSWORD=***
AUTH_LDAP_UID_FIELD=uid
AUTH_LDAP_USE_TLS=False
AUTH_LDAP_ALLOW_SELF_SIGNED=True

```

In order for it to work well, it needs to be like this

```
"""Default configuration for the Airflow webserver"""
import os

from flask_appbuilder.security.manager import AUTH_LDAP

basedir = os.path.abspath(os.path.dirname(__file__))

WTF_CSRF_ENABLED = True

AUTH_TYPE = AUTH_LDAP
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = 'Admin'
AUTH_LDAP_SERVER = 'ldaps://***:636'
AUTH_LDAP_SEARCH = 'dc=***,dc=***,dc=***'
AUTH_LDAP_BIND_USER = '***'
AUTH_LDAP_BIND_PASSWORD = '***'
AUTH_LDAP_UID_FIELD = 'uid'
AUTH_LDAP_USE_TLS = False
AUTH_LDAP_ALLOW_SELF_SIGNED = True
```

just compare

**Comment by Mauraza** [comment] 2021-07-12 06:44
Hi @echang0929, 

In the next release that will be fixed. Thanks for reporting.

**Comment by jayaswalayush** [comment] 2021-07-21 07:36
Hi @Mauraza,

With the new release the deployment is success and all pods are in running state

![image](https://user-images.githubusercontent.com/59866888/126449557-25064827-488c-45b0-b0f5-cdb129b65335.png)


However when we open the Login page in the browser we are getting too many redirects error 

![image](https://user-images.githubusercontent.com/59866888/126449723-6f8d24fa-eafa-4198-a968-e1490fb55dd4.png)

Note : I am using ingress for opening the Airflow URL also I have already added proxy fix in env variables 

![image](https://user-images.githubusercontent.com/59866888/126449933-77a7c097-4c61-48d6-bc6c-095a4913f447.png)

**Comment by Mauraza** [comment] 2021-07-21 08:02
Hi @jayaswalayush,

Did you try to use this ⬇️ ?
```
web:
  baseUrl: http://$AIRFLOW_HOST:$AIRFLOW_PORT
```
It seems is not related to LDAP. 
Could you open a new issue with your values to try to reproduce the issue?

**Comment by jayaswalayush** [comment] 2021-07-22 10:43
@Mauraza : Created a new issue 

#7010
