### ISSUE TITLE
mariabackup user cannot connect when password is complicated

### ISSUE THREAD

**Issue by zsoltbalogh** [bitnami/charts#10880] opened 2022-06-24 11:58 UTC
### Name and Version

bitnami/mariadb-galera:10.4

### What steps will reproduce the bug?

1. Set up a mariadb galera cluster using the recommended configuration
2. Create a docker secret with a complicated password (should contain special characters, example:
    ```p+G?{/`OJ1!,)U=W~5U-vPg4```
    and configure that for `MARIADB_GALERA_MARIABACKUP_PASSWORD_FILE`
4. Start the cluster. When the second node tries to join the backup would fail and the second node stops

### What is the expected behavior?

The backup works. :)

### What do you see instead?
```
    db-vm-1    | WSREP_SST: [INFO] Evaluating /opt/bitnami/mariadb//bin/mariabackup --defaults-file='/opt/bitnami/mariadb/conf/my.cnf' --backup --no-version-check --databases-exclude='lost+found' --tmpdir='/opt/bitnami/mariadb/tmp/tmp.5qKCrFrnL0' --innodb-data-home-dir='.' --log-bin='mysql-bin' --user='""mymariabackup' --socket='/opt/bitnami/mariadb/tmp/mysql.sock' --galera-info --stream=mbstream --target-dir='/tmp/tmp.2ExSbI46FC' --datadir='/bitnami/mariadb/data' --mysqld-args '--basedir=/opt/bitnami/mariadb' '--pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid' '--wsrep_provider_options=ist.recv_addr=192.168.0.184:4568;ist.recv_bind=0.0.0.0:4568' '--wsrep_node_incoming_address=192.168.0.184' '--wsrep_sst_receive_address=192.168.0.184' 2> '/bitnami/mariadb/data/mariabackup.backup.log' | socat -u stdio TCP:192.168.0.57:4444; RC=( ${PIPESTATUS[@]} ) (20220624 11:46:31.078)
    db-vm-1    | 2022-06-24 11:46:31 20 [Warning] Access denied for user '""mymariabackup'@'localhost' (using password: YES)
```
Note the double quote before the username.

### Additional information

I think the issue is coming from an escaping problem in the my.cnf:
```
    I have no name!@db-vm-1:/$ cd /opt/bitnami/mariadb/conf/
    I have no name!@db-vm-1:/opt/bitnami/mariadb/conf$ cat my.cnf
    [..]
    wsrep_sst_auth="""mymariabackup:p+G?{/`OJ1!,)U=W~5U-vPg4"""
```

**Comment by marcosbc** [comment] 2022-06-27 15:33
Hi @zsoltbalogh, this issue is most likely related to escaping the password in `my.cnf` as you say. Right now we are using the [`ini-file` tool](https://github.com/bitnami/ini-file) to set the passwords, and it is possible that it does not support input of special characters.

If you are able to fix the issue, we'd be happy to review and help with the release of those changes. In the meantime, we recommend you to avoid characters that may break the Ini file (i.e. quotes and "`").

**Comment by zsoltbalogh** [comment] 2022-06-28 07:12
Thanks, @marcosbc, I'll attempt to fix. :)

**Comment by zsoltbalogh** [comment] 2022-07-02 12:13
Working on the issue. The """ is clearly not valid, I haven't seen any reference to triple double quote in ini files.

Checked:
- https://dev.mysql.com/doc/refman/8.0/en/option-files.html#option-file-syntax
- https://en.wikipedia.org/wiki/INI_file

**Comment by zsoltbalogh** [comment] 2022-07-02 12:13
The ` character causes the problem.

**Comment by zsoltbalogh** [comment] 2022-07-02 12:22
The """-s are generated by https://github.com/go-ini/ini/

It looks like """ is a thing in .ini files by mysql does not really know what to do with those. 

So go-ini is correct, mysql is correct (they don't say the level of compatibility with this anywhere in their documentation) so we are stuck in-between.

**Comment by marcosbc** [comment] 2022-07-04 14:09
@zsoltbalogh If so, how are users supposed to escape the "`" character in the MySQL `.ini` file? Have you checked if replacing all occurrences of `"""` with `"` would work? If so, we could add a call to `replace_in_file` to get it working.

**Comment by zsoltbalogh** [comment] 2022-08-08 10:13
@marcosbc, I'm sorry for the late reply, I was afk for some weeks. I've tested and it works with a single double quote (") and without any quotes.

The way I tested was the following: created a my_custom.cnf file and added the following:
```
[galera]
wsrep_sst_auth=mariabackup:ea8`lU3jhRVPhrvMan
```

Mounted this file to /opt/bitnami/mariadb/conf/my_custom.cnf, then restarted the cluster and wait for the sync to happen and it worked.

Same is true with the double quotes:
```
[galera]
wsrep_sst_auth="mariabackup:ea8`lU3jhRVPhrvMan"
```

Probably the latter one is safer than the first one.

**Comment by marcosbc** [comment] 2022-08-11 09:15
Thanks for the update @zsoltbalogh, I've created an internal task for looking into this issue. Unfortunately I can't provide any ETA for when this issue will be fixed.

**Comment by zsoltbalogh** [comment] 2022-08-15 09:53
Thank you! There's no urgency, the workaround is simple, just avoid ` in passwords. :)

**Comment by aoterolorenzo** [comment] 2022-10-20 11:14
Hi [zsoltbalogh](https://github.com/zsoltbalogh),

The issue is now solved and a fix was released (we are now [sanitizing triple quotes produced by ini-file when using special characters like "`"](https://github.com/bitnami/containers/blob/b47e079041987a975c0e67fb88f3df21cc97f31d/bitnami/mariadb-galera/10.9/debian-11/rootfs/opt/bitnami/scripts/libmariadbgalera.sh#L407)) . Thanks for your contribution!

**Closed by aoterolorenzo** 2022-10-20 11:14 UTC
Labels: on-hold, tech-issues, mariadb-galera

**Comment by zsoltbalogh** [comment] 2022-10-24 06:11
Amazing, thank you, @aoterolorenzo!
