### ISSUE TITLE
[bitnami/grafana-operator]: Current images for grafana and grafana-operator broken

### ISSUE THREAD

**Issue by js-timbirkett** [bitnami/charts#8423] opened 2021-12-15 09:20 UTC
**Which chart**:
grafana-operator 

**Describe the bug**
There are 2 bugs going on:

1. `grafana` - The bitnami Docker image currently has (multiple) issues with the init container. Any image >=8.2.5 doesn't work, 8.2.2 does work. See: 
    - https://github.com/bitnami/bitnami-docker-grafana/pull/17
    - https://github.com/bitnami/bitnami-docker-grafana/pull/18 .

2. `grafana-operator` - The operator itself has an issue with ingress creation that I think stops it from processing `GrafanaDashboard` and other CR updates (this is fixed in v4 of the operator but this chart doesn't yet support v4 due to missing CRDs). See:
    - https://github.com/grafana-operator/grafana-operator/issues/554
  

**To Reproduce**

1. Install the Helm chart

**Expected behavior**
`grafana` and `grafana-operator` function as expected.

**Comment by carrodher** [comment] 2021-12-15 09:53
Thanks for letting us know. Once we solve the issues you mention in point 1, we will be able to unblock the PR https://github.com/bitnami/charts/pull/8059 updating the chart to v4.

As we are tracking the progress in the already linked issues/PRs, I am closing this issue to avoid duplications.

**Closed by carrodher** 2021-12-15 09:53 UTC

**Comment by js-timbirkett** [comment] 2021-12-17 09:26
This was more for informational purposes for those that are searching for why the chart doesn't work, or why things stopped working after an upgrade :)

**Comment by carrodher** [comment] 2021-12-17 12:27
Yep, it's fine, the issue is still searchable although it is closed
