### ISSUE TITLE
/bitnami/etcd/data/member_id: No such file or directory

### ISSUE THREAD

**Issue by herbalizer404** [bitnami/charts#1037] opened 2019-02-01 11:28 UTC
chart: `etc-1.5.1`

app version: `3.3.11`

kube versions:
`Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}`

`Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

Chart default values with persistence enabled default ec2 storage.

```
==> The ID of the host is 0
==> Data exists. Re-joining etcd member
cat: /bitnami/etcd/data/member_id: No such file or directory
```

**Comment by javsalgar** [comment] 2019-02-04 14:18
Hi,

Do you recall having an already existing volume? Maybe it is causing issues because of that.

**Comment by javsalgar** [comment] 2019-02-04 14:20
You say that it does not work  without persistence, could you elaborate on the platform you are using to test it?

**Comment by herbalizer404** [comment] 2019-02-07 10:02
No, i installed with helm with theses values:
persistence:
  enabled: true
  storageClass: "default"
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}

The volume are created but not bound. 
Usually, my deployements work well with pvc.

**Comment by herbalizer404** [comment] 2019-02-07 11:06
For information, I made manually the correction like in this [commit](https://github.com/bitnami/charts/pull/1043/commits/8f8e7319fc939e87675feb62fe73554630fb73fc)
And it works.

**Comment by tompizmor** [comment] 2019-02-13 08:40
The PR (https://github.com/bitnami/charts/pull/1043) is already merged. I also tested this and worked fine for me.

Please open a new issue if you find another issue.

**Closed by tompizmor** 2019-02-13 08:40 UTC

**Comment by gclawes** [comment] 2021-07-15 15:22
This appears to be happening again in chart version `6.2.9` in minikube.  I verified it with persistence enabled and disabled.
`values.yaml`:
```
replicaCount: 3

persistence:
  enabled: false

auth:
  rbac:
    enabled: false
  client:
    secureTransport: true
    useAutoTLS: true
  peer:
    secureTransport: true
    useAutoTLS: true
```
```
Events:
  Type     Reason             Age   From               Message
  ----     ------             ----  ----               -------
  Normal   Scheduled          29h   default-scheduler  Successfully assigned default/election-etcd-0 to minikube
  Normal   Started            29h   kubelet            Started container etcd
  Warning  FailedPreStopHook  29h   kubelet            Exec lifecycle hook ([/opt/bitnami/scripts/etcd/prestop.sh]) for Container "etcd" in Pod "election-etcd-0_default(568c8874-05f3-4d64-bc3f-b8fbecfd2f2b)" failed - error: command '/opt/bitnami/scripts/etcd/prestop.sh' exited with 128: cat: /bitnami/etcd/data/member_id: No such file or directory
Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex
, message: "cat: /bitnami/etcd/data/member_id: No such file or directory\nError: bad member ID arg (strconv.ParseUint: parsing \"\": invalid syntax), expecting ID in Hex\n"
  Warning  Unhealthy  29h (x5 over 29h)   kubelet  Liveness probe failed:
  Normal   Killing    29h                 kubelet  Container etcd failed liveness probe, will be restarted
  Normal   Created    29h (x2 over 29h)   kubelet  Created container etcd
  Normal   Pulled     29h (x2 over 29h)   kubelet  Container image "docker.io/bitnami/etcd:3.5.0-debian-10-r0" already present on machine
  Warning  Unhealthy  29h (x19 over 29h)  kubelet  Readiness probe failed:
```

**Comment by marcosbc** [comment] 2021-07-16 12:25
Hi @gclawes, your issue seem different than the one reported here. In your case, it seems to be caused by the following YAML block:

```yaml
auth:
  rbac:
    enabled: false
  client:
    secureTransport: true
    useAutoTLS: true
  peer:
    secureTransport: true
    useAutoTLS: true
```

If you remove it, it starts working. Could you open a new issue with this new information?

**Comment by gclawes** [comment] 2021-07-16 12:28
Sure, I'll get one opened in a little bit.
