### ISSUE TITLE
[postgresql-ha] Multiple Primaries

### ISSUE THREAD

**Issue by gnomus** [bitnami/charts#2610] opened 2020-05-18 13:16 UTC
**Which chart**:
postgresql-ha 3.2.1

**Describe the bug**
Somehow both Postgres Instances End up in Primary Mode.
This Results in pgpool redirecting requests to both instances and thus the 2 Databases drift appart with different States.

Output of repmgr cluster show:

DB 0
```
WARNING: following issues were detected
  - node "redacted-postgresql-ha-postgresql-1" (ID: 1001) is running but the repmgr node record is inactive

 ID   | Name                            | Role    | Status    | Upstream | Location | Priority | Timeline | Connection string                                                                                                                                                                                 
------+---------------------------------+---------+-----------+----------+----------+----------+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | redacted-postgresql-ha-postgresql-0 | primary | * running |          | default  | 100      | 9        | user=repmgr password=redacted host=redacted-postgresql-ha-postgresql-0.redacted-postgresql-ha-postgresql-headless.redacted.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | redacted-postgresql-ha-postgresql-1 | primary | ! running |          | default  | 100      | 8        | user=repmgr password=redacted host=redacted-postgresql-ha-postgresql-1.redacted-postgresql-ha-postgresql-headless.redacted.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

command terminated with exit code 25
```
DB 1
```
WARNING: following issues were detected
  - node "redacted-postgresql-ha-postgresql-0" (ID: 1000) is registered as standby but running as primary

 ID   | Name                            | Role    | Status               | Upstream | Location | Priority | Timeline | Connection string                                                                                                                                                                                 
------+---------------------------------+---------+----------------------+----------+----------+----------+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | redacted-postgresql-ha-postgresql-0 | standby | ! running as primary |          | default  | 100      | 9        | user=repmgr password=redacted host=redacted-postgresql-ha-postgresql-0.redacted-postgresql-ha-postgresql-headless.redacted.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | redacted-postgresql-ha-postgresql-1 | primary | * running            |          | default  | 100      | 8        | user=repmgr password=redacted host=redacted-postgresql-ha-postgresql-1.redacted-postgresql-ha-postgresql-headless.redacted.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

command terminated with exit code 25
```

**To Reproduce**
This just happens randomly as it seems.

**Expected behavior**
Only One Node at a Time being the Primary Node

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"
```

**Comment by javsalgar** [comment] 2020-05-19 16:12
Hi,

Do you remember any pattern that could lead to the issue? Did it happen after one instance crashing maybe? Or did it happen just right after deploying randomly

**Comment by Roarain** [comment] 2020-05-25 13:28
also had this bug.

1. images
```
bitnami/minideb:buster
bitnami/pgpool:4.1.1-debian-10-r90
bitnami/postgres-exporter:0.8.0-debian-10-r58
bitnami/postgresql-repmgr:12.2.0-debian-10-r48
```
2. repmgr info 

postgresql-postgresql-ha-postgresql-0
```
    1000 |                  | t      | postgresql-postgresql-ha-postgresql-0 | primary | default  |      100 | user=repmgr password=TfEkkmxw1x host=postgresql-postgresql-ha-
postgresql-0.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5 | repmgr   | repmgr_slot_1000 | /opt/bitnami
/repmgr/conf/repmgr.conf
    1001 |             1000 | t      | postgresql-postgresql-ha-postgresql-1 | standby | default  |      100 | user=repmgr password=TfEkkmxw1x host=postgresql-postgresql-ha-
postgresql-1.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5 | repmgr   | repmgr_slot_1001 | /opt/bitnami
/repmgr/conf/repmgr.conf
    1002 |             1000 | t      | postgresql-postgresql-ha-postgresql-2 | standby | default  |      100 | user=repmgr password=TfEkkmxw1x host=postgresql-postgresql-ha-
postgresql-2.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5 | repmgr   | repmgr_slot_1002 | /opt/bitnami
/repmgr/conf/repmgr.conf
```

postgresql-postgresql-ha-postgresql-1
```
    1002 |             1000 | t      | postgresql-postgresql-ha-postgresql-2 | standby | default  |      100 | user=repmgr password=TfEkkmxw1x host=postgresql-postgresql-ha-
postgresql-2.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5 | repmgr   | repmgr_slot_1002 | /opt/bitnami
/repmgr/conf/repmgr.conf
    1000 |                  | f      | postgresql-postgresql-ha-postgresql-0 | primary | default  |      100 | user=repmgr password=TfEkkmxw1x host=postgresql-postgresql-ha-
postgresql-0.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5 | repmgr   | repmgr_slot_1000 | /opt/bitnami
/repmgr/conf/repmgr.conf
    1001 |                  | t      | postgresql-postgresql-ha-postgresql-1 | primary | default  |      100 | user=repmgr password=TfEkkmxw1x host=postgresql-postgresql-ha-
postgresql-1.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5 | repmgr   | repmgr_slot_1001 | /opt/bitnami
/repmgr/conf/repmgr.conf
```

postgresql-postgresql-ha-postgresql-2
```
    1000 |                  | t      | postgresql-postgresql-ha-postgresql-0 | primary | default  |      100 | user=repmgr password=TfEkkmxw1x host=postgresql-postgresql-ha-
postgresql-0.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5 | repmgr   | repmgr_slot_1000 | /opt/bitnami
/repmgr/conf/repmgr.conf
    1001 |             1000 | t      | postgresql-postgresql-ha-postgresql-1 | standby | default  |      100 | user=repmgr password=TfEkkmxw1x host=postgresql-postgresql-ha-
postgresql-1.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5 | repmgr   | repmgr_slot_1001 | /opt/bitnami
/repmgr/conf/repmgr.conf
    1002 |             1000 | t      | postgresql-postgresql-ha-postgresql-2 | standby | default  |      100 | user=repmgr password=TfEkkmxw1x host=postgresql-postgresql-ha-
postgresql-2.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5 | repmgr   | repmgr_slot_1002 | /opt/bitnami
/repmgr/conf/repmgr.conf
```

3. correct role 
postgresql-postgresql-ha-postgresql-1: primary
postgresql-postgresql-ha-postgresql-0: standby
postgresql-postgresql-ha-postgresql-2: standby

4. logs
postgresql-postgresql-ha-postgresql-1
```
DEBUG: connecting to: "user=repmgr password=TfEkkmxw1x connect_timeout=5 dbname=repmgr host=postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local port=5432 fallback_application_name=repmgr"
ERROR: connection to database failed
DETAIL:
timeout expired
INFO: standby promoted to primary after 34 second(s)
DETAIL: server "postgresql-postgresql-ha-postgresql-1" (ID: 1001) was successfully promoted to primary
[2020-05-25 08:29:27] [NOTICE] notifying node "postgresql-postgresql-ha-postgresql-2" (ID: 1002) to follow node 1001
INFO:  node 1002 received notification to follow node 1001
[2020-05-25 08:29:27] [NOTICE] monitoring cluster primary "postgresql-postgresql-ha-postgresql-1" (ID: 1001)
```
postgresql-postgresql-ha-postgresql-2
```
^[[38;5;6mrepmgr ^[[38;5;5m08:33:50.62 ^[[0m^[[38;5;2mINFO ^[[0m ==> Auto-detected primary node: 'postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local:5432'
^[[38;5;6mrepmgr ^[[38;5;5m08:33:50.63 ^[[0m^[[38;5;2mINFO ^[[0m ==> Preparing PostgreSQL configuration...
^[[38;5;6mrepmgr ^[[38;5;5m08:33:50.63 ^[[0m^[[38;5;2mINFO ^[[0m ==> Preparing repmgr configuration...
^[[38;5;6mrepmgr ^[[38;5;5m08:33:50.64 ^[[0m^[[38;5;2mINFO ^[[0m ==> Initializing Repmgr...
^[[38;5;6mrepmgr ^[[38;5;5m08:33:50.64 ^[[0m^[[38;5;2mINFO ^[[0m ==> Waiting for primary node...
^[[38;5;6mrepmgr ^[[38;5;5m08:33:50.67 ^[[0m^[[38;5;2mINFO ^[[0m ==> Cloning data from primary node...
```

postgresql-postgresql-ha-postgresql-0
```
[2020-05-25 08:28:23] [WARNING] unable to ping "user=repmgr password=TfEkkmxw1x host=postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5"
[2020-05-25 08:28:23] [DETAIL] PQping() returned "PQPING_NO_RESPONSE"
[2020-05-25 08:28:23] [WARNING] connection to node "postgresql-postgresql-ha-postgresql-0" (ID: 1000) lost
[2020-05-25 08:28:23] [DETAIL]

[2020-05-25 08:28:28] [ERROR] connection to database failed
[2020-05-25 08:28:28] [DETAIL]
timeout expired

[2020-05-25 08:28:28] [DETAIL] attempted to connect using:
  user=repmgr password=TfEkkmxw1x connect_timeout=5 dbname=repmgr host=postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local port=5432 fallback_application_name=repmgr
[2020-05-25 08:28:28] [WARNING] reconnection to node "postgresql-postgresql-ha-postgresql-0" (ID: 1000) failed
[2020-05-25 08:28:28] [WARNING] unable to connect to local node
[2020-05-25 08:30:00] [WARNING] unable to ping "user=repmgr password=TfEkkmxw1x connect_timeout=5 dbname=repmgr host=postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local port=5432 fallback_application_name=repmgr"
[2020-05-25 08:30:00] [DETAIL] PQping() returned "PQPING_NO_RESPONSE"
[2020-05-25 08:30:05] [NOTICE] node 1000 has recovered, reconnecting
[2020-05-25 08:30:05] [NOTICE] reconnected to local node after 96 seconds
[2020-05-25 08:30:07] [NOTICE] standby node "postgresql-postgresql-ha-postgresql-2" (ID: 1002) has disconnected
[2020-05-25 08:30:07] [NOTICE] standby node "postgresql-postgresql-ha-postgresql-1" (ID: 1001) has disconnected
[2020-05-25 08:35:14] [NOTICE] standby node "postgresql-postgresql-ha-postgresql-2" (ID: 1002) has reconnected after 307 seconds
```


5.  postgresql-postgresql-ha-postgresql-1 cannot connect to postgresql-postgresql-ha-postgresql-0 ,so postgresql-postgresql-ha-postgresql-1 become to primary and notify to 
 postgresql-postgresql-ha-postgresql-2. But when postgresql-postgresql-ha-postgresql-2 start,  Auto-detected primary node: 'postgresql-postgresql-ha-postgresql-0.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local:5432' again and again until split-brain.


6. bug
6.1 postgresql-postgresql-ha-postgresql-1 doesnot get (n/2 + 1) votes to be primary.
6.2 postgresql-postgresql-ha-postgresql-0 doesnot been killed after new primary is ok.
6.3 postgresql-postgresql-ha-postgresql-2  find first node postgresql-postgresql-ha-postgresql-0 as primary (ERROR), but ignore the real primary postgresql-postgresql-ha-postgresql-2. 
    Shoud connect to all nodes and recognize the real primary postgresql-postgresql-ha-postgresql-1.
6.4 pgpool doesnot recurise all nodes to find the real primary(postgresql-postgresql-ha-postgresql-1) and exception node(postgresql-postgresql-ha-postgresql-2 shoud be remove from standby.)

**Comment by javsalgar** [comment] 2020-05-26 08:12
Hi,

So, if I understand correctly (to reproduce it correctly), did you kill node 0 so node 1 becomes the primary? If so, at which point did you perform this operation?

**Comment by vahid-sohrabloo** [comment] 2020-12-14 20:20
I have this problem too.
it's random.
~~~
opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh  repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf  cluster show
 1000 | user-db-postgresql-ha-postgresql-0 | primary | ! running |          | default  | 100      | 3        | user=repmgr password=fffffff host=user-db-postgresql-ha-postgresql-0.user-db-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | user-db-postgresql-ha-postgresql-1 | primary | ! running |          | default  | 100      | 2        | user=repmgr password=fffffff host=user-db-postgresql-ha-postgresql-1.user-db-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1002 | user-db-postgresql-ha-postgresql-2 | primary | * running |          | default  | 100      | 4        | user=repmgr password=fffffff host=user-db-postgresql-ha-postgresql-2.user-db-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

WARNING: following issues were detected
  - node "user-db-postgresql-ha-postgresql-0" (ID: 1000) is running but the repmgr node record is inactive
  - node "user-db-postgresql-ha-postgresql-1" (ID: 1001) is running but the repmgr node record is inactive
```

**Comment by javsalgar** [comment] 2020-12-15 09:06
Hi,

Any pattern that could give us any clue? Did one of the pod crash or several?

**Comment by vahid-sohrabloo** [comment] 2020-12-15 13:54
I don't know when exactly. I think when two or three of the pods crashed at the same time. Or maybe I lost my connection between nodes at the same time.

**Comment by javsalgar** [comment] 2020-12-16 09:56
Hi,

I see, not sure if there's an easy way to reproduce this kind of situations. Let's see if other users come across the same issue as well.

**Comment by javsalgar** [comment] 2021-06-15 08:01
Hi,

I see some connection issues, but it's not clear to me if it has to do with the instance startup, and then everything gets back to normal. Did you see any more connection issues with other pods?

**Comment by greenday9** [comment] 2021-06-15 23:19
@javsalgar , it is possible there was some connectivity issues during the last time of startup for instance 0.  I don't have much more data from when this event happened.  Regardless, both instances remained as masters after the last instance 0 startup. I eventually deleted instance 0 and it recovered.

**Comment by javsalgar** [comment] 2021-08-30 10:14
Let me try this again, and I will let you know if I get to the issue.

**Comment by mikeoutlaw** [comment] 2021-08-30 15:31
FWIW, to add onto @aw381246's comment, we were able to reproduce the issue via the following steps:

### Install the chart
```
➜  ~ helm install pg-ha-test bitnami/postgresql-ha
```

#### Verify the cluster status
```
➜  ~ kubectl exec pg-ha-test-postgresql-ha-postgresql-0 -- /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show
postgresql-repmgr 14:03:35.44
postgresql-repmgr 14:03:35.45 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 14:03:35.45 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 14:03:35.45 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 14:03:35.45

 ID   | Name                                  | Role    | Status    | Upstream                              | Location | Priority | Timeline | Connection string
------+---------------------------------------+---------+-----------+---------------------------------------+----------+----------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | pg-ha-test-postgresql-ha-postgresql-0 | primary | * running |                                       | default  | 100      | 1        | user=repmgr password=0EPD7026uM host=pg-ha-test-postgresql-ha-postgresql-0.pg-ha-test-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | pg-ha-test-postgresql-ha-postgresql-1 | standby |   running | pg-ha-test-postgresql-ha-postgresql-0 | default  | 100      | 1        | user=repmgr password=0EPD7026uM host=pg-ha-test-postgresql-ha-postgresql-1.pg-ha-test-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
```

### Delete the primary replica
To simulate a future deployment that would need to terminate a pod, as well as simulate a real pod termination due to unforeseen issues, we delete the primary pod.
```
➜  ~ kubectl delete pod pg-ha-test-postgresql-ha-postgresql-0
pod "pg-ha-test-postgresql-ha-postgresql-0" deleted
```

##### Oddities
* In this particular test, we needed to delete the primary pod twice in order to reproduce the eventual error state being reported, but we have experienced this same issue sometimes on the first try and on other attempts it took 3 or more tries. Regardless, we could eventually reproduce the error state.
* The expectation is that the standby replica would take over as the primary. However, we often noticed that after the primary was terminated, it would restart as the primary, even if the error wasn't immediately reproduced. Or said another way, the primary always seemed to restart as the primary and only when we got into the error state would the standby report that it was a primary.

#### Verify cluster status
From the original primary replica:
```
➜  ~ kubectl exec pg-ha-test-postgresql-ha-postgresql-0 -- /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show
postgresql-repmgr 14:09:07.02
postgresql-repmgr 14:09:07.02 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 14:09:07.03 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 14:09:07.03 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 14:09:07.03

 ID   | Name                                  | Role    | Status               | Upstream | Location | Priority | Timeline | Connection string
------+---------------------------------------+---------+----------------------+----------+----------+----------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | pg-ha-test-postgresql-ha-postgresql-0 | primary | * running            |          | default  | 100      | 1        | user=repmgr password=0EPD7026uM host=pg-ha-test-postgresql-ha-postgresql-0.pg-ha-test-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | pg-ha-test-postgresql-ha-postgresql-1 | standby | ! running as primary |          | default  | 100      | 2        | user=repmgr password=0EPD7026uM host=pg-ha-test-postgresql-ha-postgresql-1.pg-ha-test-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

WARNING: following issues were detected
  - node "pg-ha-test-postgresql-ha-postgresql-1" (ID: 1001) is registered as standby but running as primary

command terminated with exit code 25 
```

From the original standby replica:
```
➜  ~ kubectl exec pg-ha-test-postgresql-ha-postgresql-1 -- /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show
postgresql-repmgr 14:09:32.42
postgresql-repmgr 14:09:32.42 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 14:09:32.42 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 14:09:32.42 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 14:09:32.43

WARNING: following issues were detected
  - node "pg-ha-test-postgresql-ha-postgresql-0" (ID: 1000) is running but the repmgr node record is inactive

 ID   | Name                                  | Role    | Status    | Upstream | Location | Priority | Timeline | Connection string
------+---------------------------------------+---------+-----------+----------+----------+----------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | pg-ha-test-postgresql-ha-postgresql-0 | primary | ! running |          | default  | 100      | 1        | user=repmgr password=0EPD7026uM host=pg-ha-test-postgresql-ha-postgresql-0.pg-ha-test-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | pg-ha-test-postgresql-ha-postgresql-1 | primary | * running |          | default  | 100      | 2        | user=repmgr password=0EPD7026uM host=pg-ha-test-postgresql-ha-postgresql-1.pg-ha-test-postgresql-ha-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5

command terminated with exit code 25
```

**NOTE** that each replica reports both as primary, albeit with slight verbiage difference from the original primary replica in the `Role` and `Status` columns that it reports for the original standby replica, and that neither replica is communicating with the other per the `Upstream` column.

**Comment by javsalgar** [comment] 2021-08-31 08:25
Thank you so much for the detailed report!

**Comment by javsalgar** [comment] 2021-09-03 09:04
Hi,

Just a note to let you know that I was able to reproduce the issue after shutting down node 0 two times. I will open a task for investigating the issue in more detail. Thank you so much for reporting.

**Comment by mikeoutlaw** [comment] 2021-09-07 14:05
Thank you @javsalgar!

**Comment by jpsn123** [comment] 2021-10-16 12:55
<html>
<body>


postgresql-repmgr 12:52:46.10 INFO ==> ** Starting PostgreSQL with Replication Manager setup **
--
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.14 INFO ==> Validating settings in REPMGR_* env vars...
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.15 INFO ==> Validating settings in POSTGRESQL_* env vars..
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.16 INFO ==> Querying all partner nodes for common upstream node...
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.29 WARN ==> Conflict of pretending primary role nodes (previously: 'postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.gitlab.svc.cluster.local:5432', now: 'postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.gitlab.svc.cluster.local:5432')
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.29 INFO ==> This node was acting as a primary before restart!
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.29 INFO ==> Can not find new primary. Starting PostgreSQL normally...
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.30 INFO ==> There are no nodes with primary role. Assuming the primary role...
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.30 INFO ==> Preparing PostgreSQL configuration...
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.31 INFO ==> postgresql.conf file not detected. Generating it...
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.45 INFO ==> Preparing repmgr configuration...
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.46 INFO ==> Initializing Repmgr...
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.47 INFO ==> Initializing PostgreSQL database...
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.48 INFO ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.48 INFO ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.51 INFO ==> Deploying PostgreSQL with persisted data...
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.54 INFO ==> Configuring replication parameters
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.58 INFO ==> Configuring fsync
Sat, Oct 16 2021 8:52:46 pm | postgresql-repmgr 12:52:46.59 INFO ==> ** PostgreSQL with Replication Manager setup finished! **


</body>
</html>

**Comment by migruiz4** [comment] 2021-11-10 07:28
Hi @vishrantgupta,

Without getting much into details, the chart `bitnami/postgresql-ha` would need an additional Statefulset, similar to how MongoDB arbiter is implemented in `bitnami/mongodb`.

And the `bitnami-docker-postgresql-repmgr` would also require changes adding the 'register the node as `witness`' capability as it is described in the [repmgr documentation](https://repmgr.org/docs/4.3/repmgrd-witness-server.html).

**Comment by pkExec** [comment] 2021-11-18 08:50
How to recover to a proper state when this issue occurs? Is there a workaround?

**Comment by migruiz4** [comment] 2021-11-22 12:53
Hi @pkExec,

I'm sorry but I don't know the exact method to recover Postgresql. As a suggestion, maybe performing a DB dump, redeploying the PostgreSQL chart, and restoring the dump would solve the problem. The following link may help you: https://www.postgresguide.com/utilities/backup-restore/

We are aware of this issue, and we are working on a solution to prevent split-brain scenarios. We are also open to any contributions that would help improve the chart.

**Comment by pkExec** [comment] 2021-11-22 13:12
@migruiz,
I was fortunate enough that the data was still consistent on both nodes, so I recovered by removing the "wrong" primary node and let kubernetes recreate it.
For other users though that might have inconsistent data between nodes, I am afraid you'll have to follow this excellent tutorial to bring consistency to your data: https://www.2qpgconf.com/schedule/recovering-from-split-brain-with-pg_waldump-and-pg_rewind/

**Comment by migruiz4** [comment] 2021-11-24 08:16
That is great! And thank you for sharing.

**Comment by akloss-cibo** [comment] 2022-01-05 12:43
Just my $0.02 here, but this should be documented in huge letters at the top of [the readme](https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha).

**Comment by migruiz4** [comment] 2022-01-11 07:36
I'm sorry for the inconveniences, but we continue working to improve the postgresql-ha chart and implement a solution to prevent split-brain from happening.

**Comment by vishrantgupta** [comment] 2022-01-11 12:24
@migruiz4 and the owners of postgres-ha chart the split-brain issue is going on for more than 2 years, I don't see a timeline when it will be fixed.
As the postgres-ha chart is not stable please update the documentation as per @akloss-cibo suggestion so that users don't end up adopting this chart in production until this issue is resolved.

cc: @rafariossaa, @javsalgar

**Comment by vishrantgupta** [comment] 2022-01-11 12:33
Here is the proposed change https://github.com/bitnami/charts/pull/8624 to update the README

**Comment by carrodher** [comment] 2022-04-11 12:32
I'm closing this issue since different PRs were merged in order to solve this issue (for example https://github.com/bitnami/charts/pull/9035).
Please, don't hesitate to reopen it if you are still facing this issue using the latest Helm chart version. If you face a different issue, please create a new ticket.

**Closed** 2022-04-11 12:32 UTC

**Comment by colega** [comment] 2023-05-06 17:41
I think this issue should be reopened, I've been fighting this for some days. I thought it would be my setup (I'm running a jsonnet version of this helm) but then I tried to run the original helm chart, and this is still reproducible.

Steps to reproduce: 
- Create an empty cluster `kind create cluster`
- Install helm chart: `helm install bitnami/postgresql-ha --generate-name`
- Wait until all pods are healthy
- Restart them: `kubectl rollout restart sts postgresql-ha-1683393697-postgresql`
- Check the state: `kubectl exec -it postgresql-ha-1683393697-postgresql-2 -- /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr -f /opt/bitnami/repmgr/conf/repmgr.conf cluster show`

Get this:
```
 ID   | Name                                  | Role    | Status               | Upstream                              | Location | Priority | Timeline | Connection string                                                                                                                                                                          
------+---------------------------------------+---------+----------------------+---------------------------------------+----------+----------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1000 | postgresql-ha-1683393697-postgresql-0 | standby |   running            | postgresql-ha-1683393697-postgresql-2 | default  | 100      | 2        | user=repmgr password=ougc6E8kaO host=postgresql-ha-1683393697-postgresql-0.postgresql-ha-1683393697-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1001 | postgresql-ha-1683393697-postgresql-1 | standby | ! running as primary |                                       | default  | 100      | 2        | user=repmgr password=ougc6E8kaO host=postgresql-ha-1683393697-postgresql-1.postgresql-ha-1683393697-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
 1002 | postgresql-ha-1683393697-postgresql-2 | primary | * running            |                                       | default  | 100      | 2        | user=repmgr password=ougc6E8kaO host=postgresql-ha-1683393697-postgresql-2.postgresql-ha-1683393697-postgresql-headless.default.svc.cluster.local dbname=repmgr port=5432 connect_timeout=5
```

**Comment by xtianus79** [comment] 2023-11-16 05:33
this is still an issue and should be reopened because the witness doesn't do anything here to help which is just odd. the delta of the primary coming back is 40 seconds after the election happened on the other nodes and it is still setting itself up as the primary and causing a split brain. A. why doesn't the witness help here B. what is the pretending mean in this log? it's saying that 1 is "pretending" do be the primary when in fact it is. this seems to be the error.

**Comment by carrodher** [comment] 2023-11-20 08:33
Could you please create a separate issue filling the template with the specific information for your use case? Thanks

**Comment by xtianus79** [comment] 2023-11-28 14:44
I think this may be related? 

https://github.com/bitnami/containers/issues/52213

**Comment by isFxh** [comment] 2024-07-24 12:12
@javsalgar Hi, I think this problem is not solved. I reproduced this problem in bitnami/postgresql-ha 16.3.0 version. I hope to reopen this issue for discussion.
