### ISSUE TITLE
[mongodb] Wrong custom ca certs in new helm chart version

### ISSUE THREAD

**Issue by epoddubny** [bitnami/charts#6697] opened 2021-06-17 21:51 UTC
**Which chart**:
mongodb-10.20.0

**Describe the bug**
After update to mongodb-10.20.0 from mongodb-10.19.0 custom CA certificates have been replaced.
In screenshots you can see that size of certificates are different in v10.19.0 and v10.20.0.

![](https://i.ibb.co/9yg4MpJ/Screenshot-2021-06-17-at-15-14-30.png)
![](https://i.ibb.co/WP3w7w4/Screenshot-2021-06-17-at-15-14-34.png)

**To Reproduce**

1. add custom certificates to values.yml

```
tls:
  enabled: true
  caCert: ${CA_CERT}
  caKey: ${CA_KEY}
  image:
    registry: docker.io
    repository: bitnami/nginx
    tag: 1.19.5-debian-10-r19
    pullPolicy: IfNotPresent
```
2. deploy mongo with helm mongodb-10.19.0

```
String helmCommand = helmVersion == 3 ? 'helm3' : 'helm'    
invoke(kubeConfigVault) {        
  sh "${helmCommand} repo add bitnami https://charts.bitnami.com/bitnami"        
  sh "${helmCommand} repo update"        
  sh """${helmCommand} upgrade -i --wait \                
              ${helmVersion == 3 ? '--create-namespace' : ''} \                
              --namespace ${namespace} ${chartVersion ? '--version=' + chartVersion : ''} \                
              --set tls.enabled=true \                
              --set tls.caCert=${cacert} \                
              --set tls.caKey=${cakey} \                
              -f ${mongoValuesPath} \                
              ${releaseName} bitnami/mongodb"""    
}
```

3. repeat step 2 for mongodb-10.20.0
4. go to mongodb-ca secret and compare certificates

**Expected behavior**

expect the same ca certs

**Version of Helm and Kubernetes**:

- Output of `helm version`:
```
version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"dirty", GoVersion:"go1.16.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"0000000000000000000000000000000000000000", GitTreeState:"archive", BuildDate:"2021-05-07T15:36:27Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

**Additional context**

**Comment by rmuehlbauer** [comment] 2021-06-18 08:06
also some issues here - I'm providing a tls.caCert and tls.caKey in my values.yaml file to let the chart create its own certs for tls encryption and I'm also using X509 for authentication - this was working perfect before upgrading to mongodb-10.20.0.
With mongodb-10.20.0 I was not able to connect to mongodb... error message was something about cert mismatch - after downgrading to 10.19.0 it was working again.

**Comment by migruiz4** [comment] 2021-06-18 09:06
Hi @epoddubny and @rmuehlbauer,

I'm sorry for the inconvenience.

I have created this PR #6700 reverting the changes in `secrets-ca.yaml`.
Please let me know if it fixes the issue.

**Comment by rmuehlbauer** [comment] 2021-06-25 07:21
For whatever reason, my helm is still offering me 10.20.2 as latest available version for the mongod chart...strange. 
As of now, 10.20.5 is the latest available version here on github...because of this issue, I was not able to test your changes so far...
'helm repo update' runs without issues but there is no newer chart version than 10.20.2 ...

**Comment by rmuehlbauer** [comment] 2021-06-25 11:36
Hi @migruiz4, for me the mongod chart is now working again as expected - thank you very much for your efforts.

**Comment by migruiz4** [comment] 2021-06-25 14:15
Hi @rmuehlbauer,

Thank you very much for your feedback!
I'm glad the issue is solved and I'm sorry for any inconvenience caused.

@epoddubny The latest version of the MongoDB chart 10.20.5 is available now, could you please let us know if it works for you?

**Comment by epoddubny** [comment] 2021-07-05 13:02
@migruiz4 Hi!
Works for me at 10.21.0

**Comment by migruiz4** [comment] 2021-07-06 06:06
Thank you for letting us know! I'm glad the issue was solved.

And thank you for quickly reporting this, it helped us fix the problem as soon as possible.

I will now close this issue, if you need any further help please let us know.

**Closed by migruiz4** 2021-07-06 06:06 UTC
