### ISSUE TITLE
[bitnami/nginx] hpa broken with 13.2.4

### ISSUE THREAD

**Issue by PatrickSpies** [bitnami/charts#12309] opened 2022-09-07 13:16 UTC
### Name and Version

bitnami/nginx 13.2.4

### What steps will reproduce the bug?

run `helm template bitnami/nginx --version 13.2.4 --set autoscaling.enabled=true` or `helm install test-nginx bitnami/nginx --version 13.2.4 --set autoscaling.enabled=true`

### Are you using any custom parameters or values?

Enable hpa with `--set autoscaling.enabled=true`

### What is the expected behavior?

Properly rendered yaml-files including hpa.yaml or proper installation

### What do you see instead?

```
Error: template: nginx/templates/hpa.yaml:2:15: executing "nginx/templates/hpa.yaml" at <include "common.capabilities.hpa.apiVersion" (dict "context" $)>: error calling include: template: nginx/charts/common/templates/_capabilities.tpl:133:32: executing "common.capabilities.hpa.apiVersion" at <include "common.capabilities.kubeVersion" .>: error calling include: template: nginx/charts/common/templates/_capabilities.tpl:7:14: executing "common.capabilities.kubeVersion" at <.Values.global>: nil pointer evaluating interface {}.global
```
or 

```
Error: INSTALLATION FAILED: template: nginx/templates/hpa.yaml:2:15: executing "nginx/templates/hpa.yaml" at <include "common.capabilities.hpa.apiVersion" (dict "context" $)>: error calling include: template: nginx/charts/common/templates/_capabilities.tpl:133:32: executing "common.capabilities.hpa.apiVersion" at <include "common.capabilities.kubeVersion" .>: error calling include: template: nginx/charts/common/templates/_capabilities.tpl:7:14: executing "common.capabilities.kubeVersion" at <.Values.global>: nil pointer evaluating interface {}.global
```

### Additional information

Running the same commands with version 13.2.3 works without any issues.

**Comment by javsalgar** [comment] 2022-09-08 07:56
Hi,

Thank you so much for spotting the issue. The problem is in the hpa.yaml file

Instead of 

```
apiVersion: {{ include "common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
```

it should be

```
apiVersion: {{ include "common.capabilities.hpa.apiVersion" . }}

```

Would you like to submit a PR with the fix?

**Comment by javsalgar** [comment] 2022-09-09 08:59
Hi,

I've gone deeper, and I think this PR should not have been merged because this helper adds extra parameters, so we would need to revert this https://github.com/bitnami/charts/pull/12282

**Closed** 2022-09-12 12:17 UTC
Labels: in-progress, nginx, tech-issues
