### ISSUE TITLE
[bitnami/concourse] Fly-CLI not present in deployment container

### ISSUE THREAD

**Issue by quickjp2** [bitnami/charts#8992] opened 2022-02-11 18:57 UTC
### Name and Version

bitnami/concourse 0.2.1

### What steps will reproduce the bug?

1. Deploy to any kubernetes cluster
2. Attempt to download cli from GUI (as described by [concourse's documentation](https://concourse-ci.org/fly.html#fly))

### What is the expected behavior?

A fly-cli binary is downloaded to my machine. (This was attempted in 3 separate environments)

### What do you see instead?

- A browser (Chrome in my case) returns `Failed - Server Problem`.
- CURL returns `failed to open tgz archive: open /fly-linux-amd64.tgz: no such file or directory`

This is returned by the concourse software when fly is not able to be found in the `fly-assests` folder within the concourse directory on the web node.

### Additional information

The fly-cli is present in the release used by BOSH (the original method of deploying concourse). When untar-ed, that release has 3 flavors of the CLI stored in a folder called `fly-assets`, and the concourse code base expects those binaries to be there.

After investigating the differences between the BOSH deployment, the OSS concourse container image, and Bitnami's concourse container image, I found that the Bitnami's container does not pull from the same concourse release. Instead, it pulls from a [Bitnami internal repository](https://github.com/bitnami/bitnami-docker-concourse/blob/master/7/debian-10/Dockerfile#L11) that has had the `fly-assets` folder removed.

For concourse to work as described, then (in the case of using Bitnami's concourse image) the `fly-assests` folder needs to be present at `/opt/bitnami/concourse` in the web container.

I propose one of the following two options:
1. Do not remove the `fly-assests` folder from Bitnami's internal repository so the concourse container has them at the correct directory.
2. If there is a valid security or kubernetes best practice concern, then documentation needs to be included on the best practices method of adding the `fly-assests` folder into the web node.

**Comment by alemorcuq** [comment] 2022-02-14 10:56
Thanks for reporting this, @quickjp2. We are providing the fly CLI in the image's PATH so you can use it from inside the container, but I agree with you that we should also allow users to download it as intended by Concourse.

I have created an internal bug to address it. Thanks again for reporting it.

**Comment by quickjp2** [comment] 2022-02-14 17:27
@alemorcuq Thanks for looking into this! Could you provide the exact path the CLI is in? I was unable to find it anywhere in the container.

**Comment by fmulero** [comment] 2022-02-15 09:46
Hi @quickjp2.

As you mentioned the folder `fly-assets` was being removed. The propose behind, was reduce the size of the image, but it is not make sense when removing that folder affects to the expected behavior of the solution. 

During today a new image version will be released and charts will be updated to point to this new version.

**Closed** 2022-02-16 18:37 UTC

**Comment by quickjp2** [comment] 2022-02-16 21:35
Thank you @alemorcuq and @fmulero! Wanted to confirm that we tested the new image and we are seeing the correct behavior now. Thank you for the quick response and fix!
