### ISSUE TITLE
wordpress chart blog name isn't being set

### ISSUE THREAD

**Issue by michelleN** [bitnami/charts#102] opened 2016-08-31 18:28 UTC
I set the wordpressBlogName to "Michelle's Blog". It gets set in the manifest after the values have been computed, however the actual blog site is still titled "Users's Blog" and I was expecting it to to be "Michelle's Blog"

**Comment by chipironcin** [comment] 2016-09-01 09:47
Check the fix at https://github.com/bitnami/bitnami-docker-wordpres/pull/25
Once that PR is merged, this chart should work as expected :)

**Comment by chipironcin** [comment] 2016-09-01 23:05
Both PRs have been merged, can you confirm the issue is gone @michelleN ?

**Comment by sameersbn** [comment] 2016-09-02 15:10
@chipironcin I can confirm that this issue has been resolved  
![ss](https://cloud.githubusercontent.com/assets/410147/18208550/82c54d32-714d-11e6-9d46-b41b9e087ddc.png)

**Comment by sameersbn** [comment] 2016-09-14 13:27
Closing... Please reopen if problem persists. Thank you.

**Closed by sameersbn** 2016-09-14 13:27 UTC
