### ISSUE TITLE
[BUG mariadb chart] mariadb docker image failed to init custom sql files "files/docker-entrypoint-initdb.d"

### ISSUE THREAD

**Issue by inix** [bitnami/charts#888] opened 2018-10-23 07:38 UTC
### 1.environment and package version

Host OS and version: `CentOS CentOS Linux release 7.3.1611 (Core)`
Docker version (docker version): `17.06.2-ce`
kubernetes version:` v1.10.0`
Output of docker info:
[docker info.txt](https://github.com/bitnami/charts/files/2504976/docker.info.txt)

Version of this container (echo $BITNAMI_IMAGE_VERSION inside the container)
```
mariadb docker v10.1.36
helm chart v5.2.1
```
The command you used to run the container, and any relevant output you saw (masking any sensitive information)
ERROR:
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)`

### 2. Bug

Bitnami mariadb docker image failed to init custom sql script and caused container failed to start.
2.1 ERROR info:
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2)`

2.2 kubernetes dashboard error info:
```
pod has unbound PersistentVolumeClaims
Back-off restarting failed container
```

2.3 pod info:
[k8s desc.log](https://github.com/bitnami/charts/files/2504901/k8s.desc.log)

2.3 pod logs:
kubectl logs:
```
INFO  ==> ** Starting MariaDB setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
INFO  ==> Initializing mariadb database...
INFO  ==> Persisted data detected. Restoring...
INFO  ==> Loading user files from /docker-entrypoint-initdb.d ...
INFO  ==> Executing /docker-entrypoint-initdb.d/apolloconfigdb.sql
total 8
drwxrwxr-x 2 root root 4096 Oct 23 06:56 .
drwxr-xr-x 1 root root 4096 Oct 23 06:56 ..
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mariadb/tmp/mysql.sock' (2 "No such file or directory")
INFO  ==> Stopping mariadb...
```
**Tips:** 
Mariadb do not print errors "ERROR 2002 (HY000): Can't..." messages by default,you need to hack the "libmysql.sh" initializing script,and build your custom mariadb docker image from https://github.com/bitnami/bitnami-docker-mariadb.

For example,you can disable error redirect by deleting `>/dev/null 2>&1`.
Before:
```
...
mysql_execute() {
    local db="${1:-}"
    local user="${2:-root}"
    local pass="${3:-}"

    info "db=$db;user=$user;pass=$pass"

    if [ -z  "$pass" ]; then
        cat - | "$DB_BINDIR/mysql" --defaults-file="$DB_CONFDIR/my.cnf" -N -u "$user" "$db" >/dev/null 2>&1
    else
        cat - | "$DB_BINDIR/mysql" --defaults-file="$DB_CONFDIR/my.cnf" -N -u "$user" -p"$pass" "$db" >/dev/null 2>&1
    fi
}
...
```

after:
```
...
mysql_execute() {
    local db="${1:-}"
    local user="${2:-root}"
    local pass="${3:-}"

    info "db=$db;user=$user;pass=$pass"

    if [ -z  "$pass" ]; then
        cat - | "$DB_BINDIR/mysql" --defaults-file="$DB_CONFDIR/my.cnf" -N -u "$user" "$db"
    else
        cat - | "$DB_BINDIR/mysql" --defaults-file="$DB_CONFDIR/my.cnf" -N -u "$user" -p"$pass" "$db"
    fi
}
...
```

### 3. Root cause
There is no file "/opt/bitnami/mariadb/tmp/mysql.sock" when execute custom init sql files.

### 4.repeat steps

- helm fetch stable/mariadb
- tar zxvf mariadb-5.2.1.tgz
- place custom init sql files into files/docker-entrypoint-initdb.d
- create kubernetes PV
- helm install ./mariadb

example custom sql files:
[apolloportaldb sql.zip](https://github.com/bitnami/charts/files/2504973/apolloportaldb.sql.zip)

**Comment by juan131** [comment] 2018-10-23 08:36
Hi @inix 

I was unable to reproduce your issue using the same SQL files you shared. Here you have the steps I followed:

```
$ helm fetch stable/mariadb
$ tar zxvf mariadb-5.2.1.tgz
$ cp apolloportaldb.sql mariadb/files/docker-entrypoint-initdb.d/
$ helm install --name mariadb ./mariadb
```

> Note: I didn't created any PV since I have a Persistent Volume provisioner on my cluster.

Check Master is running:

```
$ kubectl logs -f mariadb-mariadb-master-0

Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MariaDB setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
INFO  ==> Initializing mariadb database...
INFO  ==> Installing database...
INFO  ==> Starting mariadb in background...
INFO  ==> Starting replication...
INFO  ==> Configure root user credentials...
INFO  ==> removing the unknown user
INFO  ==> Creating database my_database...
INFO  ==> Configuration replication mode...
INFO  ==> Configure replication user credentials...
INFO  ==> Flushing privileges...
INFO  ==> Loading user files from /docker-entrypoint-initdb.d ...
INFO  ==> Executing /docker-entrypoint-initdb.d/apolloportaldb.sql
INFO  ==> Stopping mariadb...
INFO  ==> Stopping mariadb...
INFO  ==> ** MariaDB setup finished! **

INFO  ==> ** Starting MariaDB **
2018-10-23  8:30:42 139832789146560 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.36-MariaDB) starting as process 1 ...
```

Check Slave is running:

```
$ kubectl logs -f mariadb-mariadb-slave-0

Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MariaDB setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
INFO  ==> Initializing mariadb database...
INFO  ==> Installing database...
INFO  ==> Starting mariadb in background...
INFO  ==> Configuration replication mode...
INFO  ==> Checking if replication master is ready to accept connection ...
INFO  ==> Replication master ready!
INFO  ==> Setting the master configuration...
INFO  ==> Flushing privileges...
INFO  ==> Stopping mariadb...
INFO  ==> ** MariaDB setup finished! **

INFO  ==> ** Starting MariaDB **
2018-10-23  8:31:06 140353665633216 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.36-MariaDB) starting as process 1 ...
```

Use a client to check the database:

```
$ kubectl run mariadb-mariadb-client --rm --tty -i --image  docker.io/bitnami/mariadb:10.1.36 --namespace default --command -- bash
# mysql -h mariadb-mariadb.default.svc.cluster.local -uroot -p my_database
MariaDB [my_database]> show databases;
+--------------------+
| Database           |
+--------------------+
| ApolloPortalDB     |
| information_schema |
| my_database        |
| mysql              |
| performance_schema |
| test               |
+--------------------+
6 rows in set (0.00 sec)

MariaDB [my_database]> use ApolloPortalDB;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [ApolloPortalDB]> show tables;
+--------------------------+
| Tables_in_ApolloPortalDB |
+--------------------------+
| App                      |
| AppNamespace             |
| Authorities              |
| Consumer                 |
| ConsumerAudit            |
| ConsumerRole             |
| ConsumerToken            |
| Favorite                 |
| Permission               |
| Role                     |
| RolePermission           |
| ServerConfig             |
| UserRole                 |
| Users                    |
+--------------------------+
14 rows in set (0.00 sec)
```

**Comment by inix** [comment] 2018-10-23 08:48
@juan131 
Hi,I installed mariadb by disabling replication:
`helm install ./mariadb --set replication.enabled=false`

You can try it.
Thanks

**Comment by juan131** [comment] 2018-10-23 08:52
It also worked when disabling replication:

```
$ helm install --name mariadb ./mariadb --set replication.enabled=false
$ kubectl logs -f mariadb-mariadb-0

Welcome to the Bitnami mariadb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting MariaDB setup **
INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
INFO  ==> Initializing mariadb database...
INFO  ==> Installing database...
INFO  ==> Starting mariadb in background...
INFO  ==> Configure root user credentials...
INFO  ==> removing the unknown user
INFO  ==> Creating database my_database...
INFO  ==> Flushing privileges...
INFO  ==> Loading user files from /docker-entrypoint-initdb.d ...
INFO  ==> Executing /docker-entrypoint-initdb.d/apolloportaldb.sql
INFO  ==> Stopping mariadb...
INFO  ==> Stopping mariadb...
INFO  ==> ** MariaDB setup finished! **

INFO  ==> ** Starting MariaDB **
2018-10-23  8:49:55 140081945848768 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.36-MariaDB) starting as process 1
...

$ kubectl run mariadb-mariadb-client --rm --tty -i --image  docker.io/bitnami/mariadb:10.1.36 --namespace default --command -- bash
#  mysql -h mariadb-mariadb.default.svc.cluster.local -uroot -p my_database
MariaDB [my_database]> show databases;
+--------------------+
| Database           |
+--------------------+
| ApolloPortalDB     |
| information_schema |
| my_database        |
| mysql              |
| performance_schema |
| test               |
+--------------------+
6 rows in set (0.00 sec)

MariaDB [my_database]> use ApolloPortalDB;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [ApolloPortalDB]> show tables;
+--------------------------+
| Tables_in_ApolloPortalDB |
+--------------------------+
| App                      |
| AppNamespace             |
| Authorities              |
| Consumer                 |
| ConsumerAudit            |
| ConsumerRole             |
| ConsumerToken            |
| Favorite                 |
| Permission               |
| Role                     |
| RolePermission           |
| ServerConfig             |
| UserRole                 |
| Users                    |
+--------------------------+
14 rows in set (0.00 sec)

```

**Comment by inix** [comment] 2018-10-23 09:38
@juan131 
Ok,I try again.

**Comment by inix** [comment] 2018-10-23 10:14
@juan131 
Hi,this is not a bug. I have found root cause of my case,old persistent volume data on the host path,and new db can not start due to permissions.

**Comment by juan131** [comment] 2018-10-24 07:39
hi @inix 

That's great!! I'm glad you were able to identify the issue! 

I proceed to close this issue, please feel free to reopen it if you continue facing issues.

**Closed by juan131** 2018-10-24 07:39 UTC
