### ISSUE TITLE
Documentation for importing the postrgresql full database in postgresql-ha helm chart.

### ISSUE THREAD

**Issue by parvaths1118** [bitnami/charts#3210] opened 2020-07-24 06:33 UTC
**Which chart**:

postgresql-ha-3.4.9

**Is your feature request related to a problem? Please describe.**

we are having postgresql standalone container running in our  docker environment ,we are migrating the postgresql to HA in kubernetes environment but we have almost 500GB postgresql full backup that needs to be imported in to postgresql-HA environment once the postgresql-ha helm chart is deployed .

I was going through the bitnami documentation but unfortunately i could not find any relevant documentation for importing the backup in postgresql-ha deployment.  Please can you help us pointing to if there is any documentation available to perform .

**Describe the solution you'd like**

Request to have a documetation for postgresql-ha backup and restore ,in today's world companies are migrating to kubernetes solution but looking for solutions how the migration can happen  easily. Please help if there is any documentation that could help migrating the postgresql data from docker conatiner postgres environment to kubernetes postgres deployed using helm charts.

**Describe alternatives you've considered**
Yet to explore on migration of postgres from docker to kubernetes environment.

**Additional context**

**Comment by juan131** [comment] 2020-07-24 07:27
Hi @parvaths1118 

Thanks for opening this issue! We're aware that we need to improve the docs about how to manage backups. Closing this issue as a duplicate of https://github.com/bitnami/charts/issues/3071, please check the answers we provided there.

**Closed by juan131** 2020-07-24 07:27 UTC
