### ISSUE TITLE
[bitnami/elasticsearch] Install es on k8s cluster

### ISSUE THREAD

**Issue by zhaofang1995** [bitnami/charts#5185] opened 2021-01-22 07:11 UTC
**Which chart**:
elasticsearch 7.10.2

**Describe the bug**
[WARNNING]master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster,after installing latest version with comand "helm install elasticsearch bitnami/elasticsearch"

**LOG**
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2021-01-22T07:08:20,722][INFO ][o.e.n.Node               ] [elasticsearch-elasticsearch-master-1] version[7.10.2], pid[1], build[oss/tar/747e1cc71def077253878a59143c1f785afa92b9/2021-01-13T00:42:12.435326Z], OS[Linux/4.15.0-91-generic/amd64], JVM[BellSoft/OpenJDK 64-Bit Server VM/11.0.9.1/11.0.9.1+1-LTS]
[2021-01-22T07:08:20,725][INFO ][o.e.n.Node               ] [elasticsearch-elasticsearch-master-1] JVM home [/opt/bitnami/java], using bundled JDK [false]
[2021-01-22T07:08:20,726][INFO ][o.e.n.Node               ] [elasticsearch-elasticsearch-master-1] JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -Xms128m, -Xmx128m, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=/tmp/elasticsearch-13567545046865998783, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -XX:MaxDirectMemorySize=67108864, -Des.path.home=/opt/bitnami/elasticsearch, -Des.path.conf=/opt/bitnami/elasticsearch/config, -Des.distribution.flavor=oss, -Des.distribution.type=tar, -Des.bundled_jdk=true]
[2021-01-22T07:08:21,793][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [aggs-matrix-stats]
[2021-01-22T07:08:21,794][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [analysis-common]
[2021-01-22T07:08:21,794][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [geo]
[2021-01-22T07:08:21,794][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [ingest-common]
[2021-01-22T07:08:21,795][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [ingest-geoip]
[2021-01-22T07:08:21,795][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [ingest-user-agent]
[2021-01-22T07:08:21,795][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [kibana]
[2021-01-22T07:08:21,795][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [lang-expression]
[2021-01-22T07:08:21,795][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [lang-mustache]
[2021-01-22T07:08:21,796][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [lang-painless]
[2021-01-22T07:08:21,796][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [mapper-extras]
[2021-01-22T07:08:21,796][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [parent-join]
[2021-01-22T07:08:21,796][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [percolator]
[2021-01-22T07:08:21,797][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [rank-eval]
[2021-01-22T07:08:21,797][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [reindex]
[2021-01-22T07:08:21,797][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [repository-url]
[2021-01-22T07:08:21,797][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded module [transport-netty4]
[2021-01-22T07:08:21,798][INFO ][o.e.p.PluginsService     ] [elasticsearch-elasticsearch-master-1] loaded plugin [repository-s3]
[2021-01-22T07:08:21,832][INFO ][o.e.e.NodeEnvironment    ] [elasticsearch-elasticsearch-master-1] using [1] data paths, mounts [[/bitnami/elasticsearch/data (/dev/rbd0)]], net usable_space [7.7gb], net total_space [7.8gb], types [ext4]
[2021-01-22T07:08:21,832][INFO ][o.e.e.NodeEnvironment    ] [elasticsearch-elasticsearch-master-1] heap size [123.7mb], compressed ordinary object pointers [true]
[2021-01-22T07:08:21,923][INFO ][o.e.n.Node               ] [elasticsearch-elasticsearch-master-1] node name [elasticsearch-elasticsearch-master-1], node ID [ae1x2JyDQO2vY1SS1fcZMQ], cluster name [elastic], roles [master, remote_cluster_client]
[2021-01-22T07:08:25,117][INFO ][o.e.t.NettyAllocator     ] [elasticsearch-elasticsearch-master-1] creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=1mb, factors={es.unsafe.use_unpooled_allocator=null, g1gc_enabled=false, g1gc_region_size=0b, heap_size=123.7mb}]
[2021-01-22T07:08:25,188][INFO ][o.e.d.DiscoveryModule    ] [elasticsearch-elasticsearch-master-1] using discovery type [zen] and seed hosts providers [settings]
[2021-01-22T07:08:25,453][WARN ][o.e.g.DanglingIndicesState] [elasticsearch-elasticsearch-master-1] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
[2021-01-22T07:08:25,641][INFO ][o.e.n.Node               ] [elasticsearch-elasticsearch-master-1] initialized
[2021-01-22T07:08:25,641][INFO ][o.e.n.Node               ] [elasticsearch-elasticsearch-master-1] starting ...
[2021-01-22T07:08:25,765][INFO ][o.e.t.TransportService   ] [elasticsearch-elasticsearch-master-1] publish_address {10.42.3.48:9300}, bound_addresses {0.0.0.0:9300}
[2021-01-22T07:08:27,978][WARN ][o.e.t.TcpTransport       ] [elasticsearch-elasticsearch-master-1] exception caught on transport layer [Netty4TcpChannel{localAddress=/10.42.3.48:9300, remoteAddress=/10.42.3.45:54810}], closing connection
java.lang.IllegalStateException: transport not ready yet to handle incoming requests
	at org.elasticsearch.transport.TransportService.onRequestReceived(TransportService.java:952) ~[elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:164) ~[elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:107) ~[elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:89) ~[elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:700) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82) [elasticsearch-7.10.2.jar:7.10.2]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) [transport-netty4-client-7.10.2.jar:7.10.2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) [netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by juan131** [comment] 2021-01-22 09:52
Hi @zhaofang1995 

Could you please share the command you used to install the ES chart? If you're using a custom **values.yaml**, could you also share its content? Thanks in advance.

**Comment by zhaofang1995** [comment] 2021-01-22 10:16
Everything is default . Just use this command

**Comment by zhaofang1995** [comment] 2021-01-22 10:27
> Hi @zhaofang1995
> 
> Could you please share the command you used to install the ES chart? If you're using a custom **values.yaml**, could you also share its content? Thanks in advance.

Everything is default. The only action is “helm install ealsticsearch bitnami/elasticsearch ”

**Comment by juan131** [comment] 2021-01-25 09:10
Hi @zhaofang1995 

I am unable to reproduce the issue in GKE nor locally using Minikube.

What kind of Kubernetes cluster are you using? Is it a cluster in the cloud, on-premise, local cluster?
It looks like an issue with the networking layer, see these lines:

```
[2021-01-22T07:08:27,978][WARN ][o.e.t.TcpTransport       ] [elasticsearch-elasticsearch-master-1] exception caught on transport layer [Netty4TcpChannel{localAddress=/10.42.3.48:9300, remoteAddress=/10.42.3.45:54810}], closing connection
java.lang.IllegalStateException: transport not ready yet to handle incoming requests
```

Do you have other solutions running in that cluster that setup a cluster?

**Comment by zhaofang1995** [comment] 2021-01-25 09:22
Hi @juan131 
Thank you for you reply.  My cluster is in private cloud.  At first I thought so too， However， my other applications on cluster are ok, so I think my cluster has no problem. 
In addition, I fixed this issue via using other helm chart. so I think the problem is from the latest version chart.

**Comment by juan131** [comment] 2021-01-26 08:32
Hi @zhaofang1995 

Do these other applications implement mechanisms to auto discover other peers? For instance this chart sets an environment variable on the ElasticSearch container with the list of hostnames they can use to discover other peers. Here you can find an example when installing the chart using `helm install elasticsearch bitnami/elasticsearch`:

```yaml
- name: ELASTICSEARCH_CLUSTER_HOSTS
  value: elasticsearch-elasticsearch-master.default.svc.cluster.local,elasticsearch-elasticsearch-coordinating-only.default.svc.cluster.local,elasticsearch-elasticsearch-data.default.svc.cluster.local
```

Theses hostnames correspond to each of the services created to expose the different kind of Elasticsearch nodes.

If your cluster has any kind of limitation in the DNS (so these hostnames aren't resolvable) or there are any special network policies in place that limits the communications between pods, then it's highly likely that's reason why you're facing the issue.

**Comment by zhaofang1995** [comment] 2021-01-27 03:34
Hi @juan131 

Yes. According to the k8s mechanisms, pod can access target pod via corresponding service name. I just checked my DNS, found that I have 4 DNS servers. Because k8s only support 3, maybe which is a reason.

Anyway, I only need a healthy es cluster, my goal is achieved now. Thank you for your response.

**Comment by juan131** [comment] 2021-01-27 08:43
You're welcome @zhaofang1995 
I proceed to close the issue, but please don't hesitate to come back us to us if you require further help.

**Closed by juan131** 2021-01-27 08:43 UTC
