### ISSUE TITLE
wordpress chart pod logs

### ISSUE THREAD

**Issue by michelleN** [bitnami/charts#103] opened 2016-08-31 22:17 UTC
The pod logs give me awesome information. These installation parameters however are different from the ones that I set. Should they match my input in values.yaml?
```
wordpre INFO  ########################################################################
wordpre INFO   Installation parameters for wordpress:
wordpre INFO     First Name: FirstName
wordpre INFO     Last Name: LastName
wordpre INFO     Username: user
wordpre INFO     Password: **********
wordpre INFO     Email: michelle@deis.com
wordpre INFO     Blog Name: User's Blog!
wordpre INFO   (Passwords are not shown for security reasons)
wordpre INFO  ########################################################################
```

**Comment by prydonius** [comment] 2016-09-01 00:50
Hmm... they should. What was your values.yaml, @michelleN?

**Comment by prydonius** [comment] 2016-09-01 01:04
Ah, looks like this is an issue in the Wordpress container, it's not actually using some of those ENV vars yet: https://github.com/bitnami/bitnami-docker-wordpress#environment-variables.

I created https://github.com/bitnami/bitnami-docker-wordpress/issues/24 to address the issue.

**Comment by chipironcin** [comment] 2016-09-01 09:47
Check the fix at https://github.com/bitnami/bitnami-docker-wordpres/pull/25
Once that PR is merged, this chart should work as expected :)

**Comment by chipironcin** [comment] 2016-09-01 23:06
Both PRs have been merged, can you confirm the issue is gone @michelleN ?

**Comment by sameersbn** [comment] 2016-09-14 13:28
Closing.. Please re-open if issue persists.

**Closed by sameersbn** 2016-09-14 13:28 UTC
