### ISSUE TITLE
MongoDB cluster does not have a master.

### ISSUE THREAD

**Issue by denissabramovs** [bitnami/charts#3579] opened 2020-09-01 09:19 UTC
```
beck@beck:/var/local/acp$ for i in 0 1 2; do kubectl exec -n default acp-mongodb-release-$i -- sh -c 'mongo --eval="printjson(rs.isMaster())"'; done
MongoDB shell version v4.4.0
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("34fb6222-279a-4bed-995f-ccf9a0e41f39") }
MongoDB server version: 4.4.0
{
	"topologyVersion" : {
		"processId" : ObjectId("5f4e10f7b08138c6bb5fbf2f"),
		"counter" : NumberLong(0)
	},
	"ismaster" : false,
	"secondary" : false,
	"info" : "Does not have a valid replica set config",
	"isreplicaset" : true,
	"maxBsonObjectSize" : 16777216,
	"maxMessageSizeBytes" : 48000000,
	"maxWriteBatchSize" : 100000,
	"localTime" : ISODate("2020-09-01T09:17:24.828Z"),
	"logicalSessionTimeoutMinutes" : 30,
	"connectionId" : 133,
	"minWireVersion" : 0,
	"maxWireVersion" : 9,
	"readOnly" : false,
	"ok" : 1
}
MongoDB shell version v4.4.0
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("8dff3d4f-d460-4b19-b103-9e732bde1a8e") }
MongoDB server version: 4.4.0
{
	"topologyVersion" : {
		"processId" : ObjectId("5f4e111a924f1689cf6771c7"),
		"counter" : NumberLong(0)
	},
	"ismaster" : false,
	"secondary" : false,
	"info" : "Does not have a valid replica set config",
	"isreplicaset" : true,
	"maxBsonObjectSize" : 16777216,
	"maxMessageSizeBytes" : 48000000,
	"maxWriteBatchSize" : 100000,
	"localTime" : ISODate("2020-09-01T09:17:25.748Z"),
	"logicalSessionTimeoutMinutes" : 30,
	"connectionId" : 14,
	"minWireVersion" : 0,
	"maxWireVersion" : 9,
	"readOnly" : false,
	"ok" : 1
}
MongoDB shell version v4.4.0
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("e9fb3729-e53b-42b0-aff3-649161f9bbe1") }
MongoDB server version: 4.4.0
{
	"topologyVersion" : {
		"processId" : ObjectId("5f4e1145ed4dddb377dd0969"),
		"counter" : NumberLong(0)
	},
	"ismaster" : false,
	"secondary" : false,
	"info" : "Does not have a valid replica set config",
	"isreplicaset" : true,
	"maxBsonObjectSize" : 16777216,
	"maxMessageSizeBytes" : 48000000,
	"maxWriteBatchSize" : 100000,
	"localTime" : ISODate("2020-09-01T09:17:26.826Z"),
	"logicalSessionTimeoutMinutes" : 30,
	"connectionId" : 11,
	"minWireVersion" : 0,
	"maxWireVersion" : 9,
	"readOnly" : false,
	"ok" : 1
}
```

**Comment by denissabramovs** [comment] 2020-09-01 09:19
In the logs i have this:
```
Advertised Hostname: 163.21.71.33
Pod name doesn't match initial primary pod name, configuring node as a secondary
```

**Comment by miguelaeh** [comment] 2020-09-02 07:36
Hi @denissabramovs ,
Could you share the parameters you used to install the Chart?

**Comment by denissabramovs** [comment] 2020-09-02 10:56
sure hold on
```
helm install acp-mongodb-release --set 'rbac.create=true,persistence.enabled=true,architecture=replicaset,replicaCount=3,externalAccess.autoDiscovery.enabled=true,externalAccess.enabled=true,externalAccess.service.type=NodePort,externalAccess.service.nodePorts[0]='32001',externalAccess.service.nodePorts[1]='32002',externalAccess.service.nodePorts[2]='32003',auth.rootPassword=somePassword1,auth.username=admin,auth.password=somePassword2,auth.database=admin' bitnami/mongodb
```

**Comment by miguelaeh** [comment] 2020-09-03 08:05
Hi @denissabramovs ,
Thank you very much for reporting this issue. I have been able to reproduce it. It seems this does not happen with the default parameters. I will open a task on our side to investigate the issue. 
Regards.

**Comment by denissabramovs** [comment] 2020-09-03 08:08
Thank you for your work. We will be waiting for updates.

**Comment by YannisMarios** [comment] 2020-09-06 11:15
This issue happens if you use:

```
fullnameOverride: mongodb

```

in your values

I commented it out:

![image](https://user-images.githubusercontent.com/11289298/92324521-36c03100-f04b-11ea-8de0-8f290a0f0fc6.png)

and now replicaset works:

**Comment by denissabramovs** [comment] 2020-09-06 11:21
Hmm, is there a way to override this value/param from chart install command?

**Comment by YannisMarios** [comment] 2020-09-06 16:30
@denissabramovs That's the problem. If you override it the replicaset will be created with no master.

I am not sure though if this is always the case. It seems that sometimes this works for me and sometimes even if I don't override fullname by not using "fullnameOverride" still the replicaset gets created without a master.

This needs further investigation

**Comment by denissabramovs** [comment] 2020-09-06 16:40
This is strange, how bitnami managed to launch it in replicaset mode? This chart was tested, right?

**Comment by YannisMarios** [comment] 2020-09-06 19:04
if you look at the default values.yaml

**Comment by YannisMarios** [comment] 2020-09-06 19:08
If you look at the default values.yaml

![image](https://user-images.githubusercontent.com/11289298/92333299-06998200-f08d-11ea-8b0f-71a5a65f89f5.png)

I don't know if the chart has been tested with replicaset architecture.

**Comment by miguelaeh** [comment] 2020-09-07 08:43
Hi guys,
I can confirm we are using the replicaset mode when testing the helm chart.
I guess it should be an issue with a certain combination of parameters that we have missed. It is really difficult to test all the possible combinations for the parameters so we test the basic and more used ones.
Sorry for the inconvenience, and thank you for your investigations!

**Comment by denissabramovs** [comment] 2020-09-07 08:57
Possibly i could find out the problematic parameters by adding one by one.

**Comment by YannisMarios** [comment] 2020-09-07 18:50
@miguelaeh The problem seems to be with the fullnameOverride. Have you tried it?

I have added bitname/mongodb chart as a subchart dependency in my parent Chart.yml

![image](https://user-images.githubusercontent.com/11289298/92412128-6195ac80-f153-11ea-9bc8-bc487081c95f.png)

When I don't use "fullnameOverride" in my parents values or use it with the chart's folder name (fullnameOverride: mongodb) then the replicaser gets created with master and slave ok.

![image](https://user-images.githubusercontent.com/11289298/92412234-cea94200-f153-11ea-9ddc-a915c30c4f99.png)


Does this help?

Thank you

**Comment by miguelaeh** [comment] 2020-09-08 08:05
Hi again guys!
I am not sure about the `fullnameOverride`, installing with:
```
helm install mongodb --set 'rbac.create=true,persistence.enabled=true,architecture=replicaset,replicaCount=3,externalAccess.autoDiscovery.enabled=true,externalAccess.enabled=true,externalAccess.service.type=NodePort,externalAccess.service.nodePorts[0]='32001',externalAccess.service.nodePorts[1]='32002',externalAccess.service.nodePorts[2]='32003',auth.rootPassword=somePassword1,auth.username=admin,auth.password=somePassword2,auth.database=admin' bitnami/mongodb
```

The fullnameOverride is not set and the same issue appears.

**Comment by denissabramovs** [comment] 2020-09-08 16:37
I mean, the working example of replicaset you use in tests.
Full helm install command which is working in your tests.

**Comment by miguelaeh** [comment] 2020-09-09 08:20
Hi @denissabramovs ,
Sorry for the confusion, we are testing the replication in the pipeline using docker-compose but not for the Helm Chart.
I have been doing more tests with the first command you provided and I think the issue only appears when using NodePorts services.
Checking the templates deeper it seems that the auto-discovery pod for external access is being created only when using LoadBalancer services.
I think there are two options to work around this while we work on fix it.
1. Do no use NodePort services, use LoadBalancer instead.
2. (If the external access is not needed) use ClusterIP services.


As you can see here the auto-discovery pod is only created for LoadBalancer services:
```
 {{- if and .Values.externalAccess.enabled .Values.externalAccess.autoDiscovery.enabled (eq .Values.externalAccess.service.type "LoadBalancer") }}
100         - name: auto-discovery
101           image: {{ include "mongodb.externalAccess.autoDiscovery.image" . }}
102           imagePullPolicy: {{ .Values.externalAccess.autoDiscovery.image.pullPolicy | quote }}
103           command:
104             - /scripts/auto-discovery.sh
105           env:
106             - name: MY_POD_NAME
107               valueFrom:
108                 fieldRef:
109                   fieldPath: metadata.name
110             - name: SHARED_FILE
111               value: "/shared/info.txt"
112           {{- if .Values.externalAccess.autoDiscovery.resources }}
113           resources: {{- toYaml .Values.externalAccess.autoDiscovery.resources | nindent 12 }}
114           {{- end }}
115           volumeMounts:
116             - name: shared
117               mountPath: /shared
118             - name: scripts
119               mountPath: /scripts/auto-discovery.sh
120               subPath: auto-discovery.sh
121         {{- end }}
```

**Comment by denissabramovs** [comment] 2020-09-09 08:38
Auto-discovery image is that image which is requesting external ip mirror?

**Comment by miguelaeh** [comment] 2020-09-10 08:08
Hi @denissabramovs ,
Sorry, I am not sure I understand the last question.
To expose external IPs you can use LoadBalancer services.

**Comment by denissabramovs** [comment] 2020-09-10 08:41
No no, I meant something other than LoadBalander

**Comment by denissabramovs** [comment] 2020-09-10 08:44
`The pod will try to get the external ip of the node using curl -s https://ipinfo.io/ip unless externalAccess.service.domain is provided.`

From you README

**Comment by milkeryildirim** [comment] 2020-09-25 22:46
Same issue as above described..
I tested the both option (NodePort & LoadBalander), only LoadBalancer mode works.
Is an appointment scheduled for providing fix?

**Comment by miguelaeh** [comment] 2020-09-28 10:57
Hi,
I am afraid we don't have news about this. We cannot provide an estimated date for the fix, but we will update this thread once we have news.
Sorry for the inconveniences.
Regards.

**Comment by denissabramovs** [comment] 2020-09-28 11:09
Will try to post here the results with LoadBalancer setup.

**Comment by varspare** [comment] 2020-12-02 15:15
Mostly just to add a +1 here, we're also seeing this issue and have not set `fullnameOverride`. We'll try the suggested workarounds but a fix would be appreciated.

**Comment by FraPazGal** [comment] 2020-12-03 11:44
Hello @varspare,

I will update the internal task related to this issue. Unfortunately, given the upcoming holiday season and our small team size, I'm not able to give you an ETA on this, but we'll try to move this up in our backlog! Thank you for your understanding!

**Comment by kodeine** [comment] 2022-03-19 02:47
@FraPazGal so is this issue resolved?

**Comment by javsalgar** [comment] 2022-03-21 10:23
Hi,

We recently fixed issues with NodePort external access and with cluster failover, could you check if you find the exact issue described here? If not, I believe we could close this issue.

**Closed** 2022-10-20 13:22 UTC
Labels: on-hold
