### ISSUE TITLE
postgresql-ha is down size error

### ISSUE THREAD

**Issue by truyet** [bitnami/charts#1934] opened 2020-02-17 03:19 UTC
**Which chart**: bitnami/postgresql-ha  version 1.4.3, app version 11.6.0

**Description**
Pods crash when it's restarted with error:
020-02-17 02:30:23.745 GMT [221] FATAL:  could not connect to the primary server: could not translate host name "postgresql-postgresql-ha-postgresql-1.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local" to address: Name or service not known
postgresql-repmgr 02:30:23.75 INFO  ==> ** Starting repmgrd **
2020-02-17 02:30:23.774 GMT [225] FATAL:  could not connect to the primary server: could not translate host name "postgresql-postgresql-ha-postgresql-1.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local" to address: Name or service not known
[2020-02-17 02:30:23] [NOTICE] repmgrd (repmgrd 5.0.0) starting up
INFO:  set_repmgrd_pid(): provided pidfile is /opt/bitnami/repmgr/tmp/repmgr.pid
[2020-02-17 02:30:23] [NOTICE] starting monitoring of node "postgresql-postgresql-ha-postgresql-0" (ID: 1000)
[2020-02-17 02:30:23] [ERROR] connection to database failed
[2020-02-17 02:30:23] [DETAIL]
could not translate host name "postgresql-postgresql-ha-postgresql-1.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local" to address: Name or service not known

[2020-02-17 02:30:23] [DETAIL] attempted to connect using:
  user=repmgr password=xxx connect_timeout=5 dbname=repmgr host=postgresql-postgresql-ha-postgresql-1.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local port=5432 fallback_application_name=repmgr
[2020-02-17 02:30:23] [ERROR] unable connect to upstream node (ID: 1001), terminating
[2020-02-17 02:30:23] [HINT] upstream node must be running before repmgrd can start

**Steps to reproduce the issue:**

1. Setup postgresql ha with replica = 2
2. Resize replica to 1
3. When postgresql is running only 1 pod, try to delete this pods, it will recreate new pod and crash forever

**Describe the results you received:**

NAME                                               READY   STATUS             RESTARTS   AGE
postgresql-postgresql-ha-pgpool-7c8bd64fb9-wq76h   0/1     Running            0          19h
postgresql-postgresql-ha-postgresql-0              1/2     CrashLoopBackOff   6          7m29s

**Describe the results you expected:**

postgresql-postgresql-ha-postgresql-0 should run. I try to change back replica = 2 but it can't start because pod index 0 don't start, pod index 1 will not start.

**Additional information you deem important (e.g. issue happens only occasionally):**
 2020-02-17 02:30:23.774 GMT [225] FATAL:  could not connect to the primary server: could not translate host name "postgresql-postgresql-ha-postgresql-1.postgresql-postgresql-ha-postgresql-headless.postgresql.svc.cluster.local" to address: Name or service not known

When this pod is restarted, repmgrd can't connect to pod postgresql-postgresql-ha-postgresql-0, it auto try connect to pods postgresql-postgresql-ha-postgresql-1, but pod postgresql-postgresql-ha-postgresql-1 can't start if postgresql-postgresql-ha-postgresql-0 don't start in statefulset.

**Version of Helm and Kubernetes**: 3.0

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`: 1.15

```
(paste your output here)
```

**Comment by dani8art** [comment] 2020-02-17 09:14
Hi @truyet 

Thank you for opening this issue, could you share with us more info about your cluster configuration (number of nodes, etc)  and the values override you were using, please?

Regards.

**Comment by truyet** [comment] 2020-02-17 10:12
I'm using k8s cluster on GKE with one node test using Preemptible mode. Preemptible mode will auto terminal and recreate new after 24h.

I try to set postgresql.replicaCount to 1, after pod run success, I change postgresql.replicaCount to 2 and waiting two postgresql-ha pods runned. I continue changed postgresql.replicaCount to 1 and keep this configuration. When postgresql-ha pod is recreated, it will crash with above case.

[postgresql-values.yaml.zip](https://github.com/bitnami/charts/files/4213029/postgresql-values.yaml.zip)

**Comment by dani8art** [comment] 2020-02-24 11:31
Hi, 

I see you are using old versions of the images, also, you are using a rolling tag `11.6.0` for postgresql, we strongly recommend to use not rolling tags on our charts. If there is not a strong reason for using these tags, please use the latest one.

```
  registry: docker.io
  repository: bitnami/postgresql-repmgr
  tag: 11.7.0-debian-10-r5

  ...

  registry: docker.io
  repository: bitnami/pgpool
  tag: 4.1.0-debian-10-r22

  ...

  registry: docker.io
  repository: bitnami/minideb
  tag: buster

  ...

  registry: docker.io
  repository: bitnami/postgres-exporter
  tag: 0.8.0-debian-10-r21
```

In addition, I would recommend you use the latest version of the chart too. Please, execute `helm repo update`. 

However, I can say that we could have two possible issues here.

- one of then related to `networkPolicy` which is not working pretty well, I saw several log entries were complaining about this.  I fixed it just disabling the network policy by the moment.

 - the other one seems to be related to the cluster scale-down action, I tested scale-up action and it seems to work properly.

In both cases, I would need to investigate a bit more but I wanted to give you an update, I will continue with the researches and trying to figure out the issues. Thank you for your patient. 

Regards.

**Comment by dani8art** [comment] 2020-03-02 10:47
Hi @truyet, Finally, we confirm that the issue is reproducible in our environment, we are going to open an internal task in order to find a solution to this problem. We can not give you an ETA but we will keep you updated if we have any news.

Thank you so much for your feedback.
Regards.

**Comment by sameersbn** [comment] 2020-03-09 06:21
@truyet I am trying to follow your instructions, but so far I have been unable to reproduce this issue.
Can you please go through the steps I followed and let me know if I am missing amything?

#### Step 1: Deploy postgresql-ha chart with 2 replicas

```bash
$ helm install psql  --set postgresql.replicaCount=2 bitnami/postgresql-ha
```

#### Step 2: List release

```bash
$ helm list
NAME	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
psql	default  	1       	2020-03-09 11:05:35.074788455 +0530 IST	deployed	postgresql-ha-1.4.6	11.7.0 
```

#### Step 3: Wait for statefulset rollout

```bash
$ kubectl rollout status sts psql-postgresql-ha-postgresql
```

#### Step 4: Scale down to 1 replica

```bash
$ export PGPOOL_PASSWORD=$(kubectl get secret --namespace default psql-postgresql-ha-pgpool -o jsonpath="{.data.admin-password}" | base64 --decode)
$ export POSTGRES_PASSWORD=$(kubectl get secret --namespace default psql-postgresql-ha-postgresql -o jsonpath="{.data.postgresql-password}" | base64 --decode)
$ export REPMGR_PASSWORD=$(kubectl get secret --namespace default psql-postgresql-ha-postgresql -o jsonpath="{.data.repmgr-password}" | base64 --decode)
$ helm upgrade psql \
  --set postgresqlImage.debug=true \
  --set postgresql.replicaCount=1 \
  --set pgpool.adminPassword="$PGPOOL_PASSWORD" \
  --set postgresql.password="$POSTGRES_PASSWORD" \
  --set postgresql.repmgrPassword="$REPMGR_PASSWORD" \
  bitnami/postgresql-ha
```

#### Step 5: Wait for statefulset rollout

```bash
$ kubectl rollout status sts psql-postgresql-ha-postgresql
```

#### Step 6: Manually delete pod

```bash
$ kubectl delete po psql-postgresql-ha-postgresql-0
```

#### Step 7: Wait for statefulset rollout

```bash
$ kubectl rollout status sts psql-postgresql-ha-postgresql
```

#### Step 8: Test database connection

```bash
$ kubectl exec -it $(kubectl get po -l app.kubernetes.io/component=pgpool  -o jsonpath='{.items[].metadata.name}') psql -- -Upostgres -h localhost -c '\l'
```

**Comment by sameersbn** [comment] 2020-03-09 12:16
Please note that I did notice an issue in the pgpool pod which required it to be restarted. A fix for it has been queued in our internal CI systems and should be landed soon.

**Comment by sameersbn** [comment] 2020-03-09 13:54
@truyet In the mean time I think you should have better luck scaling using the `kubectl scale` command then using the `helm upgrade` way

**Comment by truyet** [comment] 2020-03-09 16:17
Hi @sameersbn ,
I think this issue happen because error on configuration or repmgr tool of postgres. When I changed replica to 1, it still worked well and repmgr leader is setted with pod index 0. But after  it sometimes restart, it crashed because repmgr tool call timeout to pod index 1.

My environment used for dev on GKE with low resource and run will preemptible node. It is a good environment to test this case

**Comment by dani8art** [comment] 2020-03-10 08:53
I've tried the steps that @sameersbn added and it works for me, @truyet could you try to do `helm repo update`?  maybe you are missing the latest changes for this chart.

**Closed** 2020-03-11 07:57 UTC
