### ISSUE TITLE
thanos helm chart does not render with existingObjstoreSecret

### ISSUE THREAD

**Issue by jon-rei** [bitnami/charts#24536] opened 2024-03-19 09:30 UTC
### Name and Version

bitnami/thanos 14.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Use the newest thanos helm chart version 14.0.1
2. Configure existingObjstoreSecret

### Are you using any custom parameters or values?
```
existingObjstoreSecret: "custom-s3-config"
```

### What do you see instead?

```
Error: template: thanos/charts/thanos/templates/storegateway/statefulset-sharded.yaml:53:44: executing "thanos/charts/thanos/templates/storegateway/statefulset-sharded.yaml" at <include "thanos.objstoreConfig" .>: error calling include: template: thanos/charts/thanos-query-ssl/templates/_helpers.tpl:127:61: executing "thanos.objstoreConfig" at <.Values.objstoreConfig>: can't evaluate field Values in type int
```

### Additional information

it seems like the following PR https://github.com/bitnami/charts/pull/24014 has introduced this problem.

**Comment by carrodher** [comment] 2024-03-20 09:56
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by ppferrari** [comment] 2024-03-21 16:30
Faced same issue after upgrading to thanos chart version 14.0.1

**Comment by carrodher** [comment] 2024-03-21 21:08
Thank you for opening this issue and submitting the associated Pull Request. Our team will review and provide feedback. Once the PR is merged, the issue will automatically close.

Your contribution is greatly appreciated!

**Closed** 2024-03-22 09:10 UTC
Labels: triage, tech-issues, thanos

**Comment by RishabhKumarGupta** [comment] 2024-03-27 18:27
Facing the same issue using the latest chart : 14.0.2 :

Error: template: lightops-obs-metrics/charts/thanos/templates/storegateway/statefulset-sharded.yaml:54:44: executing "lightops-obs-metrics/charts/thanos/templates/storegateway/statefulset-sharded.yaml" at <include "thanos.objstoreConfig" .>: error calling include: template: lightops-obs-metrics/charts/thanos/templates/_helpers.tpl:126:18: executing "thanos.objstoreConfig" at <.Values.objstoreConfig>: can't evaluate field Values in type int

**Comment by dragoangel** [comment] 2024-03-27 18:47
> Facing the same issue using the latest chart : 14.0.2 :
> 
> Error: template: lightops-obs-metrics/charts/thanos/templates/storegateway/statefulset-sharded.yaml:54:44: executing "lightops-obs-metrics/charts/thanos/templates/storegateway/statefulset-sharded.yaml" at <include "thanos.objstoreConfig" .>: error calling include: template: lightops-obs-metrics/charts/thanos/templates/_helpers.tpl:126:18: executing "thanos.objstoreConfig" at <.Values.objstoreConfig>: can't evaluate field Values in type int

Hm, can't reproduce honestly.

**Comment by RishabhKumarGupta** [comment] 2024-03-28 09:08
Yes i am using 14.0.2 and below configuration :

 objstoreConfig: 
    type: FILESYSTEM
    config:
      directory: "/local-persistance/"

**Comment by dragoangel** [comment] 2024-03-28 09:13
> Yes i am using 14.0.2 and below configuration :
> 
>  ```
> objstoreConfig: |-
>     type: FILESYSTEM
>     config:
>       directory: "/local-persistance/"
> ```
 This not valid settings for Thanos, so yep, you get error

**Comment by RishabhKumarGupta** [comment] 2024-03-28 09:24
@dragoangel  Thanks for the response , I see Filesystem configuration for objstore given here : https://thanos.io/tip/thanos/storage.md/#:~:text=type%3A%20FILESYSTEM%0Aconfig%3A%0A%20%20directory%3A%20%22%22%0Aprefix%3A%20%22%22 , since I am using the same configuration before the 14.0.1 release and it was working . Sure I will open the new issuse for the same .

**Comment by dragoangel** [comment] 2024-03-28 09:32
> @dragoangel Thanks for the response , I see Filesystem configuration for objstore given here : https://thanos.io/tip/thanos/storage.md/#:~:text=type%3A%20FILESYSTEM%0Aconfig%3A%0A%20%20directory%3A%20%22%22%0Aprefix%3A%20%22%22 , since I am using the same configuration before the 14.0.1 release and it was working . Sure I will open the new issuse for the same .

Yes, you right, looks I see what wrong, need to check more

**Comment by dragoangel** [comment] 2024-03-28 09:44
Hm, it doesn't work only in `storegateway` `sharded` and at same time work in every other deployment or statefulset. Syntax everywhere is same. Looks like I see what is an issue here - context, sharded storegateway using `{{- range $index, $_ := until $shards }}` and loose it's context due to that.
