### ISSUE TITLE
[bitnami/redis-cluster] Allow redis modules via `redis-stack` in chart options or include libssl 

### ISSUE THREAD

**Issue by chitralverma** [bitnami/charts#27854] opened 2024-07-09 11:36 UTC
### Name and Version

bitnami/redis-cluster and bitnami/redis, latest version

### What is the problem this feature will solve?

When using these charts to create a Redis cluster or instance, the cluster cannot load modules due to missing `libssl`.

### What is the feature you are proposing to solve the problem?

The suggestion is to either add `libssl` package to the image or allow options which load modules much like `redis-stack`

**Comment by andresbono** [comment] 2024-07-18 09:49
Hi, thank you for opening this issue.

> When using these charts to create a Redis cluster or instance, the cluster cannot load modules due to missing libssl.

Could you please share how can I reproduce it?

**Comment by rajdudhare1** [comment] 2024-07-21 08:39
This occurs when you load module of redisgear and redissearch, use loadmodule directives in conf and provide the path to these libs on filesystem. if libssl is not found on system dependencies then it breaks and failed to start, you need to install libssl in image explicitly and re-run the stack then it works!

**Comment by rajdudhare1** [comment] 2024-07-22 09:30
I had to install this version `libssl1.1_1.1.1f`  the below 

####LIBSSL DEP FOR REDISTIMESERIES####
`curl -O http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb `
`dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb`

then I used following in conf and it worked!

`loadmodule /opt/bitnami/redis/lib/rediscompat.so
loadmodule /opt/bitnami/redis/lib/redisearch.so
loadmodule /opt/bitnami/redis/lib/redistimeseries.so
loadmodule /opt/bitnami/redis/lib/rejson.so
loadmodule /opt/bitnami/redis/lib/redisbloom.so
loadmodule /opt/bitnami/redis/lib/redisgears.so v8-plugin-path /opt/bitnami/redis/lib/libredisgears_v8_plugin.so`

**Comment by rajdudhare1** [comment] 2024-07-22 09:32
> Hi, thank you for providing this additional information. I see `libssl` is already installed in the system:
> 
> ```
> $ docker run --rm --entrypoint /bin/bash bitnami/redis:latest -c 'dpkg -l | grep libssl'
> ii  libssl3:amd64           3.0.13-1~deb12u1      amd64        Secure Sockets Layer toolkit - shared libraries
> $ docker run --rm --entrypoint /bin/bash bitnami/redis-cluster:latest -c 'dpkg -l | grep libssl'
> ii  libssl3:amd64           3.0.13-1~deb12u1      amd64        Secure Sockets Layer toolkit - shared libraries
> ```
> 
> I'm still missing something...
> 
> Also, it looks like it is a container image related issue, right? I wonder if this issue wouldn't better fit in https://github.com/bitnami/containers.


I had to install this version libssl1.1_1.1.1f the below

####LIBSSL DEP FOR REDISTIMESERIES####
curl -O http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb 
dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

then I used following in conf and it worked!

loadmodule /opt/bitnami/redis/lib/rediscompat.so loadmodule /opt/bitnami/redis/lib/redisearch.so loadmodule /opt/bitnami/redis/lib/redistimeseries.so loadmodule /opt/bitnami/redis/lib/rejson.so loadmodule /opt/bitnami/redis/lib/redisbloom.so loadmodule /opt/bitnami/redis/lib/redisgears.so v8-plugin-path /opt/bitnami/redis/lib/libredisgears_v8_plugin.so

**Comment by Praveen-98cs** [comment] 2024-07-23 13:08
I tried to load the redisjson module but i couldn't do that. can you help me how to do that? I have installed redis-cluster in kubernetes cluster. 

Thanks in advance

**Comment by andresbono** [comment] 2024-07-29 09:00
> I had to install this version `libssl1.1_1.1.1f` the below
> 
> ####LIBSSL DEP FOR REDISTIMESERIES#### `curl -O http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb` `dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb`
> 

That version of libssl is for a different OS distro, we shouldn't be installing it by default in the container image...

**Comment by Praveen-98cs** [comment] 2024-07-30 02:45
Isn't there any licensing  issue for using these modules in the bitnami version?

**Comment by andresbono** [comment] 2024-08-08 13:22
Please, refer to https://redis.io/legal/licenses/

**Comment by Praveen-98cs** [comment] 2024-08-08 15:39
Thank you! I went through that turns out if i am using this for internal uses, I can use this. Thanks again!

**Comment by andresbono** [comment] 2024-08-09 12:58
I'm closing this issue as I don't think it makes sense to install by default the suggested version of libssl that is for a different OS distro.

The issue is kept for reference so anyone can check the workaround. Thanks!

**Closed by andresbono** 2024-08-09 12:58 UTC
Labels: in-progress, feature-request, redis-cluster
