### ISSUE TITLE
[wordpress] Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "service" in io.k8s.api.networking.v1beta1.IngressBackend

### ISSUE THREAD

**Issue by huang-jy** [bitnami/charts#4865] opened 2020-12-31 08:51 UTC
**Which chart**:
The name (and version) of the affected chart
**Describe the bug**
Wordpress

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**
Successful deployment of wordpress

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

On deploying, I get this:

```
Release "wordpress-dev" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "service" in io.k8s.api.networking.v1beta1.IngressBackend

```

The chart was able to be deployed yesterday -- was a change made?

I noticed in the closed issues, #4791 which seems similar, but is marked as closed

**Comment by rafariossaa** [comment] 2020-12-31 15:06
Hi,
  I am closing this issue because it is a duplicate of #4866 and it is being discussed there.

**Closed by rafariossaa** 2020-12-31 15:06 UTC
